### ISSUE TITLE
Als gemeente wil ik kadastrale onroerende zaken kunnen raadplegen op aanduiding

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#1]
...zodat ik de gegevens van deze kadastrale onroerende zaken kan gebruiken.

Op basis van de kadastrale aanduiding wordt een verzoekbericht opgesteld om KADASTRALE ONROERENDE ZAAKen te selecteren.
Zoekresultaat: De KADASTRALE ONROERENDE ZAAKen waarvan de corresponderende gegevens overeenkomen met de ingevulde zoek-argumenten uit het verzoekbericht worden opgenomen in het antwoordbericht.

**Acceptatiecriteria**
- [ ] Het is mogelijk te zoeken (filteren) op de volgende eigenschappen van de kadastrale onroerende zaak:
    * kadastraleGemeentecode
    * sectie
    * perceelnummer
    * appartementsrechtindex

**Definition of done**
- [ ] Inhoud resource bepaald
- [ ] BDD- functionele specificatie
- [ ] Open API specificatie
- [ ] Bruikbaarheid (gegenereerde code + constructies + naamgeving)
- [ ] Implementatie Provider
- [ ] Implementatie consumer

**Comment by CathyDingemanse** [comment]
kadastrale aanduiding?

**Comment by JanWillemKooi** [comment]
Wie gaan dit reviewen?

**Comment by JanWillemKooi** [comment]
Deze userstory is geclosed maar staat nog in Review. Het lijkt ook meer een EPIC te zijn dan een User Story. Wat gaan we hier mee doen?
