### ISSUE TITLE
Postlocatie is nu een geïmplementeerde relatie. Vraag is of dat ook zo moet.

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#102]
In het informatiemodel is een onderscheid gemaakt tussen woonlocatie en postlocatie. Waarschijnlijk is dit in de vastlegging niet op deze wijze geïmplementeerd bij het kadaster (in de BRK) .

**Comment by JanWillemKooi** [comment]
Upadate 29 mei call: Marianne is bezig dit uit te zoeken.

**Comment by JanWillemKooi** [comment]
Update call 5 jun: Marianne probeert dit uiterlijk begin volgende week op te leveren.

**Comment by JanWillemKooi** [comment]
Issue opgelost door toepassen van nieuwe IMKAD
