### ISSUE TITLE
De OAS3 moet vanaf nu voorzien worden van een versienummer per sprint zodat duidelijk wordt welke versie in de doorontwikkeling is en welke versie op de testomgeving 

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#108]
zodat duidelijk wordt welke versie in de doorontwikkeling is en welke versie op de testomgeving van het kadaster beschikbaar wordt gesteld voor consumer-developers.

**Comment by JanWillemKooi** [comment]
Update call 5 jun: Cathy heeft dit met Jasper gesproken. Voorstel van Jasper Roes is om vanuit Haal Centraal met een groepje een voorstel voor te bereiden.

**Comment by JanWillemKooi** [comment]
update 21 aug: Voorstel is beschikbaar maar nog niet op GitHub gedeeld en besproken in het team. Dit wordt nog gedaan. 
Het voorstel wordt ook in de Landelijke API-strategie gebracht.

**Comment by JanWillemKooi** [comment]
Voor dit project wordt semantic versioning toegepast. Dat is voor de voortgang voorlopig voldoende maar deze US gaat over meer zaken. Dit is ook voor andere Haal Centraal projecten van belang. Deze US is verder te volgende bij het BRP project.
