### ISSUE TITLE
Beschikbaar stellen van de Sprint 4 API door kadaster aan Amsterdam, Vicrea en Melvin (ROZE)

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#109]
zodat de consumers-developers de gerealiseerde API-versie kunnen beproeven.

**Comment by JanWillemKooi** [comment]
Update 29 mei call: Het email adres voor de API-key van Melvin is nog niet doorgegeven. Dit moet een ades van VNG zijn.
Update 4 jun: Opdracht ligt bij VNG API-beheer. Gisteren contact over gehad. Er is een oplossing maar moet nog geverifieerd worden.

**Comment by JanWillemKooi** [comment]
Update call 5 jun: Beschikbaarstellen is door Kadaster deze week gepland. Endpoint blijft dezelfde dus ontvangers hoeven niet aan te passen.

**Comment by marianneleferink01** [comment]
De api is op vrijdag 7 juni 2019 beschikbaar gesteld op de uitgegeven api key.
Melvin kan hier nog niet bij, omdat we aan hem nog geen api key kunnen uitgeven. Dit komt omdat VNG nog geen mail adres hiervoor heeft aangeleverd.

**Comment by JanWillemKooi** [comment]
Zie #110. E-mail VNG is bekend en de API key is gegenereerd door Kadaster
