### ISSUE TITLE
Jan-Willem levert een email adres van een beheerder (Michiel of Robert) van VNG-realisatie aan

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#110]
zodat het kadaster de API-key voor het leggen van de beveiligde verbinding aan kan leveren. 

Melvin kan dan met die API-key de verbinding leggen en aan de consumer werken.

**Comment by JanWillemKooi** [comment]
Update 5 jun call: Michiel Verhoef is hier mee bezig. Johan checkt dit.

**Comment by JanWillemKooi** [comment]
Update 11 jun: Het e-mail adres is naar Marianne verstuurd.

**Comment by JanWillemKooi** [comment]
Op 11 jun is het e-mail adres beschikbaar gekomen. Daarop is op 12 jun de API-key op doorgestuurd door het Kadaster. Deze is ook verstuurd naar Melvin Lee.
