### ISSUE TITLE
Maak de OAS3 met als inhoud de kadastraal onroerende zaak en aanverwante subresources voor sprint 5 gebaseerd op de spreadsheet (GEEL)

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#111]
Er is een afspraak gepland tussen Marianne, Cathy en Johan om de content van de eerstvolgende versie van de OAS3 te bepalen.

**Comment by JanWillemKooi** [comment]
Update 1 jun call: Gisteren hebben Cathy, Johan en Marianne hier over gesproken. In de vorige sprint waren de specificaties roze in het spreadsheet. De huidige sprint heeft geel gekleurde entiteiten die als OAS3 specificaties wordt opgeleverd. Daarmee is het meeste (75%) van de BRK actueel afgehandeld m.u.v. onderzoekszaken, zekerheidsstellingen (zoals hypotheken) zijn nog niet mee genomen. Historie moet ook nog. Inschatting is dat nog 1 sprint nodig is om de basis als specificatie rond te hebben. Johan gaat de laatste versie van de spreadsheet op GitHub plaatsen.

**Comment by JanWillemKooi** [comment]
Update 5 jun call: Komt nog een aanvulling op de specificatie. Wordt bilateraal besproken tussen Cathy en Johan.

**Comment by JohanBoer** [comment]
Aanvulling op de Spec ( besproken in desig-sessie dd 28-05-2019 ) : 

	[ ] Bij objectlocatiebinneland is nu geen supertype objectlocatie en adreslocatie opgenomen. Deze moeten wel opgenomen worden. (Dit om eventueel de identificatie van een BRK-adres mee te kunnen geven. 
	[ ]Het endpoint uit sprint 4 wordt uitgebreid met links naar de 4 mogelijke personen.
	[ ] Endpoints toevoegen voor BRK-Persoon en BRK-Rechtspersoon. 
	[ ] Design Decision : De namen BRK-persoon en BRK-Rechtspersoon worden gebruikt. 
	[ ] DC: Stukdeel wordt een aparte resource.
	[ ] Aan tenaamstelling worden de twee relaties naar het stukdeel als link opgenomen. 
	[ ] Aan tenaamstelling wordt het gezamenlijk aandel embedded opgenomen
	[ ] DC: tenaamstellingfiliatie wordt niet opgenomen. Dit is een blik op historische gegevens. Van later zorg. 
	[ ] Requirement: Api ontwerpen om de gedigitaliseerde akte te ontsluiten (uit het GOR) 
	[ ] DC: Tenaamstelling wordt als resource gedefinieerd tbv de "isBeperkt tot" relatie. Deze relatie wordt als link geïmplementeerd op de zakelijkrechttenaamstelling. 
	[ ] De relatie tussen Kadastraalonroerendezaak en Aantekening wordt geïmplementeerd,door de Aantekening op te nemen als embedded resource. 
	[ ] de relatie tussen tenaamstelling en aantekening wordt niet in deze endpoint geïmplementeerd. 
	[ ] DC: Aantekening wordt een resource.
	[ ] Stukdeel wordt wordt een aparte resource.
	[ ] Ter inschrijving aangeboden stuk wordt als embedde resource opgenomen en ook het kadasterverzoek wordt embedded opgenomen
	[ ] Kadasterstuk wordt als resource gedefinieerd en als link in de stkdeel-endpoint opgenomen.

**Comment by JohanBoer** [comment]
> * Aan tenaamstelling worden de twee relaties naar het stukdeel als link opgenomen.

Doordat we de tenaamstelling als groep (inline element) opgenomen hebben bij het zakelijk recht kan je nu niet bepalen wel gezamenlijk aandeel bij welke tenaamstelling hoort. 
Dit heb ik opgelost door ook het gezamenlijkaandeel als groep op te nemen zodat deze ook weer inline met de groep tenaamstellinge komt.

**Comment by JohanBoer** [comment]
> * Aan tenaamstelling worden de twee relaties naar het stukdeel als link opgenomen.

Doordat deze links nu terechtkomen in de _links sectie van zakelijkrechttenaamstelling is niet meer  te bepalen welke stukdelen bij welke tenaamstelling horen. Dit is te voorkomen door de tenaamstelling als embedde resource op te nemen en niet als gegevensgroep.

**Comment by JohanBoer** [comment]
> * Kadasterstuk wordt als resource gedefinieerd en als link in de stkdeel-endpoint opgenomen.

Nu het kadasterstuk als embedded resource opgenomen. Dit lijkt mij eenvoudiger. Ben even kwijt welk business argument er is om hier een aparte endpoint voor te maken.

**Comment by JohanBoer** [comment]
•	Xor (oneOf) tussen de postlocaties aanbrengen. 
postlocatie:
    oneOf :
$ref: "#/components/schemas/Objectlocatiebuitenland"
$ref: "#/components/schemas/Objectlocatiebinnenland"
$ref: "#/components/schemas/Postbuslocatie"

•	Xor (oneOf) tussen de woonlocaties aanbrengen
postlocatie:
    oneOf :
         $ref: "#/components/schemas/Objectlocatiebuitenland"
         $ref: "#/components/schemas/Objectlocatiebinnenland"

•	Xor (oneOf) tussen de natuurlijkpersoon en nietnatuurlijkpersoon aanbrengen
personen:
    oneOf :
         $ref: "#/components/schemas/natuurlijkPersoon"
         $ref: "#/components/schemas/nietNatuurlijkPersoon"

Is bovenstaande wel nodig in een bevragingen API. Het feit dat er slechts 1 van deze resources teruggegeven wordt hoeft niet met polyformisme opgelost te worden. Dit kan gewoon een opsomming van optionele links en optionele embedded elementen zijn.

**Comment by JohanBoer** [comment]
> * DC: Tenaamstelling wordt als resource gedefinieerd tbv de "isBeperkt tot" relatie. Deze relatie wordt als link geïmplementeerd op de zakelijkrechttenaamstelling.

Door de tenaamstelling zowel als gegevensgroep als als resource te definieren gaan we veel gedoe over ons afroepen. Dit strookt ook niet met de REST-gedachte in mijn beleving. De voornaamste reden om het zakelijkrecht en de tenaamstelling in 1 resource te combineren zat heb in het feit dat de tennaamstelling dan inline in het zakelijkrecht zit en niet in de _embedded. Met bovenstaande wens is mijn advies om alsnog eenduidig de tennaamstelling als gerelateerde resource op te nemen in het zakelijkrecht.

**Comment by JohanBoer** [comment]
> * De relatie tussen Kadastraalonroerendezaak en Aantekening wordt geïmplementeerd,door de Aantekening op te nemen als embedded resource.
> * [ ]  de relatie tussen tenaamstelling en aantekening wordt niet in deze endpoint geïmplementeerd.
> * [ ]  DC: Aantekening wordt een resource.

In de modellen die ik tot mijn beschikking heb ontbreekt de Aantekening. ik zie wel een aantekeningWKPB, maar veronderstel dat die niet bedoeld wordt.

**Comment by JohanBoer** [comment]
> * DC: Tenaamstelling wordt als resource gedefinieerd tbv de "isBeperkt tot" relatie. Deze relatie wordt als link geïmplementeerd op de zakelijkrechttenaamstelling.

Deze als link implementeren op zakelijkrechttenaamstelling. Ook de belastmet relatie die nu als zakelijkrecht is geïmplementeerd.

**Comment by JanWillemKooi** [comment]
De werkwijze om de API-functionaliteit te specificeren en te realiseren is veranderd. Het spreadsheet https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/blob/master/docs/Infobehoefte%20BRK%20bevragen.xlsx wordt niet langer gehanteerd daarmee vervallen ook de kleuren labels (Spec GROEN, Spec ROZE, Spec Geel). Voortaan wordt het onderstaande spreadsheet gebruikt met daarin verwijzingen naar user story's in deze repository of naar afgeschermde user story's op GitLab:
https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/blob/master/docs/Infobehoefte%20BRK%20bevragen.xlsx
Nieuwe labels worden aangemaakt op basis van de EPIC's die in 'Goals_Hows_Afnemers.xlsx' staan in kolom C als roze cellen.
