### ISSUE TITLE
Als PO wil ik graag een besloten Gitlab omgeving 

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#112]
zodat we userstories die we niet willen publiceren wel kunnen administreren.

**Comment by JanWillemKooi** [comment]
Update 1 jun call:  Omgeving is aangemaakt. 
Update 4 jun: Cathy, Johan, Marianne, Remco en Melvin Lee zijn toegevoegd. Met Cathy is afgesproken dat de user story's van GitLab een corresponderende user story op GitHib krijgen echter met een nummer als omschrijving om te voorkomen dat hier informatie gaat lekken. Alleen mensen met een GitLab account krijgen toegang via de Hyperlink op Github. We moeten even zien hoe dit gaat werken in de praktijk.

**Comment by JanWillemKooi** [comment]
Update 5 jun call: Het lijkt niet praktisch om overal een schaduw user story van te maken. Maar als we geen schaduw user story in GitHIb hebben dan kan er verwarring in het spreadsheet ontstaan bij verwijzing naar user story nummers. Dit is te lossen door:
- toch schaduw US's in Github te zetten
- een prefix te gebruiken in het spreadsheet, als het een Gitlab US is.

Johan en Jan Willen gaan een voorstel doen.

**Comment by CathyDingemanse** [comment]
Hoe grappig! Dat hebben Marianne en ik al gedaan. De prefix = BUS (Besloten User Story).
