### ISSUE TITLE
Budget regelen als delivery manager

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#12]

**Comment by TCIMEddy** [comment]
@wishalg Kun je hier nog wat over zeggen? Of kan ik het als geregeld beschouwen en naar done zetten

**Comment by wishalg** [comment]
Dut kan je bij Frank Samwel navragen, hij is tot 31-12-2018 projectleider/delivery manager.

**Comment by TCIMEddy** [comment]
@wishalg haal ik hem van je naam af

**Comment by wishalg** [comment]
@CathyDingemanse de specifieke taken die Frank uitvoerde, de functionele werking van de api specificeren en illustreren, graag nog overleg hierover om na te gaan hoe we synergy voordelen kunnen realiseren met andere projecten.
Voor het budget verneem ik graag met voortschrijdendinzicht van dit project welke resources vereist zijn.

**Comment by JanWillemKooi** [comment]
De financiering van dit traject hangt samen met Haal Centraal. Het initiatief Haal Centraal is goedgekeurd maar het is nog niet bekend hoe de budgetten worden toegekend.

**Comment by JanWillemKooi** [comment]
Het project heeft nu last van het feit dat de inzet van Melvin niet geregeld is (na feb)

**Comment by wishalg** [comment]
> Het project heeft nu last van het feit dat de inzet van Melvin niet geregeld is (na feb)
@JanWillemKooi Brenda de Graaf is hiervan op de hoogte.

**Comment by JanWillemKooi** [comment]
Zie #50

**Comment by JanWillemKooi** [comment]
Dit issue wordt verder opgevolgd in #50 en gesloten.
