### ISSUE TITLE
Als medewerker monumentenzorg wil ik weten wat de kadastrale aanduiding is 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#125]
...zodat ik dit correct kan invoeren in de WKPB.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by markbacker** [comment]
Deze user story staat ook bij HC BAG bevragen. Zie https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen/issues/3. Daar staat naast de BRK, terecht ook de BAG als geldig werkingsbied. Is echter nog niet compleet.

Voorstel voor volledige user story:
_Als medewerker monumentenzorg wil ik weten wat de kadastrale aanduiding, de BAG aanduiding, de BGT aanduiding of de geo-contour is van een monument
... zodat ik deze correct kan (laten) invoeren in de BRK-PB_
