### ISSUE TITLE
Als gemeenteadvocaat wil ik inzicht hebben in de filiatie op en splitsingsakten van een kadastraal onroerende zaak  

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#128]
...zodat ik eigenaren kan aanschrijven over woningverbetering, woningonderhoud en het onderhoud van gemeenschappelijke delen.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by JohanBoer** [comment]
Deze wordt toch niet op dit moment nog toegevoegd aan 1.3 ? Dit is functionaliteit die we pas anderhalve week geleden besproken hebben. Het opnemen hiervan in versie 1.3 vereist aangepast specificatie waarschijnlijk met nieuwe endpoints.

**Comment by CathyDingemanse** [comment]
Dit is niet hetzelfde als de splitsing van zakelijke rechten tbv erfpacht.
