### ISSUE TITLE
Als projectdeelnemer wil ik graag dat de beknopte handleiding API-prortal gereviewd zien. 

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#176]
Dit document is te vinden onder /docs

**Comment by JanWillemKooi** [comment]
Remco toevoegen aan assign

**Comment by remcoveenstra** [comment]
Ik mag mezelf niet assignen, maar dit is mijn account.

**Comment by JanWillemKooi** [comment]
Ik heb je net toegevoegd aan deze US.

**Comment by JanWillemKooi** [comment]
Ik heb Remco. Agustin heb ik uitgenodigd bij deze Repro. Zodra ik reactie krijg kan ik hem ook toevoegen. Ik kan het account van Dolhuis niet vinden. Kan iemand me daarmee verder helpen?

**Comment by dolhuis** [comment]
https://github.com/dolhuis

**Comment by dolhuis** [comment]
Review van [Beknopte handleiding API Portal connectietest v1.0-1.docx](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/blob/master/docs/Beknopte%20handleiding%20API%20Portal%20connectietest%20v1.0-1.docx)

1. Algemene opmerking over het formaat:
Is het niet prettiger om dit soort documentatie in het project in een direct leesbaar, tekst-gebaseerd formaat aan te bieden (bijvoorbeeld markdown)?
    - niet iedereen heeft Word - wat bijdragen aan het bestand bemoeilijkt
    - handleiding in tekst is voor iedereen rechtstreeks te lezen in de repository in GitHub
    - bij het pull-request valt meteen en duidelijk te zien wat die bijdrage is, het valt meteen goed te keuren en te mergen
    - versie-historie is goed bij te houden en inzichtelijk, zowel op GitHub als lokaal.

2. Inhoudelijk:
Prettig uitgebreid, goed werk. Nog wat kleine tekstuele suggesties.

Ik kan me voorstellen dat de beide hoofdbestanddelen (de beveiligde verbinding met truststore/certificaat uitleg, en de functionele uitvoering via Postman) kunnen uitgroeien tot zelfstandige, in de toekomst uit te breiden handleidingen. Waarbij aan de ene kant ontwikkelaars met een Linux of MacOS systeem hun stukjes trust-store-kennis delen, en aan de andere kant nieuwe functionaliteit via Postman wordt gedemonstreerd.

Een tekstgebaseerd formaat kan ook hier helpen ('refactoren' van de handleiding in twee aparte handleidingen, bijvoorbeeld).

**Comment by remcoveenstra** [comment]
Review Beknopte handleiding API Portal

Algemeen
Ziet er mooi uit, een hoop dingen zijn erg uitgebreid uitgelegd.
Ik kan op het scrumbord geen informatie vinden over wat het doel is van deze handleiding en voor wie het bedoeld is, misschien wel nuttig om het te kunnen beoordelen.


1.1
De Kadaster Test API Portal maakt van een API key voor de authorisatie gebruik - zin klinkt wat vreemd, ik zou gebruik direct achter maakt zetten.

Over het e-mailadres: eerder bleek dat dit een aparte account moest zijn en niet op naam van een specifieke persoon mag, dit zou ik hier er ook bij zetten.

•	De API key dat -> •	De API key die

2.2
•	Na importeren van de Swagger API definitie, die van het Kadaster als een bestand is ontvangen -> dat moet zijn, de API-definitie zoals deze te vinden is in de standaard (incl. locatie hiervan)

Overigens werkt dit importeren niet in Postman met de laatste versie die ik van Marcel ontvangen heb, van https://api.test.kadaster.nl/esd/gemeenten/brk/yaml/openapi.yaml, ik krijg dan "Error while importing Open API 3.0: Could not import"
Op de versie van https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/tree/master/specificatie (of die in de sprint7-map) krijg ik dezelfde fout.
Vanuit de daaruit zelf via SwaggerHub platgeslagen versie lukt het wel.
Overigens werkt dit wel op de esd_kadastraal_object.json die ik voor de connectiviteit ontvangen heb, maar daar zit nog niet zo veel in. Overigens valt daar de https: weg in endpoint die hij ophaalt.


Voor de key kadastraleaanduiding wordt waarde apeldoorn opgegeven, maar welke identificatie kan worden gebruikt voor de onderstaande urls:
https://api.test.kadaster.nl/esd/gemeenten/brk/BRKpersonen/{identificatie}
https://api.test.kadaster.nl/esd/gemeenten/brk/BRKrechtspersonen/{identificatie}
https://api.test.kadaster.nl/esd/gemeenten/brk/stukdelen/{identificatie}
?

**Comment by JanWillemKooi** [comment]
Reveiw commentaar wordt meegenomen door Rene Kloppert en een nieuwe versie wordt in een nieuwe user story aangemaakt.

**Comment by JanWillemKooi** [comment]
Laatste versie wordt door Marianne op GitHub gezet
