### ISSUE TITLE
Als PO wil ik een wrapper voor de locatieserver

### ISSUE THREAD

**Issue by JanWillemKooi** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#177]
zodat ik de locatieserver zowel voor de BAG als voor de BRK kan gebruiken

**Comment by JanWillemKooi** [comment]
Actie: Cathy zoekt contact met Leo vd Sluijs voor project locatieserver.

**Comment by CathyDingemanse** [comment]
Loopt via het Haal Centraal BAG team. De insteek voor BRK is het BAG ID.
