### ISSUE TITLE
Prioriteit bepalen van user stories op de backlog (@PO)

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#18]
Zeer Hoog
Hoog
Medium
Laag
Zeer Laag

Label aan ieder user story plakken

Taak PO's

**Comment by CathyDingemanse** [comment]
Ik heb de eerste epic bepaald. De prioriteitsstelling voor de volgende epic volgt gaande de realisatie en de invemntarisatie informatiebehoefte.
