### ISSUE TITLE
Als PO wil ik dat een resource of subresource eenduidig wordt ontsloten

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#186]
...zodat de API consistent is.

Door "isEigendomVanIngeschrevenPersoon" en "isEigendomVanKadasterPersoon) te definieren als subresources:
- komen we meteen in de knel met de andere zakelijk gerechtigden (opstal, erfpacht etc.). Deze moeten op dezelfde manier bevraagbaar worden gemaakt.
- wordt een gebruiker direct geconfonteerd met twee typen personen. Dit onderscheid is slechts bijzaak en geen hoofdzaak en helpt niet om het geheel (van zakelijk gerechtigden, zie punt hierboven) te kunnen overzien. 

De vraag is min of meer volledig gespecificeerd in de Goals_Hows_Afnemers.

kadastraalonroerendezaken/{kadastraalontroerendeZaak}/eigenaren
kan een convenience endpoint zijn (denk shortcut), als consumer onderstaand pad niet direct snapt of zelf kan formuleren:

kadastraalonroerendezaken/{kadastraalontroerendeZaak}/zakelijkgerechtigden?type=eigenaren

Wat is dan de response voor beide paden hierboven? 
De subresource Zakelijk gerechtigden van het type eigenaren, wat mijns inziens een collectie moet zijn van tenaamstellingen gekoppeld aan een ingeschreven persoon (met naam, geboortedatum, en een link naar de BRP) of een kadasterpersoon (met naam, geboortedatum en een link naar de kadasterpersoon).

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [x] functionele specificatie
- [x] Open API specificatie
- [x] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by JanWillemKooi** [comment]
Check @CathyDingemanse of deze gesloten kan worden.

**Comment by CathyDingemanse** [comment]
> Check @CathyDingemanse of deze gesloten kan worden.

Graag open houden totdat test heeft plaatsgevonden.

**Comment by JanWillemKooi** [comment]
Opmerking Cathy:
Graag open houden totdat test heeft plaatsgevonden.
