### ISSUE TITLE
Als PO wil ik dat subresources worden gedefinieerd op basis van een businessvraag

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#187]
...zodat er geen wildgroei ontstaat.

Het gezamenlijkAandeel is als subresource van tenaamstelling gedefinieerd. 
Ik heb geen vragen gehad dat dit apart/ alleen moet worden opgehaald. Kunnen we dit niet gewoon als onderdeel van de tenaamstelling opvoeren?
 

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by JanWillemKooi** [comment]
Check of deze gesloten kan worden door @CathyDingemanse
