### ISSUE TITLE
Als PO wil ik dat de "kadasterpersoon" in lijn met andere Haal Centraal personen wordt gedefineerd 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#188]
...zodat de consistentie van de API gewaarborgd wordt.

1. Hernoemen:  
Kan deze ook nietIngeschrevenPersoon worden genomen as opposed to ingeschrevenPersoon? Evt met een nietIngeschrevenPersoonBRKID (en straks ook een nietIngeschrevenPersoonHRID). 

2.  Inhoud
Ik zie hier adellijke titel/ predicaat, aanduiding naamgebruik etc. Graag ook hier aanschrijfwijze, aanhef en gebruik in lopende tekst gebruiken/(hergebruiken?), conform de HC BRPbevragen API.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by JanWillemKooi** [comment]
Check @CathyDingemanse en dan sluiten
