### ISSUE TITLE
Als medewerker vergunningen wil ik van een perceel of appartementsrecht alle hoofd- en nevenadressen ophalen

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#199]
...zodat ik kan controleren of deze adressen legaal tot stand zijn gekomen en kan voorkomen dat adressen gelegaliseerd worden door een vergunning te verlenen. 

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by JohanBoer** [comment]
Nu worden alle adressen opgenomen, maar is niet direct te zien of het een hoofdadres of een nevenadres is. Daarvoor zou een call naar de BAG plaats moeten vinden.
Is dat afdoende of wil je de indicatieNevenAdres opgenomen zien bij de adressen van een Kadastraal Onroerende Zaak ?

**Comment by CathyDingemanse** [comment]
Het is wel een hele specifieke casus. Een call naar de BAG is in dit geval denk ik wel verdedigbaar.
