### ISSUE TITLE
Als PO wil ik een praatplaat BRK om de informatiebehoefte van BGA te kunnen bespreken

### ISSUE THREAD

**Issue by JanWillemKooi** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#20]
Tijdens de call van do, 20 dec, is afgesproken dat Marianne Leferink (Kadaster) de praatplaat waarmee Cathy Dingemanse de behoefte van de 30 a 40 afnemers, binnen Den Haag in kaart gaat brengen, centraal op Github beschikbaar zal stellen.

**Comment by JanWillemKooi** [comment]
Update 10 jan nav scrum call
Het Kadaster heeft een voorlopige praatplaat met specificaties opgesteld waarmee Cathy langs haar afnemers (30 a 40) binnen het Haagse kan gaan om de eisen en wensen vast te stellen. Marianne zal vanmiddag (10 jan) de voorlopige praatplaat delen met Johan en Cathy. Zodra de nieuwste versie rond is, zal Marianne deze delen met het team.

**Comment by marianneleferink01** [comment]
Nieuwe praatplaat is beschikbaar.

**Comment by JanWillemKooi** [comment]
PraatPlaat is als ZIP met doorklikbare HTML beschikbaar. Op 27 feb wordt de praatplaat toegelicht en beslist hoe we deze kunnen delen op GitHub
