### ISSUE TITLE
Als medewerker belastingzaken wil ik weten welk grondperceel bij het appartementsrecht behoort

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#200]
...zodat ik evt. erfpacht e.d. kan meenemen in de taxatie

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by CathyDingemanse** [comment]
Dit kan niet worden opgelost door te zoeken op kadastralegemeentecode, perceelnummer en sectie. Als voorbeeld de relatieboom van Brinkstraat 41 in Assen bijgevoegd.
![image](https://user-images.githubusercontent.com/18162831/81670702-4a1a1180-9448-11ea-8224-624318a4f4c7.png)
 
Hier is te zien dat het perceelnummer van het appartement 13357 is.
Via een appartementsrechtsplitsing is te volgen welk grondperceel hierbij betrokken is, maar het perceelnummer van dat grondperceel is 13228 en komt dus niet overeen.
Als ik zoek op ASN00 I 13228 (het grondperceel) in de BRK API, kan ik het appartement in dit voorbeeld nooit vinden.

**Comment by fsamwel** [comment]
zit in isOntstaanUit. Dat zit in v1.2.

**Comment by JohanBoer** [comment]
Zowel de relatie isOvergegaanIn (VoorwaartseFiliatie) als isOntstaanUit (Filiatie) is nu opgenomen bij de Kadastraal Onroerende Zaak.

**Comment by JohanBoer** [comment]
De filiatie is uiteindelijk niet in versie 1.2 geland. Het opnemen van isOntstaanUit en isOvergegaanIn moet in versie 1.3. Deze issue voorzien van label BRK Bevragen 1.3 en terug naar Ready for sprint.

**Comment by fsamwel** [comment]
@JohanBoer 
> De filiatie is uiteindelijk niet in versie 1.2 geland. Het opnemen van isOntstaanUit en isOvergegaanIn moet in versie 1.3. Deze issue voorzien van label BRK Bevragen 1.3 en terug naar Ready for sprint.

Je zegt het wel, maar hebt het denk ik niet gedaan?

Ik heb dit nu gewijzigd, als dat niet juist is, corrigeer je dat dan weer?

**Comment by JohanBoer** [comment]
Deze user story is nu in de specificatie ingevuld door zowel isOntstaanUit(achterwaartse filiatie) als isOvergegaanIn (voorwaartse filiatie) op te nemen bij de kadastraal onroerende zaak. Daarbij wordt ook de mogelijkheid geboden om vervallen objecten op te vragen. (daarvoor zijn de properties indicatieVervallen en einddatum toegevoegd) 

Als service zijn ook de properties "bijbehorendGrondperceelIdentificatie" en "bijbehorendeAppartementsrechtIdentificaties" toegevoegd aan de kadastraal onroerende zaak.
