### ISSUE TITLE
als medewerker belastingzaken wil ik weten of de KOZ geometrisch of administratief met het BAG-adres is gekoppeld

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#201]
...zodat ik kan bepalen welke koppelingen niet in orde zijn 
(nl. die met alleen een administratieve, of alleen een geografische koppeling).
EN zelf actie kan ondernemen om de koppeling te verbeteren.

Het kadaster probeert altijd 2 typen koppelingen te leggen: 
- een administratieve koppeling: het adres komt voor bij een VBO in de BAG. 
- geometrische koppeling: dan ligt het adres ook op de goede plaats. 

Het kadaster kan ook alleen een geometrische koppeling leveren. Dat is de koppeling met het grondperceel (is betrokken bij een splitsing, dat sluimert en is inactief, bij wijze van onmogelijkheid om het aan het appartement toe te wijzen). 

Als er alleen een administratieve koppeling is: dan is er wat mis
Als er alleen een geo koppeling is: dan is er wat mis
Als beide koppelingen zijn gelegd: dat zijn de goede koppelingen.

- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by hoebedoelu** [comment]
Waarom wordt hier onderscheid gemaakt tussen een geometrische en administratieve koppeling? Wanneer met de BAG is gekoppeld zouden beiden toch gerealiseerd moeten zijn (sleutel en coördinaten)? Als er wel verschil is, kunnen de verschillen dan op waarde worden geschat?
