### ISSUE TITLE
Als PO wil ik dat het raadplegen van de KOZ op identificatie wordt gebouwd 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#205]
...zodat alle user stories die met deze functionaliteit worden gerealiseerd kunnen worden getest.

**Acceptatiecriteria**
- zie goals canvas KOZ op ingang Kadastraal Onroerende Zaak identificatie 
- zie OAS KOZ

**Definition of done**
- [x] functionele specificatie
- [x] Open API specificatie
- [x] gegenereerde code
- [x] testgevallen
- [ ] implementatie

**Comment by JanWillemKooi** [comment]
Overgebleven functionaliteiten worden nieuwe US.
