### ISSUE TITLE
Als PO wil ik dat de OAS voor zoeken persoon wordt gedefinieerd

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#206]
...zodat deze kan worden gereviewd

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by JohanBoer** [comment]
a.	Er alleen gezocht wordt op kadasterpersonen (voor np’s)
b.	Voor nnp ’s begrijpen we dat het om alle nnp’s gaat (wel/niet ingeschreven in HR)
c.	Volgorde van invullen zoekveld:  Voor NP wordt alleen gezocht (free query) op geslachtsnaam     
         en geboortedatum (optioneel) en ook wel in die volgorde waarbij exact wordt gematched op 
          geslachtsnaam. Er moeten minimaal 2 karakters van de achternaam ingevuld zijn voordat er een resultaat wordt gezocht.
         Resultaat: gesorteerd als volgt:  geslachtsnaam / voorvoegsels/voornamen / geboortedatum
         Voor NNP wordt het Statutairenaam in combinatie de statutairezetel (optioneel) als zoekveld 
         (freequery) gebruikt waarbij exact wordt gematcht op statutairenaam.
         Additioneel wordt een optioneel veld voor de rechtsvorm aangeboden waarin de waardelijst 
         wordt aangeboden (die zelf ook via een API ontsloten gaat worden) De code van de g 
          geselecteerde rechtsvorm wordt meegegeven voor het zoeken. 
         Resultaat: gesorteerd als volgt:  statutairenaam /statutaire zetel
e.	KadasterPersoonTypen zijn dan:
           ingeschrevenPersoon
           kadasternatuurlijkPersoon
           ingeschrevenNietNatuurlijkPersoon
           kadasterNietNatuurlijkPersoon
