### ISSUE TITLE
Als PO wil ik dat de OAS voor het zoeken van KOZ op basis van persoon wordt gedefinieerd

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#207]
...zodat deze kan worden gereviewd 

**Acceptatiecriteria**
- zie goals canvas
- graag 1 november opleveren, zodat reviewers voor 7 november kunnen reviewen

**Definition of done**
- [ ] functionele specificatie
- [x] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by JohanBoer** [comment]
Zie pull request #209
