### ISSUE TITLE
Als berichtdesigner wil ik duidelijkheid over de waarden van de query-parameter TYPEGERECHTIGDE

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#208]
...zodat ik in de beschrijving op kan nemen wat de te gebruiken waarden zijn. .

Bij het opvragen van de kadastraal onroerende zaken hebben we de typegerechtigde als query-parameter gedefinieerd (ook bij het opvragen van zaeklijkgerechtigden) 
In eerste instantie om eigenaren op te kunnen vragen, maar eventueel ook een andere zakelijk recht gebruiken om zakelijk gerechtigden op te vragen. 

De waardelijst met typen zakelijk recht zoals die door het kadaster wordt gepubliceerd is te vinden op http://www.kadaster.nl/schemas/waardelijsten/AardZakelijkRecht/ .

Mijn vraag is nu of we deze lijst als mogelijke waarden gaan gebruiken om in de query-parameter in te vullen danwel of daar nog een interpretatie-slag op los gelaten wordt. 

In ons werkvoorbeeld staat “typegerechtigde=eigenaar” terwijl dat dan als volgt zou moeten zijn “typegerechtigde=Eigendom (recht van)”. Volgens mij gaan die spaties een probleem opleveren bij het doen van de Call. 

Nu niet essentieel voor de YAML. Wel belangrijk om hier een ei over te leggen……

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by JohanBoer** [comment]
Een vergelijkbare vraag geldi voor de query-parameter kadastraleGemeente. Wordt de waarde uit de waardelijst gebruik of wordt de code gebruikt. ?

**Comment by fsamwel** [comment]
In de ontwerpsessie hebben we volgens mij het volgende hierover besloten:
- voor de queryparameter wordt de code verwacht
- in het antwoord wordt het gedefinieerd als $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/schemas/Waardelijst"

in common.yaml wordt daartoe Waardetabel hernoemd naar Waardelijst, zodat hetzelfde component zowel voor BRP als BRK en ook andere HC-API's gebruikt kan worden.

Ik stel daarnaast voor dat we dit als designdecision in algemene zin opnemen, dus voor alle gegevens die in het imKad als waardelijst zijn gedefinieerd.

**Comment by JohanBoer** [comment]
De typegerechtigde lijst is inmiddels als enumeratie geïmplementeerd. 

Bovenstaande afspraak is opgenomen in de design decisions. opgenomen in PR 24 op de Haal-centraal-common repository
