### ISSUE TITLE
Als PO ik wil dat een beveiligde verbinding wordt gerealiseerd tussen de ETO Kadaster en de acceptatieomgeving van de gemeente Den Haag 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#21]
...zodat de API kan worden getest door de gemeente Den Haag.

**Acceptatiecriteria:**

- moet voldoen aan beveiligingsbeleid Kadaster en gemeente DH, behorende bij vertrouwelijkheids classificatie 2

**Definition of done**

- [ ] Risico analyse
- [ ] Voorstel beveiligingsoplossing en uitvoering van het Kadaster (Lennart van den Berg)
- [ ] Goedkeuring gemeente Den Haag (Andre van den Nouweland, ISO)
- [ ] Goedkeuring gemeente Amsterdam

**Comment by JanWillemKooi** [comment]
Volgens mij heb ik dit issue ten onrechte gesloten. Vandaag dat ik deze heb heropend.

**Comment by JanWillemKooi** [comment]
Johan doet voorstel voor end point (hello world)
Kadaster publiceert end point (open API key of PKI-overheidscertificaat)
Andre (Den Haag) en Rene (Kadaster) verbinding opzetten
Daarna hetzelfde voor proces five (Kayo)
Daarna Amsterdam (Agustin)

**Comment by JanWillemKooi** [comment]
Update n.a.v. conf call 6 maart: Johan heeft een kleine open API (2 of 3 objecten met relaties) opgeleverd in overleg met Lennart die gebouwd moet worden door Kadaster developers.
Deze is primair bedoeld om de connectiviteit met de ETO te testen. Deze wordt de HelloWorld-API genoemd maar is ook bekend als de Connectiviteit-versie en staat hier:
https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/tree/master/specificatie/Connectiviteit-versie
De komende weken wordt aan de ontwikkeling van deze HelloWorld-API, door het Kadaster gewerkt. Het kan wel een issue worden als er te veel uren worden geschreven als het budget niet is geregeld. Cathy en Karin werken hieraan (zie #50).
Lennert heeft uitleg gegeven aan de bouwer. Als er vragen zijn, dan is Johan benaderbaar.
De verwachting van Marianne is, dat de HelloWorld-API, afgerond kan worden in de komende 3 weken. Zo niet dan wordt gekeken of andere bouwers (uit het team van 8 personen) ingezet kunnen worden. Marianne en Hilde sturen het bouwteam aan. Lennart niet. Bij afwezigheid van Hilde doet Karin dat.

**Comment by JanWillemKooi** [comment]
n.a.v. call 20 mrt:  Dit is afhankelijk van de realisatie van de HelloWorld-API. Deze zal op basis van een client certificaat. Inschatting van Marianne is dat deze API net binnen planning (dus volgende week) beschikbaar is. Daarna kan Andre van den Nouweland de verbinding maken. Cathy heeft per mail aan Lennart gevraagd om een voorstel te schrijven voor de beveiligde verbinding.

**Comment by JanWillemKooi** [comment]
N.a.v. de call van 17 apr: De API-keys zijn door Rene van het Kadaster verstuurd naar gemeente Den Haag en Proces Five. Aan de gemeente Amsterdam is een adres (het contactadres voor de organisatie, dus niet een prive adres) gevraagd en zodra deze ontvangen is, stuurt het Kadaster de API-key. Voor Vicrea geldt hetzelfde: Kastaster heeft een goed adres nodig. Remco gaat hiermee aan de slag.
Kadaster verwacht dat Proces Five en gemeente Den Haag gaan testen. Kadaster kan eventueel assistentie leveren. Andre van den Nouweland (gemeente Den Haag) is betrokken.
