### ISSUE TITLE
Composite id is nu een groep inclusief versienr -- niet bekend bij Kadaster. 

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#211]
Check dat de definitie van Composite-id ook klopt zoals die binnen het kadaster gebruikt word.

**Comment by mhebbink-kad** [comment]
KadastraalObjectIdentificatie is van het type String. (NL.IMKAD...)

**Comment by JohanBoer** [comment]
Johan Checkt of dit nu in de specs op deze wijze overal is verwerkt.

**Comment by JohanBoer** [comment]
kadatsraleObjectIdentificatie is overal als string gedefinieerd. Composite-id komt niet meer voor in de OAS.
