### ISSUE TITLE
Zorg dat de verschillende API's van het kadaster gebruik maken van dezelfde structuur van gegevensgroepen

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#212]
Gegevensgroeptypen zijn:  deze overal zo gebruiken (met de vragen daarbij van mijn kant)
Adres
Geboorte
Datum_onvolledig
Waardelijst
CompositId

**Comment by JanWillemKooi** [comment]
Melvin gaat een stuk documentatie aanleveren.
