### ISSUE TITLE
Vervang de kadastraleAanduiding als Query-parameter door de individuele onderdelen 

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#213]
Zie indeling van KadastraleAanduiding.

**Comment by JohanBoer** [comment]
De individuele onderdelel (kadastraleGemeente, Sectie en Perceelnummer) zijn nu als query-parameter opgenomen. Vraag is of nu de KadastraleAanduiding als geheel weg moet als wuery-parameter.

**Comment by mhebbink-kad** [comment]
KadastraleAanduiding kan weg. In de description wordt toegelicht welke combinaties mogelijk zijn (altijd G S en P) en optioneel A. Voor de G moet altijd de waarde ingegeven worden. 
Waar nodig, patterns toevoegen.

**Comment by JohanBoer** [comment]
Voeg een description toe aan de kadastralegemeente query parameter. Daarna kan deze naar Done
