### ISSUE TITLE
Als PO wil ik dat een beveiligde verbinding wordt gerealiseerd tussen de ETO van het Kadaster en de ontwikkelomgeving van de leverancier van de gemeente Den Haag 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#22]
...zodat de leverancier een consumer kan ontwikkelen.

**Acceptatiecriteria**
- moet voldoen aan beveiligingsbeleid Kadaster en gemeente DH, behorende bij vertrouwelijkheids classificatie 2 

**Definition of done**
- risico analyse
- Voorstel beveiligingsoplossing en uitvoering van het Kadaster (Lennart van der Berg)
- goedkeuring gemeente DH (Andre van den Nouwland, ISO)

Deze userstory's zijn gerelateerd aan elkaar: 
#21 (voor Den Haag),
#22 (voor Proces Five)
#25 (voor gemeente Amsterdam)
#26 (voor Vicrea) 

#63 (document met beveiliging specificatie)

**Comment by JanWillemKooi** [comment]
Update n.a.v. conf call 6 maart: Johan heeft een kleine open API (2 of 3 objecten met relaties)  opgeleverd in overleg met Lennart die gebouwd moet worden door Kadaster developers. 
Deze is primair bedoeld om de connectiviteit met de ETO te testen. Deze wordt de HelloWorld-API genoemd maar is ook bekend als de Connectiviteit-versie en staat hier:
https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/tree/master/specificatie/Connectiviteit-versie
De komende weken wordt aan de ontwikkeling van deze HelloWorld-API, door het Kadaster gewerkt. Het kan wel een issue worden als er te veel uren worden geschreven als het budget niet is geregeld. Cathy en Karin werken hieraan (zie #50). 
Lennert heeft uitleg gegeven aan de bouwer. Als er vragen zijn, dan is Johan benaderbaar. 
De verwachting van Marianne is, dat de HelloWorld-API, afgerond kan worden in de komende 3 weken. Zo niet dan wordt gekeken of andere bouwers (uit het team van 8 personen) ingezet kunnen worden. Marianne en Hilde sturen het bouwteam aan. Lennart niet. Bij afwezigheid van Hilde doet Karin dat.

**Comment by JanWillemKooi** [comment]
Zie voor update #21
