### ISSUE TITLE
Links en Id's naar andere API's vormgeven 

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#223]
Als we willen beproeven dan nemen we voor externe verwijzingen (andere API) 
Zowel de id van een relatie als de link in _links op. Dan kunnen leveranciers op de API-lab allebeid de werkwijzen beproeven. 

BV. Voor bagAdressen nemen we ook een element op in de body met alleen de BAG-ID. 

Daarnaast bij de links ook een element (type, title of name) toevoegen waarmee aangegeven wordt naar welk domein de link verwijst. 
Dus bv : BAG, BRP, KvK, BRK.

**Comment by JanWillemKooi** [comment]
Conclusie uit het API-lab en de sprintwissel:

Zowel HAL link, identificatie en type opnemen. Voorstel ook uitwerken voor de landelijke API strategie.

**Comment by JanWillemKooi** [comment]
Ook opnemen in de design decision.

**Comment by JohanBoer** [comment]
N.a.v. de beslissing om templated URL's te gaan aanbieden als HalLink gaan we voor **iedere** gerelateerde resource de id's opnemen als element in de basis resource. Ook dat moet nog vastgelegd worden als design dcision.

**Comment by JohanBoer** [comment]
Voor alle gerelateerde resources de id's opgenomen. Ook enkel links  tot commentaar gebombardeerd omdat er geen endpoint voo de betreffende links beschikbaar is. Dan moet je die ook niet aanbieden.
