### ISSUE TITLE
Als PO wil ik een SLA voor de API wordt afgesproken  

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#23]
...zodat de API in productie door (alle) binnengemeentelijke afnemers kan worden gebruikt.

**Acceptatiecriteria**
- Acceptabel voor gebruik door weinig gebruikers (10 bevragingen per uur per gemeente)
- Service window binnen kantooruren (8.00 uur 18.00 uur)
- responsetijden < 1 seconde.

**Definition of done**
- goedgekeurde SLA door alle gemeenten die binnen de projectperiode een consumer realiseren

**Comment by CathyDingemanse** [comment]
Hilde Vos, Kadaster maakt voorstel

**Comment by JanWillemKooi** [comment]
Hilde heeft gisteren vlak voor haar vakantie een laatste versie opgeleverd aan Marianne en Karin. Als zij akkoord zijn gaat deze naar Cathy.

**Comment by JanWillemKooi** [comment]
N.a.v. call van 20 mrt: Hilde heeft een voorstel dat Marianne met Karin gaat bespreken. Daarna gaat deze naar Cathy.

**Comment by JanWillemKooi** [comment]
Tijdens de Sprintwissel van 2 - 3 is als team besloten dat deze US voldoende afgerond is.
