### ISSUE TITLE
Lege lijsten worden meegegeven in resultaat

### ISSUE THREAD

**Issue by hvdijk-p5** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#230]
In het resultaat worden op dit moment lege lijsten getoond:

Voorbeeld 1
https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76370602970000 heeft in resultaat:

"onderzoekErfdienstbaarheden": {},

Voorbeeld 2
https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76370602970000/privaatrechtelijkebeperkingen

"_embedded": {
        "aantekeningen": []
    }

Let op, hier moet aantekeningen weg, maar de lege _embedded blijven staan!

**Comment by CathyDingemanse** [comment]
opgelost
