### ISSUE TITLE
Foutafhandeling niet correct/compleet

### ISSUE THREAD

**Issue by hansvandijk93** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#231]
Ik verwacht dat foutafhandeling op dit moment nog niet compleet geïmplementeerd is, tot zover ben ik in ieder geval alvast het volgende tegengekomen.

Foutafhandeling is op sommige plekken nog niet aanwezig:
-  https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken geeft een blanco 200 response.
- https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76370602970000?expandd=plaatscoordinaten geen validatie op query parameters, het gebruik van expand en fields lijkt uberhaupt nog niet geïmplementeerd.
- Dit komt voor andere paden/foutcombinaties ook voor, ik verwacht daarom dat foutafhandeling in de breedte nog correct geïmplementeerd moet worden.

Opmerkingen over wel geïmplementeerde foutmelding:
- https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.763706029700001 geeft een 404 Not Found response. In het response zijn de correcte velden opgenomen, echter is de inhoud van de velden nog niet correct. Zie https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/master/features/foutafhandeling.feature voor de correcte inhoud.

Voorstel:
Van object Foutbericht is Code nu van het type string, is het een idee om hier een enumeratie met alle gestandaardiseerde foutcodes van te maken? (geldt ook voor de BRP api)

**Comment by fsamwel** [comment]
Ik zie nog de volgende zaken niet of niet goed geïmplementeerd wat betreft foutafhandeling:
- request zonder API Key geeft 400 (Bad request) fout met als body de tekst "Invalid API Key" (dus geen problem+json). Verwacht was een 401 (Unauthorized)
- request met onjuiste (onbekende) API keu geeft een 401 fout (correct) met als body de tekst "Invalid API Key". Verwacht wordt een problem+json bericht zoals gespecificeerd.
- request met niet-ondersteund content-type (in Accept request header) geeft een 406 fout (correct), maar zonder inhoud. Verwacht wordt een problem+json bericht zoals gespecificeerd.

**Comment by fsamwel** [comment]
@JohanBoer @CathyDingemanse waarom is dit destijds op de backlog gezet? Moet dit niet gewoon opgelost worden?

**Comment by CathyDingemanse** [comment]
Jazeker, ik heb geen idee hoe het op de backlog terecht is gekomen. Moet idd gewoon worden opgelost.

**Comment by JohanBoer** [comment]
> @JohanBoer @CathyDingemanse waarom is dit destijds op de backlog gezet? Moet dit niet gewoon opgelost worden?

Ik weet echt niet meer waarom ik dit op 16 januari op de backing gezet heb.

**Comment by rhengeveld** [comment]
* 400/401: Ik ben het met je eens wat betreft de responses op een API key, echter dit wordt afgehandeld door de gateway, wat een generiek Kadaster component is waar ik 0 controle over heb. Oftewel ik denk niet dat we die kunnen oplossen 😝 
* 406: Wordt inderdaad behandeld in #563 
* 404: Moet ik nader bekijken

**Comment by rhengeveld** [comment]
Voorbeeld oplossing **406 Not Acceptable**:
```
{
    "type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?view=netcore-3.1#System_Net_HttpStatusCode_NotAcceptable",
    "title": "Gevraagde contenttype wordt niet ondersteund.",
    "status": 406,
    "detail": "Ondersteunde contenttypes: 'application/hal+json', 'application/problem+json'",
    "instance": "/kadasternatuurlijkpersonen/70882239?fields=kadastraalOnroerendeZaakIdentificaties",
    "code": "notAcceptable"
}
```
Het stond niet expliciet beschreven, dus ik heb ervoor gekozen om in de _details_ de ondersteunde contenttypes ("Accept") terug te geven.

**Comment by fsamwel** [comment]
Vanuit het BAG team is er een nieuwe situatie toegevoegd voor de foutafhandeling: wanneer bij een endpoint een combinatie van parameters niet is toegestaan, wordt de volgende foutmelding gegeven in "title": "De combinatie van opgegeven parameters is niet toegestaan."

Dit is bijvoorbeeld het geval bij /kadastraalonroerendezaken bij het combineren van postcode+huisnummer met kadasterpersoonidentificatie. Nu wordt daar nog "Minimale combinatie van parameters moet worden opgegeven." gegeven, die niet zo duidelijk (niet correct) is.

**Comment by mhebbink-kad** [comment]
> * 400/401: Ik ben het met je eens wat betreft de responses op een API key, echter dit wordt afgehandeld door de gateway, wat een generiek Kadaster component is waar ik 0 controle over heb. Oftewel is door mij niet op te lossen 😝
> * 406: Wordt inderdaad behandeld in #563
> * 404: Moet ik nader bekijken
> 
> **UPDATE** @mhebbink-kad gaat uitzoeken of we in ieder geval iets aan de 400 response kunnen doen

De 400/401 fouten worden afgehandeld door de API gateway en niet door de applicatie zelf. Hierdoor hebben wij geen invloed op de invulling van deze fouten. Aangezien de API gateway een generiek systeem is en meerdere klanten hier gebruik van maken is het niet mogelijk om het formaat hiervan aan te passen op basis van de wensen van 1 klant. 
Wat ik wel heb begrepen van het BAG team is dat de content-type aangepast wordt naar `application/json` i.p.v. `text/plain` van deze fouten.

**Comment by fsamwel** [comment]
Opmerking https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/231#issuecomment-654098542 is verplaatst naar nieuw issue #572

**Comment by fsamwel** [comment]
> De 400/401 fouten worden afgehandeld door de API gateway en niet door de applicatie zelf. 

Heb je het hier over de 400 op het ontbreken van de apikey? Of ook over parametervalidaties? Zoals adres__huisnummer=abc (geen integer) of fields=bestaatNiet (is geen property van resource) of expand=geenResource (geen te expanden subresource). Daar geldt namelijk net als bij 404 dat de titles niet overeen komen met de feature.

**Comment by fsamwel** [comment]
ik krijg onterecht een 404 fout bij /kadastraalonroerendezaken/zakelijkgerechtigden?type=erfpachter

{
   "type" : "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_NotFound",
   "title" : "Opgevraagde resource bestaat niet.",
   "status" : 404,
   "detail" : "Not Found",
   "instance" : "/kadastraalonroerendezaken/zakelijkgerechtigden?type=erfpachter",
   "code" : "notFound"
}

Hier wordt geen zakelijkGerechtigde gevonden, maar dat zou een lege collectie moeten teruggeven met http status code 200.

**Comment by rhengeveld** [comment]
Volgens mij wordt `/kadastraalonroerendezaken/zakelijkgerechtigden` toegepast op URL `/kadastraalonroerendezaken/{kadastraalonroerendezaakidentificatie}`. Die onroerende zaak bestaat inderdaad niet 😉 

Ik denk dat je URL `/kadastraalonroerendezaken/{kadastraalonroerendezaakidentificatie}/zakelijkgerechtigden` bedoeld. Deze geeft inderdaad een 404 response als de onroerende zaak niet bestaat:
![image](https://user-images.githubusercontent.com/1228038/87126725-04819580-c28d-11ea-94cd-e8b4220f571c.png)

Dit terwijl een bestaande onroerendezaak (bijv. 76870487970000) een lege collectie geeft. **Ik zal het aanpassen!**

**Comment by fsamwel** [comment]
ahrg, ik zie het. In laatste omzetting nieuwe OAS was de kadastraalonroerendezaakidentificatie weggevallen uit het request.

**Comment by rhengeveld** [comment]
@fsamwel ik zie nu trouwens dat dit conflicteert met wat in #500 is gesteld. Moet dit nog aangepast worden?

**Comment by fsamwel** [comment]
goed om te checken, want ik had het bedoeld zoals in #500 staat.

als in /kadastraalonroerendezaken/{kadastraalonroerendezaakidentificatie}/zakelijkgerechtigden

1. kadastraalonroerendezaakidentificatie niet bestaat: 404 fout (de uri is immers niet correct)
2. er geen zakelijkgerechtigden zijn: lege collectie teruggeven

als in /kadastraalonroerendezaken/{kadastraalonroerendezaakidentificatie}/zakelijkgerechtigden/{zakelijkgerechtigdeidentificatie}

1. kadastraalonroerendezaakidentificatie niet bestaat: 404 fout 
2. zakelijkgerechtigdeidentificatie niet bestaat in combinatie met kadastraalonroerendezaakidentificatie: 404 fout

Volgens mij werkt dit nu ook zo. Niks aanpassen dus.
Dit is allemaal ontstaan doordat ik mijn testproject moest aanpassen op gewijzigde parameternamen. Daardoor is de waarde voor kadastraalonroerendezaakidentificatie weggevallen en stuurde ik /kadastraalonroerendezaken/zakelijkgerechtigden. Had ik niet gezien (dacht dat ik wel kadastraalonroerendezaakidentificatie had ingevuld), en melde daarom ten onrechte die fout.

**Comment by rhengeveld** [comment]
Duidelijk, geen wijzigingen nodig, dan sluit ik deze melding 🙂

**Comment by fsamwel** [comment]
> Duidelijk, geen wijzigingen nodig, dan sluit ik deze melding 

Nou...
Mijn opmerking over "Niks aanpassen dus." had alleen betrekking op https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/231#issuecomment-656309438.

De eerdere opmerkingen gelden nog wel en zijn dacht ik nog niet opgelost.

**Comment by rhengeveld** [comment]
✔️ Alle punten benoemde in de [eerste opmerking](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/231#issue-534908511) zijn ondertussen opgelost.

> request zonder API Key geeft 400 (Bad request) fout met als body de tekst "Invalid API Key" (dus geen problem+json). Verwacht was een 401 (Unauthorized)
> request met onjuiste (onbekende) API key geeft een 401 fout (correct) met als body de tekst "Invalid API Key". Verwacht wordt een problem+json bericht zoals gespecificeerd.

⚠️ Zoals [beschreven door Marcel](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/231#issuecomment-654657237) kunnen wij 400/401 foutmeldingen die betrekking hebben op de API key niet veranderen, omdat we de APIE gateway niet kunnen aanpassen. Het content-type wordt (ooit) nog veranderd. 
Daarentegen zijn 400 foutmeldingen over ongeldige _fields_ / _expand_ afkomstig van de applicatie, deze kunnen we wél veranderen.

> request met niet-ondersteund content-type (in Accept request header) geeft een 406 fout (correct), maar zonder inhoud. Verwacht wordt een problem+json bericht zoals gespecificeerd.

✔️ Dit is [ondertussen](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/563#issuecomment-656643036) opgelost in eerstvolgende oplevering. Voorbeeld: 
![image](https://user-images.githubusercontent.com/1228038/87519848-72a9cc00-c682-11ea-9030-57a449391d44.png)

> request naar resource(identificatie) die niet bestaat geeft een 404 fout, maar title komt niet overeen met wat verwacht wordt in foutafhandeling feature

✔️ Opgelost in eerstvolgende oplevering. Voorbeeld:
![image](https://user-images.githubusercontent.com/1228038/87517590-57898d00-c67f-11ea-9f27-1f01c2e4f585.png)

> request die fout geeft op parametervalidatie (bijvoorbeeld huisnummer is geen integer, postcode voldoet niet aan pattern, enz.) met 400 fout, komt title niet overeen met foutafhandeling feature

✔️ Opgelost in eerstvolgende oplevering. Voorbeeld:
![image](https://user-images.githubusercontent.com/1228038/87519499-fb743800-c681-11ea-9738-c7a99df4dc7b.png)

**Comment by rhengeveld** [comment]
Beschikbaar op de testomgeving ✔️

**Comment by fsamwel** [comment]
Nog openstaande foutafhandeling issues (exlusief de authenticatie issues) waar antwoord niet overeenkomt met foutafhandeling feature:

- 404 fout title "Not Found" - verwacht "Opgevraagde resource bestaat niet.", code "Not Found" - verwacht "notFound"
Deze zie ik op sommige plekken wel goed en andere plekken niet volgens feature.
/kadastraalonroerendezaken/1234567890123456/zakelijkgerechtigden/30493367  >>> "title" : "Not Found"
/kadastraalonroerendezaken/76870487970000/zakelijkgerechtigden/12345678  >>> "title" : "Opgevraagde resource bestaat niet."

**Comment by rhengeveld** [comment]
Goede vondst, deze heb ik blijkbaar over het hoofd gezien. Zal het oplossen.

**Comment by rhengeveld** [comment]
**Opgelost ✔️ en beschikbaar op de testomgeving**  

![image](https://user-images.githubusercontent.com/1228038/87671225-4325bd00-c771-11ea-9b20-16fcf21ba467.png)

Tevens een onterechte _400 Bad Request_ gevonden opgelost voor request `/kadastraalonroerendezaken/1234/zakelijkgerechtigden/1234` (2x dezelfde identificatie); deze geeft nu ook een _404 Not Found_
