### ISSUE TITLE
HAL links bevatten een onbekend property "type" in het resultaat

### ISSUE THREAD

**Issue by hvdijk-p5** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#233]
De volgende resultaten bevatten property "type" die niet voorkomt in de specs.

https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76370602970000
```
"bagAdressen": [
            {
                "href": "0200200000032765",
                "type": "BAG"
            }
        ],
```
https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76370602970000/zakelijkgerechtigden

```
"_links": {
   "persoon": {
        "href": https://www.haalcentraal.nl/haalcentraal/api/brp/ingeschrevenpersonen/999991905",
        "type": "BRP"
   }
}
```

**Comment by CathyDingemanse** [comment]
niet meer aan de orde
