### ISSUE TITLE
AbstractPersoonCompact mist property type met een enumeratie voor de mogelijke types

### ISSUE THREAD

**Issue by hvdijk-p5** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#234]
AbstractPersoonCompact is de abstracte base class van CompactPersoon en NietNatuurlijkPersoonCompact. Om deze reden moet AbstractPersoonCompact een property "type" bevatten zodat van het json resultaat kan worden afgeleid om welk derived type het gaat. Zie Geometry waar dit ook gedaan is.

Dit is al wel geïmplementeerd in de Brk api maar staat nog niet in de specs, en wordt dus niet gegenereerd. 

https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76370602970000/zakelijkgerechtigden

```
"persoon": {
	"type": "PersoonCompact",
	"identificatie": "999991905",
	"naam": "Linda Haglund",
	"geboortedatum": {
		"dag": 5,
		"datum": "1963-09-05",
		"jaar": 1963,
		"maand": 9
	}
}
```

**Comment by CathyDingemanse** [comment]
is nu anders gemodelleerd. Achterhaald
