### ISSUE TITLE
Hebben Kadaster Persoon paden bewust alleen expands?

### ISSUE THREAD

**Issue by hansvandijk93** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#237]
In de specs zijn voor paden
- ​/kadasternatuurlijkpersonen​/{identificatie}
- /kadasternietnatuurlijkpersonen/{identificatie}

bij de parameters alleen identificatie en expands opgenomen, is fields hier bewust niet aan toegevoegd?

**Comment by JohanBoer** [comment]
Inmiddels is Fields aan deze endpoints toegevoegd en is expand verwijderd omdat we bij de personen geen embedded resources meer hebben gedefinieerd.
