### ISSUE TITLE
Stuk mist property 'type' met een enumeratie voor de mogelijke types

### ISSUE THREAD

**Issue by hvdijk-p5** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#238]
Stuk is de abstracte base class van AangebodenStuk en KadasterStuk. Om deze reden moet Stuk een property "type" bevatten zodat van het json resultaat kan worden afgeleid om welk derived type het gaat. Zie Geometry waar dit ook gedaan is.

Stuk wordt geretourneerd door /stukken/{identificatie}

**Comment by CathyDingemanse** [comment]
is reeds anders gedefinieerd
