### ISSUE TITLE
Pad /hypotheken, moet parameter 'type' een enumeratie hebben?

### ISSUE THREAD

**Issue by hvdijk-p5** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#239]
Het lijkt me handig om hier een enumeratie aan toe te voegen gezien er maar een beperkt aantal mogelijkheden zijn:

> Bij een hypotheek is er sprake van een 'Geldverstrekker' en er is sprake van een 'Onderpandgever'

**Comment by CathyDingemanse** [comment]
is obsolete
