### ISSUE TITLE
Als PO wil ik dat de resource kadastrale onroerende zaak wordt gedefinieerd

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#24]
...zodat een OAS specificatie kan worden gemaakt op basis waarvan een resource kan worden gerealiseerd.

**Acceptatiecriteria**
- resource moet te raadplegen zijn met een ID

Uitvoering Johan Boer.

**Comment by JanWillemKooi** [comment]
Uit deze EPIC ontstaan nieuwe US's
