### ISSUE TITLE
Als PO wil ik dat een beveiligde verbinding wordt gerealiseerd tussen de ETO van het Kadaster en de ontwikkelomgeving van de gemeente Amsterdam

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#25]

**Comment by JanWillemKooi** [comment]
zie #21

**Comment by JanWillemKooi** [comment]
Zie voor update #21

**Comment by JanWillemKooi** [comment]
Deze userstory's zijn gerelateerd aan elkaar: 
#21 (voor Den Haag),
#22 (voor Proces Five)
#25 (voor gemeente Amsterdam)
#26 (voor Vicrea) 

#63 (document met beveiliging specificatie)

**Comment by JanWillemKooi** [comment]
Vandaag (24 apr) is door Vicrea het e-mail adres opgeleverd.

**Comment by JanWillemKooi** [comment]
Status per 24 apr: Gemeente Amsterdam moet nog een e-mail adres aanleveren.

**Comment by JanWillemKooi** [comment]
Update call 1 mei: e-mail adres is aangeleverd. API-key is aangemaakt. Amsterdam kan dit gaan testen.

**Comment by marianneleferink01** [comment]
Update van Jan Willem klopt niet helemaal. Vicrea heeft mail adres doorgegeven; Amsterdam nog niet.

**Comment by JanWillemKooi** [comment]
Update call 8 mei: Agustin gaat achter een e-mail adres aan. Marianne benadrukt dat dit niet een persoonlijk e-mail adres gaat, maar een algemeen e-mail adres waar meerdere personen bij kunnen.

**Comment by MarcelMoerman** [comment]
Is geregeld, e-mail is doorgegeven. API-Key ontvangen, ontwikkelaar heeft gegevens ontvangen.
