### ISSUE TITLE
Type zakelijk gerechtigde (omschrijving) implementeren conform lijstje dat bij bewaarder in review is

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#250]
**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by CathyDingemanse** [comment]
@ Johan, lijst is aangepast door bewaarder. Graag in spec opnemen.

**Comment by mhebbink-kad** [comment]
code wordt meegegeven als parameter van de waardelijst.

**Comment by JohanBoer** [comment]
Opgenomen in de toelichting van de parameter typegerechtigde
