### ISSUE TITLE
Als PO wil ik dat de field en expand parameter wordt geimplementeerd 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#251]
...zodat [vul aan].

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by mhebbink-kad** [comment]
werkt nu alleen voor endpoint /kadastraalonroerendezaken/{kadastraalobjectidentificatie} en ook maar 1 nivo diep. Momenteel zijn we bezig om dit door te voeren voor alle endpoints en ook meerdere nivo's diep.
