### ISSUE TITLE
Parameters hebben niet een prefix van het pad.

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#254]
In BRP (in navolging van Zaken) worden parameters opgenomen met het hele pad. Met dubbele underscore tussen pad-elementen. Bijvoorbeeld naam__voornamen. In BRK is dat niet gedaan. Bijvoorbeeld appartementsrechtVolgnummer zou moeten zijn kadastraleAanduiding__appartementsrechtVolgnummer

**Comment by JohanBoer** [comment]
Dit levert misschien wat onduidelijkheid op bij bijvoorbeeld de kadastraleAanduiding. Perceelnummer en sectie heten kadastraleaanduiding__perceelnummer en kadastraleaanduiding__secti, maar de gemeentecode heet kadastralegemeente__code. 

Als je echter het hele pad mee gaat nemen krijg je extreem lange parameternamen. Ik denk dat we dit moeten accepteren, maar wil graag ook dat er meer mensen over meedenken.

**Comment by JohanBoer** [comment]
Zag dat bij /hypotheken de typegerechtigde als queryparameter ontbrak. Alsnog toegevoegd.

**Comment by fsamwel** [comment]
ik denk dat wanneer een parameter een property is van de resource zelf, we bij de conventie moeten blijven
wanneer het geen property is van de resource, maar van een gerelateerde resource (zoals zakelijk gerechtigde, persoon, adres) we creatief moeten zijn

in het geval van personen hebben we nu in op een aantal plekken alle soorten personen in elkaar geschoven. dus ook een ingeschreven persoon heeft dan een identificatie i.p.v. een burgerservicenummer. dat levert nu issues op, omdat we wel een parameter burgerservicenummer hebben.
een oplossing is om ook voor de parameter alleen identificatie te gebruiken, ongeacht of dit een kadastraal persoonsidentificatie is of een burgerservicenummer (of in de toekomst wellicht een rsin)
ik weet niet zo goed of dit wel duidelijk is, want men kent toch het begrip burgerservicenummer. dat is voor iedereen duidelijk...

**Comment by JohanBoer** [comment]
Ik ben ervoor om alleen de identificatie te gaan gebruiken en de endpoint met het burgerservicenummer te laten vallen, maar ik kan me voorstellen dat dat vanuit gebruiksgemak geen goede keuze is. @MelvLee en @CathyDingemanse wat vinden jullie daarvan. 

Verder snap ik dat we creatief moeten zijn als het geen element uit de resource betreft, maar creativiteit leidt altijd tot meningsverschillen (zie opmerkingen van Frank op mijn creatieve keuzes). Misschien moeten we toch proberen om ook die moeilijkere keuzes in een naamgevingsconventie te gieten.

**Comment by JohanBoer** [comment]
N.a.v bovenstaande 2 beslissingen :

1.  De naamgevingsconventie voor parameters wordt aangepast. Indien een element maar 1 keer in een resource (en bijbehorende groepen en subresources ) voorkomt wordt er niet geprefixed. 
Alleen als een element meermaals voorkomt wordt er een prefix toegepast. In die prefix wordt een zo logisch en eenduidig mogelijke keuze gemaakt. 

2. Het endpoint voor het zoeken van een KOZ op basis van het burgerservicenummer komt te vervallen. Het burgerservicenummer is ook een identificatie van een persoon. Dus bij het zoeken van een KOZ op basis van de persoon_identificatie kan ook het burgerservicenummer in de identificatie gezet worden. Dit moet nog opgenomen worden in de description van dat endpoints.

**Comment by JohanBoer** [comment]
Johan checked en stemt met Marcel af.

**Comment by JohanBoer** [comment]
Afgestemd met Marcel. 
Conclusie t.a.v. punt 1 : De path-parameter KadastraalObjectIdentificatie wordt omgenoemd naar KadastraalOnroerendeZaakIdentificatie. 
Conclusie t.a.v. punt 2 : Dit wordt niet doorgevoerd. Het is aan de provider-side aanzienlijk moeilijker om uit 1 veld te kunnen bepalen of het nu om een burgerservicenummer gaat of een kadasterpersoonIdentificatie omdat er geen type-persoon als parameter wordt meegeleverd (wat wel in de response zit.).

**Comment by JohanBoer** [comment]
N.a.v. #354 Opnieuw afgestemd met Marcel. Daar bleek een aanvullende beslissing te staan t.a.v. de path parameters. Alle path-parameters krijgen de prefix van de resource in hun naam. 
In die issue is bijkomend de beslissing genomen dat alle identificatie-properties in de resources "identificatie" genoemd worden. Dus in de resource KadastraalOnroerendeZaak wordt de "kadastraalOnroerendeZaakIdentificatie" omgenoemd naar "identificatie.
