### ISSUE TITLE
Endpoint voor Aantekeningen nodig ?

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#256]
In de _links van zakelijkGerechtigden staat de link naar aantekeningen .
Er is geen endpoint voor aantekeningen gedefinieerd. 

Is hier wel behoefte aan of moet de link naar aantekeningen verwijderd worden ?

**Comment by JohanBoer** [comment]
Voor de link persoon is er geen endpoint wanneer de persoon geen ingeschreven persoon is (niet in BRP of HR staat): de kadasterpersonen. Wordt in die gevallen geen link opgenomen? Of moeten endpoints nog worden toegevoegd?

**Comment by CathyDingemanse** [comment]
We hadden afgesproken dat er een link komt naar de kadasterPersoon en de kadasterNietNatuurlijkPersoon.

**Comment by fsamwel** [comment]
Zie #221 opmerking 20:
> Aantekeningen horen gewoon bij het Zakelijk Recht (dus bij de ZakelijkGerechtigde). Wat mij betreft dus geen aparte link(s).
Aangepast.

Ik concludeer hieruit dat de links naar aantekeningen moeten worden verwijderd  op verschillende plekken (i.t.t. wat in #221 staat dat het is aangepast):
- Hypotheek_links
- Beslag_links
- KadastraalOnroerendeZaak_links
- ZakelijkGerechtigde_links

Idem voor het embedded ervan, toch?
- KadastraalOnroerendeZaak_embedded

@CathyDingemanse @mhebbink-kad @JohanBoer klopt dat?

**Comment by JohanBoer** [comment]
De links heb ik nu verwijderd, maar voor de embedded is dat niet vanzelfsprekend. Als de business de aantekening embedded meegeleverd wil krijgen kan dat. Er is alleen geen zelfstandig endpoint naar die aantekening toe.

@CathyDingemanse  Wil je dat de aantekening embedded opgenomen blijft bij de KadastraalOnroerendeZaak ?

**Comment by fsamwel** [comment]
Waarom dan niet de aantekeningen opnemen als gegevensgroep?

**Comment by CathyDingemanse** [comment]
> Waarom dan niet de aantekeningen opnemen als gegevensgroep?

Volgens mij zijn de aantekening al als gegevensgroep van de tenaamstelling opgenomen in de zakelijk gerechtigde, zoals door Marianne aangegeven in #221.

Na overleg met Hilde komen wij tot de volgende conclusie:
- De aantekeningen voor publiekrechtelijke beperkingen zijn voor nu buiten scope, want die komen met "beter kenbaar"
- Privaatrechtelijke aantekening zijn overgeheveld naar het recht zelf, dus daar hoeven we ze niet meer apart op te nemen,

Dat zou het moeten zijn.
