### ISSUE TITLE
Als PO wil ik dat een beveiligde verbinding wordt gerealiseerd tussen de ETO van het Kadaster en de ontwikkelomgeving van Vicrea

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#26]

**Comment by JanWillemKooi** [comment]
Zie #21

**Comment by JanWillemKooi** [comment]
Zie voor update #21

**Comment by JanWillemKooi** [comment]
Deze userstory's zijn gerelateerd aan elkaar: 
#21 (voor Den Haag),
#22 (voor Proces Five)
#25 (voor gemeente Amsterdam)
#26 (voor Vicrea) 

#63 (document met beveiliging specificatie)

**Comment by JanWillemKooi** [comment]
Update call 1 mei: e-mail adres is aangeleverd. API-key is aangemaakt en door Vicrea vanmorgen ontvangen.

**Comment by JanWillemKooi** [comment]
Update call 8 mei: Remco geeft aan dat het werkt. Remco heeft ook code generatie geprobeerd op basis van de JSON die vanuit de test-API terug komt. Hij heeft een paar issue en die gedeeld met Johan per e-mail. Marianne geeft aan dat dit nog niet de echte API is. De scope van deze US is afgerond dus hij gaat naar Done.
