### ISSUE TITLE
Als PO wil ik een overzicht van Haal Centraal foutcodes die worden gebuikt door BRP waar naar kan worden verwezen

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#261]
...zodat Marcel hier naar kan verwijzen.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by fsamwel** [comment]
400: https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_BadRequest
401: https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_Unauthorized
403: https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_Forbidden
404: https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_NotFound
500: https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_InternalServerError

**Comment by fsamwel** [comment]
@mhebbink-kad Hoi Marcel, ik heb de type vulling, zoals we die in Den Haag voor de BRP API gebruiken toegevoegd. Groeten, Frank
