### ISSUE TITLE
Als PO wil ik een zoek API (RPC) voor de kadastrale onroerende zaak conform BAG 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#262]
...zodat e.e.a. consistent is.

**Acceptatiecriteria**
- De specificatie is free query, de implementatie beperkt zich tot de zoekopties postcode/huisnummer/huisletter/huisnummertoevoeging en openbare ruimte, huisnummer huisletter en huisnummertoevoeging
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by JohanBoer** [comment]
In het endpoint /kadastraalonroerendezaken/ worden postcode huisnummer huisletter en huisnummertoevoeging toegevoegd. De free query endpoint wordt later toegevoegd. 
Huisnummer, huisletter en huisnummertoevoeging mogen alleen in combinatie met de postcode worden ingevuld. (Toevoegen aan decription)
