### ISSUE TITLE
Als PO wil ik dat de free query zoekapi voor kadasterpersonen consistent wordt gemaakt de zoekapi's voor BAG en BRK

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#263]
...zodat [vul aan].

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by JohanBoer** [comment]
Er is een discussie gepasseerd over het al dan niet restfull maken van de zoek-functie voor adressen. Melvi's voorstel was om het zoeken meer restful te maken en het zoek endpoint te integreren in /adressen.   Daarmee komt /adressen/zoeken te vervallen. 

Als ik dit doorvertaal naar BRK dan wordt  de (free-query) zoekfunctionaliteit  voor personen aangeboden op /kadasternatuurlijkpersonen  en op /kadasternietnatuurlijkpersonen 

Dit is ook  zzo geïmplementeerd middel #262. Volgens mij hebben we ook ergens afgesproken dat dit als design decision vastgelegd moet worden, maar dat kan ik niet meer terugvinden in de issues.....

Gaarne bevestiging van aanwezigen bij de ontwerpsessie BRK.....

**Comment by JohanBoer** [comment]
Bovenstaande is niet goed gegaan. Ik heb onterecht 2 endpoints toegevoegd terwijl we een aparte Zoek-API hebben omdat die ook apart geïmplementeerd moet worden. 

De discusiie over het "zoeken"- keyword verander hier niet mee volgens mij. Ik verwijder de aangemaakte endpoints weer.
