### ISSUE TITLE
Als PO wil ik dat de termen geldverstrekker en onderpandgever wordt afgestemd met bewaarder

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#266]
...zodat [vul aan].

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by JohanBoer** [comment]
Marcel, ik hoorde gisteren wel dat jij dit met de bewaarder had besproken. Onderpandgever werd niet geregistreerd (is verwerkt) , maar ik weet niet of de term geldverstrekker nu akkoord is.  Zie ook opmerking van Frank bioj #264

**Comment by mhebbink-kad** [comment]
Vraag ligt bij de bewaarder.

**Comment by mhebbink-kad** [comment]
Antwoord bewaarder: 
> We registreren bij het Kadaster hypotheken en hebben het in KOL en op de site en in onze producten over hypotheekinformatie, hypotheek en hypotheekhouder. Ik vind ook dat we die terminologie moeten blijven gebruiken. We registreren tenslotte de hypotheek en niet de specifieke geldlening. We zouden wel in de begrippenlijst op kunnen nemen dat de hypotheekhouder degene is die een recht van hypotheek vestigt voor de zekerheid van de lening die hij als geldverstrekker heeft verstrekt.

Dus graag de term **hypotheekhouder** gebruiken.

**Comment by CathyDingemanse** [comment]
Ok, dan maken we een andere omschrijving. Gebaseerd op bovenstaande wordt de description dan:
"De hypotheekhouder is de geldverstrekker die een recht van hypotheek vestigt als zekerheid voor de lening." 
Akkoord?
