### ISSUE TITLE
Als PO wil ik de BRK waardenlijsten als API gespecificeerd hebben

### ISSUE THREAD

**Issue by mhebbink-kad** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#267]
...zodat [vul aan].

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by fsamwel** [comment]
Zie [specificaties landelijke tabellen BRP](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/master/api-specificatie/Landelijke%20tabellen/openapi.yaml)

**Comment by fsamwel** [comment]
[Voorbeeldimplementatie](http://www.quality-of-service.nl/landelijke_tabellen/tabellen) landelijke tabellen BRP
