### ISSUE TITLE
Als PO wil ik een consumer friendly spec van de link naar personen in de zakelijk gerechtigden

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#271]
...zodat de consumer een loose coupled implementatie van een client kan maken .

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by JohanBoer** [comment]
@MelvLee , Volgens mij heb jij deze nu opgenomen op het niveau van de zakelijkgerechtigde, maar er staan ook persoonsgegevens (inclusief identificatie) in de gegevensgroep tenaamstelling. Dat wil zeggen dat we nu op 2 plekken binnen de zakelijk gerechtigde de identificatie naar de persoon vastleggen en ook nog op verschillende manier. 

@CathyDingemanse Wil je in de zakelijk gerechtigde alleen de links naar de persoon of wil je ook de naam / geboortedatum danwel de statutairenaam terug (Dit heeft ook een relatie met de mail die Frank vanmorgen verstuurd heeft.)

**Comment by MelvLee** [comment]
@JohanBoer de persoon en stukken property in ZakelijkGerechtigde is niet correct. De discriminator mag alleen gebruikt worden i.c.m. met oneOf, allOf, anyOf keywords. Bij beide properties is dit niet het geval. Dit was één van de issues die ik met mijn pull request had gefixt. Deze heb ik over het hoofd gezien

**Comment by JohanBoer** [comment]
@MelvLee Zou deze dan alsnog correct kunnen maken en is deze in de gegevensgroep Tennaamstellingen voor de persoon dan wel correct ? 
Maar de kern van mijn opmerking was dat er nu op 2 plekken een referentie naar de persoon voorkomt in de component ZakelijkeGerechtigde. Daar kan er 1 van weg lijkt mij.

**Comment by CathyDingemanse** [comment]
> @CathyDingemanse Wil je in de zakelijk gerechtigde alleen de links naar de persoon of wil je ook de naam / geboortedatum danwel de statutairenaam terug (Dit heeft ook een relatie met de mail die Frank vanmorgen verstuurd heeft.)

Dit hangt idd samen met de mail van vanmorgen, en ook met consistentie over de verschillende API's zoals ik van Melvin begrijp. Ik heb aan Melvin gevraagd om de verschillende scenario's te visualiseren, zodat we hierover een beslissing kunnen nemen.
