### ISSUE TITLE
Als medewerker Erfpacht wil ik weten wie het recht van erfpacht heeft van een kadastrale onroerende zaak binnen en buiten de gemeentegrenzen waarvan de gemeente het eigendom heeft

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#28]
...zodat ik kan bepalen bij wie de erfpacht geind kan worden
En ik deze ingeschreven of niet ingeschreven natuurlijke of niet natuurlijke persoon een rekening kan sturen

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by JanWillemKooi** [comment]
Feedback Marco B: Waarom de specificatie ‘Waar de gemeente het eigendom heeft’? Ik heb geen idee of er andere gevallen van eigendom zijn met erfpacht, maar ik kan me voorstellen dat andere gevallen ook relevant zijn. Zouden we deze story niet breder moeten trekken en eigenlijk moeten kijken naar alle zakelijke rechten op percelen, dus inclusief vruchtgebruik, opstal en gestapelde rechten?

**Comment by JohanBoer** [comment]
Bij de eerste versie die gerealiseerd is worden alle zakelijke rechten van een kadastraal object opgeleverd zonder selectiecriteria. Dat is conform het voorstel van Marco B.

**Comment by JohanBoer** [comment]
Op basis van haar eigen kadastrale identificatie kan de gemeente alle kadastraal onroerende zaken ophalen die zij in eigendom heeft. In de respons zitten per kadastraal onroerende zaak de gegevens alle zakelijkgerechtigden van de kadastraal onroerende zaak (expand=zakelijkGerechtigden). Van die zakelijk gerechtigden zullen dan door de consumer alleen degene met typegerechtigde=Erfpachthouder worden gefilterd.
