### ISSUE TITLE
Hoe moet waarde Onbekend uit waardelijst burgelijkeStaatTenTijdeVanVerkrijging afgehandeld worden. 

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#285]
Uit de mail van Frank dd 28-01-2020 

In de waardelijst voor burgerlijkeStaatTenTijdeVanVerkrijging, zit een waarde voor Onbekend. Wordt die (net als in BRP) leeggelaten?
Dat zal een implementatie-eis moeten zijn. Ik weet niet of dat nu zo is.
Mijn voorkeur gaat uit naar leeg laten

Hier moet dus nog een beslissing over worden genomen en verwerkt in een design decision en/of feature.

Liefst een generieke beslissing dat alle waarden "Onbekend"uit waardelijsten op dezelfde wijze worden behandeld.

**Comment by CathyDingemanse** [comment]
Als het kan leeg laten!

**Comment by JohanBoer** [comment]
Marcel controleert in hoeverre dit is geïmplementeerd.

**Comment by rhengeveld** [comment]
Dit was nog niet geïmplementeerd. Heb dit zojuist aangepast; als een waardelijst de waarde _"onbekend"_ heeft (hoofdletterongevoelig) dan wordt de waardelijst nu leeg (null) gelaten.  

Dit komt mee in een toekomstige release / update.
