### ISSUE TITLE
Adreseen bij personen als embedded subresources of als gegevensgroepen opnemen.

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#286]
Nav opmerking van Frank dd 28-01: 

In _embedded van KadasterNatuurlijkpersoon en KadasterNietNatuurlijkPersoon zitten een aantal gerelateerde resources, terwijl hier in _links geen relaties naar zijn. De gebruiker is dus verplicht expand/_embedded te gebruiken om te weten of en welke relaties er zijn. Ik zou het ook mogelijk willen maken deze gerelateerde resources op te halen vanuit _links.

Als er geen endpoints voor deze adressen komen is het ook het overwegen waard om deze als gegevensgroep op te nemen.

**Comment by CathyDingemanse** [comment]
De laatste overweging lijkt prima, ook voor woonlocatie binnenland en postlocatie binnenland. Dit zijn BAG adressen. Op dezelfde manier oplossen als in de BRP? Opnemen als gegevensgroep + link naar BAG?
