### ISSUE TITLE
Component Waardelijst dubbel gebruikt

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#291]
# Impediment

We hebben nu in de common.yaml een component Waardelijst die een waardelijstwaarde (combinatie code en waarde voor een specifieke rij in een waardelijst) bevat.
We hebben ook in de Waardelijsten API een component Waardelijst die een waardelijst (combinatie code en omschrijving voor een specifieke waardelijst) bevat.

Bij resolven en bij genereren gaat dit niet goed. We hebben dan twee componenten=twee classes met dezelfde naam. Een van de twee wordt dan bijvoorbeeld Waardelijst_2.

Ik denk dat we een van de twee een andere naam moeten geven die nog wel voldoende verwijst naar "Waardelijst" uit het imKad.

Bijvoorbeeld voor de Waardelijsten API kan Waardelijst worden:
* Lijst
* ...

Bijvoorbeeld in common.yaml (en alle referenties hiernaar) kan Waardelijst worden:
* LijstWaarde
* WaardelijstWaarde
* ...

@MelvLee @JohanBoer @mhebbink-kad suggesties of voorkeuren?

**Comment by MelvLee** [comment]
Is het in dit geval niet beter om de code en waarde properties toe te voegen in deze waardelijst i.p.v deze te referencen van de common implementatie? Er is heel veel veranderd om dit mogelijk te maken.

Ook vind ik het toevoegen van BRK_ niet echt handig, want als de BAG ook waardelijsten heeft, krijgen we dan ook een BAG_ variant?

Wat was/is de reden dat datumVanaf, datumTot en toelichting properties niet bij de Haal-Centraal common waardelijst zijn toegevoegd? Want als ze optioneel zijn zouden ze niet tot breaking changes leiden bij de BRP versie.

**Comment by JohanBoer** [comment]
In het algemeen:  De commit die ik gedaan heb was voordat ik doorhad dat Frank hiervoor al een Pullrequest had gedaan. Ik heb per abuis gecommit op de master. Ik wil graag in overleg met Frank die fout rechttrekken.
