### ISSUE TITLE
Als PO wil ik aanpassingen op de schema descriptions 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#292]
zodat alleen beschrijvingen worden opgenomen die informatief en relevant zijn voor de consumer.

Acceptatiecriteria
[ ]
[ ]
Definition of done
functionele specificatie
Open API specificatie
gegenereerde code
testgevallen

**Comment by CathyDingemanse** [comment]
Schema's:

Aantekeningen descriptions:
Was:
Waardelijst is een samengesteld datatype voor het weergeven van een gegeven binnen een extern beheerde referentielijst.
code: De code van deze waarde. De code is uniek binnen de Waardelijst en taalonafhankelijk.
waarde: De waarde zoals aangetroffen in de Waardelijst. het moment waarop de waarde geassocieerd is met de meegeleverde code is onbepaald.
Wordt:
Geen description. Een waardenlijst is een lijst met codes en bijbehorende waarden. Maar dat staat al in het schema, dus dat hoeven we niet ook nog eens in de beschrijving te zetten (dubbelop). Bovenstaande description biedt geen verduidelijking en is bovendien irrelevant voor de gebruiker.

Graag de toelichting bij code en waarde ook weg. De code die bij de waarde hoort en de waarde die bij de code hoort....haha. Let's not go there....

Bij HypotheekHal: Hypotheek_links{geldverstrekkerisGeldverstrekker}
Staat nog het woord geldverstrekker. Dit moet zijn hypotheeknemer, zie voor uitkomst en tekst #266...zodat [vul aan].

KadastraalOnroerendeZaak bij kadastraleAanduiding TypeKadastraleAanduiding:
Was:
Kadastrale aanduiding is de unieke aanduiding van een onroerende zaak, die door het kadaster wordt vastgesteld. Percelen worden kadastraal aangeduid door vermelding van achtereenvolgens de kadastrale gemeente en sectie, waarin de percelen en gedeelten van percelen zijn gelegen waarvan het grondgebied tot die zaak behoort, alsmede de nummers van die percelen. Voor een onroerende zaak die zich krachtens een opstalrecht op, in of boven de grond van een ander bevindt, geldt dezelfde kadastrale aanduiding als van de onroerende zaak die met dat opstalrecht is bezwaard. Dit is van overeenkomstige toepassing op een onroerende zaak die zich op, in of boven de grond van een ander bevindt krachtens een recht als bedoeld in het voor 1 januari 1992 geldende artikel 5, derde lid, onder b, laatste zinsnede, van de Belemmeringenwet Privaatrecht. Appartementsrechten worden kadastraal aangeduid door de vermelding van achtereenvolgens de kadastrale gemeente en sectie, waarin de in de splitsing betrokken percelen zijn gelegen, de complexaanduiding en de appartementsindex (Een oplopend volgnummer van 0001 tot 9999). De complexaanduiding bestaat uit het voor de in de splitsing betrokken percelen vastgestelde complexnummer, gevolgd door de hoofdletter A. Onze Minister stelt regelen vast omtrent de vaststelling van het complexnummer. Er zijn 1111 kadastrale gemeentenamen. Elke kadastrale gemeentenaam is uniek.

Wordt:
Kadastrale aanduiding is de unieke aanduiding van een onroerende zaak door het Kadaster

**Comment by CathyDingemanse** [comment]
@HildeVos , graag reviewen!

**Comment by JohanBoer** [comment]
Johan voert deze door in een aparte pull request mey #332 net vraagt @HildeVos  om review.

**Comment by fsamwel** [comment]
@CathyDingemanse de descriptions van waardelijsten (zie #309 en #376) verwijzen nu alleen via een url naar de waardelijst. Wat het property is, staat er niet. Wat is bijvoorbeeld statusStukOr of AKRregistercode? Deze zitten nu ook niet beschreven in dit issue. Is het op basis van alleen de mogelijke waarden voldoende duidelijk waar dit over gaat? Ik weet bijvoorbeeld niet wat het AKRregister is, of wat die "Or" is bij de status stuk.

**Comment by CathyDingemanse** [comment]
statusstukOr
Geeft aan wat de juridische status is van een aangeboden stuk.

AKRregistercode
Code van een kadasterstuk uit een voormalige registratie, bedoeld om vervolgonderzoek gemakkelijker mogelijk te maken. 

perceelnummerRotatie:
Rotatie van het perceelnummer ten behoeve van visualisatie op de kaart. Perceelnummers worden bijvoorbeeld gekanteld om in een smal perceel te passen.

Perceelnummerverschuiving: 
Verschuiving van het perceelnummer ten behoeve van visualisatie op een kaart. Dit voorkomt dat perceelnummers van kleine percelen elkaar overlappen.

Aardcultuurbebouwd & AardcultuurOnbebouwd
Geen aparte description. De betekenis kan beter worden opgemaakt uit de waarde dan dat ik het kan omschrijven. @HildeVos heb jij een beter voorstel?

**Comment by HildeVos** [comment]
Opmerking van Thijs over bewaardersverklaring: Makkelijkere omschrijving is dat een bewaardersverklaring een correctie in de openbare registers zelf is, omdat de bewaardersverklaring zelf een stuk in de openbare registers is.

Ik heb zelf verder ook alles bekeken. Nog een aantal opmerkingen:
* 'Beslag 
Een beslag is een tijdelijke maatregel waarbij de overheid bepaalde zaken van iemand afneemt, zodat hij er niets meer mee kan doen' --> Is gekopieerd uit het Kadaster woordenboek, maar is niet echt een duidelijke omschrijving. Voorstel: Een beslag is een tijdelijke maatregel opgelegd door een partij (hoeft niet per se overheid te zijn) waardoor de zakelijk gerechtigde niets met de KOZ kan doen.
* 'Kadasternatuurlijkpersoon 
een bij het kadaster geregistreerde natuurlijke persoon die niet in de basisregistratie personen (BRP) is ingeschreven.   Kadasternatuurlijkpersonen worden niet geactualiseerd.' --> Kan ook zijn dat een persoon wel is ingeschreven in de BRP maar wij niet hebben kunnen koppelen. Kadasternatuurlijkpersonen worden wel geactualiseerd (subjectnr en BSN blijven gelijk, maar overige gegevens worden wel geactualiseerd)
* 'Kadasternietnatuurlijkpersoon(HAL)
een bij het kadaster geregistreerde niet natuurlijke persoon die niet in het Handelsregister is ingeschreven.   Kadasternietnatuurlijkpersonen worden niet geactualiseerd.' --> Of NNP die niet gekoppeld kan worden (komt vaak voor).

**Comment by HildeVos** [comment]
Aardcultuurbebouwd & AardcultuurOnbebouwd
Geen aparte description. De betekenis kan beter worden opgemaakt uit de waarde dan dat ik het kan omschrijven. @HildeVos heb jij een beter voorstel?

In het Kadaster woordenboek staat bij Cultuurcode: Een cultuurcode is een aanduiding van het gebruik van een stuk grond en alles wat erin of erop staat.

De cultuurcode wordt alleen op basis van een ingeschreven stuk gewijzigd.

**Comment by CathyDingemanse** [comment]
> Aardcultuurbebouwd & AardcultuurOnbebouwd
> Geen aparte description. De betekenis kan beter worden opgemaakt uit de waarde dan dat ik het kan omschrijven. @HildeVos heb jij een beter voorstel?
> 
> In het Kadaster woordenboek staat bij Cultuurcode: Een cultuurcode is een aanduiding van het gebruik van een stuk grond en alles wat erin of erop staat.
> 
> De cultuurcode wordt alleen op basis van een ingeschreven stuk gewijzigd.

Duidelijk! Doen we zo!

**Comment by CathyDingemanse** [comment]
bewaardersverklaring:  
correctie in de openbare registers door de bewaarder.
> 
 
> * 'Beslag
> Tijdelijke maatregel opgelegd door een partij (hoeft niet per se overheid te zijn) waardoor de zakelijk gerechtigde niets met de kadastraal onroerende zaak kan doen.


Duidelijk, @JohanBoer ik heb mijn varianten hiervan aangepast of verwijderd. Graag deze beschrijvingen overnemen!

**Comment by JohanBoer** [comment]
> [ ] - gezamenlijk aandeel: wanneer twee of meer personen een gezamenlijk aandeel hebben in een zakelijk recht, waarbij het afzonderlijke aandeel in het gezamenlijk aandeel niet bekend is.

Dit is een verwijzing naar TypeBruek. Die beschrijving kan ik niet opnemen bij typebreuk en als ik de description bij gezamenlijkAandeel opneem wordt deze niet in de swagger weergave getoond. Dat laatste heb ik gedaan. 

> [ ] - identificatie: Unieke identificatie voor de persoon. Voor een Kadasterpersoon is dit de identificatie zoals die door het Kadaster is vastgesteld. Voor een ingeschreven natuurlijk persoon is dit het burgerservicenummer.

De identificatie wordt voor beide personen (natuurlijk en niet-natuurlijk ) hergebruikt vanuit de persoonBasis. Ik heb de omschrijvingen samengevoegd. 


> Cultuurcode bebouwd en cultuurcode onbebouwd
> 
> * [ ]  Cultuurcode is een aanduiding van het gebruik van een stuk grond en alles wat erin of erop staat. De cultuurcode wordt alleen op basis van een ingeschreven stuk gewijzigd.

Dit zijn waardelijsten. Ik kan hier alleen een specifieke omschrijving toevoege als ik de allOf constructie toevoeg. Dat is ongewenst omdat er dan overtollige objectej worden gegenereerd. Ik heb deze description niet toegevoegd

> statusstukOr (vervanging zie boven, had ik al geadresseerd)
> 
> * [ ]  description: Geeft aan wat de juridische status is van een aangeboden stuk.
> 
> AKRregistercode
> 
> * [ ]  Code van een kadasterstuk uit een voormalige registratie, bedoeld om vervolgonderzoek gemakkelijker mogelijk te maken.

Dit zijn ook waardelijsten. Daar geldt hetzelfde voor. 

> @JohanBoer ik heb mijn varianten aangepast op de opmerkingen van Hilde en Thijs. Succes met overnemen!

@Cathy: jouw omschrijvingen van Kadaster(niet)NatuurllijkPersoon  zijn niet aangepast aan de laatste opmerkingen van Hilde. Is dat terecht ?

**Comment by CathyDingemanse** [comment]
> 
> > @JohanBoer ik heb mijn varianten aangepast op de opmerkingen van Hilde en Thijs. Succes met overnemen!
> 
> @Cathy: jouw omschrijvingen van Kadaster(niet)NatuurllijkPersoon zijn niet aangepast aan de laatste opmerkingen van Hilde. Is dat terecht ?

Ja klopt.
