### ISSUE TITLE
Update openapi.yaml specificaties (2020-03-12 12:06)

### ISSUE THREAD

**Issue by kad-hebbim** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#301]
versie: https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/blob/master/specificatie/BRK-Bevragen/openapi.yaml (12-3-2020 12:06)

**Comment by mhebbink-kad** [comment]
nav aanpassing ZakelijkGerechtigden/Kadasterpersonen
