### ISSUE TITLE
OAS aanpassen, zodat deze aansluit op de MVP.

### ISSUE THREAD

**Issue by mhebbink-kad** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#302]

**Comment by JohanBoer** [comment]
Maak een versie vn de OAS waarin alleen de onderdelen staan die door het Kadaster worden gerealiseerd en die we op de API-lab aanbieden. 

MVP: Kadaster
•	Kadastraal onroerende zaak + zakelijk gerechtigden
•	Zoeken persoon
•	Zoeken kadastraal onroerende zaak op pc hnr
•	Zoeken kadastraal onroerende zaak op persoon
•	testgevallen
•	Getest met postman door Frank, Remco en ontwikkelaar Adam

**Comment by mhebbink-kad** [comment]
In MVP zitten de volgende endpoints:
- /kadastraalonroerendezaken
- /kadastraalonroerendezaken/{kadastraalonroerendezaakidentificatie}
- /kadastraalonroerendezaken/{kadastraalonroerendezaakidentificatie}/zakelijkgerechtigden/{zakelijkgerechtigdeidentificatie}
- /kadastraalonroerendezaken/{kadastraalonroerendezaakidentificatie}/zakelijkgerechtigden
- /kadasternatuurlijkpersonen/{kadasternatuurlijkpersoonidentificatie}
- /kadasternietnatuurlijkpersonen/{kadasternietnatuurlijkpersoonidentificatie}
- ​/kadasternatuurlijkpersonen
- /kadasternietnatuurlijkpersonen
