### ISSUE TITLE
Specificaties aanpassen betreffende gebruik expand en fields parameters

### ISSUE THREAD

**Issue by kad-hebbim** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#303]

**Comment by fsamwel** [comment]
1. het is nu niet duidelijk wat wel en wat niet expand mag worden --> opnemen in description

2. gebruik fields en expand op _links properties (met of zonder _links)

**Comment by fsamwel** [comment]
eerste punt is opgelost voor /kadastraalonroerendezaken en /kadastraalonroerendezaken/{kadastraalobjectidentificatie} in pull request #308

**Comment by fsamwel** [comment]
tweede punt opgelost in pull request (voor BRP) https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/pull/595
