### ISSUE TITLE
Feature maken om templated urls te gebruiken

### ISSUE THREAD

**Issue by kad-hebbim** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#304]
gebruik van absolute en relatieve urls
documentatie om templated uris te linken aan de identificaties met features/voorbeelden

**Comment by JohanBoer** [comment]
Zie ook BRP issue 563.

**Comment by fsamwel** [comment]
is gemaakt: https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/master/features/uri-templating.feature
