### ISSUE TITLE
nen3610 namespace opgenomen in identificaties

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#311]
in alle BRK identificaties is nu de nen3610 namespace opgenomen. Bijvoorbeeld een identificatie voor een kadastraal onroerende zaak is "NL.IMKAD.KadastraalObject.76370602970000".

Is hier geen sprake van implementation bleed wanneer het (interne) informatiemodel wordt opgenomen in de identificatie?

**Comment by JohanBoer** [comment]
In de definitie (en dus de OAS3 ) wordt dit model niet opgenomen. De identificatie wordt als één string gecommuniceerd.  Ik betwijfel of de afnemers iets kunnen zeggen over de inhoud van die identificatie. In feite dicteert de bron wat er in de identificatie zit. Dus al bij het opvragen van een kadastraal object in de het element "identificatie" de waarde  "NL.IMKAD.KadastraalObject.76370602970000"  wordt geretourneerd, dan is dat de identificatie van dat object en zal dat overal waar deze id wordt vastgelegd (om bv. een relatie vast te leggen) de hele identificatie vastgelegd moeten worden.

**Comment by JohanBoer** [comment]
Bezwaar op bovenstaande oplossing is dat afnemers mogelijk code bouwen op de betekenis van een deel van de identificatie. Dat levert potentieel problemen op bij de afnemers.
