### ISSUE TITLE
Property zonder waarde moet niet worden opgenomen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#312]
GET https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken?burgerservicenummer=999991905

Dit levert in het antwoord: "onderzoekErfdienstbaarheden" : { },

Wanneer een property leeg is, moet die niet worden opgenomen. Dit geldt ook voor een property dat een object (gegevensgroep) is. Wanneer alle properties daarbinnen leeg zijn, en er dus geen enkel property in zit met een waarde, moet het niet worden opgenomen in het antwoord.

**Comment by rhengeveld** [comment]
✔️ opgelost voor _null_ objecten
✔️ opgelost voor lege lijsten of arrays
❌ kan niet zomaar opgelost worden voor lege objecten

De reden dat dit voor lege objecten niet zomaar opgelost kan worden is een technische beperking: we gebruiken momenteel [Jackson](https://github.com/FasterXML/jackson-databind) voor de vertaling van objecten naar JSON, deze lijkt echter nog steeds niet fatsoenlijk _"laat lege objecten weg"_ te ondersteunen ([link](https://github.com/FasterXML/jackson-databind/issues/1934)).

Mogelijke oplossingen hiervoor:
* Schrijven van een [custom Jackson serializer](https://www.baeldung.com/jackson-custom-serialization). Met extra uitdaging dat een object óók leeg is als al diens kinderen _null_ of leeg zijn. Oftewel `"a" : { "a-kind" : {} }"` = `"a" : {}"` = weglaten.
* Overstappen naar [Gson](https://github.com/google/gson) en kijken of die dit _out-of-the-box_ werkend heeft.

Gezien de risico's, het meerwerk om dit _mogelijkerwijs_ op te lossen en de beperkte meerwaarde die dit oplevert heeft het mijn voorkeur om hier niet meer tijd aan te besteden en het te laten voor wat het nu is.

----

Ter illustratie van het verschil tussen een _null_ en leeg object, hierbij een voorbeeld met het opvragen van het veld _begrenzingPerceel_. Velden _identificatie_, _typeKadastraalOnroerendeZaak_ en __links.self_ zijn altijd verplicht aanwezig.

**GET Request**
```
https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken?zakelijkgerechtigde__typegerechtigde=eigenaar&ingeschrevenpersoon__burgerservicenummer=999991905&fields=begrenzingPerceel
````
**Resultaat met "begrenzingPerceel" _null_**
```
{
    "_links": {
        "self": {
            "href": "http://localhost:8080/esd/gemeenten/brk/kadastraalonroerendezaken?zakelijkgerechtigde__typegerechtigde=EiGeNaar&ingeschrevenpersoon__burgerservicenummer=999991905&fields=begrenzingPerceel"
        }
    },
    "_embedded": {
        "kadastraalOnroerendeZaken": [
            {
                "identificatie": "NL.IMKAD.KadastraalObject.22310827210003",
                "typeKadastraalOnroerendeZaak": "appartementsrecht",
                "_links": {
                    "self": {
                        "href": "http://localhost:8080/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.22310827210003"
                    }
                }
            }
        ]
    }
}
```
**Resultaat met "begrenzingPerceel" leeg object**
```
{
    "_links": {
        "self": {
            "href": "http://localhost:8080/esd/gemeenten/brk/kadastraalonroerendezaken?zakelijkgerechtigde__typegerechtigde=EiGeNaar&ingeschrevenpersoon__burgerservicenummer=999991905&fields=begrenzingPerceel"
        }
    },
    "_embedded": {
        "kadastraalOnroerendeZaken": [
            {
                "identificatie": "NL.IMKAD.KadastraalObject.22310827210003",
                "begrenzingPerceel": {},
                "typeKadastraalOnroerendeZaak": "appartementsrecht",
                "_links": {
                    "self": {
                        "href": "http://localhost:8080/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.22310827210003"
                    }
                }
            }
        ]
    }
}
```

**Comment by fsamwel** [comment]
@rhengeveld in het voorbeeld dat je beschrijft heb je al wel een heleboel objecten weggelaten die ook leeg zijn:
  "plaatscoordinaten": {  },
  "koopsom": { },
  "aardCultuurBebouwd": {  },
  "aardCultuurOnbebouwd": {  },
  "kadastraleAanduiding": {  },
  "kadastraleGrootte": {  },
  "perceelnummerVerschuiving": {  }

krijg ik die dan ook altijd terug? Volgens mij was dat tot nu tot niet zo. Of speelt het probleem alleen bij sommige objecten?

Het maakt denk ik wel uit of het gaat om enkele specifieke gegevens of de hele rij zoals hierboven genoemd.

@MelvLee heb jij er als gebruiker (client developer) last van als je lege objecten krijgt?

**Comment by MelvLee** [comment]
Voor het implementeren van business logica is het wel lastig. Je kan dan alleen de conclusie trekken dat een gegevensgroep niet bestaat, als alle properties van dat gegevensgroep null zijn.
Dus niet gegevensgroep == null maar gegevensgroep.property1 == null && gegevensgroep.property2 == null enz.

**Comment by rhengeveld** [comment]
@fsamwel dit geldt momenteel voor alle lege objecten, maar is afhankelijk van _wat_ je opvraagt:  
* Als je niks expliciet opvraagt (geen _fields_ opgeeft) dan krijg je alles terug. Als plaatscoordinaten, koopsom, etc. dan leeg zijn krijg je die ook als zijnde leeg terug. 
* Als je expliciet een veld opvraagt zoals ik in mijn voorbeeld deed, krijg je alleen dat veld terug. Deze kan vervolgens leeg zijn. Andere velden die je _niet_ vroeg die _wel_ leeg zijn krijg je niet terug.

@MelvLee daar heb je een goed punt te pakken, als ik dit niet aanpas verplaats ik het probleem dus eigenlijk naar de ontvanger 😅 

Ok, ik zal het verder oppakken en proberen hier een werkbare oplossing voor te vinden.

**Comment by rhengeveld** [comment]
Oplossing geïmplementeerd; voordat het object (bijv. _KadastraalOnroerendeZaakHal_) wordt aangeboden aan Jackson voor serialisatie naar JSON, worden eerst _recursief_ alle velden nagelopen. Een veld wordt op _null_ als deze leeg is: 
* Bevat lege collectie `[ ]`
* Bevat leeg object `{ }`
* Bevat een lege String `"   "`

Vervolgens zal Jackson deze _null_ velden negeren en niet meegeven in de JSON response.

----

**Voorbeeld 1**
```
{
    "_embedded": {
        "kadastraalOnroerendeZaken": [
            {
                "identificatie": "NL.IMKAD.KadastraalObject.22310827210003",
                "typeKadastraalOnroerendeZaak": null,
                "_links": {
                    "self": {
                        "href": "   "
                    }
                }
            }
        ]
    }
}
``` 
na opschonen krijgen we als resultaat
```
{
    "_embedded": {
        "kadastraalOnroerendeZaken": [
            {
                "identificatie": "NL.IMKAD.KadastraalObject.22310827210003"
            }
        ]
    }
}
```

----

**Voorbeeld 2**
```
{
    "_embedded": {
        "kadastraalOnroerendeZaken": [
            {
                "identificatie": "",
                "typeKadastraalOnroerendeZaak": null,
                "_links": {
                    "self": {
                        "href": "   "
                    }
                }
            }
        ]
    }
}
``` 
na opschonen krijgen we als resultaat
```
{ }
```
Want _**alle**_ onderliggende velden zijn uiteindelijk leeg.

**Comment by fsamwel** [comment]
Ziet er beter uit. Voorbeeld 1 is precies zoals ik het zou verwachten. 

Bij voorbeeld 2 twijfel ik, dit is misschien een uitzondering. 
@MelvLee Wanneer je kadastraalonroerendezaken zoekt en niks is gevonden, wil je dan 
`{ }`
of 
```
{
  "_embedded": { } 
}
```
of 
```
{
  "_embedded": { 
    "kadastraalOnroerendeZaken": [ ]
  }
}
```

**Comment by MelvLee** [comment]
Voor consistentie zou ik ervoor kiezen om bij geen zoek resultaat _embedded null te maken. Je krijgt alleen geen lege response terug omdat ik wel een _links met self link verwacht. Dus:
```
{
  "_links": {
    "self": "<een url>"
  }
}
```

**Comment by rhengeveld** [comment]
Je hebt gelijkt @MelvLee; alle items dienen **altijd** een self link te hebben welke niet leeg is, dus het 2e extreme scenario komt eigenlijk niet voor. Het was meer ter illustratie dat het nu mogelijk is om _cascading_ alles leeg te maken. 

Als er items zijn die geen self link hebben is dit een bug die dient te worden opgelost 😉 
Volgens mij is dit item daarmee opgelost. Komt mee en kan getest worden in de volgende versie.

**Comment by fsamwel** [comment]
dit (antwoord wanneer er geen zoekresultaten zijn) is niet opgelost, zie #464. Ik sluit deze, want het oorspronkelijke issue is wel opgelost.  In #464 wordt het gegeven van antwoord bij 0 resultaten opgelost.
