### ISSUE TITLE
omschrijving onderzoek Erfdienstbaarheden dubbel in antwoord

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#313]
een Kadastraal onroerende zaak heeft nu twee properties die een omschrijving van onderzoek erfdienstbaarheden bevatten:
- omschrijvingOnderzoekErfdienstbaarheden
- onderzoekErfdienstbaarheden.omschrijving

beide hebben als title: omschrijvingOnderzoekErfdienstbaarheden

is dit gegeven niet dubbel opgenomen?

**Comment by CathyDingemanse** [comment]
@ Hilde, kun jij hier antwoord op geven?

**Comment by fsamwel** [comment]
moeten beide verwijderd worden, ook perceelnummertotatie verwijderen en perceelnummerverschuiving

**Comment by JohanBoer** [comment]
Alsnog Perceelnummerrotatie en perceelnummerverschuiving opnemen i.v.m. de update API. Deze elementen zitten wel in de BRK-levering.
