### ISSUE TITLE
ALS WOZ-medewerker WIL IK een notificatie ontvangen wanneer in de BRK een (oud) kadastraal object is gesplitst in twee of meer (nieuwe) kadastrale objecten

### ISSUE THREAD

**Issue by paul-pfc** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#314]
...ZODAT ik de WOZ-administratie kan actualiseren.

**Acceptatiecriteria**
- [ ] notificatie bevat aanduiding van het soort gebeurtenis (splitsing kadastraal object)
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by CathyDingemanse** [comment]
duplicaat #422 
sluiten
