### ISSUE TITLE
ALS WOZ-medewerker WIL IK een notificatie ontvangen wanneer in de BRK n.a.v. appartementsrechtssplitsing een appartementscomplex is gevormd

### ISSUE THREAD

**Issue by paul-pfc** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#319]
...ZODAT ik de WOZ-administratie kan actualiseren.

Iedere splitsing apart of in bulk?
Splitsing tbv Appartementscomplex is hetzelfde als iedere andere splitsing.
Voorstel: sluiten

**Acceptatiecriteria**
- [ ] notificatie bevat aanduiding van het soort gebeurtenis (Vormen appartementsrechtbasis)
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by CathyDingemanse** [comment]
sluiten, duplicaat
