### ISSUE TITLE
ALS WOZ-medewerker WIL IK een notificatie ontvangen wanneer in de BRK twee of meer groepen van gegevens (kadastraal objectgegevens, zakelijke rechten met bijbehorende aantekeningen, kadastraal object aantekeningen) van één of meer kadastrale objecten zijn gewijzgd

### ISSUE THREAD

**Issue by paul-pfc** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#323]
...ZODAT ik de WOZ-administratie kan actualiseren.

Onduidelijk waarom twee of meer wijzigingen tot een specifieke trigger moeten leiden. Wijzigingen kunnen individueel worden geleverd of individueel  worden geoormerkt.
Voorstel: sluiten 

**Acceptatiecriteria**
- [ ] notificatie bevat aanduiding van het soort gebeurtenis (Wijziging kadastraal object)
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by CathyDingemanse** [comment]
sluiten
