### ISSUE TITLE
ALS medewerker belastingzaken WIL IK een notificatie ontvangen als één of meer nieuwe Kadastraal Onroerende Zaken (appartementsrechten en parkeerplaatsen) zijn ontstaan 

### ISSUE THREAD

**Issue by paul-pfc** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#324]
...ZODAT ik een of meer nieuwe WOZ objecten kan vormen.

Het ontstaan van een appartementsrecht is het ontstaan van een KOZ zonder dat de KOZ waaruit zij ontstaat wordt beëindigd. 
Na bespreking met het Thijs Pothoven (kadaster): 
Dit kan alleen het ontstaan van een appartementsrecht of parkeerplaats??? zijn: het bijbehorende grondperceel wordt niet beëindigd. Verder kan dit niet voorkomen, tenzij het kadaster een fout maakt.

**Acceptatiecriteria**
- [ ] notificatie bevat aanduiding van het soort gebeurtenis (Ontstaan appartementsrecht)
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by CathyDingemanse** [comment]
duplicaat van #441
