### ISSUE TITLE
zakelijkgerechtigde met identificatie

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#326]
Identificatie van zakelijkgerechtigde == identificatie tenaamstelling
- "identificatie" toevoegen aan zakelijkgerechtigde
- endpoint .../zakelijkgerechtigden/{identificatie} toevoegen
- links naar zakelijkgerechtigden vanuit KOZ templated
- links naar zakelijkgerechtigden vanuit KOZ als array
- array met "zakelijkGerechtigdenIdentificaties" toevoegen in KOZ

**Comment by JohanBoer** [comment]
> * links naar zakelijkgerechtigden vanuit KOZ templated
> * links naar zakelijkgerechtigden vanuit KOZ als array

Frank, deze 2 spreken elkaar tegen. Volgens mij neem ik alleen de templated link naar de zakelijkgerechtigde in de KOZ_links.

**Comment by fsamwel** [comment]
@JohanBoer gisteren hadden we het hier ook kort over volgens mij. Mijn argument is dat we in de interface specificatie (het contract) niet voorschrijven of het als normale url dan wel als templated url wordt geleverd. Dit mag de provider, al dan niet runtime, bepalen. Dus moeten de specs beide manieren ondersteunen. Evolvability dingetje dus.

**Comment by JohanBoer** [comment]
Als we dat doen, dan moeten we deze 2 opties voor alle links gaan bieden, of zie ik dat verkeerd ? 

Daarbij betekent dit dat de consumer niet van tevoren weet hoe hij de links aangeboden krijgt en dus logica moet bouwen om beide manieren te kunnen verwerken. Dat lijkt mij niet consumer-friendly. Het contract is er juist om zo strak mogelijk te definieren wat de consumer mag verwachten. Maar misschien begrijp ik niet helemaal hoe het met templated links werkt.... 
Misschien kan @MelvLee hier wat van vinden ? Hij kan beter bepalen wat de impact op een consumer is dan ik.

**Comment by JohanBoer** [comment]
- "identificatie" toevoegen aan zakelijkgerechtigde
- endpoint .../zakelijkgerechtigden/{identificatie} toevoegen
- links naar zakelijkgerechtigden vanuit KOZ templated
- array met "zakelijkGerechtigdenIdentificaties" toevoegen in KOZ
Zijn verwerkt. 

De link naar Zakelijkgerechtigde als array staat nog ter discussie.

**Comment by fsamwel** [comment]
> Als we dat doen, dan moeten we deze 2 opties voor alle links gaan bieden, of zie ik dat verkeerd ?

Klopt. Dat betekent uiteraard niet dat elke link een array moet zijn, maar wel dat -om beide opties te bieden- elke link die naar meerdere resources kan verwijzen als array moet zijn gedefinieerd. Voor zover ik weet hebben we dat ook overal gedaan (maar heb geen volledige check gedaan op BAG en BRK op dit punt).

**Comment by JohanBoer** [comment]
Helemaal goed. Ik heb het verkeerd begrepen. Snap nu wat de bedoeling is.
