### ISSUE TITLE
Descriptions van endpoints doornemen API's

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#332]
Alle descriptions van elementen en componenten van de BRK doornemen. Er blijken bij veel elementen geen descriptions opgenomen te zijn.

**Comment by CathyDingemanse** [comment]
endpoint:
/kadastraalonroerendezaken/
Nu:
Het ophalen van een collectie Kadastraal Onroerende zaken. Ten minste één van de volgende combinaties van parameters moet worden gebruikt. Het combineren van parameters uit verschillende combinaties is niet toegestaan.

1. Kadastrale aanduiding
kadastralegemeente__code (verplicht), perceelnummer (verplicht), sectie (verplicht), appartementsrechtnummer (optioneel)
2. Ingeschreven persoon als zakelijk gerechtigde
burgerservicenummer (verplicht), typegerechtigde (optioneel), 
3. Niet ingeschreven persoon of niet natuurlijk persoon als zakelijk gerechtigde
kadasterpersoonidentificatie (verplicht), typegerechtigde (optioneel), 
4. Adres 
postcode (verplicht),  huisnummer (optioneel), huisletter (optioneel), huisnummertoevoeging (optioneel).

Graag wijzigen in:
Het ophalen van een collectie Kadastraal Onroerende zaken door een of meer parameters van kadastrale aanduiding, ingeschreven persoon, kadasterpersoon of Adres op te geven. Het combineren van parameters uit verschillende categorieën is niet toegestaan.
1. Kadastrale aanduiding
kadastralegemeente__code (verplicht), perceelnummer (verplicht), sectie (verplicht), appartementsrechtnummer (optioneel)
2. Ingeschreven persoon als zakelijk gerechtigde
burgerservicenummer (verplicht), typegerechtigde (optioneel), 
3. kadasternatuurlijkpersoon of Kadasternietnatuurlijkpersoon als zakelijk gerechtigde
kadasterpersoonidentificatie (verplicht), typegerechtigde (optioneel), 
4. Adres 
postcode (verplicht),  huisnummer (optioneel), huisletter (optioneel), huisnummertoevoeging (optioneel).





/kadastraalonroerendezaken/{kadastraalobjectidentificatie}
Bij kadastraleobjectidentificatie:
Nu:
Kadastrale aanduiding is de unieke aanduiding van een onroerende zaak, die door het kadaster wordt vastgesteld. Kadastrale aanduiding is de unieke aanduiding van een onroerende zaak, die door het kadaster wordt vastgesteld. Toelichting : In de tijd gezien kan dezelfde onroerende zaak wel meerdere kadastrale aanduidingen hebben, te weten in het geval dat er een herindeling plaatsvindt.

Graag wijzigen in:
De kadastraleobjectidentificatie is de unieke identificatie van een kadastrale onroerende zaak.

**Comment by JohanBoer** [comment]
Johan verwerkt deze in een aparte pull request en zet @HildeVos daarbij als reviewer

**Comment by HildeVos** [comment]
* /kadasternietnatuurlijkpersonen/{identificatie}
Het raadplegen van een bij het kadaster geregistreerde niet natuurlijke persoon die niet in het handelsregister (HR) is ingeschreven. Kadasternietnatuurlijkpersonen worden niet geactualiseerd.  --> Of waar geen koppeling tussen BRK en HR tot stand is gekomen. 

* /kadasternatuurlijkpersonen
Moet worden:
Het zoeken van bij het kadaster geregistreerde natuurlijke personen die niet in de basisregistratie personen (BRP) zijn ingeschreven. Kadasternatuurlijkpersonen worden niet geactualiseerd.  --> Of waar geen koppeling tussen BRK en BRP tot stand is gekomen. Worden wel geactualiseerd (subjectnr en BSN wijzigen niet)

**Comment by JohanBoer** [comment]
@HildeVos en @CathyDingemanse  Ik heb bij jullie commentaren afvinkboxjes toegevoegd. Is handig voor mij bij het verwerken. Ik heb inhoudelijk niets veranderd.

**Comment by JohanBoer** [comment]
> * Het raadplegen van een kadastrale onroerende zaak. De kadastraleobjectidentificatie is de unieke identificatie van een kadastrale onroerende zaak.

Tweede zin is De kadastraalonroerendezaakidentificatie is de unieke identificatie van een kadastraal onroerende zaak.

In een ander pull request is de kadatraalobjectidentificatie omgenoemd naar kadastraaloroerendezaakidentificatie. 

> parameters:
> kadastraalobjectidentificatie
> Was:
> Kadastrale aanduiding is de unieke aanduiding van een onroerende zaak, die door het kadaster wordt vastgesteld. Kadastrale aanduiding is de unieke aanduiding van een onroerende zaak, die door het kadaster wordt vastgesteld. Toelichting : In de tijd gezien kan dezelfde onroerende zaak wel meerdere kadastrale aanduidingen hebben, te weten in het geval dat er een herindeling plaatsvindt.
> 
> * [ ]  Wordt:
>   Kadastrale aanduiding is de unieke aanduiding van een onroerende zaak door het Kadaster. Bij een herindeling kan dezelfde onroerende zaak meer kadastrale aanduidingen hebben.

Deze was al fout omschreven. De kadastraalobjectidentificatie wordt de kadastraalonroerendezaakidentificatie (ander pull request) end dat is iets anders dan de Kadastrale Aanduiding. Ik heb overal voor de kadastraalonroerendezaakidentificatie de volgende omschrijving gebruikt : _De kadastraalonroerendezaakidentificatie is de unieke identificatie van een kadastraal onroerende zaak._

> /kadasternatuurlijkpersonen​/{identificatie}
> Is:
> Het ophalen van een bij het Kadaster geregistreerd Natuurlijk Persoon, niet zijnde een ingeschreven natuurlijk persoon
> 
> * [ ]  Moet worden:
>   Het raadplegen van een bij het kadaster geregistreerde natuurlijke persoon die al dan niet in de basisregistratie personen (BRP) is ingeschreven. Kadasternatuurlijkpersonen worden niet geactualiseerd.

Klopt dit wel ? Als een persoon is geregistreerd in de BRP kunnen we die toch niet ophalen als Kadasterpersoon ? Vooralsnog wel doorgevoerd zoals aangegeven. 

Ik heb n.a.v het Commentaar van @HildeVos aanpassingen aan de betreffende descriptions gedaan. @CathyDingemanse wil jij die reviewen ?

**Comment by CathyDingemanse** [comment]
> > * Het raadplegen van een kadastrale onroerende zaak. De kadastraleobjectidentificatie is de unieke identificatie van een kadastrale onroerende zaak.
> 
> Tweede zin is De kadastraalonroerendezaakidentificatie is de unieke identificatie van een kadastraal onroerende zaak.
> 
> In een ander pull request is de kadatraalobjectidentificatie omgenoemd naar kadastraaloroerendezaakidentificatie.
> 
> > parameters:
> > kadastraalobjectidentificatie
> > Was:
> > Kadastrale aanduiding is de unieke aanduiding van een onroerende zaak, die door het kadaster wordt vastgesteld. Kadastrale aanduiding is de unieke aanduiding van een onroerende zaak, die door het kadaster wordt vastgesteld. Toelichting : In de tijd gezien kan dezelfde onroerende zaak wel meerdere kadastrale aanduidingen hebben, te weten in het geval dat er een herindeling plaatsvindt.
> > 
> > * [ ]   Wordt:
> >   Kadastrale aanduiding is de unieke aanduiding van een onroerende zaak door het Kadaster. Bij een herindeling kan dezelfde onroerende zaak meer kadastrale aanduidingen hebben.
> 
> Deze was al fout omschreven. De kadastraalobjectidentificatie wordt de kadastraalonroerendezaakidentificatie (ander pull request) end dat is iets anders dan de Kadastrale Aanduiding. Ik heb overal voor de kadastraalonroerendezaakidentificatie de volgende omschrijving gebruikt : _De kadastraalonroerendezaakidentificatie is de unieke identificatie van een kadastraal onroerende zaak._
> 

Dat lijkt mij perfect!

> > /kadasternatuurlijkpersonen​/{identificatie}
> > Is:
> > Het ophalen van een bij het Kadaster geregistreerd Natuurlijk Persoon, niet zijnde een ingeschreven natuurlijk persoon
> > 
> > * [ ]   Moet worden:
> >   Het raadplegen van een bij het kadaster geregistreerde natuurlijke persoon die al dan niet in de basisregistratie personen (BRP) is ingeschreven. Kadasternatuurlijkpersonen worden niet geactualiseerd.
> 
> Klopt dit wel ? Als een persoon is geregistreerd in de BRP kunnen we die toch niet ophalen als Kadasterpersoon ? Vooralsnog wel doorgevoerd zoals aangegeven.
> 
Nee klopt idd niet. Moet worden:
Het raadplegen van een bij het kadaster geregistreerde natuurlijke persoon die niet in de basisregistratie personen (BRP) is ingeschreven (of wel is ingeschreven maar niet is "gemached" bij het inschrijven van de akte). Kadasternatuurlijkpersonen worden niet geactualiseerd.

Graag bij /kadasternatuurlijkpersonen
description wijzigen in:
Het zoeken van bij het kadaster geregistreerde natuurlijke personen die niet in de basisregistratie personen (BRP) zijn ingeschreven (of wel zijn ingeschreven maar niet zijn "gemached" bij het inschrijven van de akte). Kadasternatuurlijkpersonen worden niet geactualiseerd.


> Ik heb n.a.v het Commentaar van @HildeVos aanpassingen aan de betreffende descriptions gedaan. @CathyDingemanse wil jij die reviewen ?

**Comment by CathyDingemanse** [comment]
> * /kadasternietnatuurlijkpersonen/{identificatie}
>   Het raadplegen van een bij het kadaster geregistreerde niet natuurlijke persoon die niet in het handelsregister (HR) is ingeschreven. Kadasternietnatuurlijkpersonen worden niet geactualiseerd.  .
> 
> * [x]  > Of waar geen koppeling tussen BRK en HR tot stand is gekomen.
> 
> * /kadasternatuurlijkpersonen
> 
> * [x]  Moet worden:
>   Het zoeken van bij het kadaster geregistreerde natuurlijke personen die niet in de basisregistratie personen (BRP) zijn ingeschreven. Kadasternatuurlijkpersonen worden niet geactualiseerd.  --> Of waar geen koppeling tussen BRK en BRP tot stand is gekomen. Worden wel geactualiseerd (subjectnr en BSN wijzigen niet)

@Johan, Graag overnemen zoals ik in het comment hierboven heb aangegeven. Heb het vrijdag met Hilde besproken.
