### ISSUE TITLE
typegerechtigde ten onrechte verplicht

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#335]
GET https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken?burgerservicenummer=999991905

dit geeft nu een fout:
{
   "type" : "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_BadRequest",
   "title" : "Request is niet valide",
   "status" : 400,
   "detail" : "The request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modification.",
   "instance" : "http://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken?burgerservicenummer=999991905",
   "code" : "Bad Request",
   "invalidParams" : [
      {
         "name" : "typegerechtigde",
         "reason" : "must not be null"
      }
   ]
}

Dit suggereert dat typegerechtigde verplicht is. Dat is volgens mij niet de bedoeling. Het moet ook mogelijk zijn op burgerservicenummer te zoeken zonder typegerechtigde

**Comment by mhebbink-kad** [comment]
Opgelost door laatste versie openapi specs te implementeren.
