### ISSUE TITLE
soortGrootte onjuist gedefinieerd en geïmplementeerd

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#336]
kadastraleGrootte.waarde is gedefinieerd als "Oppervlak grootte, met als eenheid de soortGrootte."

Bij kadastraleGrootte.soortGrootte staat een link naar de [waardelijst](http://www.kadaster.nl/schemas/waardelijsten/SoortGrootte/)

Deze heeft waarden als "Vastgesteld" en "Geschat". Dat zijn naar mijn weten geen eenheden. Ik zou eerder iets verwachten als vierkante meters, kubieke meters, hectares, enz.

Het is ook gebouwd zoals het gespecificeerd is (geef ze eens ongelijk), bijvoorbeeld bij kadastraal object 76370602970000 krijg ik:
      "kadastraleGrootte":       {
         "soortGrootte":          {
            "code": "1",
            "waarde": "Vastgesteld"
         },
         "waarde": 600
      },

Ik denk dus dat óf de description bij grootte moet worden aangepast, óf de description bij soortGrootte én de implementatie van de API

**Comment by JohanBoer** [comment]
Aangepast en in de pull request klaargezet.

**Comment by JohanBoer** [comment]
Check deze of de spc ok is. Zo ja, dan naar implementatie bord.

**Comment by mhebbink-kad** [comment]
@JohanBoer: is de uitkomst van deze story dat de description alleen aangepast moest worden en dat er dus geen implementatie wijziging nodig is?

**Comment by JohanBoer** [comment]
Ja
