### ISSUE TITLE
server error bij onjuiste kadastraalobjectidentificatie

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#337]
Bijvoorbeeld GET https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/15710077470000

(hier is de namespace niet opgenomen in de kadastraalobjectidentificatie)

dit levert een 500 server fout (404 was verwacht):
{
   "type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_InternalServerError",
   "title": "Interne server fout",
   "status": 500,
   "detail": "Op dit moment kan opgevraagde resource niet worden geleverd. Probeer het later nog eens.",
   "instance": "https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/15710077470000",
   "code": "Internal Server Error"
}

**Comment by mhebbink-kad** [comment]
Opgelost.
