### ISSUE TITLE
lege lijst zakelijkgerechtigden bij onjuiste kadastraalobjectidentificatie

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#338]
Bijvoorbeeld GET https://api.test.kadaster.nl/esd/gemeenten/brk/esd/gemeenten/brk/kadastraalonroerendezaken/bestaatniet/zakelijkgerechtigden

dit levert {
   "_links": {"self": {"href": "https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/bestaatniet/zakelijkgerechtigden"}},
   "_embedded": {}
}

Ik had hier een 404 verwacht.

**Comment by mhebbink-kad** [comment]
Opgelost
