### ISSUE TITLE
zakelijkGerechtigden worden embedded zonder gebruik van expand

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#339]
gerelateerde resources (hier zakelijkGerechtigden) moeten alleen worden meegeladen wanneer daar expliciet om is gevraagd. Dus wanneer er niet expand=zakelijkGerechtigden (of een verdere specificatie van velden daarin) is gebruik, moeten deze ook niet worden opgenomen in het antwoord.

Op dit moment gebeurt dat wel.

Bijvoorbeeld GET https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000 levert ook "_embedded": {"zakelijkGerechtigden":    [ ...

**Comment by mhebbink-kad** [comment]
Opgelost
