### ISSUE TITLE
zakelijkGerechtigdeIdentificaties en _links.zakelijkGerechtigden wordt niet gevuld

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#340]
Bijvoorbeeld bij GET https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000

Deze heeft twee zakelijk gerechtigden. Dus had ik ook zakelijkGerechtigdeIdentificaties verwacht met twee waarden. En _links.zakelijkGerechtigden met twee HAL-links.

Beide ontbreken nu in het antwoord.

**Comment by mhebbink-kad** [comment]
Opgelost.
