### ISSUE TITLE
typeGerechtigde ontbreekt in zakelijkGerechtigde

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#341]
Bijvoorbeeld GET https://api.test.kadaster.nl/esd/gemeenten/brk/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000/zakelijkgerechtigden

Beide zakelijk gerechtigden zijn (volgens beschrijving in de getting started) een eigenaar. Dus had ik ook in beide voorkomens property typeGerechtigde met waarde "eigenaar" verwacht. Maar deze ontbreken in het antwoord.

**Comment by mhebbink-kad** [comment]
Opgelost
