### ISSUE TITLE
link in zakelijkGerechtigde naar persoon niet goed opgebouwd

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#342]
GET https://api.test.kadaster.nl/esd/gemeenten/brk/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000/zakelijkgerechtigden

dit bevat in _links:
"persoon":         
{
            "href": "NL.IMKAD.Persoon.50550743",
            "templated": false,
            "title": "BRK"
 }

Deze link is niet goed opgebouwd. Dit zou namelijk (als relatieve link) leiden naar https://api.test.kadaster.nl/esd/gemeenten/brk/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000/zakelijkgerechtigden/NL.IMKAD.Persoon.50550743. Dus naar een zakelijk gerechtigde i.p.v. naar een kadaster persoon.

Vergelijkbaar issue met link bij kadastraalonroerendezaken naar bagAdressen:
"bagAdressen": [      {
         "href": "0200200000003734",
         "templated": false,
         "title": "BAG"
      }]

href zou moeten zijn gevuld met "https://api.test.kadaster.nl/lvbag/api/huidigebevragingen/vhc/adressen/0200200000003734"

**Comment by fsamwel** [comment]
idem voor link naar ingeschreven natuurlijk persoon:
GET https://api.test.kadaster.nl/esd/gemeenten/brk/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.22310827210003/zakelijkgerechtigden
      "_links": {"persoon":       {
         "href": "999991905",
         "templated": true,
         "title": "BRP"
      }}

bij href is nu alleen het burgerservicenummer ingevuld, i.p.v. de url "https://www.haalcentraal.nl/haalcentraal/api/brp/ingeschrevenpersonen/999991905"

**Comment by mhebbink-kad** [comment]
Opgelost

**Comment by fsamwel** [comment]
GET https://api.test.kadaster.nl/esd/gemeenten/brk/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870488070000/zakelijkgerechtigden

levert:
```
      "persoon":       {
         "identificatie": "NL.IMKAD.Persoon.71291440",
         "omschrijving": "Bankbedrijf",
         "type": "kadaster_niet_natuurlijk_persoon"
      },
      "_links":       {
         "self": {"href": "http://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.ZakelijkRecht.30217152/zakelijkgerechtigden/%257Bidentificatie%255D"},
         "persoon":          {
            "href": "https://api.test.kadaster.nl/esd/gemeenten/brk/kadasternatuurlijkpersonen/NL.IMKAD.Persoon.71291440",
            "templated": false,
            "title": "BRK"
         }
      }
```
volgens persoon.type is dit een niet-natuurlijk persoon, maar de url in _links.persoon.href verwijst naar /kadasternatuurlijkpersonen

**Comment by mhebbink-kad** [comment]
Opgelost
