### ISSUE TITLE
identificatie niet correct gevuld bij ingeschreven natuurlijk persoon

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#343]
GET https://api.test.kadaster.nl/esd/gemeenten/brk/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.22310827210003/zakelijkgerechtigden

Bevat in het antwoord:
```
      "persoon":       {
         "identificatie": "NL.IMKAD.Persoon.71303565",
         "omschrijving": "Linda Haglund",
         "type": "ingeschreven_natuurlijk_persoon"
      },
      "_links": {"persoon":       {
         "href": "999991905",
         "templated": true,
         "title": "BRP"
      }}

```
Dit is een ingeschreven natuurlijk persoon, dus had ik bij persoon.identificatie het burgerservicenummer verwacht, zoals dat wel is gevuld in _links.persoon.href.

N.B. De link naar de persoon is niet correct opgebouwd, zie #342

**Comment by mhebbink-kad** [comment]
Opgelost
