### ISSUE TITLE
fields geeft onterecht fouten

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#345]
GET https://api.test.kadaster.nl/esd/gemeenten/brk/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870488070000/zakelijkgerechtigden?fields=identificatie%2Ctenaamstelling

dit levert een foutmelding:
{
   "type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_BadRequest",
   "title": "Request is niet valide",
   "status": 400,
   "detail": "The request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modification.",
   "instance": "http://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870488070000/zakelijkgerechtigden?fields=identificatie%252Ctenaamstelling",
   "code": "Bad Request",
   "invalidParams":    [
            {
         "name": "fields",
         "reason": "Attribuut 'tenaamstelling' is geen geldige waarde."
      },
            {
         "name": "fields",
         "reason": "Attribuut 'identificatie' is geen geldige waarde."
      }
   ]
}

Dat is m.i. niet terecht, want zowel identificatie als tenaamstelling zijn geldige eigenschappen van de resource.

**Comment by mhebbink-kad** [comment]
Opgelost
