### ISSUE TITLE
title van links niet als verwacht

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#347]
de title in een HAL link moet een voor mensen leesbare beschrijving zijn van waar de link naar verwijst. Dat zou bijvoorbeeld voor een link persoon de samengestelde naam van de persoon kunnen zijn.

Bijvoorbeeld:
GET https://api.test.kadaster.nl/esd/gemeenten/brk/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870488070000/zakelijkgerechtigden

Geeft:
{
   "_links": {"self": {"href": "http://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870488070000/zakelijkgerechtigden"}},
   "_embedded": {"zakelijkGerechtigden": [   {
      "identificatie": "NL.IMKAD.ZakelijkRecht.30217152",
      "typeGerechtigde": "eigenaar",
      "tenaamstelling": {"aandeel":       {
         "noemer": 1,
         "teller": 1
      }},
      "persoon":       {
         "identificatie": "NL.IMKAD.Persoon.71291440",
         "omschrijving": "Bankbedrijf",
         "type": "kadaster_niet_natuurlijk_persoon"
      },
      "_links":       {
         "self": {"href": "http://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.ZakelijkRecht.30217152/zakelijkgerechtigden/%257Bidentificatie%255D"},
         "persoon":          {
            "href": "https://api.test.kadaster.nl/esd/gemeenten/brk/kadasternatuurlijkpersonen/NL.IMKAD.Persoon.71291440",
            "templated": false,
            "title": "BRK"
         }
      }
   }]}
}

De title "BRK" is nikszeggende voor de link. De waarde uit persoon.omschrijving was duidelijker geweest (in dit voorbeeld  "Bankbedrijf").

Overigens is title niet verplicht, maar als je het gebruikt, moet er wel een zinvolle waarde in zitten.

**Comment by mhebbink-kad** [comment]
Opgelost
Voor een link naar de BRP wordt titel gevuld met de naam van de persoon.
Voor een link naar de BAG wordt de titel niet gevuld.
