### ISSUE TITLE
internal server error bij opvragen kadasternatuurlijkpersoon

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#348]
GET https://api.test.kadaster.nl/esd/gemeenten/brk/kadasternatuurlijkpersonen/NL.IMKAD.Persoon.71291440

Geeft een fout:
{
   "type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_InternalServerError",
   "title": "Internal Server Error",
   "status": 500,
   "detail": "Internal Server Error",
   "instance": "https://api.test.kadaster.nl/esd/gemeenten/brk/kadasternatuurlijkpersonen/NL.IMKAD.Persoon.71291440",
   "code": "Internal Server Error"
}

**Comment by fsamwel** [comment]
Deze url heb ik uit de href van _links.persoon gehaald uit
GET https://api.test.kadaster.nl/esd/gemeenten/brk/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870488070000/zakelijkgerechtigden

Dit issue raakt denk ik twee problemen:
1. deze persoon is een niet natuurlijk persoon, maar geeft een link naar kadasternatuurlijkpersonen
2. een onjuiste persoon geeft een 500 server error, waar een 404 correct was geweest

**Comment by mhebbink-kad** [comment]
Opgelost
