### ISSUE TITLE
self link bij embedded zakelijkgerechtigden ontbreekt

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#349]
GET https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000?expand=zakelijkGerechtigden

Deze levert de zakelijkgerechtigden, maar hierin ontbreekt _links.self

N.B. wanneer ik de zakelijkgerechtigden vraag via /kadastraalonroerendezaken/{kadastraalobjectidentificatie}/zakelijkgerechtigden krijg ik de _links.self wel

N.B. deze _links.self moet altijd geleverd worden bij een embedded zakelijkgerechtigde, ook wanneer er alleen specifiek is gevraagd om andere properties

**Comment by fsamwel** [comment]
_links.self wordt nu wel geleverd. Alleen is er geen rekening gehouden met:
> N.B. deze _links.self moet altijd geleverd worden bij een embedded zakelijkgerechtigde, ook wanneer er alleen specifiek is gevraagd om andere properties

Bijv. https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000?expand=zakelijkGerechtigden.persoon.omschrijving%2CzakelijkGerechtigden.typeGerechtigde

levert geen _links.self

**Comment by rhengeveld** [comment]
@mhebbink-kad deze is opgelost en zit in onze volgende update / release (zie ESD-122 punt 2)
