### ISSUE TITLE
zakelijkgerechtigde__typegerechtigde geeft foutmelding op correcte waardes

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#350]
bij het zoeken van kadastraalonroerendezaken op persoon identificatie en zakelijkgerechtigde__typegerechtigde krijg ik een fout bij gebruik van valide waarden (zoals "eigenaar" of "erfpachter") voor zakelijkgerechtigde__typegerechtigde.

GET https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken?ingeschrevenpersoon__burgerservicenummer=999991905&zakelijkgerechtigde__typegerechtigde=eigenaar

geeft:
 {
   "type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_BadRequest",
   "title": "Request is niet valide",
   "status": 400,
   "detail": "The request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modification.",
   "instance": "http://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken?ingeschrevenpersoon__burgerservicenummer=999991905&zakelijkgerechtigde__typegerechtigde=eigenaar",
   "code": "Bad Request",
   "invalidParams": [   {
      "name": "zakelijkgerechtigde__typegerechtigde",
      "reason": "Type mismatch for 'zakelijkgerechtigde__typegerechtigde' with value 'eigenaar'"
   }]
}

**Comment by mhebbink-kad** [comment]
In hoofdletters werkt het wel... dus EIGENAAR.

**Comment by mhebbink-kad** [comment]
Werkt nu ook weer gewoon in kleine letters.
