### ISSUE TITLE
Benaming identificaties controleren/ aanpassen

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#354]
Bijvoorbeel de identificatie van de zakelijkgerechtigde heet als element nu "identificatie" Als er op meerder plekken in de api een element identificatie opgenomen is dan kan dat verwarrend werken. Voorstel is om de componentnaam vooraf te laten gaan aan het woord identificatie in de benaming.

In dit geval wordt dat dan dus zakelijkGerechtigdeIdentificatie.

**Comment by fsamwel** [comment]
"zeklijkGerechtigdeIdentificatie"?

**Comment by JohanBoer** [comment]
> "zeklijkGerechtigdeIdentificatie"?

Ben een beetje moe aan het worden. Morgen weer verder :)

**Comment by JohanBoer** [comment]
Conclusie: Bij de path-parameters wordt de resourcenaam als prefix voor de identificatie geplaatst. In de resources zelf wordt de property "identificatie genoemd. 
Dit betekent een wijziging in een aantal path-parameters en in de kadastraalobject identiicatie --> identificatie.

Verder in de path parameter wordt kadastraalobjectidentificatie --> kadastraalonroerendezaakidentificatie.
