### ISSUE TITLE
Description van query parameter 'q' aanscherpen

### ISSUE THREAD

**Issue by mhebbink-kad** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#358]
Description aanscherpen voor de endpoints /kadasternatuurlijkpersonen en /kadasternietnatuurlijkpersonen, zodat duidelijk is hoe de free query gebruikt dient te worden. Denk bijv. aan notatie van de geboortedatum [YYYY-mm-dd]

**Comment by JohanBoer** [comment]
Cathy levert een voorstel van aan te passen descriptions.

**Comment by CathyDingemanse** [comment]
opgenomen in #332
