### ISSUE TITLE
Als medewerker Vergunningen wil ik van een kadastrale onroerende zaak de x-y coördinaten van het perceel, de functie (cultuur bebouwd en cultuur onbebouwd), de oppervlakte, en of het een appartementsrecht is kunnen raadplegen 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#36]
...zodat ik kan bepalen of de vergunningsaanvraag conform bestemming is.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [x] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by JanWillemKooi** [comment]
Feedback Marco B: Bedoel je met x-y-coördinaten de geometrische afbakening (dus het vlak waarmee het perceel wordt aangeduid) of bedoel je bijvoorbeeld een centroide binnen het perceel?

**Comment by JohanBoer** [comment]
Hoe leg ik de relatie tussen een appartementsrecht en een perceel ? Loopt dat via de onroerendezaakfiliatie ?

**Comment by MelvLee** [comment]
Aan kadastraal onroerende zaak voegen we type element toe met de waarde appartementsrecht, perceel

**Comment by JohanBoer** [comment]
[ ] de x-y coördinaten van het perceel
 [ ] de functie (cultuur bebouwd en cultuur onbebouwd)
 [ ] de oppervlakte
 [ ]  en of het een appartementsrecht is kunnen raadplegen

**Comment by JohanBoer** [comment]
Ik heb mijn comment van 16 april gechecked en dat is in de huidige versie allemaal valide.
