### ISSUE TITLE
Bij GET {{baseUrl}}/kadastraalonroerendezaken wil ik kunnen zoeken op KvK nummer of statutaire naam

### ISSUE THREAD

**Issue by idr2019** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#368]
Waarom is het zoeken naar kadastrale onroerende zaken waar een niet natuurlijk persoon rechten op heeft niet mogelijk gemaakt? 
Bij GET {{baseUrl}}/kadastraalonroerendezaken kan wel gezocht worden op ingeschrevenpersoon__burgerservicenummer of persoon_kadasterpersoonidentificatie maar niet op identificerende kenmeren van een niet natuurlijk persoon. Wordt dit nog toegevoegd?

**Comment by CathyDingemanse** [comment]
Het zoeken van kadastraal onroerende zaken met een RSIN of KVK nr levert slechts 40% van de kadastraal onroerende zaken op waarop een zakelijk recht rust van deze nnp. Dat komt omdat in slechts 40% van de gevallen een identificerend kenmerk van de nnp is opgenomen in de BRK.
Wij hebben deze identificerende kenmerken niet opgenomen als queryparameter omdat het resultaat niet betrouwbaar is. 

In plaats daarvan hebben we alle niet natuurlijke personen als kadasterpersonen opgenomen, zodat een afnemer de nnp kan opzoeken bij het kadaster en de identificatie van de kadasterpersoon kan gebruiken als queryparameter. Dat geeft een betrouwbaarder resultaat.

**Comment by idr2019** [comment]
Dank je wel Cathy. Duidelijk antwoord.
