### ISSUE TITLE
Getting started voor productie document maken

### ISSUE THREAD

**Issue by kad-hebbim** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#369]
Ook link in readme toevoegen hier naar toe.

**Comment by mhebbink-kad** [comment]
Zie pull request: https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/pull/512

**Comment by fsamwel** [comment]
@HildeVos @rhengeveld in de door Marcel geschreven getting started staat beschreven hoe met productie kan worden verbonden. In de API-lab staat beschreven dat tijdens de API-lab met een algemene apiKey kan worden getest.
Hoe moet dit gaan voor aansluiters straks? Gaan die direct op de productieomgeving testen, dus mét persoonsgegevens?(!)
Of is de testomgeving, met de testdata die ik ook gebruik (https://api.test.kadaster.nl/esd/gemeenten/brk/) voor heb beschikbaar?
Zo ja, werkt die dan ook met apiKey? En hoe/waar kunnen ze die aanvragen?
Of werkt die dan ook met een PKIoverheid certificaat? (lijkt me lastig om dan te proberen met Postman)
