### ISSUE TITLE
Als medewerker vergunningen wil ik weten wanneer de huidige eigenaar het eigendom heeft gekregen 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#37]
...zodat ik kan bepalen of er op die datum sprake was van onderzoeksplicht wanneer ik  vergunningsaanvraag behandel die buiten het bestemmingsplan valt .

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by JohanBoer** [comment]
Aan de tenaamstellingen Historie toegevoegd. Daarmee wordt dus wel de eis toegevoegd dat als je alleen actuele gegevens wilt, dat je bij de uitvraag een parameter toe zal moeten voegen.

**Comment by marianneleferink01** [comment]
Vooralnog nog niet uitgaan van mappen Johan. Ik kom hier nog op terug.
