### ISSUE TITLE
Links naar onroerendezaken bij zoeken naar kadasternietnatuurlijkpersoon worden niet getoond

### ISSUE THREAD

**Issue by kad-hebbim** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#370]

**Comment by mhebbink-kad** [comment]
@JohanBoer: volgens mij missen we in de KadasterNatuurlijkPersoon nog een veld welke een lijst teruggeeft van ids van kadastraalonroerendezaken waar hij rechthebbende is. Geldt ook voor KadasterNietNatuurlijkPersoon. Morgen maar even bespreken.

**Comment by JohanBoer** [comment]
Deze is denk ik gerelateerd met #330
