### ISSUE TITLE
Links naar onroerendezaken bij zoeken naar kadasternatuurlijkpersoon worden niet getoond

### ISSUE THREAD

**Issue by mhebbink-kad** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#371]

**Comment by fsamwel** [comment]
Ik krijg nog geen zakelijkGerechtigdeIdentificaties en geen _links.zakelijkGerechtigden bij de Kadasterpersonen.

Daarvoor had ik ook issue #447 gemaakt. Dus deze is dubbel daarmee.
