### ISSUE TITLE
foutmelding bij gebruik fields op links

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#373]
https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000?fields=zakelijkGerechtigden%2CbagAdressen

dit geeft een foutmelding:
{
   "type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_BadRequest",
   "title": "Request is niet valide",
   "status": 400,
   "detail": "The request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modification.",
   "instance": "http://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000?fields=zakelijkGerechtigden%2CbagAdressen",
   "code": "Bad Request",
   "invalidParams":    [
            {
         "name": "fields",
         "reason": "Attribuut 'zakelijkGerechtigden' is geen geldige waarde."
      },
            {
         "name": "fields",
         "reason": "Attribuut 'bagAdressen' is geen geldige waarde."
      }
   ]
}

Die had ik niet verwacht, want dit zijn bestaande properties in _links

**Comment by fsamwel** [comment]
Wanneer ik _links. ervoor zet werkt het wel goed. Het moet ook mogelijk zijn deze weg te laten, zie  https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/master/features/fields.feature

**Comment by mhebbink-kad** [comment]
Is volgens mij achterhaald.
zie pull request (https://github.com/VNG-Realisatie/Haal-Centraal-common/pull/23)

**Comment by fsamwel** [comment]
ik denk niet dat het achterhaald is. De pull request die je aanhaalt (heb ik zelf gemaakt) zegt 2 dingen:
1. je kan een relatie ophalen met of zonder _links ervoor
2. als er een property in de resource is met dezelfde naam als een property in _links, dan moet je _links ervoor zetten om de link te krijgen, anders krijg je het property uit de resource

In dit geval heb ik fields aangeroepen zonder _links voor de linknaam. Dat geeft nu een fout. En dat is volgens de feature (ook na de pull requrest) niet terecht.

**Comment by mhebbink-kad** [comment]
Persoonlijk vind ik dat het er dan niet overzichtelijker op wordt als we punt 1 aanhouden. De ene keer krijg je de _links.property terug (als de resource niet een property met dezelfde naam heeft) en de andere keer de property (als de resource wel een property met dezelfde naam heeft).
Morgen maar even bespreken.

**Comment by JohanBoer** [comment]
@MelvLee Wat is jouw visie op het gebruik van _links in de fields parameter. 
Moet je altijd _links gebruiken als prefix (voorstel Marcel) of alleen als er ook een property in de resource voorkomt met dezelfde naam als de link (huidige beschrijving in common + uitleg Frank).

**Comment by MelvLee** [comment]
Voor consistentie zou ik er wel voor kiezen om _links.property te kiezen, want als bijv. geslachtsnaam kan ik ook alleen ophalen via naam.geslachtsnaam.
Maar voor gebruiksvriendelijkheid zou ik er wel voor kiezen om beide te kunnen doen. Ik vind het zelf niet gebruiksvriendelijk als ik geslachtsnaam en voorletters wil ophalen, dat ik fields=naam.geslachtsnaam,naam.voorletters moet opgeven i.p.v. fields=geslachtsnaam,voorletters. Als ik hierdoor teveel data terug zou krijgen, dan kan ik het altijd strakker maken door de resource naam op te geven.

**Comment by JohanBoer** [comment]
We hebben ervoor gekozen om in versie 1 alleen huidige implementatie te ondersteunen. D.w.z. dat bij  de _links prefix gebruikt moet worden in de fields parameter als er een specifieke link opgevraagd wordt en dat ook voor properties uit een gegevensgroep de naam van de betreffende component als prefix moet worden opgegeven. We plaatsen een issue op de backlog voor een volgende versie om ook te ondersteunen dat de betreffende properties en links zonder prefix kunnen worden opgevraagd.

**Comment by fsamwel** [comment]
deze is al opgelost met #418
