### ISSUE TITLE
Als medewerker gemeente wil ik aanschrijfwijze, aanhef en referentie in lopende tekst van kadasterpersonen 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#375]
...zodat ik kadasterpersonen kan aanschijven.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by JohanBoer** [comment]
Nu dezelfde constructie toegevoegd als in de BRP-bevragen-ingeschrevenPersoon. Vraag is of het Kadaster ook de gegevens heeft die nodig zijn voor het samenstellen van de aanschrijfwijze, aanhef en gebruikInlopendeTekst. Indien er minder naam-componenten beschikbaar zijn zal de feature voor het kadaster waarschijnlijk aanzienlijk makkelijker zijn.

**Comment by rhengeveld** [comment]
Ik heb ondertussen de features geïmplementeerd voor [aanhef](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/blob/Versie-1.2.0/features/aanhef.feature), [aanschrijfwijze](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/blob/Versie-1.2.0/features/aanschrijfwijze.feature), [gebruikInLopendeTekst](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/blob/Versie-1.2.0/features/gebruik_in_lopende_tekst.feature) en de daarbij benodigde [voorletters](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/blob/Versie-1.2.0/features/voorletters.feature). Tijdens de implementatie kwam ik een aantal typo's in de features tegen, hier heb ik pull request #662 voor ingediend.

Tevens kwam ik een aantal onvolkomenheden tegen die niet in de feature behandeld worden. Bijvoorbeeld:
1. Wat als een persoon (om wat voor reden dan ook) überhaupt geen naam heeft? Wat is dan de aanhef? Aanschrijfwijze? Gebruik?  
2. Ongebruikelijk, maar wat als een persoon geen _geslachtsnaam_ heeft (evt. wel voorvoegsel)?  Wat als de partner dit niet heeft?
3. Wat als de persoon geen partner heeft, terwijl _aanduidingNaamgebruik_ om type `P`, `V` of `N` vraagt?

Dit zijn misschien ongebruikelijke of _'horen nooit voor te komen'_ scenario's, maar ik denk wel dat het handig is om duidelijk te maken wat je kan verwachten als de persoon geen naam of partner heeft 😉 Kan iemand (@fsamwel?) hier antwoord op geven?

---

Voor **punt 1** gebruik ik nu _aanhef_ `Geachte heer/mevrouw`, _aanschrijfwijze_ ` ` (leeg) en _gebruik_ `de heer/mevrouw`.
Voor **punt 2 & 3** negeer ik momenteel dat deze velden (of partner) leeg zijn, dat geeft echter interessante combinaties als:
* Aanhef `V`, man, geen eigen geslachtsnaam, partner De Vries = `Geachte heer De Vries`
* Aanschrijfwijze `V`, adellijke titel, geen eigen geslachtsnaam, partner Jansen = `H.H.G J. Jansen-baron`
* Aanschrijfwijze `V`, adellijke titel, eigen geslachtsnaam De Vries, geen partner = `H.H.G J. baron de Vries`
* Gebruik `V`, vrouw, eigen voorvoegsel "van", partner voorvoegsel "de", geen geslachtsnamen = `mevrouw De-van`

**Comment by fsamwel** [comment]
> 1. Wat als een persoon (om wat voor reden dan ook) überhaupt geen naam heeft? Wat is dan de aanhef? Aanschrijfwijze? Gebruik?

In BRP (dus ingeschreven personen) kan dit niet voorkomen. In BRK mogelijk wel, weet ik niet. We kunnen dit zo mooi maken als we willen, maar komt dit voor?

Als het wel regelmatig voorkomt:
- als alleen voornamen gevuld is, niet voorvoegsel of geslachtsnaam, dan voornamen behandelen als ware het geslachtsnaam
- als voorvoegsel en/of geslachtsnaam gevuld is, niet voornamen, dan voorletters weglaten
- als voornamen, voorvoegsel en geslachtsnaam allen niet gevuld zijn, dan ook geen aanschrijfwijze en gebruikInLopendeTekst leveren. Aanhef leveren met alleen "geachte heer" of "geachte mevrouw"

Als het niet of nauwelijks voorkomt, denk ik dat je gewoon kan leveren wat er is. Kan dan alsnog lege aanschrijfwijze opleveren, of gebruikInLopendeTekst "mevrouw" of "de heer". Dit is als ik je goed begrijp wat je nu hebt gebouwd.

> 2. ... Wat als de partner dit niet heeft?

Kan je hier iets anders doen dan de naam samenstellen alsof aanduidingNaamgebruik is E (eigen)? 
Wat je liever niet wilt is dat het tussenstreepje wordt opgenomen zonder dat er een voorvoegsel of geslachtsnaam van de partner is (doe je niet in jouw voorbeeld, dus dat is mooi).
Wat je ook niet wilt is dat er helemaal geen geslachtsnaam meer is bij aanduidingNaamgebruik P (partner). In dat geval denk ik dat vullen van de eigen geslachtsnaam beter is.

> 3. Wat als de persoon geen partner heeft, terwijl aanduidingNaamgebruik om type P, V of N vraagt?

In de BRP kan dit voorkomen. Dan blijft men bijvoorbeeld de achternaam van de overleden partner gebruiken. Om dan de wanschrijfwijze correct samen te stellen moet je de naam van de (laatste) ex-partner hebben. BRP heeft dat, maar heeft BRK dat ook? Zo niet, dan doen alsof aanduidingNaamgebruik is E (eigen).

De overweging hier is denk ik vooral een keuze tussen:
- aanschrijfnamen zo goed mogelijk samenstellen
- aanschrijfnamen alleen leveren wanneer ze zeker goed zijn

@CathyDingemanse wat vind jij?

**Comment by rhengeveld** [comment]
> Als het niet of nauwelijks voorkomt, denk ik dat je gewoon kan leveren wat er is. Kan dan alsnog lege aanschrijfwijze opleveren, of gebruikInLopendeTekst "mevrouw" of "de heer". Dit is als ik je goed begrijp wat je nu hebt gebouwd.

Yep, er wordt op dit moment gevuld wat beschikbaar is. Als een streepje aanwezig kan zijn werk ik in 'secties', waarbij afhankelijk van de samenstelling adellijke titel, predikaat, voorvoegsel en geslachtsnaam als 1 sectie worden behandeld. Zie ook voorbeeld hieronder 🙂 

> Wat je liever niet wilt is dat het tussenstreepje wordt opgenomen zonder dat er een voorvoegsel of geslachtsnaam van de partner is (doe je niet in jouw voorbeeld, dus dat is mooi).

Ter toelichting, uitgebreidere combinaties als `GA VP GP-AP VV GN` (_gebruik V adellijk_) verwerk ik in secties `[GA] [VP GP]-[AP VV GN]`:
* `[GA]` geslachtsaanduiding
* `[VP GP]` 'naam partner'
* `[AP VV GN]` 'eigen naam'

Het streepje "-" alleen wordt toegevoegd als de sectie ervoor én erna aanwezig zijn; respectievelijk 'eigen naam' en 'naam partner'. Wat dit voorbeeld overigens nóg leuker maakt is de regel _"Het voorvoegsel van de eerste geslachtsnaam in gebruikInLopendeTekst wordt met een hoofdletter geschreven"_; bij geen 'naam partner' dient het voorvoegsel van 'eigen naam' vervolgens deze hoofdletter te krijgen 😉 

Dit leidt tot deze combinaties voor _**gebruik V adellijk**_:
* `GA VP GP-AP VV GN` _volledig_ ➡️ `de heer De Vries-baron van Velzen` of `de heer De-baron van` (geen geslachtsnamen)
* `GA VP GP` _geen 'eigen naam'_ ➡️ `de heer De Vries` of `de heer De` (ook geen partner geslachtsnaam)
* `GA AP VV GN` _geen 'naam partner'_ ➡️ `de heer baron Van Velzen` (hoofdletter!) of `de heer baron Van` (ook geen eigen geslachtsnaam)

Overigens zit adellijke titel niet altijd in de sectie 'eigen naam', bij _**gebruik N**_ heb je `GA VV GN-VP GP` of `AP VV GN-VP GP`, welke ik weer verwerk als `[GA/AP] [VV GN]-[VP GP]`. Dan is `baron De Vries` (geen 'eigen naam') zonder streepje weer mogelijk.
_Hmmm 🤔 nu ik dit zo schrijf, misschien dat ik deze secties toch nog iets consistenter moet definiëren..._

@fsamwel zo gewenst kan ik wel een hele lijst aan voorbeelden geven, misschien dat dan blijkt dat de implementatie toch nét anders moet.

> In de BRP kan dit voorkomen. Dan blijft men bijvoorbeeld de achternaam van de overleden partner gebruiken. Om dan de aanschrijfwijze correct samen te stellen moet je de naam van de (laatste) ex-partner hebben. BRP heeft dat, maar heeft BRK dat ook? Zo niet, dan doen alsof aanduidingNaamgebruik is E (eigen).

Volgens mij krijg ik op dit moment maar 1 partner binnen. Ik zal moeten nagaan / navragen of dit klopt dan wel anders kan.

**Comment by rhengeveld** [comment]
Besproken. 
* In principe heeft een persoon altijd een naam én geslachtsnaam
* Voornamen zijn optioneel, in welk geval de persoon geen voorletters heeft - jammer dan
* In principe vullen we wat beschikbaar is _(best effort)_
* Als _`aanduidingNaamgebruik`_ vraagt om de gegevens van een partner (varianten P, V, N) terwijl er geen partner is, dan doen we de bepaling opnieuw als zijnde variant E (eigen geslachtsnaam)

**Comment by rhengeveld** [comment]
Is geïmplementeerd en is als het goed is beschikbaar op de testomgeving.

**Let op:** dit is een _preview_ versie, want de Kadaster testers zijn dit nog aan het testen 😉

**Comment by fsamwel** [comment]
@rhengeveld ik heb nu 3 kadasternatuurlijkpersonen, alledrie lijken aanduiding naamgebruik=E (eigen) te hebben. Bij 50550743 kan ik dat niet zien, want persoon en partner hebben dezelfde achternaam.

Kortom, heb je voor mij een aantal testgevallen waarmee ik dit kan bekijken?

**Comment by rhengeveld** [comment]
@kad-hebbim jij weet deze denk ik iets makkelijker te vinden / maken? 😇

**Comment by fsamwel** [comment]
Ik ben voor testgevallen erg geïnteresseerd in:
- testgevallen voor alle 4 de vormen aanduiding naamgebruik
- voor alle vormen aanduiding naamgebruik testgeval met en zonder voorvoegsel (voor zowel persoon als partner)
- voornaam die begint met diakriet (bijv. Ö of É)
- voornaam van één letter
- persoon met adellijke titel (heeft het Kadaster dat gegeven?)
- man, vrouw, en onbekend geslacht

**Comment by kad-hebbim** [comment]
Ziehier wat testgevallen om dit te testen:
- **id: geslacht | (titel) aanduiding | naam | partner |**
- 8000001: Onbekend | E | Anne Janssens | X | 
- 8000002: Man | E | Jan Groenen | Petra Anne Veldwijk |
- 8000003: Vrouw | N | Susan in het Veld | Jeroen van Velzen |
- 8000004: Vrouw | P | Petra Anne Veldwijk | Jan Groenen |
- 8000005: Vrouw | V | H Pieters | Jan Pietersen |
- 8000006: Man | E | Öle Klaassen | X |
- 8000007: Man | E | Baron Jan-Jaap de Vierde | X |

Deze kunnen bevraagd worden via endpoint /kadasternatuurlijkpersonen/{id} en hebben geen onroerendezaken onder zich.

Zal deze ook toevoegen aan het getting-started document.

**Comment by fsamwel** [comment]
@kad-hebbim heb je deze nieuwe testpersonen ook in acceptatie toegevoegd?

{
    "type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_NotFound",
    "title": "Opgevraagde resource bestaat niet.",
    "status": 404,
    "detail": "Not Found.",
    "instance": "/kadasternatuurlijkpersonen/8000001",
    "code": "notFound"
}

**Comment by kad-hebbim** [comment]
@fsamwel 
Aarghhh, heb een nulletje te weinig gezet voor de ids. Het moet 80000001 zijn (6 nullen).

**Comment by fsamwel** [comment]
@CathyDingemanse in de feature voor gebruik in lopende tekst en aanhef nemen we nu, net als bij BRP, bij geslachtsaanduiding onbekend op "heer/mevrouw".

In BRP is hierna issue https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/issues/674 gemaakt voor een genderneutrale aanschrijving. Die erkent dat geslachtsaanduiding "onbekend" naast echt onbekend ook kan betekenen dat de persoon geen gender heeft (de "X" in het paspoort).

Moeten we hier nu ook (al) iets mee doen in BRK?

Nu (wat nu gespecificeerd en gebouwd is voor v1.2) wordt dan bijvoorbeeld geleverd:
```
    "omschrijving": "Anne Janssens",
    "geslachtsaanduiding": "onbekend",
    "naam": {
        "geslachtsnaam": "Janssens",
        "voornamen": "Anne",
        "aanschrijfwijze": "A. Janssens",
        "aanhef": "Geachte heer/mevrouw Janssens",
        "gebruikInLopendeTekst": "de heer/mevrouw Janssens"
    },
```

**Comment by CathyDingemanse** [comment]
Bij geslacht onbekend liever geen heer/mevrouw, maar Geachte A. Janssen.

**Comment by rhengeveld** [comment]
@fsamwel ik heb de aangepaste features van #709 geïmplementeerd. Het is beschikbaar op de acceptatieomgeving ✔️

**Comment by fsamwel** [comment]
@rhengeveld de gebruikte testgevallen voor aanschrijving krijg ik alleen bij direct raadplegen op identificatie, niet bij zoeken op bijvoorbeeld naam+geboortedatum. Dit is neem ik aan een testdata probleempje (verschillende bronnen voor raadplegen en zoeken)?
Of is hier iets anders aan de hand?

**Comment by kad-hebbim** [comment]
> @rhengeveld de gebruikte testgevallen voor aanschrijving krijg ik alleen bij direct raadplegen op identificatie, niet bij zoeken op bijvoorbeeld naam+geboortedatum. Dit is neem ik aan een testdata probleempje (verschillende bronnen voor raadplegen en zoeken)?
> Of is hier iets anders aan de hand?

@fsamwel: dit heeft inderdaad te maken met dat we daarvoor andere bronnen raadplegen waar we niet veel invloed op hebben. Dit heb ik als punt gezet in de getting-started.doc dat deze testgevallen niet raadpleegbaar zijn via /kadasternatuurlijkpersonen?q=

**Comment by rhengeveld** [comment]
☝️ dit inderdaad. Er wordt momenteel een poging gedaan door standaard _aanduidingNaamgebruik_ met waarde _"Eigen geslachtsnaam"_ te hanteren, maar als verder de gegevens niet door de _personen-zoeken-bron_ geleverd worden, kunnen we dit ook niet teruggeven.

Vanaf de eerstvolgende versie `v1.2.1.x` schakelen we over naar de nieuwe mogelijkheden die onze _onroerende-zaken-bron_ biedt. Daardoor kunnen we vanaf dat moment _altijd_ _**alle**_ persoonsgegevens uit deze bron ophalen, inclusief _aanduidingNaamgebruik_.  
Voor mij als ontwikkelaar vereenvoudigt dit de wijze van gegevens ophalen, voor gebruikers is het voordeel dat we dan altijd op consistente wijze alle benodigde persoonsgegevens hebben. 

Dit laatste punt zal dan ook opgelost zijn, dus ik sluit dit issue gezien _aanhef_, _aanschrijfwijze_ en _gebruikInLopendeTekst_ ondertussen op productie beschikbaar zijn 🙂
