### ISSUE TITLE
expand van relatie geeft fout

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#379]
https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000?expand=zakelijkGerechtigden._links.persoon

Dit levert een foutmelding:
{
   "type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_BadRequest",
   "title": "Request is niet valide",
   "status": 400,
   "detail": "The request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modification.",
   "instance": "http://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000?expand=zakelijkGerechtigden._links.persoon",
   "code": "Bad Request",
   "invalidParams": [   {
      "name": "expand",
      "reason": "Attribuut 'zakelijkGerechtigden._links.persoon' is geen geldige waarde."
   }]
}

Deze fout is niet terecht, want in de zakelijkGerechtigden bestaat een property _links.persoon

**Comment by rhengeveld** [comment]
@mhebbink-kad deze is opgelost en zit in onze volgende update/release.
