### ISSUE TITLE
Arrays definities verwijderen uit _linkcomponenten

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#397]
Op dit ogenblik staan  in de divers _links componenten de links nog steeds als arrays gedefinieerd. 
Volgens mij is dat nergens voor nodig. Als wij de templated URL aanbieden, dan hoeft dat er maar 1 te zijn. 
De consumer kan dan zelf met de array van identificaties de links opbouwen. 

M.i. moeten we hier dus overal in de _links componenten de array definitie verwijderen.

**Comment by MelvLee** [comment]
Ik dacht dat de reden om een array te gebruiken was om de optie open te houden om geen templated urls aan te bieden. Want in dat geval moet de spec worden gewijzigd en is dat een breaking change.

Ik zie zelf geen andere redenen om niet voor templated urls te gaan, dus wat mij betreft kunnen wij inzetten op templated urls en moeten we t.z.t. voorbeelden maken voor consumers hoe zij met templated urls om moeten gaan.

**Comment by fsamwel** [comment]
ik ben er voorstander van het al dan niet gebruiken van templated links open te laten in de definities. Op basis van gebruikerswensen kan de provider dan altijd nog kiezen voor templated of niet-templated.

**Comment by JohanBoer** [comment]
Uit jullie reactie maak ik op dat daar al over is nagedacht. Die discussie is langs mij heen gegaan. Ik heb geen grote bezwaren wel wat argumenten, maar ik wil een gelopen discussie niet opnieuw starten.
