### ISSUE TITLE
klopt de beschrijving identificatie persoon wel?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#398]
De description van de identificatie voor een persoon zegt dat een ingeschreven niet-natuurlijk persoon als identificatie de rsin heeft. Is dat nu ook zo geïmplementeerd? Ik denk namelijk dat we op dit moment elke niet-natuurlijk persoon als kadasternietnatuurlijkpersoon behandelen, en dus altijd de kadasterpersoonidentificatie leveren. Voor een niet-natuurlijk persoon wordt nu dus nooit de rsin of het kaknummer geleverd, ook niet wanneer we die wel hebben.

```
PersoonBasis:
      type: object
       properties:
         identificatie:
           type: string
           description: 'Unieke identificatie voor de persoon. Voor een Kadasterpersoon
             is dit de identificatie zoals die door het Kadaster is vastgesteld. Voor
             een ingeschreven natuurlijk persoon is dit het burgerservicenummer. Voor
             een ingeschreven niet-natuurlijk persoon is dit het rsin.
             een ingeschreven niet-natuurlijk persoon is dit het rsin. Voor een ingeschreven
             natuurlijk persoon is dit het burgerservicenummer. '
```

@mhebbink-kad klopt dat? Of lever je soms wel de rsin bij een persoonidentificatie (in zakelijkgerechtigde.persoon.identificatie).
Zo ja, hoe zit dat in dat geval met de bijbehorende link (naar BRK kadasternietnatuurlijkpersonen of naar KvK?) en de identificatie van zo'n niet-natuurlijk persoon in kadasternietnatuurlijkpersonen?

**Comment by mhebbink-kad** [comment]
@fsamwel: dat klopt inderdaad. Elk niet-natuurlijk persoon wordt momenteel behandeld als een kadasternietnatuurlijkpersoon en wordt de kadasterpersoonidentificatie teruggegeven.

**Comment by JohanBoer** [comment]
Bij de description van de identificatie in PersoonBasis : verwijder de zin " Voor een ingeschreven niet-natuurlijk persoon is dit het rsin."

Voeg in de KadasternietnatuurlijkPersoon de elementen KvKnummer en RSIN toe.
