### ISSUE TITLE
descriptions voor waardelijsten worden niet getoond

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#399]
er is nu een manier gekozen om descriptions voor waardelijsten op te nemen (description na $ref i.p.v. in allOf). Hierdoor wordt in Swaggerhub de description niet getoond. Wat is dan het nut van die descriptions als die toch niet getoond worden?

Is er geen alternatieve manier die wel toont in Swagger en ook goed werkt met code genereren?

**Comment by fsamwel** [comment]
Bij BRP hebben we hiervoor descriptions van dit soort velden opgenomen in de description van de schema component. Is het niet beter dat hier ook te doen?

**Comment by JohanBoer** [comment]
Melvin checked of in de huidige oplossing de description in de code terecht komt.

**Comment by JohanBoer** [comment]
Marcel en Hilde lopen de mapping naar de waardelijsten in de descriptions door en Hilde loopt de descriptions door.

**Comment by MelvLee** [comment]
Tijdens het resolven worden deze descriptions weggegooid. Dat is waarschijnlijk de reden waarom je het ook niet zie in de UI

**Comment by JohanBoer** [comment]
Descriptions van waardelijsten worden ook toegevoegd aan de component naam van de component waar de waardelijst in zit zodat de developer deze ook beschikbaar heeft.
