### ISSUE TITLE
Als gemeente wil ik kadastrale onroerende zaken kunnen zoeken op de zakelijk gerechtigde ingeschreven niet-natuurlijk persoon met RSIN

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#4]
...zodat ik de gegevens van deze kadastrale onroerende zaken kan gebruiken.

Op basis van de het RSIN (van de NIET NATUURLIJK PERSOON als zakelijk gerechtigde) wordt een verzoekbericht opgesteld om KADASTRALE ONROERENDE ZAAKen te selecteren.

Zoekresultaat: De KADASTRALE ONROERENDE ZAAKen waarvan het RSIN van een zakelijke gerechtigde NIET NATUURLIJK PERSOON overeenkomt met het ingevulde zoek-argument uit het verzoekbericht worden opgenomen in het antwoordbericht.

**Acceptatiecriteria**
- [ ] Het is mogelijk te zoeken op de volgende eigenschap van de zakelijk gerechtigde van de kadastraal onroerende zaak:
    * rsin

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by CathyDingemanse** [comment]
> ...zodat ik de gegevens van deze kadastrale onroerende zaken kan gebruiken.
> 
> Op basis van de het RSIN (van de NIET NATUURLIJK PERSOON als zakelijk gerechtigde) wordt een verzoekbericht opgesteld om KADASTRALE ONROERENDE ZAAKen te selecteren.

TITEL is ONJUIST! Het is een ingeschreven niet natuurlijke persoon i.p.v. een niet ingeschreven natuurlijke persoon :-).

**Comment by fsamwel** [comment]
dank voor de scherpe waarneming Cathy. Ik heb het aangepast

**Comment by CathyDingemanse** [comment]
Doen we niet omdat deze relatie slechts in 40% procent van het bronbestand goed wordt gelegd, en het resultaat van deze queryparameter onbetrouwbaar is.
