### ISSUE TITLE
Definitie van de acceptCrs bezien. 

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#408]
Welk coördinatenstels kan er geleverd worden. 
Is content-negotiation uberhaupt nodig.

**Comment by mhebbink-kad** [comment]
Bij BAG loopt hierover ook een discussie zag ik: https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen/issues/59

Momenteel leveren wij alleen RD (EPSG:28992). Verder weet ik niet of we de default hierop ook mogen zetten als er niks wordt meegegeven door de aanvrager volgens de API-strategie.

Mijn voorstel zou zijn om dit toch te laten staan en voor de CRS (die we dan nog niet ondersteunen) een 406 Not acceptable terug te geven. 

Verder mis ik dan nog wel de content-crs header in de specs.

**Comment by JohanBoer** [comment]
Ik heb de accept-Crs header parameter laten staan en de Content-Crs header in de response toegevoegd.

**Comment by mhebbink-kad** [comment]
AcceptCrs worden verwijderd.
Content-Crs wordt wel geleverd door de provider.
