### ISSUE TITLE
afkortingen in propertynamen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#409]
voor een KadasterStuk gebruiken we in properties verschillende afkortingen. Is het niet duidelijker uitgeschreven namen te gebruiken?

- acgIdentificatie
- AKRregistercode 
- akrStukdeel1
- akrStukdeel2
- akrStukdeel3

**Comment by fsamwel** [comment]
@MelvLee heb je liever korte propertynamen (met afkortingen, zoals acgIdentificatie) of liever uitgeschreven propertynamen (zoals ambtelijkCorrectiegegevenIdentificatie)?

**Comment by MelvLee** [comment]
Ik zou het uitschrijven, net als bij burgerservicenummer

**Comment by JohanBoer** [comment]
Ik heb IKAd er op nageken. Daar wordt in de omschrijvingen verwezen naar een AKR/HYP register. en naar een omzetting van AKR naar KVS. 

Omschrijving van AKRregistercode in IMKAD : _Unieke identificatie van het soort AKR/HYP-register, waarbinnen stukken worden genummerd. Welke nog gehanteerd wordt zolang de registratie in AKR plaatsvindt._

Omschriiving akrStukdeel1 in IMKAD: _Hoewel er nu alleen nog numerieke waarden worden toegekend, moet het domein type Tekst blijven omdat er in het verleden alfanumerieke waarden zijn toegekend. Bij conversie vanuit AKR naar KVS zullen we bijvoorbeeld deel 1000A nr. 1 aantreffen._

Een google search levert op dat AKR staat voor _Automatisering Kadastrale Registratie_. De meeste berichten die ik zie hebben te maken met de MO AKR (Massale Output AKR) en dat is de voorloper van de BRK-levering (deze is 4 jaar geleden gestopt. Vergelijkbaar traject als nu van BRK-Levreing 1.0 naar 2.0) 

Ruikt dus sterk naar Legacy-codes. Ik heb geen idee in hoeverre deze nu gebruikt worden en ik weet ook niet of het er beter van wordt als je de naam gaat aanpassen van elementen die op de nominatie (lijkt mij tenminste) staan om uitgefaseerd te worden.

**Comment by JohanBoer** [comment]
Met bovenstaande informatie wil ik graag van @CathyDingemanse en @HildeVos  weten wat zij ervan vinden.

**Comment by CathyDingemanse** [comment]
@fsamwel @JohanBoer , zie #372

**Comment by JohanBoer** [comment]
> AKRregistercode
> Code van een kadasterstuk uit een voormalige registratie, bedoeld om vervolgonderzoek gemakkelijker mogelijk te maken.

Dit is een $ref naar een waardelijst. De description wordt daarbij niet getoond. Ik deze description wel toegevoegd. 

> description: Een ambtelijk correctie gegeven is een kadasterstuk waarmee het kadaster foute gegevens in de Basisregistratie Kadaster kan herstellen.

Deze stond al in de specs.
