### ISSUE TITLE
Als medewerker belastingzaken wil ik  een  perceel of appartementsrecht binnen mijn gemeente kunnen zoeken op nummeraanduidingidentificatie   

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#41]
...zodat ik hieraan een WOZ object kan koppelen.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by fsamwel** [comment]
parameter nummeraanduidingIdentificatie toevoegen aan /kadastraalonroerendezaken

**Comment by CathyDingemanse** [comment]
Is toegevoegd aan de endpoint 

- [ ]

**Comment by JohanBoer** [comment]
kan naar done

**Comment by fsamwel** [comment]
dit zit niet (meer) in specs v1.2, dus moet status en label anders

**Comment by JohanBoer** [comment]
Is nu (weer) toegevoegd aan de specificaties.

**Comment by fsamwel** [comment]
@kad-hebbim zoeken op nummeraanduidingIdentificatie van het hoofdadres/eerste adres werkt goed. Zoeken op nummeraanduidingIdentificatie van een van de volgende adressen vindt niks.

Bijvoorbeeld https://api.brk.acceptatie.kadaster.nl/esd/bevragen/v1/kadastraalonroerendezaken?nummeraanduidingIdentificatie=0518200000781378 levert /kadastraalonroerendezaken/23280647970000. Deze KOZ heeft meerdere adressen:
                "adressen": [
                    {
                        "nummeraanduidingIdentificatie": "0518200000781378"
                    },
                    {
                        "nummeraanduidingIdentificatie": "0518200000498229"
                    },
                    {
                        "nummeraanduidingIdentificatie": "0518200000363399"
                    },
                    {
                        "nummeraanduidingIdentificatie": "0518200000564166"
                    },
                    {
                        "nummeraanduidingIdentificatie": "0518200000597483"
                    }

Zoeken op een van de andere nummeraanduidingIdentificaties levert geen resultaat. Bijvoorbeeld:
{
    "_links": {
        "self": {
            "href": "/kadastraalonroerendezaken?nummeraanduidingIdentificatie=0518200000498229"
        }
    },
    "_embedded": {}
}

**Comment by kad-hebbim** [comment]
0518200000498229 ontbrak nog in de mapping. 
Deze is toegevoegd.

**Comment by fsamwel** [comment]
@kad-hebbim nu is het opgelost voor nummeraanduidingIdentificatie=0518200000498229, nog niet voor de andere nevenadressen. Kan je die ook toevoegen?

**Comment by kad-hebbim** [comment]
@fsamwel Argh, ik had niet al mijn wijzigingen doorgezet. Nu moeten ze allemaal weer werken.

**Comment by fsamwel** [comment]
is nu opgelost
