### ISSUE TITLE
Update openapi.yaml specificatie [MVP versie]

### ISSUE THREAD

**Issue by mhebbink-kad** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#413]
**Endpoints:**
- /kadastraalonroerendezaken/{kadastraalonroerendezaakidentificatie}
- /kadastraalonroerendezaken?burgerservicenummer={burgerservicenummer} 
- /kadastraalonroerendezaken?kadasterpersoonidentificatie={kadasterpersoonidentificatie}
- /kadastraalonroerendezaken?postcode={postcode}
- /kadastraalonroerendezaken?kadastraleaanduiding={kadastraleaanduiding}
- /kadastraalonroerendezaken/{kadastraalonroerendezaakidentificatie}/zakelijkgerechtigden
- /kadastraalonroerendezaken/{kadastraalonroerendezaakidentificatie}/zakelijkgerechtigden/{zakelijkgerechtigdeidentificatie}
- /kadasternatuurlijkpersoon/{kadasternatuurlijkpersoonidentificatie}
- /kadasternatuurlijkpersoon?q={zoekterm}
- /kadasternietnatuurlijkpersoon/{kadasternietnatuurlijkpersoonidentificatie}
- /kadasternietnatuurlijkpersoon?q={zoekterm}

**Excluded:**
- links naar de BAG API:
  - KadastraalOnroerendeZaak: _links.adressen 
  - Kadaster(Niet)NatuurlijkPersoon: _links.woonadres & _links.postadres
- links naar de BRP API:
  - ZakelijkGerechtigde: _links.persoon _(alleen als het om een persoon is die bekend is bij de BRP)_
  - ZakelijkGerechtigde: _links.betrokkenPartner _(alleen als het om een persoon is die bekend is bij de BRP)_
- links naar nog niet geïmplementeerde endpoints van BRK API:
  - KadastraalOnroerendeZaak: _links.stukken
  - ZakelijkGerechtigde: _links.stukken

**Comment by mhebbink-kad** [comment]
@JohanBoer: wat is de status van de openapi.yaml file die we nodig hebben voor het MVP en waar bovenstaande allemaal in staat?

Dan kunnen we de volgende stories daarmee ook afronden:
- #408: contentCrs implementeren
- #462: endpoint om kadastraalonroerendezaak op te vragen via kadastraleaanduiding

**Comment by JohanBoer** [comment]
> links naar de BRP API:
> * ZakelijkGerechtigde: _links.persoon _(alleen als het om een persoon is die bekend is bij de BRP)_
> * ZakelijkGerechtigde: _links.betrokkenPartner _(alleen als het om een persoon is die bekend is bij de BRP)_

Dit wordt niet in de specificatie geregeld. Dat is namelijk dezelfde property die je gebruikt om de link naar een kadasterPersoon te retourneren.
