### ISSUE TITLE
Als developer wil ik de vrijheid hebben om wel of niet een groepsnaam te gebruiken bij de fields parameter.

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#418]
...zodat ik zowel met als zonder groepsnaam te gebruiken de gewenste properties op kan nemen in de response. 

N.a.v. #373 is voor de implementatie van versie 1 gekozen om bij gebruik van de fields parameter verplicht een groepsnaam of de _links prefix vooraf te laten gaan aan de gewenst property als die zich in een groep of in de _links bevind. 

Nu wordt er een error geretourneerd als dit niet gedaan wordt. 

De gewenste situatie is dat bij gebruik van fields de betreffende property in het antwoord geleverd wordt ongeacht of de groepsnaam voor de propertynaam staat. 

In het geval dat de property-naam zonder groepsnaam niet meer uniek is zal er een beslissing genomen moeten worden of dan beide properties opgeleverd worden in de response of dat er een foutmelding geretourneer word.

**Comment by rhengeveld** [comment]
Ik denk niet dat we dit voor v1.1 gaan doen 😉

**Comment by rhengeveld** [comment]
Zoals besproken in de call op 08-07-2020.

**Voorbeeld nu:**
|Veld|Gevonden velden|
|---|---|
|tenaamstelling|tenaamstelling|
|tenaamstelling.aandeel|tenaamstelling.aandeel|
|tenaamstelling.aandeel.noemer|tenaamstelling.aandeel.noemer|
|aandeel|-|
|noemer|-|

**Voorbeeld gewenst**
|Veld|Gevonden velden|
|---|---|
|tenaamstelling|tenaamstelling|
|tenaamstelling.aandeel|tenaamstelling.aandeel|
|tenaamstelling.aandeel.noemer|tenaamstelling.aandeel.noemer|
|aandeel|tenaamstelling.aandeel|
|noemer|tenaamstelling.aandeel.noemer|

Oftewel de implementatie wijzigen van _"veld moet overeenkomen met_" naar _"veld moet eindigen op"_.  

---

Vermoedelijk is dit relatief goed te implementeren, omdat we op dit moment al een verzameling gebruiken welke _alle_ combinaties bevat van de aanwezige velden. Alleen moet de matching veranderd worden. Het kost waarschijnlijk wat meer moeite om dit aan te passen, maar lijkt te doen.

Enige vraagstuk is wat we doen als om "code" gevraagd wordt, wat héél veel velden kan teruggeven.

**Comment by fsamwel** [comment]
> Enige vraagstuk is wat we doen als om "code" gevraagd wordt, wat héél veel velden kan teruggeven.

@MelvLee wat vind jij hiervan? Wanneer ik bijvoorbeeld "code" vraag, moet ik dan elk waardelijst-veld terugkrijgen? Of een foutmelding dat het niet uniek is?

**Comment by MelvLee** [comment]
Ik denk foutcode omdat het veel kan zijn

**Comment by fsamwel** [comment]
Mee eens. @rhengeveld voorstel is dus om een foutmelding te geven wanneer een veldnaam niet uniek is. De reason hierbij zou iets kunnen zijn als "Deel van de parameterwaarde niet uniek: {waarde}."

Aandachtspunt hierbij zijn velden als "identificatie" en "type" (maar dit is geen complete lijst). Wanneer je bijvoorbeeld filtert op fields= identificatie bij zakelijkgerechtigden, dan kan dit betrekking hebben identificatie of persoon.identificatie of tenaamstelling.aantekeningen.identificatie, tenaamstelling.betrokkenPartner.identificatie, enz. Dus is het niet uniek (en komt vaak voor). Toch moet het mogelijk zijn het veld "identificatie" te selecteren.
Dus wanneer een opgegeven veld niet uniek is als einde van het pad, maar wel als je het exact beschouwd, moet dat m.i. geen fout geven.
Bijvoorbeeld ook in de kadasterpersonen is er een groep woonadres en _links.woonadres. Een verzoek met fields=woonadres moet dan wel de groep woonadres teruggeven, maar niet _links.woonadres

**Comment by rhengeveld** [comment]
Ok, duidelijk, dus de strategie wordt...

Beginnen met fields ophalen die _**eindigen op**_ gegeven waarde:
* **Aantal gevonden == 0**
Bestaande foutmelding `Deel van de parameterwaarde niet correct: {waarde}.`
* **Aantal gevonden == 1** 
Field leveren ✔️ 
* **Aantal gevonden > 1**
Fields ophalen met _**exacte match**_ op gegeven waarde  
  * **Gevonden**
Field leveren ✔️ 
  * **Niet gevonden**
Nieuwe foutmelding `Deel van de parameterwaarde niet uniek: {waarde}.`

**Comment by rhengeveld** [comment]
Geïmplementeerd ✔️ en binnenkort beschikbaar. Hieronder alvast voorbeelden van de werking.

---
[JSON resultaat](https://gist.github.com/rhengeveld/4fed0e6af122453fa8d38541fe356b79) van `/NL.IMKAD.KadastraalObject.76870487970000?fields=type,self&expand=aandeel`
* `type` komt op meerdere plekken voor, er is echter ook een exacte match voor 🙂 
* `self` komt op maar één plek in _fields_ voor
* `aandeel` komt op maar één plek in _expand_ voor

[JSON resultaat](https://gist.github.com/rhengeveld/653588de0abd855cde52685abd5bfbe0) van `/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000?fields=typ1,typ2,href&expand=andeel,identificatie,href`
* `typ1` en `typ2` zijn onbekende _fields_
* `andeel` is een onbekende _expand_
* `identificatie` en `href` hebben meerdere resultaten bij _fields_ en _expand_

_P.S. Ja, de request bevat per abuis nog "NL.IMKAD.KadastraalObject", het resultaat is vergelijkbaar zonder dit domein_

**Comment by rhengeveld** [comment]
Beschikbaar op de testomgeving ✔️
