### ISSUE TITLE
Als medewerker Belastingzaken wil ik van een kadastraal onroerende zaak iedere splitsing of samenvoeging raadplegen waarbij de kadastraal onroerende zaak betrokken is geweest, inclusief de identificaties van alle andere bij de splitsing(en) of samenvoeging(en) betrokken kadastraal onroerende zaken

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#42]
...zodat ik bijbehorend(e) WOZ object(en) kan definiëren.

Toelichting:
Ik voer met terugwerkende kracht een WOZ-object betreffende een nieuwbouw woning op. Daarbij ben ik verplicht een sluitende tijdslijn van relaties met kadastrale objecten te hebben. Deze relaties worden op dit moment op basis van kadastrale aanduiding gelegd.
Het gaat hier echter om een bouwterrein, waar het grondbedrijf de afgelopen maand op alle werkdagen een extra perceel heeft aangemaakt voor het scheppen van nieuwe kavels.
Op sommige dagen hebben er dubbele filiaties plaatsgevonden, maar in de WOZ is het niet toegestaan om percelen te koppelen die nog dezelfde dag vervallen.
Ik wil daarom in de kaart kunnen klikken, op de locatie waar de woning is gebouwd, en hier een overzicht krijgen van alle percelen die op deze locatie gelegen hebben.
Ik wil de begin- en vervaldatum weten van alle percelen die deze locatie bestonden, om te bepalen of er percelen zijn die minder dan een dag bestaan hebben, en om te controleren hoe lang de relatie van een specifiek kadastraal object kan duren.
Ik wil van het laatst gekoppelde g-perceel kunnen zien of het is over gegaan naar appartementsrechten, en zo ja, in welke akte(s) van (onder/wijziging-) splitsing ik kan vinden waar deze appartementsrechten zich bevinden in het pand. Ook wil ik direct kunnen zien op welke datum deze appartementsrechten zijn ontstaan, en wanneer van toepassing, zijn ondergesplitst of vervallen.

**Acceptatiecriteria**
We willen er dit van kunnen maken:
![image](https://user-images.githubusercontent.com/18162831/80503245-e258c680-8971-11ea-9c34-bf621b35ad38.png)

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by hoebedoelu** [comment]
Op sommige dagen hebben er dubbele filiaties plaatsgevonden, maar in de WOZ is het niet toegestaan om percelen te koppelen die nog dezelfde dag vervallen:
In principe maakt dit ook niet uit. Echter, van belang is dat er een aansluitende kadastrale registratie is (verplichting LV-WOZ). Hier mag geen gat in ontstaan. Daarnaast kan het soms voor de filiatie of historie handig zijn om terug te kunnen zoeken (ook bij dubbele filiaties). Denk hierbij aan objectvorming, maar ook bezwaarfase.

**Comment by JohanBoer** [comment]
De mogelijkheid om de gevraagde gegevens op te halen wordt nu geboden doordat er ook vervallen objecten geretourneerd kunnen worden. Hierdoor kan consumer-software op basis van de fiiliatie (isOntstaanuit en isOvergegaanIn) de bovenstaande "boom"opbouwen. Om dit mogelijk te maken is in de resource "Kadastraal Onroerende Zaak" een indicatieVervallen en een einddatum opgenomen. 

@CathyDingemanse Ik heb nu een toelichting opgenomen over het waarom van de indicatieVervallen. Wil jij controleren of die gewenst is en indien nodig herformuleren ?

**Comment by CathyDingemanse** [comment]
description 

indicatieVervallenKadastraalOnroerendeZaak bij isOvergegaanIn
Geeft aan dat de kadastraal onroerende zaak is overgegaan in een vervallen kadastraal onroerende zaak.

indicatieVervallenKadastraalOnroerendeZaak bij isOntstaanUit
Geeft aan dat de kadastraal onroerende zaak is ontstaan uit een vervallen kadastraal onroerende zaak.


@HildeVos, klopt dat?

**Comment by JohanBoer** [comment]
> indicatieVervallenKadastraalOnroerendeZaak bij isOvergegaanIn
> Geeft aan dat de kadastraal onroerende zaak is overgegaan in een vervallen kadastraal onroerende zaak.
> 
> indicatieVervallenKadastraalOnroerendeZaak bij isOntstaanUit
> Geeft aan dat de kadastraal onroerende zaak is ontstaan uit een vervallen kadastraal onroerende zaak.

Ik heb hier een herbruikbaar component "Filiatie"voor gemaakt. Hiervoor zou dus 1 description moeten komen die de lading dekt. Nu staat er : "Geeft aan of de filiatie verwijst naar een vervallen kadastraal onroerende zaak."


Mijn originele vraag ging om de indicatieVervallen die bij de Kadastraal Onroerende Zaak zelf is opgenomen. Die desctription is nu : "Vervallen objecten zijn opvraagbaar met de stand van zaken direct voordat het object vervallen is verklaard. Deze informatie is nodig om de filiatie-"boom" af te kunnen lopen en inzicht te krijgen in betrokken appartementsrechten en grondpercelen."

en voor einddatum heb ik de volgende opgenomen : "Datum waarop de kadastraal onroerende zaak is vervallen"

In swagger te bekijken op 
https://petstore.swagger.io/?url=https://raw.githubusercontent.com/JohanBoer/Haal-Centraal-BRK-bevragen/develop/specificatie/genereervariant/openapi.yaml#/Kadastraal%20Onroerende%20Zaken/GetKadastraalOnroerendeZaken

**Comment by JohanBoer** [comment]
@CathyDingemanse zou jij de bovenstaande vraag over de descriptions kunnen beantwoorden ? (Eventueel samen met @HildeVos

**Comment by CathyDingemanse** [comment]
@HildeVos wat vind je van het volgende voorstel:
Indicatie vervallen bij de onroerende zaak zelf:
Geeft aan dat de de kadastraal onroerende zaak is vervallen. Is raadpleegbaar zodat je kunt achterhalen uit welke splitsingen en samenvoegingen een actuele kadastraal onroerende zaak is ontstaan (filiatie).

indicatieVervallen
Geeft aan dat de kadastraal onroerende zaak is ontstaan uit of is overgegaan in een vervallen kadastraal onroerende zaak.

**Comment by HildeVos** [comment]
Prima voorstel!
