### ISSUE TITLE
Als PO wil ik dat de aantekeningen bij KOZ, hypotheken en beslagen worden toegevoegd, en alle aantekeningen van een description worden voorzien 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#423]
...zodat de geleverde KOZ volledig is.

Aantekeningen zitten op:
de KOZ
de tenaamstelling zakelijk recht
hyoptheken
beslagen
de persoon

Besproken met Hilde en Marcel: aantekeningen op KOZ en persoon wordt nog meegenomen in 1.0 
@JohanBoer pas jij de OAS aan met onderstaande descriptions?

description bij aantekening KOZ
Een aantekening is een verwijzing naar een ter inschrijving aangeboden stuk. Een aantekening op een Kadastraal object is meestal een beperking zoals de vestiging of beëindiging van erfdienstbaarheden of kwalitatieve verplichtingen.

description bij aantekening zakelijk recht
Een aantekening is een verwijzing naar een ter inschrijving aangeboden stuk. Een aantekening op een specifieke tenaamstelling van een zakelijk recht is meestal een beperking, zoals de verkrijging van een aandeel in een zakelijk recht onder opschortende voorwaarde.

description bij aantekening hypotheken
Een aantekening is een verwijzing naar een ter inschrijving aangeboden stuk. Een aantekening op een hypotheek is bijvoorbeeld een rangwisseling hypotheek, waarbij een hypotheek voorrang heeft boven eerder ingeschreven hypotheken of rechten op dezelfde kadastraal onroerende zaak.

description bij aantekening beslagen
Een aantekening is een verwijzing naar een ter inschrijving aangeboden stuk. Een aantekening op een beslag is bijvoorbeeld een ??????????????Thijs?

description bij aantekening persoon
Een aantekening is een verwijzing naar een ter inschrijving aangeboden stuk. Een aantekening op een persoon is meestal een gerechtelijke uitspraak, zoals een beperking van de beschikkingsbevoegdheid van een persoon.

**Comment by JohanBoer** [comment]
> description bij aantekening KOZ
Deze wordt nu ontsloten als privaatrechtelijke beperking van een KOZ via het endpoint : /kadastraalonroerendezaken/{kadastraalonroerendezaakidentificatie}/privaatrechtelijkebeperkingen

We waren hem dus niet vergeten bij de KOZ, maar ontsluiten hem als privaatrechtelijke beperking via een apart endpoint. Dat is denk ik iets anders dan het leveren van de aantekening als een gegevensgroep van de KOZ. 
Willen we dit endpoint laten vervallen en de aantekening opnemen als gegevensgroep ?

> description bij aantekening zakelijk recht
In deze API kennen we geen zakelijk recht. Wil je de aantekening toevoegen aan de zakelijkgerechtigde of aan de tenaamstelling ?  Advies: volgens mij moet deze bij de tenaamstelling worden toegevoegd. 

> en aantekening is een verwijzing naar een ter inschrijving aangeboden stuk. Een aantekening op een beslag is bijvoorbeeld een ??????????????Thijs?
Ik hoop dat hier nog input op komt. 

> description bij aantekening persoon
Ik veronderstel dat je hier de persoon binnen de zakelijkgerechtigde bedoelt. en niet in het algemeen de kadasterNatuurlijkPersoon of de kadasterNietNatuurlijkPersoon.

**Comment by CathyDingemanse** [comment]
> > description bij aantekening KOZ
> > Deze wordt nu ontsloten als privaatrechtelijke beperking van een KOZ via het endpoint : /kadastraalonroerendezaken/{kadastraalonroerendezaakidentificatie}/privaatrechtelijkebeperkingen
> 
> We waren hem dus niet vergeten bij de KOZ, maar ontsluiten hem als privaatrechtelijke beperking via een apart endpoint. Dat is denk ik iets anders dan het leveren van de aantekening als een gegevensgroep van de KOZ.
> Willen we dit endpoint laten vervallen en de aantekening opnemen als gegevensgroep ?

Nee, we laten het bij de privaatrechtelijke beperkingen.

> > description bij aantekening zakelijk recht
> > In deze API kennen we geen zakelijk recht. Wil je de aantekening toevoegen aan de zakelijkgerechtigde of aan de tenaamstelling ?  

Ja, daar was hij ook bedoeld. Na overleg met Thijs blijkt ook de aantekening op persoon hier bij te horen. Dat betekent een nieuwe description bij de aantekening op de tenaamstelling:
"Een aantekening is een verwijzing naar een ter inschrijving aangeboden stuk. Een aantekening op een tenaamstelling van een zakelijk recht is meestal een beperking. Bijvoorbeeld de verkrijging van een aandeel in een zakelijk recht onder opschortende voorwaarde, een beperking van de handelingsbevoegdheid van de zakelijk gerechtigde, of een koopovereenkomst".

Na overleg met Thijs:
Aantekening op beslag krijgt de volgende description:
Een aantekening is een verwijzing naar een ter inschrijving aangeboden stuk. Een aantekening op een beslag is theoretisch mogelijk, maar komt bijna niet voor. 

> 
> > description bij aantekening persoon
> > Ik veronderstel dat je hier de persoon binnen de zakelijkgerechtigde bedoelt. en niet in het algemeen de kadasterNatuurlijkPersoon of de kadasterNietNatuurlijkPersoon.
Deze wordt ondergebracht bij de aantekening op de tenaamstelling. En ja, het kan gaan over alle personen. Het kan ook bijvoorbeeld koopovereenkomst zijn (waarbij een nnp eigenaar is) of is eigendom van een nnp in oprichting.

**Comment by HildeVos** [comment]
Geen opmerkingen/aanvullingen. Wat mij betreft akkoord.
