### ISSUE TITLE
Als API-designer wil ik descriptions toonbaar maken in een swagger of redoc omgeving als die relevant zijn

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#427]
...zodat ook uit de grafisch opgemaakte specificaties informatie over de functionele betekenis van componenten en properties gelezen kan worden. 

N.a.v. een opmerking van Frank bij Pull Request #417  : 

Naast waardelijsten speelt dit ook bij de andere soorten generiek herbruikbare componenten, zoals geometrie, datum_onvolledig en HalLink. Ik zeg niet dat altijd overal een description nodig is (overlijden.datum lijkt mij vrij duidelijk), maar wellicht zijn er ook plekken waar toelichting wel handig zou zijn (bijvoorbeeld onderscheid tussen begrenzing , begrenzingDienendErf en begrenzingHeersendErf).

**Comment by JohanBoer** [comment]
@MelvLee Zou jij dit analoog aan de BRP-repository in kunnen richten ?

**Comment by rhengeveld** [comment]
@JohanBoer volgens mij is dit klaar en kan dit issue gesloten worden?
