### ISSUE TITLE
Ik mis nummeraanduidingIdentificatie via code

### ISSUE THREAD

**Issue by anikbin** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#432]
**Beschrijf de bug**
Ik heb een stukje code geschreven om kadastraalonroerendezaken binnen te halen.
Via de code mis ik een variabel “nummeraanduidingIdentificatie”.
 
**To Reproduce**
Via postman krijg ik hem zoals hieronder 
 "nummeraanduidingIdentificatie": "0518200000842213",
Terwijl ik hem via de code krijg zoals hieronder
"adresIdentificaties":["0518200000842213"]
 
 
**Verwacht gedrag**
Volgens de beschrijving van Github moet ik de waarde via nummeraanduidingIdentificatie binnen krijgen maar in werkelijkheid is het niet zo.
Welke is recent? Hoe moet ik mijn Class bouwen?

**Screenshots**
In postman:
{
    "kadastraalObjectIdentificatie": "NL.IMKAD.KadastraalObject.22310827210003",
    "koopsom": {
        "koopsom": 450000,
        "koopjaar": 1989,
        "indicatieMetMeerObjectenVerkregen": false
    },
    "typeKadastraalOnroerendeZaak": "appartementsrecht",
    "aardCultuurBebouwd": {
        "code": "12",
        "waarde": "Wonen (appartement)"
    },
    "kadastraleAanduiding": {
        "appartementsrechtVolgnummer": 3,
        "kadastraleGemeente": {
            "code": "881",
            "waarde": "'s-Gravenhage"
        },
        "perceelnummer": 8272,
        "sectie": "N"
    },
    "nummeraanduidingIdentificatie": "0518200000842213",
    "zakelijkGerechtigdeIdentificaties": [
        "90283613"
    ],
    "_links": {
        "self": {
            "href": "https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.22310827210003"
        },
        "bagAdressen": [
            {
                "href": "https://{hostname}/lvbag/api/huidigebevragingen/vhc/adressen/0518200000842213",
                "templated": true
            }
        ],
        "zakelijkGerechtigden": [
            {
                "href": "https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.22310827210003/zakelijkgerechtigden/90283613",
                "templated": false
            }
        ]
    }
}

Via code

{"identificatie":"NL.IMKAD.KadastraalObject.22310827210003","koopsom":{"koopsom":450000,"koopjaar":1989,"indicatieMetMeerObjectenVerkregen":false},
"typeKadastraalOnroerendeZaak":"appartementsrecht","aardCultuurBebouwd":{"code":"12","waarde":"Wonen (appartement)"},
"kadastraleAanduiding":{"appartementsrechtVolgnummer":3,"kadastraleGemeente":{"code":"881","waarde":"'s-Gravenhage"},"perceelnummer":8272,"sectie":"N"},
"adresIdentificaties":["0518200000842213"],"zakelijkGerechtigdeIdentificaties":["90283613"],"
_links":{"self":{"href":"https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.22310827210003"},
"adressen":[{"href":"https://{hostname}/lvbag/api/huidigebevragingen/vhc/adressen/0518200000842213","templated":true}],
"zakelijkGerechtigden":[{"href":"https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.22310827210003/zakelijkgerechtigden/90283613"}]}}

**Comment by fsamwel** [comment]
de software is inmiddels aangepast zodat deze weer aansluit op de specificaties. Wat je hierboven beschrijft is het gevolg van wijzigingen aan de specificaties die op dat moment nog niet direct waren doorgevoerd in de implementatie.
