### ISSUE TITLE
zakelijk gerechtigde is partner van zichzelf

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#434]
https://api.test.kadaster.nl/esd/gemeenten/brk/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000/zakelijkgerechtigden

in het antwoord is _embedded.zakelijkGerechtigden[0].betrokkenPartner.identificatie: "NL.IMKAD.Persoon.70882239"
en _embedded.zakelijkGerechtigden[0].persoon.identificatie: "NL.IMKAD.Persoon.70882239"

De zakelijk gerechtigde is dus partner van zichzelf. Zelf in tijden van social distancing is dat een vreemde keuze.

Ook zijn betrokkenSamenwerkingsverband en betrokkenGorzenEnAanwassen dezelfde. Ook dat is een erg onwaarschijnlijke situatie. Ook voor het testen is het nuttig om te zien dat ze met iets verschillends gevuld worden.

**Comment by fsamwel** [comment]
Ook bijzonder is dat deze zakelijkgerechtigde burgerlijkeStaatTenTijdeVanVerkrijging "Ongehuwd en geen geregistreerd partnerschap" had.

**Comment by mhebbink-kad** [comment]
Fout in testdata.
