### ISSUE TITLE
typeGerechtigde is type geworden

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#435]
in de zakelijkGerechtigde is nu nog "typeGerechtigde" opgenomen (bijvoorbeeld met waarde "eigenaar"). Dat is in de specificaties "type" geworden.

**Comment by fsamwel** [comment]
Ook is zakelijkgerechtigde.tenaamstelling.aantekening.aardAantekening gewijzigd naar aard.

**Comment by mhebbink-kad** [comment]
Komt mee als we de laatste wijzigingen op de openapi specificaties hebben doorgevoerd.
Versie openapi = https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/blob/master/specificatie/BRK-Bevragen/genereervariant/openapi.yaml [20200428 17:56]

**Comment by rhengeveld** [comment]
Implementatie bijgewerkt met nieuwe `openapi.yaml`. De velden zijn nu inderdaad "type" en "aard". Komt mee met de volgende release/update.
