### ISSUE TITLE
Gebruik van uri template {hostname} als link kan verwijzen naar verschillende bronnen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#437]
bij zakelijkgerechtigden wordt_links.persoon.href nu geleverd als rui template met {hostname}.

Dat is denk ik erg onhandig voor de gebruiker, omdat dit kan verwijzen naar verschillende bronnen, namelijk BRP (ingeschreven personen) of BRK (Kadasterpersonen).

De identificatie daarentegen is weer niet in de tempalte opgenomen, terwijl die juist wel gevuld zou kunnen worden uit de persoon.identificatie (hoewel ik daar hier niet echt de toegevoegde waarde van zie).

Op andere plekken, zoals in de self link, wordt dan weer geen {hostname} template gebruikt, maar wordt de hostname hard in de uri opgenomen.

**Comment by fsamwel** [comment]
@MelvLee Hoe moeten we hiermee omgaan? Is dit inderdaad onhandig voor de gebruiker, of is het juist wel handig hier de hostname template te gebruiken? Wanneer is gebruik van een template gewenst en wanneer juist niet?

**Comment by MelvLee** [comment]
Ik denk dat het in ieder geval handig is om de {hostname} placeholder te gebruiken als de url naar een andere Web API verwijst, bijv. van uit BRK een link opnemen naar de BRP.
Verder denk ik dat het gewenst is om templates te gebruiken als de response veel links van dezelfde soort bevat. Dit zorgt ervoor dat de response klein blijft.
Ik ben nog niet tegengekomen dat er situaties zijn dat het niet gewenst is om templates te gebruiken. Zelf denk ik dat het weinig zin heeft als je maar één link heb van dezelfde soort

**Comment by fsamwel** [comment]
voor links in hetzelfde domein, is er dan een reden om niet gewoon relatieve urls te gebruiken?

**Comment by MelvLee** [comment]
Nee, ik kan geen redenen bedenken.

**Comment by rhengeveld** [comment]
Gaan we naar mijn weten niet oppakken voor v1.1

**Comment by fsamwel** [comment]
> Gaan we naar mijn weten niet oppakken voor v1.1

In mijn beeld is de status nu:
1. er worden relatieve urls geleverd bij interne links
2. er worden nooit externe links geleverd

Het leveren van externe links kan alleen wanneer die externe api ook beschikbaar is. De eerste zal BAG zijn voor adressen. Het moment dat die in productie is lijkt mij een goed moment om ook deze externe links beschikbaar te stellen mét de juiste templated placeholder. Of gaan jullie dit in v1.2 bouwen en in productie pas aanzetten wanneer BAG ook in productie is?

**Comment by rhengeveld** [comment]
Punt 1 en 2 zijn correct. Naar mijn weten wachten we met de implementatie van externe links, tot de externe api daadwerkelijk op productie beschikbaar is. Label `v1.2` had ik als (tijdelijk) label toegewezen, om in een volgende versie op te pakken als dit van toepassing is - om anders door te schuiven naar een volgende versie. 

Ik vind het echter ook prima om de versie labels eraf te halen, tot duidelijk is in welke versie we dit daadwerkelijk gaan implementeren.

**Comment by JohanBoer** [comment]
Naar versie 1.3 zetten.

**Comment by JohanBoer** [comment]
BAG-links zijn in productie beschikbaar

**Comment by fsamwel** [comment]
> BAG-links zijn in productie beschikbaar

@JohanBoer hoe bedoel je dit? Volgens mij:
1. worden nu in productie (en ook in test en acceptatie) geen links naar BAG objecten opgenomen
2. is dit issue gepland voor realisatie in release 1.3

Waarom staat deze dus nu in de backlog?

N.B. ook opnemen adresseerbaarObject (zoals besproken op 24 november) verandert hier denk ik niks aan, want er moet nog steeds ook een link zijn in veld adressen (op basis van nummeraanduiding), die al in de specificaties is opgenomen

**Comment by JohanBoer** [comment]
@fsamwel Deze links naar de BAG zijn nu (mede n.a.v. de bespreking op 24 november) opgenomen in de specificatie en kunnen dus in versie 1.3. ingebouwd gaan worden in de BRK. Ik heb het wat ongelukkig geformuleerd, maar ik bedoelde dat de HC BAG-api nu in productie is, dus we kunnen de BAG-links ook daadwerkelijk aan consumers beschikbaar stellen.

**Comment by fsamwel** [comment]
@JohanBoer dan zou toch de status voor implementatie juist "To Do" moeten zijn, en niet "Backlog"? Dus waarom heb je deze in de backlog gezet?

Ik heb de status nu gezet zoals ik denk dat die moet zijn, als je het daar niet mee eens bent, hoor ik dat graag

**Comment by JohanBoer** [comment]
Ik zet eigenlijk nooit wat op het implementatie board en ik weet niet wat de afspraken zijn. Ik vind het uitstekend dat het nu op Todo staat.

**Comment by fsamwel** [comment]
@MelvLee @CathyDingemanse de externe links (van BRK naar BAG) worden nu geleverd als absolute links (bijv. "https://api.bag.kadaster.nl/esd/huidigebevragingen/v1/adressen/{adressen.nummeraanduidingIdentificatie}"), dus niet met templating van de base url. Zien we dat al probleem of "fout", i.v.m. het gebruik van de API achter een API gateway of ander soort proxy?

**Comment by MelvLee** [comment]
Volgens mij is het geen fout. Het maakt het makkelijker om urls te re-writen. Maar met behulp van een regular expression kan het makkelijk worden uitgefilterd en worden vervangen
