### ISSUE TITLE
Boolean niet leveren bij waarde false

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#444]
De booleans in de antwoorden zijn altijd indicatoren dat er iets bijzonders aan de hand is. Dat is alleen interessant wanneer dat ook het geval is. Dus hebben we gekozen deze properties alleen te leveren bij de waarde true.

Bijvoorbeeld bij https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000
krijg ik nu:
```
   "koopsom" : {
      "koopsom" : 185000,
      "koopjaar" : 2015,
      "indicatieMetMeerObjectenVerkregen" : false
   },
```
Hierin is indicatieMetMeerObjectenVerkregen false, dus had deze niet opgenomen moeten worden.

**Comment by rhengeveld** [comment]
Aangepast, komt mee in de volgende release/update.

**Comment by rhengeveld** [comment]
@fsamwel ik heb dit ☝️ dus aangepast, maar wat als je via de _fields_ expliciet om dit veld vraagt, terwijl dit veld de waarde _false_ heeft? De waarde wordt nu dus alsnog uit de response gefiltered, terwijl ik mij kan voorstellen dat je deze wél wil als je hier expliciet om vraagt.

Bijvoorbeeld een GET op 
```
.../esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000/zakelijkgerechtigden?fields=tenaamstelling.aantekening.betreftGedeelteVanPerceel
```
