### ISSUE TITLE
korteNaam moet altijd worden worden geleverd

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#445]
de korteNaam van een adres moet altijd worden geleverd, niet alleen wanneer de straatnaam heel lang is. Dan kan de gebruiker namelijk een straatnaam die gegarandeerd niet te lang is gebruiken vanuit één property. Aftesten welke van de twee gevuld is, is dan niet meer nodig.

**Comment by mhebbink-kad** [comment]
Waar haal ik de korteNaam vandaan? Die krijg ik niet terug uit het model van het Kadaster.

**Comment by mhebbink-kad** [comment]
Vraag staat uit bij Ronald Peeters.

**Comment by fsamwel** [comment]
@JohanBoer op dit moment wordt korteNaam nog niet geleverd. Dus moet deze verwijderd worden uit MVP.
