### ISSUE TITLE
Persoon met gerelateerde KOZ maar geen gerelateerde zakelijkgerechtigden?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#447]
https://api.test.kadaster.nl/esd/gemeenten/brk/kadasternatuurlijkpersonen/NL.IMKAD.Persoon.70882239

Deze Kadasterpersoon heeft in het antwoord 2 kadastraalOnroerendeZaakIdentificaties, maar geen zakelijkGerechtigdeIdentificaties. Hoe kan dat?

**Comment by mhebbink-kad** [comment]
Testdata niet  volledig genoeg. Bepaalde mapping ontbreekt nog. 
Ben ik aan het oppakken.

**Comment by fsamwel** [comment]
dit issue geldt voor alle kadasterpersonen, zowel naturlijk als niet-natuurlijk. Geen van de kadasterpersonen toont op dit moment _links.zakelijkGerechtigden.

**Comment by mhebbink-kad** [comment]
Is deze nog wel van toepassing nav #470?

**Comment by fsamwel** [comment]
@mhebbink-kad 
> Is deze nog wel van toepassing nav #470?

#470 gaat alleen over de zaakgerechtigdeIdentificaties. De links naar zakelijkGerechtigden moeten nog blijven. En daar gaat dit issue over.

**Comment by mhebbink-kad** [comment]
Opgelost.
