### ISSUE TITLE
Diakrieten komen niet goed over in natuurlijke persoon

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#448]
https://api.test.kadaster.nl/esd/gemeenten/brk/kadasternatuurlijkpersonen/NL.IMKAD.Persoon.50550743

Deze bevat in het antwoord:
   "woonadres" : {
      "adresregel1" : " PRIMA PLEIN 123",
      "adresregel2" : "LUIK",
      "adresregel3" : "WalloniÃ«",
      "land" : {
         "code" : "5010",
         "waarde" : "BelgiÃ«"
      }
   },

De "ë" van Wallonië en België is niet goed overgekomen.

Mogelijk komt dit omdat er in de content-type header geen UTF-8 o.i.d. is opgenomen, zodat de ontvanger niet weet in welke charset is gebruikt.

**Comment by rhengeveld** [comment]
@fsamwel waarmee heb je dit resultaat verkregen? Welke browser?

----

Ik snap wat je zegt met charset. Ik zou dit verwachten:
> ContentType: application/hal+json; charset=UTF-8

Echter de response bevat:
> Content-Type: application/hal+json

Vreemd. Vroeger heb ik ook met dit HATEOAS framework gewerkt, toen was er een optie voor UTF-8. Deze blijkt verwijderd te zijn [[issue](https://github.com/spring-projects/spring-hateoas/issues/987), [commit](https://github.com/spring-projects/spring-hateoas/commit/feaa56a68ccaac04aca9826d164b226927eb42b6)] evenals verwijderd uit het Spring framework [[issue](https://github.com/spring-projects/spring-framework/issues/22788)].   

De motivatie hiervoor is te vinden in de nieuwere [RFC 8259 punt 8.1](https://tools.ietf.org/html/rfc8259#section-8.1):
> JSON text exchanged between systems that are not part of a closed ecosystem MUST be encoded using UTF-8 [RFC3629].

Met andere woorden, als je JSON gebruikt dan gebruik je impliciet charset UTF-8, dus charset hoef je niet meer op te geven (en doet ook niks meer). Gezien dit ook gefixt is in alle recente browsers ([Chromium in 2017](https://bugs.chromium.org/p/chromium/issues/detail?id=438464)) is besloten om dit te verwijderen.

----

Lokaan een klein testje met Postman lijkt prima om te gaan met diakrieten:
```
{
    "_embedded": {
        "zakelijkGerechtigden": [
            {
                "identificatie": "Diakrieten ü-î-ç",
                "type": "eigenaar",
```
Het enige wat ik verder kan bedenken, is dat de _bron_ van HaalCentraal de gegevens niet correct aanlevert dan wel dat HaalCentraal deze niet als zijnde UTF-8 inleest. De JSON response kan het in ieder geval niet aan liggen.

**Comment by rhengeveld** [comment]
Ik heb mijn lokale HaalCentraal aangesloten op hetzelfde _data endpoint_ als de testomgeving op `api.test.kadaster.nl` en zie:
✔️ diakrieten in XML response van _data endpoint_
✔️ diakrieten in JSON response van HaalCentraal
Volgens mij klopt alles dus 👍 

----

**GET .../esd/gemeenten/brk/kadasternatuurlijkpersonen/NL.IMKAD.Persoon.50550743**
```
{
    "identificatie": "NL.IMKAD.Persoon.50550743",
    "omschrijving": "Sidonia Jansens",
    "woonadres": {
        "adresregel1": "PRIMA PLEIN 123",
        "adresregel2": "LUIK",
        "adresregel3": "Wallonië",
        "land": {
            "code": "5010",
            "waarde": "België"
        }
    },
    "kadastraalOnroerendeZaakIdentificaties": [
        "NL.IMKAD.KadastraalObject.76870487970000"
    ],
    "geheimhoudingPersoonsgegevens": false,
    "landWaarnaarVertrokken": {
        "code": "5010",
        "waarde": "België"
    },
```
