### ISSUE TITLE
opmaak buitenlands adres niet als verwacht

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#449]
https://api.test.kadaster.nl/esd/gemeenten/brk/kadasternatuurlijkpersonen/NL.IMKAD.Persoon.50550743

Dit bevat in het antwoord:
   "woonadres" : {
      "adresregel1" : " PRIMA PLEIN 123",
      "adresregel2" : "LUIK",
      "adresregel3" : "WalloniÃ«",
      "land" : {
         "code" : "5010",
         "waarde" : "BelgiÃ«"
      }
   },

- adresregel1 begint met een spatie
- adresregel2 bevat geen postnummer

Zit dit zo in de testdata (bron) of heeft dit met de mapping naar de API te maken?

**Comment by mhebbink-kad** [comment]
@fsamwel: is testdata vanuit de bron. Zal kijken of ik dit kan aanpassen.
