### ISSUE TITLE
Adresregels niet gevuld voor postbus

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#452]
https://api.test.kadaster.nl/esd/gemeenten/brk/kadasternietnatuurlijkpersonen/NL.IMKAD.Persoon.71291440 
Dit levert als postadres:
```
   "postadres" : {
      "postcode" : "1000AA",
      "woonplaats" : "Amsterdam",
      "postbusnummer" : 100
   },
```
Hierin zijn adresregel1 en adresregel2 niet opgenomen. Die had ik wel verwacht, zodat de gebruiker altijd deze adresregels kan gebruiken, ongeacht het soort adres (postbus, binnenlands, buitenlands).

In het woonadres zijn de adresregels bijvoorbeeld wel voor een binnenlandsadres gevuld.

**Comment by fsamwel** [comment]
ook land wordt niet gevuld voor een postbus, terwijl dit wel voor een binnenlandsadres wordt gevuld

**Comment by mhebbink-kad** [comment]
2 vragen:
1. Willen we voor zowel een binnenlands als een postbus standaard land vullen met Nederland of dit leeg laten?
2. Voor bovenstaand voorbeeld, worden de adresregels dan als volgt:
adresregel1: Postbus 100
adresregel2: 1000AA Amsterdam

**Comment by mhebbink-kad** [comment]
Antwoorden:
1. Land altijd vullen met Nederland
2. Notatie klopt

**Comment by rhengeveld** [comment]
Aangepast in implementatie, komt mee volgende release/update.
