### ISSUE TITLE
Straat ontbreekt in woonadres van nietnatuurlijkpersoon

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#455]
https://api.test.kadaster.nl/esd/gemeenten/brk/kadasternietnatuurlijkpersonen/NL.IMKAD.Persoon.440650207
en
https://api.test.kadaster.nl/esd/gemeenten/brk/kadasternietnatuurlijkpersonen/NL.IMKAD.Persoon.71291440

in de antwoorden op beide requests ontbreekt een straat in het antwoord. Deze had ik wel verwacht in woonadres.straat, woonadres.korteNaam en woonadres.adresregel1

```
   "woonadres" : {
      "huisnummer" : 1,
      "postcode" : "2141PP",
      "woonplaats" : "ROTTERDAM",
      "adresregel1" : "1",
      "adresregel2" : "2141PP ROTTERDAM",
      "land" : {
         "code" : "6030",
         "waarde" : "Nederland"
      }
   },
```

**Comment by mhebbink-kad** [comment]
Mapping ontbreekt voor straat. 
Is toegevoegd en komt mee in de volgende update van de applicatie.
