### ISSUE TITLE
Rechtsvorm niet consequent gevuld

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#456]
https://api.test.kadaster.nl/esd/gemeenten/brk/kadasternietnatuurlijkpersonen/NL.IMKAD.Persoon.440650207
bevat in het antwoord:
```
   "rechtsvorm" : {
      "code" : "2",
      "waarde" : "Besloten vennootschap"
   },
```
https://api.test.kadaster.nl/esd/gemeenten/brk/kadasternietnatuurlijkpersonen/NL.IMKAD.Persoon.71291440 
hier bevat het antwoord:
```
   "rechtsvorm" : {
      "code" : "2",
      "waarde" : "BV"
   },
```

Hoe kan dezelfde code uit een waardelijst de ene keer een andere waarde hebben dan de andere keer?

**Comment by mhebbink-kad** [comment]
Fout in testdata. Waarde is overal omgezet naar "Besloten vennootschap"
