### ISSUE TITLE
hele adres leveren, ook wanneer het een BAG adres is

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#459]
Bij kadasterpersonen wordt nu, wanneer het adres een BAG-adres is, en er dus een nummeraanduidingIdentificatie is (op dit moment gevuld als adresIdentificatie), het adres alleen gevuld met de adresIdentificatie (=nummeraanduidingIdentificatie).

Het is wel zo vriendelijk voor de gebruiker altijd een adres te geven aan de gebruiker, als comfortgegeven. Dat scheelt de gebruiker weer een call en een aansluiting op een andere API.

@CathyDingemanse zo wil je het toch?

**Comment by CathyDingemanse** [comment]
Dat doen we ook bij de BRP. Zolang er sprake is van niet-BAG adressen (ook binnen NL) is dit idd wel zo vriendelijk. Uiteraard wel de nummeraanduidingidentificatie leveren.

**Comment by rhengeveld** [comment]
Aangepast; naast adresIdentificatie (= nummeraanduidingIdentificatie) komen nu ook de adresgegevens weer mee. Zit in de volgende oplevering.
