### ISSUE TITLE
TypePerceelnummerVerschuiving zijn integers

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#460]
deltax en deltat in TypePerceelnummerVerschuiving zijn gespecificeerd als integers. In imKad zijn het REALS. Dus zou ik verwachten dat ze gespecificeerd zijn als number.

Is dit een bewuste keuze geweest om de verschuiving af te ronden naar gehele getallen?

**Comment by JohanBoer** [comment]
Nee, dat is geen bewuste keuze geweest. Wordt aangepast.
