### ISSUE TITLE
instance bij foutmelding is http

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#461]
https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000?fields=bestaatniet

geeft een foutmelding met
"instance" : "http://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000?fields=bestaatniet",

Hier is https gewijzigd in http

**Comment by rhengeveld** [comment]
Goede vondst, dit treedt alleen op bij foutmeldingen. Voor de _href_ links in een succes resultaat had ik dit met HTTP / HTTPS namelijk al wél opgelost. Zal dit ook toepassen voor de foutmeldingen 👍

**Comment by rhengeveld** [comment]
Opgelost in volgende oplevering.
