### ISSUE TITLE
zoeken KOZ filtert niet op appartementsrechtVolgnummer

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#462]
https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken?kadastralegemeente__code=881&kadastraleaanduiding__perceelnummer=8272&kadastraleaanduiding__sectie=N&kadastraleaanduiding__appartementsrechtvolgnummer=4

dit vindt een kadastraal onroerende zaak met kadastrale aanduiding
```
            "kadastraleAanduiding" : {
               "appartementsrechtVolgnummer" : 3,
               "kadastraleGemeente" : {
                  "code" : "881",
                  "waarde" : "'s-Gravenhage"
               },
               "perceelnummer" : 8272,
               "sectie" : "N"
            },
```
deze had niet gevonden moeten worden, aangezien kadastraleaanduiding__appartementsrechtvolgnummer=4 is opgegeven in de query

**Comment by mhebbink-kad** [comment]
Fout in mapping van testdata.

**Comment by fsamwel** [comment]
@mhebbink-kad het werkt nog niet als ik zou verwachten.

Wanneer je nu het juiste appartementsrechtVolgnummer opgeeft, wordt deze zaak gevonden (correct).
Wanneer je nu een onjuist appartementsrechtVolgnummer opgeeft, wordt geen zaak gevonden (correct).
Wanneer je geen appartementsrechtVolgnummer opgeeft, wordt geen zaak gevonden. Dat is niet correct. Wanneer ik zoek zonder appartementsrechtVolgnummer, moeten alle onroerende zaken gevonden worden die voldoen aan de opgegeven parameters, dus alle onroerende zaken met opgegeven gemeente, sectie en perceelnummer.

Het niet opnemen van een parameter (zoals hier kadastraleaanduiding__appartementsrechtvolgnummer) mag niet geïnterpreteerd worden als kadastraleaanduiding__appartementsrechtvolgnummer=NULL.

**Comment by fsamwel** [comment]
zelfde speelt bij zoeken op adres:
- adres__postcode=7361EW&adres__huisnummer=29 levert een kadastraal onroerende zaak
- adres__postcode=7361EW levert geen onroerende zaak

En:
- adres__postcode=7441JC&adres__huisnummer=1&adres__huisletter=a levert een onroerende zaak
- adres__postcode=7441JC&adres__huisnummer=1 levert geen onroerende zaak

**Comment by mhebbink-kad** [comment]
> @mhebbink-kad het werkt nog niet als ik zou verwachten.
> 
> Wanneer je nu het juiste appartementsrechtVolgnummer opgeeft, wordt deze zaak gevonden (correct).
> Wanneer je nu een onjuist appartementsrechtVolgnummer opgeeft, wordt geen zaak gevonden (correct).
> Wanneer je geen appartementsrechtVolgnummer opgeeft, wordt geen zaak gevonden. Dat is niet correct. Wanneer ik zoek zonder appartementsrechtVolgnummer, moeten alle onroerende zaken gevonden worden die voldoen aan de opgegeven parameters, dus alle onroerende zaken met opgegeven gemeente, sectie en perceelnummer.
> 
> Het niet opnemen van een parameter (zoals hier kadastraleaanduiding__appartementsrechtvolgnummer) mag niet geïnterpreteerd worden als kadastraleaanduiding__appartementsrechtvolgnummer=NULL.

De service die wij aanroepen ondersteunt dit niet. Deze kijkt puur of het een geldige kadastraleaanduiding is. @CathyDingemanse wordt deze manier van zoeken veel gebruikt door de afnemers? Dit omdat je er bijvoorbeeld niet van kunt uitgaan dat de grondperceel en bijbehorende appartementsrechten dezelfde sectie en perceelnummer hebben. Zie antwoord Hilde : ???

Hierover nadenkend zou ik er bijna voor pleiten om voor de kadastrale-aanduiding geen 'zoek endpoint', maar een 'raadpleeg endpoint' te gebruiken...

**Comment by mhebbink-kad** [comment]
@fsamwel:
> zelfde speelt bij zoeken op adres:
> 
> 1. adres__postcode=7361EW&adres__huisnummer=29 levert een kadastraal onroerende zaak
> 2. adres__postcode=7361EW levert geen onroerende zaak
> 
> En:
> 
> 3. adres__postcode=7441JC&adres__huisnummer=1&adres__huisletter=a levert een onroerende zaak
> 4. adres__postcode=7441JC&adres__huisnummer=1 levert geen onroerende zaak

nr. 2: dit komt omdat er meerdere resultaten zijn gevonden, waarvoor geen testgevallen zijn en er dus een Not Found wordt teruggeven. Zal kijken of ik de testdata kan updaten hierop. Is wel wat werk.

nr. 4: hier krijg ik resultaat terug met 2 kadastraalonroerendezaken, wat mijns inziens klopt.
```
{
    "_links": {
        "self": {
            "href": "https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken?fields=identificatie,kadastraleAanduiding&adres__postcode=7441JC&adres__huisnummer=1"
        }
    },
    "_embedded": {
        "kadastraalOnroerendeZaken": [
            {
                "identificatie": "NL.IMKAD.KadastraalObject.65490485270000",
                "type": "perceel",
                "kadastraleAanduiding": {
                    "kadastraleGemeente": {
                        "code": "395",
                        "waarde": "Hellendoorn"
                    },
                    "perceelnummer": 4852,
                    "sectie": "G"
                },
                "_links": {
                    "self": {
                        "href": "https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.65490485270000"
                    }
                }
            },
            {
                "identificatie": "NL.IMKAD.KadastraalObject.65490485370000",
                "type": "perceel",
                "kadastraleAanduiding": {
                    "kadastraleGemeente": {
                        "code": "395",
                        "waarde": "Hellendoorn"
                    },
                    "perceelnummer": 4853,
                    "sectie": "G"
                },
                "_links": {
                    "self": {
                        "href": "https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.65490485370000"
                    }
                }
            }
        ]
    }
}
```

**Comment by fsamwel** [comment]
> > 1. adres__postcode=7361EW&adres__huisnummer=29 levert een kadastraal onroerende zaak
> > 2. adres__postcode=7361EW levert geen onroerende zaak
>
> nr. 2: dit komt omdat er meerdere resultaten zijn gevonden, waarvoor geen testgevallen zijn en er dus een Not Found wordt teruggeven. Zal kijken of ik de testdata kan updaten hierop. Is wel wat werk.

@mhebbink-kad zou je dit wat verder kunnen uitleggen? Er is ten minste één testgeval op postcode 7361EW, namelijk die op huisnummer 29. Die wordt al gevonden bij direct zoeken met huisnummer, maar wordt niet gevonden bij zoeken zonder huisnummer. Vanuit mijn perspectief (vanuit functionaliteit, zonder enige kennis van de implementatie) is het testgeval er al, maar wordt het niet gevonden.

**Comment by CathyDingemanse** [comment]
Voortschrijdend inzicht, n.a.v. #200
Ik vraag mij af als je met deze "filter" geen appartementen kunt vinden op het grondperceel (want die hebben soms een ander perceelnummer), wat is dan nog het functionele nut van deze queryparameter als filter? Wij voorzien dan alleen in de behoefte van een afnemer die "alleen de gemeentecode en het perceelnummer weet van een appartementsrecht".  Mmmmh, ik vraag me af of we daar al die moeite voor moeten doen. Die kunnen we dan beter stoppen in #200 .

Voorstel: we definiëren de queryparameter kadastrale aanduiding als string, zodat we hem alleen in zijn geheel kunnen gebruiken, en hij niet als filter werkt. Dan kan hij ook mee in deze oplevering.

@HildeVos wat vind jij er van?
@MelvLee, wat vind jij er van?
@mhebbink-kad wat vind jij er van?

**Comment by MelvLee** [comment]
Is dit dan niet hetzelfde als appartementsrechtVolgnummer verplicht maken? Is dit niet makkelijker dan een string als kadastrale aanduiding? In geval van string moet je (neem ik aan) de kadastrale aanduiding ook op een bepaalde manier formatteren. Dat is dan logica die je moet documenteren en die iedere consumer moet implementeren. Persoonlijk is dat geen probleem, ik denk alleen dat de eerste makkelijker is

**Comment by CathyDingemanse** [comment]
Ok, maar het  appartementsrechtVolgnummer is niet altijd aanwezig. Nillable maken dan?

**Comment by MelvLee** [comment]
Als appartementsrechtVolgnummer verplicht wordt gemaakt en het is niet altijd aanwezig, dan moet het inderdaad Nillable worden gemaakt.

**Comment by JohanBoer** [comment]
> Ok, maar het appartementsrechtVolgnummer is niet altijd aanwezig. Nillable maken dan?

Dat vind ik ook geen charmante oplossing. Wij hebben als vuistregel dat we properties die geen waarde hebben niet retourneren en dan gaan we nu consumers dwingen een property zonder waarde in de call op te nemen.

**Comment by JohanBoer** [comment]
Conclusie is dat we de kadastrale aanduiding als in 1 string als query-parameter gaan definiëren. In de toelichting wordt uitgelegd dat die string opgebouwd moet worden in de volgorde: Kadastralegemeente, perceelnummer, sectie en indien van toepassing  appartementsrechtVolgnummer .

**Comment by mhebbink-kad** [comment]
@JohanBoer: heb antwoord gekregen: opbouw String kadastraleAanduiding is als volgt:
[kadastralegemeentenaam]<spatie>[sectie]<spatie>[perceelnummer]<spatie>A[appartementsrechtvolgnummer]

Voorbeeld:
Amsterdam A 1090 A2

**Comment by rhengeveld** [comment]
Hierbij de regex voor deze ☝️ kadastrale aanduiding. Deze mag wat mij betreft in de spec.
```
^([a-zA-Z0-9'][a-zA-Z0-9' ,-]*[a-zA-Z0-9]) ([A-IK-Z]{1,2}) ([1-9][0-9]{0,4})( A[1-9][0-9]{0,3})?$
```
* Gebruikt regex groups om makkelijker segmenten te identificeren en op te knippen
* Appartementsrechtvolgnummer is optioneel

Voorbeeld getest met [deze online regex tester](https://www.freeformatter.com/java-regex-tester.html):
![ESD-182-regex-kadastraleaanduiding](https://user-images.githubusercontent.com/1228038/83024643-f9e9a480-a02e-11ea-987f-b60b634ca4b1.png)

**Comment by CathyDingemanse** [comment]
Dat ziet er goed uit!
