### ISSUE TITLE
Zoekresultaat wanneer niks gevonden mag geen 404 geven

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#464]
Bijvoorbeeld https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken?adres__postcode=1234AB&adres__huisnummer=567&adres__huisletter=A&adres__huisnummertoevoeging=1

Hier wordt geen kadastraal onroerende zaak gevonden. Maar het antwoord is een 404:
```
{
  {
   "type" : "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_NotFound",
   "title" : "Not found",
   "status" : 404,
   "detail" : "Opgevraagde resource is niet gevonden.",
   "instance" : "https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken?adres__postcode=1234AB&adres__huisnummer=567&adres__huisletter=A&adres__huisnummertoevoeging=1",
   "code" : "Not Found"
}
```

Dit is niet terecht. Een 404 moet gegeven worden wanneer de resource of (in dit geval) de collection niet gevonden is. Dit is alleen het geval wanneer er niks gevonden wordt op de uri. Wanneer niks gevonden wordt als gevolg van de querystring, mag dat niet leiden tot een 404.

Verwacht was http statuscode 200 met:
{
   "_links" : {
      "self" : {
         "href" : "https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken?adres__postcode=1234AB&adres__huisnummer=567&adres__huisletter=A&adres__huisnummertoevoeging=1"
      }
   },
   "_embedded" : { }
}

**Comment by rhengeveld** [comment]
In de brede zin aangepast voor alles waar "embedded" wordt gebruikt (= type _"xxxxHalCollectieEmbedded"_). 

Waar voorheen een `GONE` of `NOT FOUND` zou resulteren in het resultaat als hierboven ☝️ resulteert dit nu -zoals gewenst- in een lege "embedded":
```json
{
    "_links": {
        "self": {
            "href": "http://localhost:8080/esd/gemeenten/brk/kadastraalonroerendezaken?adres__postcode=1234AB&adres__huisnummer=567&adres__huisletter=A&adres__huisnummertoevoeging=1"
        }
    },
    "_embedded": {}
}
```

Komt mee met de volgende oplevering.

**Comment by mhebbink-kad** [comment]
@rhengeveld: het lijkt nog niet te werken voor het endpoint: /kadastraalonroerendezaken?ingeschrevenpersoon__burgerservicenummer=999991906. Daar krijg ik nog steeds een 404 Not Found terug.

**Comment by fsamwel** [comment]
ik krijg nog 404 op:
- /kadastraalonroerendezaken?adres__postcode=7361EW
- /kadastraalonroerendezaken?kadastralegemeente__code=881&kadastraleaanduiding__perceelnummer=8272&kadastraleaanduiding__sectie=N
- /kadasternatuurlijkpersonen?q=jansens

**Comment by rhengeveld** [comment]
Ook opgelost voor deze situaties 👍
