### ISSUE TITLE
fields indicatieMetMeerObjectenVerkregen levert hele koopsom

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#466]
https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000?fields=koopsom.indicatieMetMeerObjectenVerkregen

Hier wordt van de koopsom alleen indicatieMetMeerObjectenVerkregen gevraagd, niet andere velden van de koopsom. 

https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000?fields=koopsom.koopjaar

Hier wordt van de koopsom alleen het koopjaar gevraagd.

Het antwoord bevat echter in beide gevallen:
```
   "koopsom" : {
      "koopsom" : 185000,
      "koopjaar" : 2015
   },
```

Bij het leveren van koopsom hoort ook koopjaar meegeleverd te worden. Maar is het omgekeerde ook waar, dat bij koopjaar of indicatieMetMeerObjectenVerkregen ook altijd koopsom moet worden geleverd?

Andere situatie hierbij:
https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.22590043870000?fields=koopsom.koopsom

Alleen koopsom is gevraagd, maar die is hier leeg. Nu bevat het antwoord:
```
   "koopsom" : {
      "koopjaar" : 1999,
      "indicatieMetMeerObjectenVerkregen" : true
   },
```

**Comment by fsamwel** [comment]
@HildeVos kan jij aangeven hoe dit moet werken? 

Dus gaat het om de hele groep (koopsom, koopjaar, indicatieMetMeerObjectenVerkregen) wanneer daar iets uit wordt gevraagd, moet de hele groep geleverd worden?
Of gaat het alleen om koopjaar bij de koopsom?

**Comment by mhebbink-kad** [comment]
@mhebbink-kad: feature beschrijven welke velden altijd teruggegeven worden, ook al wordt er niet om gevraagd.
@HildeVos: uitwerken welke gegevens(groepen) altijd geleverd moeten worden.

**Comment by HildeVos** [comment]
De combinatie koopsom/koopjaar/cultuurcodebebouwd of cultuurcodeonbebouwd is verplicht. Deze 3 moeten altijd samen geleverd worden. Als bijvoorbeeld 1 van deze ontbreekt, mogen alle 3 niet geleverd worden. IndicatieMetMeerObjectenVerkregen mag in principe los geleverd worden, maar heeft eigenlijk geen waarde zonder de voornoemde 3 items.

**Comment by rhengeveld** [comment]
Als volgt geïmplementeerd, komt mee met de volgende oplevering.

---

.. als je om tenminste één van deze fields vraagt:
* "koopsom" of "koopsom.xyz" (koopjaar, etc.)
* "aardcultuurBebouwd" of "aardcultuurOnbebouwd"

.. dan krijg je nu altijd deze fields in de response:
* "koopsom", "koopsom.koopjaar", "koopsom.koopsom", "koopsom.indicatieMetMeerObjectenVerkregen", "aardcultuurBebouwd", "aardcultuurOnbebouwd"

_( Uiteraard enkel mits de waarde van het veld niet *null* of *false* is )_

**Comment by mhebbink-kad** [comment]
Zie #520
