### ISSUE TITLE
gebruik templated links verduidelijken

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#468]
Ik denk dat het gebruik van templated links kan worden verduidelijkt in uri-templating.feature:

1. duidelijk maken precies welke placeholders gebruikt kunnen worden

2. in description van HAL-links verwijzing naar deze feature opnemen

3. duidelijk maken dat altijd templating mogelijk is, maar vooral gebruikt wordt voor verwijzen naar externe API (met hostname) en voor beperken omvang bericht bij groot aantal links naar zelfde API.

Ik denk dat de volgende placeholders mogelijk zijn:
- {hostname}: dit is de volledige url naar de API
  Dus niet "https://{hostname}/lvbag/api/haal-centraal-bag-bevragen/v{version}/adressen/{adresidentificatie}"
maar "{hostname}//adressen/{adresidentificatie}"
  Hier moeten we ook duidelijk maken hoe om te gaan met meerdere verschillende bronnen. 
  Bijvoorbeeld een link persoon (vanuit zakelijkGerechtigde) kan een Kadasterpersoon zijn, een ingeschreven natuurlijk persoon of een ingeschreven niet-natuurlijk persoon. Dus verwijzen naar BRK, BRP of HR API.

- elke property uit de resource
  Kan ook een gegeven uit een gegevensgroep zijn, bijvoorbeeld "tenaamstelling.betrokkenPartner.identificatie"

**Comment by rhengeveld** [comment]
Ik wijs deze toe aan v1.2, om voor de volgende versie iets met dit issue te doen. 
Niks met dit issue doen of geen veranderingen maken kan natuurlijk ook een uitkomst zijn, als dat maar duidelijk is 😉 

_(Dit om het aantal openstaande issues te verminderen. In mijn ervaring zijn issues die langere tijd open staan kennelijk niet belangrijk genoeg om iets mee te doen, dus kan je ze net zo goed sluiten.)_

**Comment by JohanBoer** [comment]
> 2\. in description van HAL-links verwijzing naar deze feature opnemen

Deze heb ik in pull request  66 van haal-centraal-common klaargezet

**Comment by fsamwel** [comment]
https://github.com/VNG-Realisatie/Haal-Centraal-common/pull/66/files is gemerged, dus dit issue is opgelost
