### ISSUE TITLE
zakelijkGerechtigdeIdentificaties niet voldoende om zakelijkGerechtigde te vinden

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#470]
We  hebben in de kadasterpersonen property zakelijkGerechtigdeIdentificaties opgenomen, zodat een gebruiker op basis hiervan de zakelijk rechten kan ophalen van deze persoon.

Apart hiervan hebben we kadastraalOnroerendeZaakIdentificaties opgenomen om de kadastrale zaken waar de persoon een recht op heeft op te kunnen halen.

Voor het ophalen van een zakelijkGerechtigde moet de volgende template worden gebruikt: 
{hostname}/kadastraalonroerendezaken/{kadastraalOnroerendeZaakIdentificaties}/zakelijkgerechtigden/{zakelijkGerechtigdeIdentificaties}

Een gebruiker kan nu niet weten welke kadastraalOnroerendeZaakIdentificatie hoort bij welke zakelijkGerechtigdeIdentificatie. Beide (bij elkaar horende identificaties) zijn nodig om een zakelijkGerechtigde op te halen.

**Comment by fsamwel** [comment]
@CathyDingemanse moet vanuit een persoon zowel de zaak als het recht opgehaald kunnen worden? Of is alleen de onroerende zaak voldoende? Dat zou het "probleem" direct oplossen.

Of kunnen we hier de identificaties weglaten en het beperken tot HAL-links. We hebben het hier immers niet opgenomen om een relatie aan te duiden of zoiets, puur vanuit discoverability.

**Comment by CathyDingemanse** [comment]
> @CathyDingemanse moet vanuit een persoon zowel de zaak als het recht opgehaald kunnen worden? Of is alleen de onroerende zaak voldoende? Dat zou het "probleem" direct oplossen.
> 
Nee, ik denk het niet, alleen de KOZ. Een recht bestaat toch helemaal niet zonder de KOZ?

> Of kunnen we hier de identificaties weglaten en het beperken tot HAL-links. We hebben het hier immers niet opgenomen om een relatie aan te duiden of zoiets, puur vanuit discoverability.

Dan doen we toch geen templating? De link is gewoon niet zelf samen te stellen uit een willekeurige lijst KOZen en gerechtigenidentificaties.

**Comment by CathyDingemanse** [comment]
Na overleg: @JohanBoer zakelijkgerechtigden identificaties weghalen!

**Comment by fsamwel** [comment]
@JohanBoer is dit al gedaan of moet hier nog iets aan gedaan worden?

**Comment by rhengeveld** [comment]
@fsamwel @JohanBoer als ik het goed begrijp is dit opgelost - ook i.c.m. de templating van #467 die we nu toepassen.  
Als mijn aanname niet klopt dan kan dit issue weer geopend en opgepakt worden (label v1.2?).

---

**1: `/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000?expand=zakelijkGerechtigden`**   
* [Response gist](https://gist.github.com/rhengeveld/a0fd211aaf21f15e9649123b9fcadaff)
* Links als deze `/kadastraalonroerendezaken/76870487970000/zakelijkgerechtigden/{zakelijkGerechtigdeIdentificaties}`
* En bij expand zakelijkGerechtigde `/kadastraalonroerendezaken/76870487970000/zakelijkgerechtigden/30491235`

**2: `/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000/zakelijkgerechtigden`**  
* [Response gist](https://gist.github.com/rhengeveld/c98cc94dfd7453915f02e6022abe0aa1)
* Links als `/kadastraalonroerendezaken/76870487970000/zakelijkgerechtigden/30493367`

**3: `/kadastraalonroerendezaken/76870487970000/zakelijkgerechtigden/30493367`**  
* [Response gist](https://gist.github.com/rhengeveld/b38cd60737c019756b2782e04f0b3e4e)

**Comment by JohanBoer** [comment]
Deze stond in ready for sprint. Geen assignment naar mij toe en geen label. Deze is aan mijn aandacht ontasnapt. Ik hoef echter alleen nog maar wat weg te halen uit de specificaties (Zakelijkgerechtigdeidentidentificaties bij kKadasterPersoon)

**Comment by rhengeveld** [comment]
Prima, ik dacht ik breng het even opnieuw onder de aandacht, dan is het of klaar of kan nog even opgepakt worden 😃
