### ISSUE TITLE
geslachtsaanduiding  ontbreekt in kadasternatuurlijkpersonen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#471]
https://api.test.kadaster.nl/esd/gemeenten/brk/kadasternatuurlijkpersonen/NL.IMKAD.Persoon.70882239

Hierin ontbreekt de geslachtsaanduiding.

Idem voor de andere kadasternatuurlijkpersonen

**Comment by mhebbink-kad** [comment]
Veld is veranderd in de laatste openapi.yaml file van geslacht naar geslachtsaanduiding, waardoor onze mapping niet meer up to date is.
