### ISSUE TITLE
onjuiste kadastraalOnroerendeZaakIdentificaties bij kadasternatuurlijkpersoon

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#472]
https://api.test.kadaster.nl/esd/gemeenten/brk/kadasternatuurlijkpersonen/NL.IMKAD.Persoon.71303564
geeft in het antwoord:
```
   "kadastraalOnroerendeZaakIdentificaties" : [
      "NL.IMKAD.KadastraalObject.76870488070000"
   ],
```

Maar https://api.test.kadaster.nl/esd/gemeenten/brk/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870488070000/zakelijkgerechtigden
heeft 1 zakelijkGerechtigde, met:
```
            "persoon" : {
               "identificatie" : "NL.IMKAD.Persoon.71291440",
               "omschrijving" : "Bankbedrijf",
               "type" : "kadaster_niet_natuurlijk_persoon"
            },
```
En https://api.test.kadaster.nl/esd/gemeenten/brk/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870482570000/zakelijkgerechtigden 
heeft 3 zakelijkGerechtigden, waarvan de tweede met:
```
            "persoon" : {
               "identificatie" : "NL.IMKAD.Persoon.71303564",
               "omschrijving" : "Christiaan Goede",
               "type" : "kadaster_natuurlijk_persoon"
            },
```

**Comment by mhebbink-kad** [comment]
Fout in mapping van testdata.
