### ISSUE TITLE
Onjuiste vulling invalid-params bij fout in gebruik fields parameter

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#474]
https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000?fields=bestaatniet

Dit levert in de foutmelding de volgende invalidParams:
```
   "invalidParams" : [
      {
         "type" : "some-url-here",
         "name" : "bestaatniet",
         "code" : "fields",
         "reason" : "Deel van de parameterwaarde niet correct: bestaatniet."
      }
   ]
```

- bij type staat "some-url-here". Wanneer er geen url is om naar te verwijzen, waar echt een toelichting staat over deze foutmelding, dan liever geen geen url tonen. Maar in dit geval zou je ook kunnen verwijzen naar de [fields feature](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/master/features/fields.feature).

- name moet gevuld zijn met de paramter waar de fout in zit. In dit geval is dat "fields", niet "bestaatniet" (dat is de onjuiste waarde van de fields parameter)

**Comment by fsamwel** [comment]
zelfde probleem bij fout in expand parameter:
```
{
   "type" : "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_BadRequest",
   "title" : "Request is niet valide",
   "status" : 400,
   "detail" : "The request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modification.",
   "instance" : "https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000?expand=true",
   "code" : "Bad Request",
   "invalidParams" : [
      {
         "type" : "some-url-here",
         "name" : "true",
         "code" : "expand",
         "reason" : "Deel van de parameterwaarde niet correct: true."
      }
   ]
}
```

**Comment by rhengeveld** [comment]
Aangepast:
* Type blijft nu leeg
* Reason voor _fields_ veranderd in _"Deel van de parameterwaarde niet correct: fields."
* Reason voor _expand_ veranderd in _"Deel van de parameterwaarde niet correct: expand."

Komt mee met volgende oplevering.

**Comment by fsamwel** [comment]
@rhengeveld heb je ook de waarde in name gewijzigd? De tekst in reason was juist wel goed

Dus waar het was:
 ```
   "invalidParams" : [
      {
         "type" : "some-url-here",
         "name" : "bestaatniet",
         "code" : "fields",
         "reason" : "Deel van de parameterwaarde niet correct: bestaatniet."
      }
```
had ik verwacht:
```
   "invalidParams" : [
      {
         "name" : "fields",
         "code" : "fields",
         "reason" : "Deel van de parameterwaarde niet correct: bestaatniet."
      }
```

**Comment by rhengeveld** [comment]
Oh oops, dat had ik verkeerd begrepen / gelezen. Ik heb de _reason_ aangepast i.p.v. de _name_ 😅 
Zal dit corrigeren.

**Comment by rhengeveld** [comment]
Aangepast, komt mee met volgende oplevering.
