### ISSUE TITLE
KOZ zoeken op burgerservicenummer vindt niet de juiste onroerende zaken

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#475]
https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken?ingeschrevenpersoon__burgerservicenummer=999991905

dit levert 1 kadastraal onroerende zaak (223108272100030

Verwacht was nog een tweede onroerende zaak, NL.IMKAD.KadastraalObject.76870482570000.
Deze heeft 3 zakelijk gerechtigden, waarvan de 3e tenaam gesteld is op 999991905 met type erfpachter.

**Comment by rhengeveld** [comment]
Opgelost in volgende oplevering. Makkelijkst te controleren met deze URL:

https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken?ingeschrevenpersoon__burgerservicenummer=999991905&fields=identificatie&expand=zakelijkGerechtigden.identificatie,zakelijkGerechtigden.type,zakelijkGerechtigden.persoon

Zodat de nadruk op de zakelijkGerechtigden in de expand ligt
