### ISSUE TITLE
invalidParams.name is onjuist

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#476]
in een aantal gevallen van parameters met underscore (snake case) worden in foutmeldingen invalidParams[].name omgezet naar camelCase.

Bijvoorbeeld:
- https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken?kadastralegemeente__code=87&kadastraleaanduiding__perceelnummer=0&kadastraleaanduiding__sectie=K
  geeft in invalidParams: "name" : "kadastraleaanduidingPerceelnummer"
- https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken?kadastralegemeente__code=87&kadastraleaanduiding__perceelnummer=4879&kadastraleaanduiding__sectie=J
  geeft in invalidParams: "name" : "kadastraleaanduidingSectie"
- https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken?ingeschrevenpersoon__burgerservicenummer=1234567890
  geeft in invalidParams: "name" : "ingeschrevenpersoonBurgerservicenummer"

**Comment by fsamwel** [comment]
- adres__postcode --> adresPostcode

**Comment by rhengeveld** [comment]
Automatisch gegenereerde code op basis van de `openapi.yaml`:
```java
@Valid @RequestParam(name = "adres__huisnummertoevoeging") String adresHuisnummertoevoeging
```

De _@Valid_ triggered automatische validatie. Deze gebruikt de naam van van de String parameter (_adresHuisnummertoevoeging_) en heeft verder geen kennis van het bestaan van _@RequestParam_.

@mhebbink-kad wat vind jij? We zijn dit eerder tegengekomen, alleen was het toen nog _"String arg5"_. Dat heb ik toen verholpen. Daarbij heb ik ook deze ☝️ constatering hier gemaakt, maar we hebben toen besloten dit niet te doen, omdat ik dan moet inbreken op het gedrag van de [StandardReflectionParameterNameDiscoverer](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/core/StandardReflectionParameterNameDiscoverer.html) (of een _custom_ variant schrijven).

**Comment by mhebbink-kad** [comment]
Persoonlijk ben ik niet voor om hier een custom variant voor te gaan schrijven, omdat dit toch wat werk is wat weinig oplevert.

**Comment by rhengeveld** [comment]
Ok, misschien dacht ik te moeilijk, laten we deze optie proberen:
* De _InvalidParams_ in de response maak ik zelf vanuit de code
* ... dus op dat punt zou het ook mogelijk moeten zijn de _camelCase_ weer naar snake__case te vertalen

Mocht dit niet werken kan ik altijd nog 1-2 uurtjes proberen de _StandardReflectionParameterNameDiscoverer_ aan te passen.

**Comment by rhengeveld** [comment]
De eenvoudige oplossing werkt 😄 

* OpenApi spec `kadastraleaanduiding__perceelnummer`
* ⬇️ code generatie `String kadastraleaanduidingPerceelnummer`
* ⬇️ URL verzoorzaakt _ConstraintViolation_ welke vertaald wordt naar response met _InvalidParams_
* ⬇️ **(nieuw)** converteer `kadastraleaanduidingPerceelnummer` terug naar `kadastraleaanduiding__perceelnummer`

Dit gaat er vanuit dat de naamgeving vanuit de OpenApi spec niet veranderd. Dus dat we dit niet in een toekomstige versie veranderen in "kadastraleaanduiding-perceelnummer" of "kadastraleaanduidingPerceelnummer". Anders moet de nieuwe laatste conversiestap aangepast worden (paar minuten werk) 😉 

Voorbeeld na aanpassing, response op originele eerstgenoemde URL:
```json
{
    "type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_BadRequest",
    "title": "Request is niet valide",
    "status": 400,
    "detail": "The request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modification.",
    "instance": "https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken?kadastralegemeente__code=87&kadastraleaanduiding__perceelnummer=0&kadastraleaanduiding__sectie=K",
    "code": "Bad Request",
    "invalidParams": [
        {
            "name": "kadastraleaanduiding__perceelnummer",
            "code": "minimum",
            "reason": "Waarde is lager dan minimum 1."
        }
    ]
}
```
