### ISSUE TITLE
adres__huisnummertoevoeging heeft ten onrechte geen maximale lengte

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#478]
parameter adres__huisnummertoevoeging  is gedefinieerd met pattern: "^([a-z,A-Z,0-9])+$"

Dit betekent dat de lengte niet beperkt is. In imBAG is de huisnummerToevoeging gedefinieerd met maximale lengte 4.

Wanneer ik nu een huisnummertoevoeging invul met lengte>4 krijg ik een internal server error. Bijvoorbeeld https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken?adres__postcode=7441JC&adres__huisnummer=1&adres__huisnummertoevoeging=1a3D5

@JohanBoer ik denk dat een maxLength: 4 moet worden toegevoegd.

@mhebbink-kad ik vermoed dat de internal server error hierdoor veroorzaakt wordt, dus het toevoegen van controle op maximale lengte zou hier de oplossing voor kunnen zijn. Kan jij dat bevestigen? En zo ja, deze validatie toevoegen.

**Comment by mhebbink-kad** [comment]
Zie https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/495
