### ISSUE TITLE
Bij meerdere gelijktijdige foute parameters wordt er maar één fout gemeld

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#479]
https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken?adres__postcode=7441jc&adres__huisnummer=1a&adres__huisletter=bc&adres__huisnummertoevoeging=-bis

Hierin zijn alle parameters onjuist (postcode, huisnummer, huisletter en huisnummertoevoeging.

Maar in de foutmelding wordt maar één van de fouten genoemd:
```
   "invalidParams" : [
      {
         "type" : "some-url-here",
         "name" : "adres__huisnummer",
         "code" : "integer",
         "reason" : "Waarde is geen geldige integer."
      }
   ]

```

Ik had hier verwacht dat alle onjuiste invoer wordt gemeld.

**Comment by rhengeveld** [comment]
Dat wordt reeds gedaan, zie deze URL http://localhost:8080/esd/gemeenten/brk/kadastraalonroerendezaken?adres__postcode=7441jc&adres__huisnummer=999999999&adres__huisletter=bc&adres__huisnummertoevoeging=-bis
```json
{
    "type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_BadRequest",
    "title": "Request is niet valide",
    "status": 400,
    "detail": "The request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modification.",
    "instance": "http://localhost:8080/esd/gemeenten/brk/kadastraalonroerendezaken?adres__postcode=7441jc&adres__huisnummer=999999999&adres__huisletter=bc&adres__huisnummertoevoeging=-bis",
    "code": "Bad Request",
    "invalidParams": [
        {
            "name": "adresHuisletter",
            "code": "pattern",
            "reason": "Waarde voldoet niet aan patroon ^[a-zA-Z]$."
        },
        {
            "name": "adresPostcode",
            "code": "pattern",
            "reason": "Waarde voldoet niet aan patroon ^[1-9][0-9][0-9][0-9][A-Z][A-Z]$."
        },
        {
            "name": "adresHuisnummer",
            "code": "maximum",
            "reason": "Waarde is hoger dan maximum 99999."
        },
        {
            "name": "adresHuisnummertoevoeging",
            "code": "pattern",
            "reason": "Waarde voldoet niet aan patroon ^([a-z,A-Z,0-9])+$."
        }
    ]
}
```

Het issue is dat de validatie meerdere stadia heeft. Als een stadium faalt is het klaar (invalid).
1. Allereerst wordt geprobeerd "1a" te mappen op een integer. Dat mislukt, resulterend in _MethodArgumentTypeMismatchException_. Klaar (invalid).
2. Vervolgens worden alle constraints gecheckt. Dat gebeurt in jouw voorbeeld niet, in mijn voorbeeld wel gezien het nu een correcte _integer_ is. 

Dit is het default gedrag. Ik weet niet of dit überhaupt veranderd kan worden (zonder heel veel extra moeite). De enige werkbare optie is:
* Veranderd in de OpenApi spec `adres__huisnummer` in type _string_.
* Voeg hier een regex _pattern_ aan toe als voorheen. 
* Enige nadeel voor mij is dat ik dan zelf de String weer mag omzetten naar Integer.

**Comment by fsamwel** [comment]
@rhengeveld dit speelt dus niet alleen bij huisnummer, maar ook bij perceelnummer en appartementsrechtVolgnummer. En we krijgen dus niet fouten op de "gewone" parameters en de fields en expand parameters tegelijk door.

@CathyDingemanse @MelvLee hoe denken jullie hierover? Hoe belangrijk is het alle fouten in één keer gemeld te krijgen?
En zou een oplossing waarbij alle integer parameters worden omgezet naar string met pattern dan beter zijn dan maar één fout gemeld krijgen?

**Comment by MelvLee** [comment]
Dit is een lastige.
Een reden om parameters te typen is de developer helpen om niet een verkeerde waarde op te geven voor een parameter. Als je code genereert, dan heeft adres__huisnummer als type int. De consumer kan in dit geval geen andere waarde opgeven dan een int. Aan de provider kant gaat dit niet helemaal op omdat je ook consumers heb zoals postman of de browser waar je wel een letter kan opgeven als huisnummer.
Alle parameters een string te maken betekent dus wel dat de consumers die code genereren niet aan het type kunnen zien dat het niet om een string gaat. Bij een date parameter is het nog lastiger omdat je dan de string op de juiste manier moet formatteren. Als developer zou ik het niet erg vinden om niet altijd alle fouten in één keer terug te krijgen.

**Comment by fsamwel** [comment]
is dus geen "ramp". Nu niet oplossen.
