### ISSUE TITLE
Hoe vullen persoon.type

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#480]
Op de verschillende plekken waar verwezen wordt naar een persoon in de API (m.n. vanuit de zakelijk gerechtigde), wordt naast identificatie en omschrijving ook een type opgenomen.

We kennen daar nu 4 mogelijke typen:
      - "ingeschreven_natuurlijk_persoon"
      - "kadaster_natuurlijk_persoon"
      - "ingeschreven_niet_natuurlijk_persoon"
      - "kadaster_niet_natuurlijk_persoon"

Zowel de ingeschreven_niet_natuurlijk_persoon als de kadaster_niet_natuurlijk_persoon hebben nu als identificatie de kadasterpersoon identificatie. En de link naar de persoon verwijst in beide gevallen naar de /kadasternietnatuurlijkpersonen in de BRK API.

Volgens mij hebben we het type alleen opgenomen, zodat de gebruiker weet waar dit naar verwijst, dus hoe de persoon opgehaald kan worden op basis van de identificatie.
En we hebben nu "ingeschreven_niet_natuurlijk_persoon" opgenomen zodat in de toekomst, wanneer we wel naar een KvK API gaan verwijzen, ook dat type in de API ondersteunen.

Is het dan wel terecht dat we nu niet-natuurlijk personen waarvan we KvK-nummer en/of rsin hebben, het type "ingeschreven_niet_natuurlijk_persoon" geven?

**Comment by fsamwel** [comment]
@MelvLee wat denk jij dat een client developer hier zou willen zien?

**Comment by MelvLee** [comment]
Ik denk dat het goed is om een niet-natuurlijk persoon met een KvK-nummer en/of rsin al het type "ingeschreven_niet_natuurlijk_persoon" te geven en in documentatie aan te geven dat wanneer de KvK is ontsloten via een API dat deze daar kan worden bevraagd en dat het tot die tijd via /kadasternietnatuurlijkpersonen kan worden bevraagd.

**Comment by fsamwel** [comment]
in overleg besloten dat:
- als er een rsin is, dan is het ingeschreven niet natuur persoon, en wordt rsin in identificatie gestopt
- als er geen rsin is, dan is het kadaster niet natuurlijk persoon, ook als er wel een kvk nummer is

moet worden gewijzigd in de implementatie en in de specificaties (description van persoon.identificatie)

**Comment by fsamwel** [comment]
bijvoorbeeld: https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.56020234070000/zakelijkgerechtigden/50037358

```
   "persoon" : {
      "identificatie" : "NL.IMKAD.Persoon.440650207",
      "omschrijving" : "Gassie Test B.V.",
      "type" : "ingeschreven_niet_natuurlijk_persoon"
   },
```
Hier is de identificatie gevuld met de kadasterpersoonidentificatie, maar is het type ingeschreven_niet_natuurlijk_persoon
Ik had hier in identificatie de rsin verwacht:

```
   "persoon" : {
      "identificatie" : "900000001",
      "omschrijving" : "Gassie Test B.V.",
      "type" : "ingeschreven_niet_natuurlijk_persoon"
   },
```

**Comment by mhebbink-kad** [comment]
Klopt het dan dat we voor bovenstaand voorbeeld de link als volgt definiëren (interne link , ongeacht of het dus een ingeschreven_niet_natuurlijk_persoon is). Dit i.v.m. de slechte dekking van RSIN binnen het kadaster:
```
"_links": {
      ...
      "persoon": {
        "href": "/kadasternatuurlijkpersonen/NL.IMKAD.Persoon.440650207"
      }
}
```

**Comment by fsamwel** [comment]
@mhebbink-kad in bovenstaand voorbeeld is het een niet-natuurlijk persoon, dus moet de link ook verwijzen naar /kadasternietnatuurlijkpersonen. Maar verder klopt je conclusie

**Comment by rhengeveld** [comment]
Samenvattend, 
* "ingeschreven_niet_natuurlijk_persoon" = identificatie RSIN
* "niet_natuurlijk_persoon" = Kadaster persoonsidentificatie (KPI)
* De link van de persoon bevat in beide gevallen de KPI

**Comment by rhengeveld** [comment]
Geïmplementeerd, is beschikbaar voor volgende oplevering. 

Voorbeeld response (ingekort) van /kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000/zakelijkgerechtigden

```json
{
    "_links": {
        "self": {
            "href": "/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000/zakelijkgerechtigden"
        }
    },
    "_embedded": {
        "zakelijkGerechtigden": [
            {
                "identificatie": "30493367",
                "type": "eigenaar",
                "aanvangsdatum": "2018-10-11",
                "tenaamstelling": {
                    ...,
                    "betrokkenPartner": {
                        "identificatie": "NL.IMKAD.Persoon.50550743",
                        "omschrijving": "Sidonia Jansens",
                        "type": "kadaster_natuurlijk_persoon"
                    },
                    "betrokkenSamenwerkingsverband": {
                        "identificatie": "NL.IMKAD.Persoon.71291440",
                        "omschrijving": "Bankbedrijf",
                        "type": "kadaster_niet_natuurlijk_persoon"
                    },
                    "betrokkenGorzenEnAanwassen": {
                        "identificatie": "999999999",
                        "omschrijving": "Bankbedrijf van vrucht",
                        "type": "ingeschreven_niet_natuurlijk_persoon"
                    }
                },
                "persoon": {
                    "identificatie": "NL.IMKAD.Persoon.70882239",
                    "omschrijving": "Willem Jansens",
                    "type": "kadaster_natuurlijk_persoon"
                },
                "_links": {
                    "self": {
                        "href": "/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000/zakelijkgerechtigden/30493367"
                    },
                    "persoon": {
                        "href": "/kadasternatuurlijkpersonen/NL.IMKAD.Persoon.70882239"
                    },
                    "betrokkenPartner": {
                        "href": "/kadasternatuurlijkpersonen/NL.IMKAD.Persoon.50550743"
                    },
                    "betrokkenSamenwerkingsverband": {
                        "href": "/kadasternietnatuurlijkpersonen/NL.IMKAD.Persoon.71291440"
                    },
                    "betrokkenGorzenEnAanwassen": {
                        "href": "/kadasternietnatuurlijkpersonen/NL.IMKAD.Persoon.71291493"
                    }
                }
            },
            { ... }
        ]
    }
}
```

**Comment by rhengeveld** [comment]
@fsamwel een vraag over het volgende scenario:
* RSIN is toegevoegd aan de beschrijving van identificatie in **PersoonBasis**
* Type **KadasterPersoon** erft van **PersoonBasis**
* Deze **KadasterPersoon** komt terug in de response op de volgende request: `/kadasternietnatuurlijkpersonen/NL.IMKAD.Persoon.71291440` ➡️ [JSON response](https://gist.github.com/rhengeveld/70209ca5a2de0f25aafde9649ba12192)  
In de response is een RSIN aanwezig, echter de KPI wordt nog voor identificatie gebruikt.  

Op basis van de beschrijving bij **PersoonBasis** 🔽, moet de RSIN hier als identificatie gebruikt worden? 
Of geldt dat hier niet, omdat hier geen type aanwezig is die expliciet benoemd dat het hier om een ingeschreven niet-natuurlijk persoon gaat?

> Unieke identificatie voor de persoon. Voor een Kadasterpersoon is dit de identificatie zoals die door het Kadaster is vastgesteld. Voor een ingeschreven natuurlijk persoon is dit het burgerservicenummer. Voor een ingeschreven niet-natuurlijk persoon is dit het RSIN. Of de waarde in identificatie een burgerservicenummer, een RSIN of een kadasterpersoonidentificatie is kan worden afgeleid uit het type persoon.

**Comment by rhengeveld** [comment]
Ik kan me ook voorstellen dat _"Voor een Kadasterpersoon is dit de identificatie zoals die door het Kadaster is vastgesteld."_ betekent: we gebruiken hier altijd de KPI. Oftewel dat deze RSIN regel alleen geldt voor type **PersoonBeperkt**.

**Comment by fsamwel** [comment]
> Dat dit betekent: KadasterPersoon en PersoonBeperkt erven van PersoonBasis. Voor KadasterPersoon gebruiken we altijd KPI, voor PersoonBeperkt gebruiken we in de beschreven situatie RSIN als identificatie.

Klopt

**Comment by rhengeveld** [comment]
Top! Bedankt voor de opheldering 😄

**Comment by fsamwel** [comment]
@rhengeveld er wordt nog niet altijd rsin gevuld:
/kadastraalonroerendezaken/56020234070000/zakelijkgerechtigden/50037358
bevat:
```
   "persoon" : {
      "identificatie" : "440650207",
      "omschrijving" : "Gassie Test B.V.",
      "type" : "ingeschreven_niet_natuurlijk_persoon"
   },
   "_links" : {
      "self" : {
         "href" : "/kadastraalonroerendezaken/56020234070000/zakelijkgerechtigden/50037358"
      },
      "persoon" : {
         "href" : "/kadasternietnatuurlijkpersonen/440650207"
      }
   }
```

Dit is een ingeschreven_niet_natuurlijk_persoon, maar desondanks wordt er bij persoon.identificatie de kadasterpersoonidentificatie gevuld. Deze persoon heeft "rsin" : "900000001", dus die waarde had ik ook in persoon.identificatie verwacht.
