### ISSUE TITLE
Onjuiste fout bij incorrecte zaakgerechtigde identificatie

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#484]
https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000/zakelijkgerechtigden/12345678

In dit geval is bestaat er geen zakelijk gerechtigde bij kadastraal object 76870487970000 met de identificatie 12345678.

Dus verwacht ik een 404 Not found.

Ik krijg echter een 400 Bad request:
{
   "type" : "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_BadRequest",
   "title" : "Bad Request",
   "status" : 400,
   "detail" : "Bad Request",
   "instance" : "https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000/zakelijkgerechtigden/12345678",
   "code" : "Bad Request"
}

In de foutmelding wordt ook niet toegelicht wat er precies fout is. Een 400 foutmelding is m.i. niet terecht, omdat de request wel voldoet aan de specificaties, maar een 404 moet komen omdat de gevraagde resource niet bestaat.

**Comment by rhengeveld** [comment]
Opgelost:
```json
{
    "type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_NotFound",
    "title": "Not Found",
    "status": 404,
    "detail": "Not Found",
    "instance": "https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000/zakelijkgerechtigden/12345678",
    "code": "Not Found"
}
```
