### ISSUE TITLE
request naar niet geïmplementeerd endpoint levert 404 i.p.v. 501

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#487]
https://api.test.kadaster.nl/esd/gemeenten/brk/stukken/NL.IMKAD.Stukdeel.1001591789

Dit levert een 404 Not found fout:
{
   "type" : "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_NotFound",
   "title" : "Not Found",
   "status" : 404,
   "detail" : "Not Found",
   "instance" : "https://api.test.kadaster.nl/esd/gemeenten/brk/stukken/NL.IMKAD.Stukdeel.1001591789",
   "code" : "Not Found"
}

Ik dacht dat dit nog niet geïmplementeerd is, dus had ik een 501 Not implemented verwacht.

Het opgevraagde stuk is overigens wel een bestaande stukidentificatie, die ik heb teruggekregen uit /kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000/zakelijkgerechtigden/30493367

**Comment by fsamwel** [comment]
Idem op https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000/privaatrechtelijkebeperkingen
De kadastraal object identificatie bestaat, dus had hier geen 404 mogen komen.

**Comment by fsamwel** [comment]
En zelfde bij hypotheken en beslagen

**Comment by mhebbink-kad** [comment]
In de specs van de MVP worden deze endpoints er nog uitgehaald.

**Comment by mhebbink-kad** [comment]
Zie #302
