### ISSUE TITLE
Als medewerker Grondzaken wil ik ALLE adressen van appartementsrechten op een perceel (bijv. woontoren) kunnen raadplegen (paging)

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#49]
...zodat ik een Wvg besluit of een onteigeningsbesluit kan voorbereiden en deze kan controleren in de BAG 

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by JohanBoer** [comment]
Dit kan nu niet in 1 call. We leveren wel alle bijbehorende appartementsrechten bij een grondperceel, dus de consumer kan relatief eenvoudig de betreffende adressen bij elkaar zoeken op basis van de bijbehorende appartementsrechten.
Is daarmij de betreffende user story afdoende ingevuld ?

**Comment by CathyDingemanse** [comment]
ja, adressen kunnen worden geraadpleegd in de BAG
