### ISSUE TITLE
Verwijderen zoeken op kadastraleaanduiding

### ISSUE THREAD

**Issue by mhebbink-kad** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#490]
Endpoint:
/kadastraalonroerendezaken?

**Comment by fsamwel** [comment]
Voordat dit doorgevoerd wordt, er wordt nog discussie over gevoerd: https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/462#issuecomment-627257935
