### ISSUE TITLE
feature over altijd meeleveren bij fields en expand

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#492]
Ik denk dat het goed is dat er een feature komt die voor fields en expand duidelijk maakt:
- welke gegevens altijd worden geleverd (zoals identificatie en _links.self)
- welke gegevens altijd in combinatie worden geleverd (zoals aardCultuurBebouwd en koopsom)
- welke gegevens in worden geleverd in combinatie met links i.v.m. templating

**Comment by fsamwel** [comment]
@mhebbink-kad als ik het me goed herinner hebben we eerder besproken dat jij dit zou maken?

**Comment by mhebbink-kad** [comment]
Klopt. Pak ik op.

**Comment by mhebbink-kad** [comment]
Zie pull request: https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/pull/512

**Comment by rhengeveld** [comment]
Zoals in de pull request vermeld: pull request is gemerged (v1.1) en openstaande opmerkingen of verdere verbeteringen kunnen voor volgende versie (v1.2)
