### ISSUE TITLE
te lange huisnummertoevoeging veroorzaakt 500 server error

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#495]
https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken?adres__postcode=7441JC&adres__huisnummer=1&adres__huisnummertoevoeging=1a3D5

dit resulteert in:
{
   "type" : "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_InternalServerError",
   "title" : "Internal Server Error",
   "status" : 500,
   "detail" : "Internal Server Error",
   "instance" : "https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken?adres__postcode=7441JC&adres__huisnummer=1&adres__huisnummertoevoeging=1a3D5",
   "code" : "Internal Server Error"
}

**Comment by rhengeveld** [comment]
Onderliggende Kadaster systeem voor opvragen adressen heeft een lengte limiet van 4 voor huisnummertoevoeging:
> _Value '1a3D5' with length = '5' is not facet-valid with respect to maxLength '4'_

Ik zal het verwerken van deze validatiefoutmelding verbeteren, echter een gebruiker van HaalCentraal kan dan nog steeds een huisnummertoevoeging opvragen die _eigenlijk_ te lang is. 

Er zit een regex pattern op dit veld:
```
pattern: ^([a-z,A-Z,0-9])+$
```
Volgens mij kunnen we deze het beste veranderen in de **OpenApi** spec naar een limiet van 4 tekens:
```
pattern: ^([a-z,A-Z,0-9]){1,4}$
```
Na aanpassing krijg ik dit als foutmelding:
```json
{
    "type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_BadRequest",
    "title": "Request is niet valide",
    "status": 400,
    "detail": "The request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modification.",
    "instance": "https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken?adres__postcode=7441JC&adres__huisnummer=1&adres__huisnummertoevoeging=1a3D5",
    "code": "Bad Request",
    "invalidParams": [
        {
            "name": "adres__huisnummertoevoeging",
            "code": "pattern",
            "reason": "Waarde voldoet niet aan patroon ^([a-z,A-Z,0-9]){1,4}$."
        }
    ]
}
```

@mhebbink-kad mee eens dat het _pattern_ aangepast dient te worden?

**Comment by mhebbink-kad** [comment]
@rhengeveld: zit in update van de specs. Zie https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/pull/481

**Comment by rhengeveld** [comment]
Ah, heel mooi 👍

**Comment by rhengeveld** [comment]
Een zgn. _Validation error_ vanuit een achterliggend systeem wordt nu vertaald naar Bad Request:
```json
{
    "type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_BadRequest",
    "title": "Request is niet valide",
    "status": 400,
    "detail": "The request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modification.",
    "instance": "https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken?adres__postcode=7441JC&adres__huisnummer=1&adres__huisnummertoevoeging=1a3D5",
    "code": "Bad Request"
}
```

Heb tevens op het merge request vooruitgelopen door het pattern `^([a-z,A-Z,0-9]){1,4}$` alvast toe te passen. Originele request krijgt nu deze foutmelding:
```json
{
    "type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_BadRequest",
    "title": "Request is niet valide",
    "status": 400,
    "detail": "The request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modification.",
    "instance": "https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken?adres__postcode=7441JC&adres__huisnummer=1&adres__huisnummertoevoeging=1a3D5",
    "code": "Bad Request",
    "invalidParams": [
        {
            "name": "adres__huisnummertoevoeging",
            "code": "pattern",
            "reason": "Waarde voldoet niet aan patroon ^([a-z,A-Z,0-9]){1,4}$."
        }
    ]
}
```
Komt mee met de volgende oplevering.
