### ISSUE TITLE
onjuiste propertynamen bij fields parameter validatie

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#499]
https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000/zakelijkgerechtigden/30493367?fields=aanvangsdatum%2CbestaatNiet%2Ctenaamstelling.aandeel.teller%2Ctenaamstelling.aandeel.bestaatNiet

Dit geeft een foutmelding met:
"reason" : "Deel van de parameterwaarde niet correct: bestaat__niet, tenaamstelling.aandeel.bestaat__niet."

Hier zijn dus propertynamen uit de inhoud van de fields parameter omgezet van camelCase naar een soort snakeCase met dubbele underscore.

**Comment by fsamwel** [comment]
zelfde gebeurt in foutmeldingen onjuist gebruik expand parameter.

https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000?expand=zakelijkGerechtigden.persoon.omschrijving%2CzakelijkGerechtigden.persoon.bestaatNiet%2CzakelijkGerechtigden.persoon.identificatie

"reason" : "Deel van de parameterwaarde niet correct: zakelijk__gerechtigden.persoon.bestaat__niet."

**Comment by fsamwel** [comment]
mogelijk veroorzaakt door oplossing van #474?

**Comment by rhengeveld** [comment]
Yep. Ben iets te enthousiast geweest met het omzetten van de property namen. Zal het corrigeren :)

**Comment by rhengeveld** [comment]
Opgelost
