### ISSUE TITLE
Als Kadaster wil ik budget beschikbaar hebben 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#50]
...zodat projectmedewerkers uren kunnen boeken.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by JanWillemKooi** [comment]
Update n.a.v. conf call 6 maart: Cathy is hier druk mee bezig

**Comment by JanWillemKooi** [comment]
n.a.v. call 20 mrt: Cathy en Karin hebben contact gehad over de subsidie aanvraag over het loskrijgen van de BZK-gelden van de investeringsvraag. Dat kost tijd en BZK voelt niet veel urgentie (geëscaleerd bij VNG Theo). Daarom is voorfinanciering nodig. Karin heeft dat voor het Kadaster geregeld voor Marianne en Lennart. Voor de ontwikkelaars is dit echter minimaal. Hierdoor zal de ontwikkeling achterlopen op de ontwikkelingen van de user story's.
Ook common ground heeft last van vertraging van de subidieaanvraag.

**Comment by JanWillemKooi** [comment]
N.a.v. call 17 apr:  Het wachten is op de subsidie aanvraag bij BZK door VNG. Dat wordt nu besproken. De verwachting is dat het nu snel opgelost gaat worden.
Vraag aan Hilde: Is er al een contactpersoon waarmee de opdracht verstrekking geregeld kan worden? Hilde  vraagt dit aan Karin Bourgraaf.

**Comment by JanWillemKooi** [comment]
Tijdens de Sprintwisselbijeenkomst op 24 apr meldde Cathy dat de subsidie is goedgekeurd door de VNG directie. We wachten nog op de bevestiging van het versturen van de subsidie-aanvraag.

**Comment by JanWillemKooi** [comment]
Jan Willem heeft op 26 apr contact gehad met Theo Peters. Hij verwacht dat de subsidie-aanvraag begin week 18 wordt verstuurd (de week van 29 april).

**Comment by JanWillemKooi** [comment]
Vanuit Den Haag zijn alle opdrachtverstrekkingen verstuurd. Johan checkt bij Theo of de subside-aanvraag al is verstuurd. Vanuit Den Haag is een offerte aanvraag naar VNG gestuurd.

**Comment by JanWillemKooi** [comment]
Update call 8 mei: Johan bevestigt dat de subside-aanvraag vanuit VNG is verstuurd naar BZK.

**Comment by JanWillemKooi** [comment]
Update 22 mei: Subside-aanvraag is verstuurd naar BZK en daar ook ontvangen maar kent een dispuut rond btw. Het is onbekend wanneer dit is opgelost.

**Comment by JanWillemKooi** [comment]
Update 1 jun call: Volgende week is de stuurgroep. Hugo Aalders is op de hoogte en wil ook dat het nu snel wordt opgelost.
