### ISSUE TITLE
Ten onrechte geen foutmelding bij onjuiste kadastraalonroerendezaakidentificatie bij zakelijkgerechtigden

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#500]
https://api.test.kadaster.nl/esd/gemeenten/brk/esd/gemeenten/brk/kadastraalonroerendezaken/bestaatniet/zakelijkgerechtigden 

De identificatie van het kadastraal object in de uri is niet juist. Er bestaat geen kadastraal onroerende zaak met deze identificatie.
Dus verwijst de uri niet naar een resource of collectie die bestaat.

Dus had ik hier een 404 Not Found foutmelding verwacht

**Comment by fsamwel** [comment]
wellicht gevolg van oplossing van #464?

**Comment by rhengeveld** [comment]
Klopt, komt inderdaad door #464. Denk dat ik hier onderscheid moet gaan maken tussen:
* Eerst wordt een onroerende zaak 'bestaatniet' opgehaald. Dit zou een 404 moeten geven.
* Vervolgens worden de zakelijkgerechtigden opgehaald. Deze mag nooit 404 geven.

Ik zal het aanpassen.

**Comment by rhengeveld** [comment]
Aangepast, nieuwe (oude) response:
```json
{
    "type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_NotFound",
    "title": "Not found",
    "status": 404,
    "detail": "Opgevraagde resource is niet gevonden.",
    "instance": "https://api.test.kadaster.nl/esd/gemeenten/brk/esd/gemeenten/brk/kadastraalonroerendezaken/bestaatniet/zakelijkgerechtigden",
    "code": "Not Found"
}
```
