### ISSUE TITLE
zoeken op alleen postcode vindt niks

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#501]
afgeleid uit #462 (omdat die vooral gaat over de kadastrale aanduiding).

/kadastraalonroerendezaken?adres__postcode=7361EW
levert geen kadastraal onroerende zaak
/kadastraalonroerendezaken?adres__postcode=7361EW&adres__huisnummer=29
levert wel een kadastraal onroerende zaak

reactie van @mhebbink-kad:
> dit komt omdat er meerdere resultaten zijn gevonden, waarvoor geen testgevallen zijn en er dus een Not Found wordt teruggeven. Zal kijken of ik de testdata kan updaten hierop. Is wel wat werk.

Dat moet nog gebeuren. 

Maar ik vraag me af of uitbreiden testdata op deze nu genoemde situatie voldoende is. We weten namelijk niet welke zoekvragen (dus welke postcodes) aansluiters op de API zullen gaan gebruiken. Wanneer ze dan onverwachte resultaten (geen resultaat) krijgen kan dit vervelend voor hun zijn. Grote kans dat ze eerst de oorzaak voor het ontbreken van resultaten gaan zoeken in de eigen applicatie.

Is er een oplossing die zorgt dat zoek-data en raadpleeg-testdata consistente resultaten geeft voor elke zoekvraag?

**Comment by mhebbink-kad** [comment]
@fsamwel: heb de testdata zo aangepast dat alleen de postcodes gevonden worden die beschikbaar zijn op de ETO. Zie ook getting-started document. Alle andere postcodes geven een lege collectie terug. Hiervoor heb ik bij bepaalde onroerende zaken het aantal nummeraanduidingidentificaties omlaag gebracht om wel voor elk nummeraanduiding een adres te hebben die ook bestaat in de testdata.
