### ISSUE TITLE
Als PO wil ik een overzicht van de vereiste objecten voor alle user stories  

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#51]
...zodat het team resoiurces kan definieren
en ik een prioriteitstelling kan aanbrengen in de definitie van (sub)resources en gegevensgroepen.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by JanWillemKooi** [comment]
Welke acties moeten hiervoor ondernomen worden? En wie voort die uit?

**Comment by JanWillemKooi** [comment]
Dit wordt op maandag 11 maart besproken door Cathy en Marianne

**Comment by JanWillemKooi** [comment]
N.a.v. call van 20 mrt: Aan deze US wordt gewerkt. De belangrijkste zijn gedaan.

**Comment by JanWillemKooi** [comment]
Overzicht is hier te vinden
https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/blob/master/docs/Infobehoefte%20BRK%20bevragen%20vs%200.1.xlsx

**Comment by JanWillemKooi** [comment]
N.a.v. call 17 apr: Deze US blijft steeds in ontwikkeling maar afgerond tot op dit moment. Eigenlijk is dit ongoing acties. Het team is zich hiervan bewust. Zodra iets expliciets gedaan moet worden, zal een nieuwe user story gemaakt worden.
