### ISSUE TITLE
Toevoegen domein n.a.v. notitie toepassing NEN3610

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#510]
In notitie "Toepassing NEN3610 - Kadaster implementatie ontwerp - 2020-05-26.pdf" is voorgesteld naast identificatie ook property "domein" op te nemen bij resources.
Als ik het goed begrijp betekent dit toevoegen van property domein aan alle resources. Deze nieuwe property wordt dan gevuld met de namespace van de nen3620 identificatie.

De namespace moet ook worden verwijderd uit de identificatie properties en uri's.

**Comment by fsamwel** [comment]
@mhebbink-kad kan jij deze doorvoeren?
- toevoegen domein
- verwijderen namespace uit identificaties (dus elke identificatie=lokaalId)

**Comment by rhengeveld** [comment]
Samenvattend, ik begrijp dat de huidige object identificatie bestaat uit het domein én een identifier. Bijvoorbeeld `NL.IMKAD.KadastraalObject.76870487970000`:
* Bestaande uit _identificatie_ `76870487970000`
* Bestaande uit _domein_ `NL.IMKAD.KadastraalObject`

Voor het toepassen van NEN3610 willen we de object identificatie opknippen in de _identificatie_ en het _domein_. Dat kan er dan als volgt uit komen te zien.

---

### Huidige situatie
*Request*
```
/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000
```
*Response*
```json
{ 
  "identificatie": "NL.IMKAD.KadastraalObject.76870487970000",
  "verdereWaardes": "..."
}
```

### Situatie NEN3610
*Request*
```
/kadastraalonroerendezaken/76870487970000
```
*Response*
```json
{
  "identificatie": "76870487970000",     
  "domein": "NL.IMKAD.KadastraalObject",
  "verdereWaardes": "..."
}
```

---

Deze aanpassing dient verwerkt te worden in de OpenApi specificatie en vervolgens doorgevoerd te worden in de BRK implementatie.

**Comment by rhengeveld** [comment]
@fsamwel ik zag dat er al een [voorzet was gemaakt](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/commits/revert-511-nen3610_domein) voor de specificatie.  
Hoe staat het hiermee of welke obstakels zijn er nog?

**Comment by fsamwel** [comment]
wijziging is doorgevoerd in de specificaties (master).

zie https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/pull/531#issuecomment-641871117 en https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/pull/531#issuecomment-642546760

**Comment by rhengeveld** [comment]
Ik ben ondertussen redelijk ver gevorderd met de implementatie; identificaties van KadasterPersoon, Aantekening, OnroerendeZaak bevatten geen domein meer. Tevens is het domein gevuld en werken de zoekingangen op basis van identificatie zonder domein. Ingekort voorbeeld:
```json
{
    "identificatie": "71291440",
    "omschrijving": "Bankbedrijf",
    "domein": "NL.IMKAD.Persoon",

    "kadastraalOnroerendeZaakIdentificaties": [
        "76870488070000",
        "76870482570000"
    ],

    "rsin": "805315366",
    "_links": {
        "self": {
            "href": "/kadasternietnatuurlijkpersonen/71291440"
        },
        "kadastraalOnroerendeZaken": [
            {
                "href": "/kadastraalonroerendezaken/{kadastraalOnroerendeZaakIdentificaties}",
                "templated": true
            }
        ]
    }
}
```

---

Nu kom ik het volgende tegen. Wat zal ik met onderstaande situaties doen @fsamwel?

1. Intern wordt het domein voor de identificatie geplakt. Als het domein reeds aanwezig is, zijn we direct klaar. Requests werken nu mét en zonder domein. 
Is dit prima? Of zal ik de variant met domein eruit halen? _(momenteel meer werk)_
   * `/kadasternietnatuurlijkpersonen/71291440` ✔️ 
   * `/kadasternietnatuurlijkpersonen/NL.IMKAD.Persoon.71291440` ✔️  

2. Willen we in het voorbeeld hieronder de identificatie van persoon mét of zonder domein? PersoonBeperkt heeft geen domein. De link naar deze persoon bevat geen domein.
```json
{
    "identificatie": "20170717",
    "type": "erfpachter",


    "persoon": {
        "identificatie": "NL.IMKAD.Persoon.71303564",
        "omschrijving": "Christiaan Goede",
        "type": "kadaster_natuurlijk_persoon"
    },


    "_links": {
        "self": {
            "href": "/kadastraalonroerendezaken/76870482570000/zakelijkgerechtigden/20170717"
        },
        "persoon": {
            "href": "/kadasternatuurlijkpersonen/71303564"
        }
    }
}
```

**Comment by fsamwel** [comment]
@rhengeveld 
1. Wat mij betreft is het niet erg dat gebruik van het domein ook werkt. Als we maar consequent zijn in wat we communiceren als de "echte" uri van resources (dat is de variant zonder domein).

2. Alle identificaties in de API zijn bedoeld om hiermee de uri te kunnen samenstellen, voor gebruikers die de HAL links niet willen of kunnen gebruiken. De juiste context (wat ook het doel is van domein) wordt hier aangegeven in de berichtstructuur ("persoon") en in geval van een persoon (een polymorf gegeven) aangevuld met het "type".

**Comment by rhengeveld** [comment]
Ok, dus 1 laten we zo 😄 en bij 2 is de context het type, dus het domein mag uit de identificatie gehaald worden. Ik zal het aanpassen 👍

**Comment by rhengeveld** [comment]
Implementatie afgerond ✔️ komt met volgende oplevering mee
