### ISSUE TITLE
Zoeken op huisletter niet meer case insensitive

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#517]
Tot nu was zoeken op huisletter niet-hoofdlettergevoelig. Dus:
- https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken?adres__postcode=7441JC&adres__huisnummer=1&adres__huisletter=a
- https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken?adres__postcode=7441JC&adres__huisnummer=1&adres__huisletter=A

vonden beide hetzelfde kadastrale object. Op dit moment niet meer, nu wordt met de onjuiste case geen kadastraal object meer gevonden.

Dat is denk ik niet erg gebruikersvriendelijk, aangezien men vaak wel de huisletter zal weten, maar niet of het een hoofdletter dan wel kleine letter zal zijn.

Kan dit weer hoofdletter-ongevoelig worden gemaakt, zodat de case niet meer uitmaakt bij huisletters? Idem bij huisnummerToevoeging.

**Comment by mhebbink-kad** [comment]
Opgelost.
