### ISSUE TITLE
aardCultuurBebouwd, aardCultuurOnbebouwd en koopjaar geleverd terwijl er geen koopsom is

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#519]
https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.22590043870000

Dit levert:
```
   "koopsom" : {
      "koopjaar" : 1999,
      "indicatieMetMeerObjectenVerkregen" : true
   },
   "aardCultuurBebouwd" : {
      "code" : "11",
      "waarde" : "Wonen"
   },
   "aardCultuurOnbebouwd" : {
      "code" : "57",
      "waarde" : "Erf - tuin"
   },
```

Volgens levering-koopsom.feature (nu in pull request #512) mogen koopjaar,  aardCultuurBebouwd en aardCultuurOnbebouwd niet geleverd worden, omdat koopsom ontbreekt.

Ik had dus alleen indicatieMetMeerObjectenVerkregen verwacht:
```
   "koopsom" : {
      "indicatieMetMeerObjectenVerkregen" : true
   },
```

**Comment by fsamwel** [comment]
Idem voor https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.22310827210003
```
   "koopsom" : {
      "koopjaar" : 1989
   },
   "aardCultuurBebouwd" : {
      "code" : "12",
      "waarde" : "Wonen (appartement)"
   },
```

**Comment by fsamwel** [comment]
Ik krijg nu ook niet koopsom.indicatieMetMeerObjectenVerkregen @HildeVos is dat correct? Dus geldt de regel voor leveren koopsom, koopjaar, aardcultuur(on)bebouwd ook voor indicatieMetMeerObjectenVerkregen? Zo staat dat nu niet in de feature, dus ik twijfel

**Comment by HildeVos** [comment]
De regel van alles of niets tonen telt alleen voor koopsom, koopjaar, aardcultuur(on)bebouwd. IndicatieMetMeerObjectenVerkregen staat hier los van. Dus als bijvoorbeeld de cultuurcode ontbreekt, maar er wel een IndiciatieMetMeerObjectenVerkregen is, mag deze laatste gewoon getoond worden.

**Comment by fsamwel** [comment]
@HildeVos dit betekent dus ook dat wanneer er wel IndiciatieMetMeerObjectenVerkregen=true is, maar geen koopsom, dat koopjaar en aardcultuur(on)bebouwd niet wordt geleverd, maar IndiciatieMetMeerObjectenVerkregen wel?

**Comment by HildeVos** [comment]
Dat klopt inderdaad Frank.

**Comment by rhengeveld** [comment]
Volgens mij is dit opgelost samen met #520

**Comment by fsamwel** [comment]
in versie die ik nu heb zit die oplossing inderdaad nog niet. maar ik sluit deze, omdat dit in #520 opgelost wordt
