### ISSUE TITLE
Als berichtontwerper wil ik de technische keuzes op basis van het informatiemodel uitwerken

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#52]
...zodat ik de basis voor de resource-definities klaar heb staan en snel kan schakelen als de business de reource-definitie =s klaar heeft.

**Definition of done**
- [ ] Technisch model (UGM) af
-[ ] Check op samenhang met informatiemodel en gemaakte technische keuzes
- [ ] Open API specificatie voor "Systeem-API's'
- [ ] check op genereren code

**Comment by JanWillemKooi** [comment]
Nav call van 6 mrt: Is Johan mee bezig. Deze US gaat naar In Progress.

**Comment by JanWillemKooi** [comment]
N.a.v. call 17 apr: Deze US blijft steeds in ontwikkeling maar afgerond tot op dit moment. Eigenlijk is dit ongoing acties. Het team is zich hiervan bewust. Zodra iets expliciets gedaan moet worden, zal een nieuwe user story gemaakt worden.
