### ISSUE TITLE
fields=indicatieMetMeerObjectenVerkregen levert ook koopsom en aardCultuurBebouwd

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#520]
https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.19560032970000?fields=koopsom.indicatieMetMeerObjectenVerkregen

Hier is niet gevraagd om een van de gegevens koopsom, koopjaar, aardCultuurBebouwd of aardCultuurOnbebouwd.
Toch worden deze gegevens geleverd:
```
   "koopsom" : {
      "koopsom" : 8300000,
      "koopjaar" : 2015
   },
   "type" : "perceel",
   "aardCultuurBebouwd" : {
      "code" : "22",
      "waarde" : "Bedrijvigheid (industrie)"
   },
   "aardCultuurOnbebouwd" : {
      "code" : "57",
      "waarde" : "Erf - tuin"
   },
```

**Comment by rhengeveld** [comment]
Originele opmerking afkomstig [hier](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/466#issuecomment-623390864) in #466:
> De combinatie koopsom/koopjaar/cultuurcodebebouwd of cultuurcodeonbebouwd is verplicht. Deze 3 moeten altijd samen geleverd worden. Als bijvoorbeeld 1 van deze ontbreekt, mogen alle 3 niet geleverd worden. IndicatieMetMeerObjectenVerkregen mag in principe los geleverd worden, maar heeft eigenlijk geen waarde zonder de voornoemde 3 items.

Dit heb ik toentertijd geïnterpreteerd als _"elk veld van koopsom"_, niet _"koopsom.koopsom of koopsom.koopjaar"_. Ik ga onderzoeken/bedenken/proberen of deze combinatie te realiseren is:
|Field|Alias naar aardcultuur?|
|------|-----|
|koopsom|✔️|
|koopsom.koopsom|✔️|
|koopsom.koopjaar|✔️|
|koopsom.indicatieMetMeerObjectenVerkregen|**~✔️~ ❌**|  

De uitdaging is dat "koopsom" wél moet blijven werken.

**Comment by rhengeveld** [comment]
Opgelost ✔️ en beschikbaar met eerstvolgende oplevering. Hieronder testvoorbeelden.

---

**Voorbeeld [koopsom](https://gist.github.com/rhengeveld/bc94068efca1b2d8a56908ade15c0376)**
* koopsom, aardcultuurBebouwd
* Inclusief _indicatieMetMeerObjectenVerkregen_

**Voorbeeld [koopsom.koopsom](https://gist.github.com/rhengeveld/b12821f07fc85f34dd9a493facd694c2)**
* koopsom.koopjaar, koopsom.koopsom, aardcultuurBebouwd
* Geen _indicatieMetMeerObjectenVerkregen_

**Voorbeeld [koopsom.koopjaar](https://gist.github.com/rhengeveld/13640905a0fa6d01bc43d3f87f9a45f7)**
* koopsom.koopjaar, koopsom.koopsom, aardcultuurBebouwd
* Geen _indicatieMetMeerObjectenVerkregen_

**Voorbeeld [koopsom.indicatieMetMeerObjectenVerkregen](https://gist.github.com/rhengeveld/d4f585543183c6ed2a73a96e35c74052)**
* ⚠️ Selecteert nu zoals gewenst enkel _indicatieMetMeerObjectenVerkregen_ ⚠️ 

**Voorbeeld [aardcultuurbebouwd.code](https://gist.github.com/rhengeveld/7a781a87fa156bd291dea446b29a78d3)**
* koopsom.koopjaar, koopsom.koopsom, aardcultuurBebouwd
* Geen _indicatieMetMeerObjectenVerkregen_

**Voorbeeld [aardcultuuronbebouwd](https://gist.github.com/rhengeveld/0d2cf7294cf73c30cf23b2db0d3ad099)**
* koopsom.koopjaar, koopsom.koopsom, aardcultuurBebouwd
* Geen _indicatieMetMeerObjectenVerkregen_ 
* ⚠️ Selecteren van aardcultuurOnbebouwd selecteert dus ook de andere velden. Dat aardcultuurOnbebouwd vervolgens geen waarde heeft, is niet relevant ⚠️

**Comment by fsamwel** [comment]
ik zie nu ook het volgende:
Gegeven
- koopsom.koopjaar, koopsom.koopsom, aardCultuurBebouwd, aardCultuurOnbebouwd
- Geen indicatieMetMeerObjectenVerkregen
opvragen met fields=koopsom.indicatieMetMeerObjectenVerkregen

Dit levert: koopsom.koopjaar, koopsom.koopsom, aardCultuurBebouwd, aardCultuurOnbebouwd

Is dit nu terecht? Of moet indicatieMetMeerObjectenVerkregen helemaal los worden gezien van koopsom.koopjaar, koopsom.koopsom, aardCultuurBebouwd, aardCultuurOnbebouwd? 

Ik test met:
/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.19560032970000?fields=koopsom.indicatieMetMeerObjectenVerkregen

**Comment by rhengeveld** [comment]
Yep. Zoals ik het begrepen heb (zie ook tabel hierboven) dient `indicatieMetMeerObjectenVerkregen` helemaal los worden gezien, zoals in [dit voorbeeld](https://gist.github.com/rhengeveld/d4f585543183c6ed2a73a96e35c74052) waar `indicatieMetMeerObjectenVerkregen` opgevraagd en aanwezig is, maar de andere velden niet terwijl die [wel waarden hebben](https://gist.github.com/rhengeveld/b12821f07fc85f34dd9a493facd694c2)).

**Comment by fsamwel** [comment]
@rhengeveld wat ik beschrijf is dat de huidige werking is dat er wél een koppeling is. Wanneer ik fields=koopsom.indicatieMetMeerObjectenVerkregen doe, krijg ik koopsom.koopjaar, koopsom.koopsom, aardCultuurBebouwd, aardCultuurOnbebouwd terug. Dat had ik dan niet verwacht, want als er geen koppeling is, moet alleen geleverd worden wat is gevraagd, dus koopsom.indicatieMetMeerObjectenVerkregen en geen andere koopsom properties

**Comment by rhengeveld** [comment]
Correct, dat is wat ik hier ook beschrijf. Die versie heb jij nog niet 😉 
> Ik betwijfel overigens dat je dit al kan testen; ik weet niet zeker of de testomgeving waar ik dingen naar deploy, ook de omgeving is waar jij op test. Vandaar dat ik de testvoorbeelden had toegevoegd, zodat het resultaat alvast bekeken kan worden 😉
