### ISSUE TITLE
zoeken persoon levert minder dan raadplegen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#521]
https://api.test.kadaster.nl/esd/gemeenten/brk/kadasternatuurlijkpersonen?q=jansens%201971-11-01
Dit vindt persoon "/kadasternatuurlijkpersonen/NL.IMKAD.Persoon.70882239"

Maar in het zoekresultaat zitten minder gegevens dan bij het raadplegen. Wat ik tot nu gevonden heb (dus geen uitputtende lijst) voor kadasternatuurlijkpersonen:
- beschikkingsbevoegdheid
- postadres
- woonadres.straat
- woonadres.woonplaats
- woonadres.huisletter
- woonadres.huisnummerToevoeging
- geboorte.land
- geslachtsaanduiding
- heeftPartnerschap[].naam

**Comment by mhebbink-kad** [comment]
De volgende velden worden momenteel niet geleverd door de ZoekenPersoon API:
- indicatieNietToonbareDiakriet
- beschikkingsbevoegdheid
- landWaarnaarVertrokken
- heeftPartnerschap
- overlijden

Vraag staat bij dat team uit wat de reden hiervoor is.

**Comment by rhengeveld** [comment]
Update @mhebbink-kad: ligt nog bij het KPR team. Wordt vervolgd. Misschien op tijd opgelost voor v1.2?

**Comment by rhengeveld** [comment]
@kad-hebbim heb je hier een update van?

**Comment by fsamwel** [comment]
zie ook #725

**Comment by kad-henger** [comment]
@fsamwel kan je het opnieuw proberen? Versie 1.2.1.x is ondertussen live, dus ik vermoed dat dit is opgelost.

**Comment by rhengeveld** [comment]
@fsamwel kan je het opnieuw proberen? Versie 1.2.1.x is ondertussen live, dus ik vermoed dat dit is opgelost.
