### ISSUE TITLE
Wijziging type kadastraleAanduiding van TypeKadastraleaanduiding naar string

### ISSUE THREAD

**Issue by anikbin** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#528]
**Beschrijf de bug**
Wijziging type kadastraleAanduiding van TypeKadastraleaanduiding naar string

**To Reproduce**
Vandaag worden mijn Json berichten niet meer Deserialize want krijg de type van kadastraleAanduiding inmiddels gewijzigd naar String.
Terwijl de beschrijving in de Swagger is nog steeds TypeKadastraleAanduiding . zien jullie hieronder een kopie hiervan
"kadastraleAanduiding": {
          "appartementsrechtVolgnummer": 0,
          "kadastraleGemeente": {
            "code": "string",
            "waarde": "string"
          },
          "perceelnummer": 0,
          "sectie": "string"
        },
Ik heb vaak deze situatie meegemaakt.
Wanneer worden de structuur van de berichten vast?

Alvast bedankt voor uw reactie.

**Comment by rhengeveld** [comment]
Ter aanvulling op hierboven; in de [specificatie](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/blob/master/specificatie/BRK-Bevragen/openapi.yaml) is "kadastraleAanduiding" inderdaad vlak voor oplevering veranderd in een String. De beslissingen en uitwerkingen hiervan zijn benoemd in #462 en #498.  

Mocht je het makkelijker vinden om met losse velden te werken, de [regex uit #462](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/462#issuecomment-634662993) (ook te vinden in de specificatie) kan uitkomst bieden om de ontvangen kadastrale aanduiding weer op te knippen.

Wat Cathy beschrijft wat er ook aan komt:
* #510 over NEN3610
* #480 over RSIN
* #467 en #468 over templating

Voor het laatste punt over nummeraanduiding weet ik zo niet het issue nummer.

**Comment by anikbin** [comment]
De volgende wijziging hoort ook voor de volgende lijst. toch?

- Deze code kan je niet meer bij komen Accept-Crs : epsg:4258 met deze welepsg:28992
- De adresIdentificaties is ook verdwijnen.

**Comment by fsamwel** [comment]
> Deze code kan je niet meer bij komen Accept-Crs : epsg:4258 met deze welepsg:28992

Dit zit er al in. We ondersteunen alleen epsg:28992 (RD)

> De adresIdentificaties is ook verdwijnen.

Dit is hetzelfde als het nummeraanduiding issue: #529 (ik kon ook geen bijbehorend issue vinden, dus heb die maar gemaakt)

**Comment by rhengeveld** [comment]
Volgens mij is het hiermee duidelijk, dus ik sluit dit issue.
