### ISSUE TITLE
koppelingswijze toevoegen aan nummeraanduiding van kadastraal onroerende zaak

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#529]
in v1.0.0 is tijdelijk de nummeraanduidingIdentificaties uit de specificatie en implementatie gehaald, omdat bleek dat voor BRK levering (alternatief) naast de nummeraanduidingIdentificatie(s) ook de koppelingswijze belangrijk is.

Dit moet dus nog worden toegevoegd.

**Comment by JohanBoer** [comment]
Cathy gaat met Mark Backer in overleg over de noodzaak van de koppelingswijze. Eventueel nog navraag doen bij de mensen uit de business die deze wens geuit hebben

**Comment by rhengeveld** [comment]
Gezien het nog niet expliciet benoemd stond: ik heb begrepen dat dit noodzakelijk is.

**Comment by CathyDingemanse** [comment]
Ja hoor, is nodig, zie #201. @rhengeveld, je kunt aan de slag!

**Comment by rhengeveld** [comment]
Heropend voor implementatie van aangepaste specificatie 😉

**Comment by rhengeveld** [comment]
Geïmplementeerd ✔️ 

---

Voorbeeld response:
![image](https://user-images.githubusercontent.com/1228038/86345028-4a21db00-bc5b-11ea-82bf-66d301653b06.png)
