### ISSUE TITLE
Als berichtenontwerper wil ik weten wanneer de kadastersprint begint voor realisatie

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#53]
...zodat ik weet wanneer de OAS moet worden aangeleverd aan het kadaster voor realisatie.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by JanWillemKooi** [comment]
Nav call van 6 mrt: Kadaster heeft een story  in elke ontwikkelsprint staan waar aan gewerkt wordt. Dit staat niet als commitment maar er wordt wel aan gewerkt. Johan levert de technische specificatie en wil dit afstemmen met het ontwikkelteam. Marianne geeft aan dat dat niet kritisch is. Johan loopt niet het risico door een dag te laat te zijn de ontwikkelsprint te missen want is alle komende sprints staat Haal Centraal met US op de sprint backlog van het Kadaster.

**Comment by JanWillemKooi** [comment]
n.a.v. call 20 mrt: Johan is hier mee bezig. Versie Hello-World is beschikbaar voor de ontwikkelaars van Kadaster. Binnen deze sprint zal deze US als eerste opzet afgerond worden maar daarna is hier nog extra werk nodig.
