### ISSUE TITLE
Aantekening bij tenaamstelling moet een array zijn

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#534]
Er kunnen bij een tenaamstelling meerdere aantekeningen aanwezig zijn. Dit is nu maar 1 aantekening. 
@HildeVos @mhebbink-kad @rhengeveld : Klopt deze stelling ?

**Comment by rhengeveld** [comment]
@JohanBoer correct, in zoverre dat ik vanuit ons achterliggende systeem meerdere aantekeningen kan ontvangen. In de huidige implementatie wordt alleen de eerste aantekening vertaald naar de spec en teruggeven.

**Comment by JohanBoer** [comment]
@rhengeveld is het complex om van deze aantekening een array te maken en zou die wijziging in release 1.1. mee kunnen ? Dit is een ontwerpfout in de specificaties die we afgelopen vrijdag ontdekt hebben.

**Comment by rhengeveld** [comment]
@JohanBoer ja hoor, deze wijziging kan zo mee. Volgens mij verandert de specificatie van:
```json
        aantekening:
          $ref: '#/components/schemas/Aantekening'
```
naar
```
        aantekeningen:
          type: array
          items:
              $ref: '#/components/schemas/Aantekening'
```
_(De $ref is waarschijnlijk anders, ik gebruik hier de genereervariant)_

HaalCentraal zelf heeft vervolgens vrijwel geen aanpassingen nodig; intern worden alle aantekeningen reeds verwerkt, enkel bij de vertaling naar API specificatie dient de hele lijst i.p.v. het 1e element teruggegeven te worden. Dus ik denk minder dan een uur werk 😉

**Comment by rhengeveld** [comment]
Ik heb mijn bovengenoemde wijziging toegepast, levert als verwacht een array van aantekeningen op. 
Implementatie hierop aangepast ✔️ koste me een half uur 😉 

@JohanBoer als je dit ook opneemt in de OpenApi spec morgen dan is het reeds gerealiseerd
