### ISSUE TITLE
zakelijkgerechtigde tenaamstelling aantekening bevat aantekening op onroerende zaak

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#535]
/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000/zakelijkgerechtigden/30493367

Dit levert in tenaamstelling.aantekening.aard.waarde "Erfdienstbaarheid".

Bij de aantekening in Tenaamstelling staat als description: "Een aantekening is een verwijzing naar een ter inschrijving aangeboden stuk. Een aantekening op een tenaamstelling van een zakelijk recht is meestal een beperking. Bijvoorbeeld de verkrijging van een aandeel in een zakelijk recht onder opschortende voorwaarde, een beperking van de handelingsbevoegdheid van de zakelijk gerechtigde, of een koopovereenkomst"

Het gaat dus om een aantekening die geldt voor een tenaamstelling. Erfdienstbaarheid is denk ik een soort aantekening die op een kadastraal object rust.

**Comment by fsamwel** [comment]
@HildeVos klopt dit?

**Comment by rhengeveld** [comment]
Vraag per e-mail uitgezet

**Comment by rhengeveld** [comment]
@fsamwel ik weet niet of je hier genoeg aan hebt, maar van Thijs krijg ik het volgende antwoord:

> Een erfdienstbaarheid is altijd een aantekening op een kadastraal object.  
> Het is geen aantekening die op een tenaamstelling kan rusten.

**Comment by fsamwel** [comment]
@rhengeveld dan is dit een terechte "bug", want ik krijg die wel op een zakelijk gerechtigde. Moet dus opgelost worden.

**Comment by rhengeveld** [comment]
Ah, omdat dit een aantekening is met de waarde "erfdienstbaarheid", dient deze op ~kadastraal object~ `OnroerendeZaak` te zijn ipv `Tenaamstelling`. Scherp. Ik zal ernaar kijken.

**Comment by rhengeveld** [comment]
Hmmm, ik had in gedachten dat een `OnroerendeZaak` ook een `Aantekening` kan hebben. Dat blijkt niet het geval. 

Je ziet deze aantekening inderdaad terug met jouw request op zakelijkGerechtigden (van OnroerendeZaak): `/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000/zakelijkgerechtigden/30493367`
Je ziet ditzelfde ook terug met de expand zakelijkGerechtigden (van OnroerendeZaak):
`/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000?expand=zakelijkGerechtigden`

@fsamwel wat wil je dat er met deze aantekening gebeurt? Voor één of beide van deze URLs weglaten?

**Comment by fsamwel** [comment]
Vanaf v1.2 hebben we aantekeningen op zakelijkgerechtigden, en daarnaast hypotheken, beslagen privaatrechtelijkebeperkingen en publiekrechtelijkebeperkingen.  Een erfdienstbaarheid is een privaatrechtelijke beperking. In v1.0.0 (en v1.1) zit dit nog niet, dus moet dit ook nog niet worden geleverd

**Comment by rhengeveld** [comment]
Vanaf de introdutie van privaatrechtelijke beperkingen mag dit dus weer geleverd worden.
Check, dan pas ik het aan: filter Aantekeningen op erfdienstbaarheid. Bedankt voor de toelichting :)
