### ISSUE TITLE
Als medewerker Belastingzaken wil ik van iedere kadastraal onroerende zaak weten uit welke KOZ(zen) hij is ontstaan 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#537]
...zodat ik op juiste wijze mijn WOZ administratie kan bijwerken,
op correcte wijze historie kan opbouwen van deze basisadministratie,

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by JohanBoer** [comment]
Zowel Filiatie als VoorwaartseFiliatie is nu opgenomen, Je kan in de huidige stand van een kadastraal Onroerende Zaak dus zien waarin hij is over gegaan en waaruit hij is ontstaan(indien van toepassing. Vraag is of deze informatie afdoende is om de door de WOZ gewenste historie op te bouwen.

**Comment by JohanBoer** [comment]
De filiatie is uiteindelijk niet in versie 1.2 geland. Het opnemen van isOntstaanUit en isOvergegaanIn moet in versie 1.3. Deze issue voorzien van label BRK Bevragen 1.3 en terug naar Ready for sprint.

**Comment by fsamwel** [comment]
@JohanBoer 
> De filiatie is uiteindelijk niet in versie 1.2 geland. Het opnemen van isOntstaanUit en isOvergegaanIn moet in versie 1.3. Deze issue voorzien van label BRK Bevragen 1.3 en terug naar Ready for sprint.

Label en status was nog v1.2 en review. Ik pas dat aan

**Comment by JohanBoer** [comment]
Deze user story is nu in de specificatie ingevuld door zowel isOntstaanUit(achterwaartse filiatie) als isOvergegaanIn (voorwaartse filiatie) op te nemen bij de kadastraal onroerende zaak. Daarbij wordt ook de mogelijkheid geboden om vervallen objecten op te vragen. (daarvoor zijn de properties indicatieVervallen en einddatum toegevoegd)

Als service zijn ook de properties "bijbehorendGrondperceelIdentificatie" en "bijbehorendeAppartementsrechtIdentificaties" toegevoegd aan de kadastraal onroerende zaak.

Zie ook #200
