### ISSUE TITLE
Als medewerker belastingzaken wil ik van iedere kadastraal onroerende zaak weten welke kadastraal onroerende zaken in deze kadastraal onroerende zaak zijn overgegaan

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#538]
...zodat ik mijn WOZ administratie correct kan bijwerken en op correcte wijze historie kan opbouwen van deze basisadministratie.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by JohanBoer** [comment]
Deze functionaliteit zou met het opnemen van de isOntstaanUit relatie moeten zijn gerealiseerd.

**Comment by JohanBoer** [comment]
De filiatie is uiteindelijk niet in versie 1.2 geland. Het opnemen van isOntstaanUit en isOvergegaanIn moet in versie 1.3. Deze issue voorzien van label BRK Bevragen 1.3 en terug naar Ready for sprint.
