### ISSUE TITLE
_embedded en _links componenten voor HalCollection-componenten apart definieren. 

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#539]
Zie https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/pull/532#issuecomment-643349328  en de opmerkingen daarna tot https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/pull/532#issuecomment-644056517

Dit doorvoeren brengt geen breaking changes met zich mee, maar heeft wel impact op de provider-implementatie. 

@rhengeveld Kan jij inschatten hoe groot die impact is en of die voor de 1.1.0 versie haalbaar is ?

**Comment by rhengeveld** [comment]
Ik zal hier morgenochtend naar kijken. Van wat ik zo snel las verandert de structuur van een aantal classes. Afhankelijk van de hoeveelheid kan dit een paar uur tot 2-3 dagen werk zijn. Klinkt als mogelijk haalbaar voor v1.1.0, maar zal hier morgenochtend een betere reactie op geven 😉

**Comment by rhengeveld** [comment]
@JohanBoer op basis van de beschrijving en opmerkingen zie ik nog niet helemaal voor mij wat er gaat veranderen. 

Momenteel heb ik bijvoorbeeld dit:
```json
KadasterNatuurlijkPersoonHalCollectie:
      type: object
      properties:
        _links:
          $ref: '#/components/schemas/HalCollectionLinks'
        _embedded:
          $ref: '#/components/schemas/KadasterNatuurlijkPersoonHalCollectie__embedded'
```
```json
KadasterNatuurlijkPersoonHalCollectie__embedded:
      type: object
      properties:
        kadasterNatuurlijkPersonen:
          type: array
          items:
            $ref: '#/components/schemas/KadasterNatuurlijkPersoonHal'
```
Hierbij is het _embedded component al apart gedefinieerd?  
Ik denk dat ik moet zien hoe de spec veranderd en wat voor code dan gegenereerd wordt.

---

Nu zijn in het verleden ook dingen verplaatst, verwijderd of hernoemd. Tevens is nog niet alle functionaliteit (Beslag, Hypotheken, ..) geïmplementeerd, dus de impact is beperkt. Ik verwacht dat ik alleen de _mapping_ en gerelateerde testen moet aanpassen. Op basis daarvan denk ik dat het met een dag te doen moet zijn.  

Komende maandag hebben we weer een meeting gepland staan, laten we dit dan verder bespreken.

**Comment by JohanBoer** [comment]
Check of deze wijzigingen impact heeft op de resolved versie . Zo ja, dan bespreken met Rik, Zo nee, dan kan dit worden doorgevoerd zonder impact op de provider implementatie.

**Comment by JohanBoer** [comment]
@rhengeveld Het enige verschil als ik bovenstaande wijzigingen doorvoer is dat in de resolved versie een dubbele unserscore gebruikt wordt voor de betreffende componenten (ZakelijkGerechtigdeHalCollectie__embedded:). Als ik ze expliciet in de unresolved versie opneem is dat een enkele underscore (ZakelijkGerechtigdeHalCollectie_embedded:)

Ik neem haast aan dat die impact overzichtelijk is. Graag jouw reactie .. en of we dit dan in versie 1.1. kunnen doorvoeren.

**Comment by rhengeveld** [comment]
@JohanBoer zoals aangegeven in pull request #549 zie ik aan mijn kant geen impact 👍
