### ISSUE TITLE
Verwijderen niet-gebruikte responses

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#541]
Als HC willen we dat alleen foutresponses in de API specificatie staan, die ook worden ondersteund, zodat clients en provider weten welke foutresponses ondersteund en afgehandeld moeten worden.

**Acceptatiecriteria**
Alleen foutmeldingen die nu ondersteund worden staan in de API specificatie.
Alle foutmeldingen die door de API ondersteund worden, staan in de API specificatie. Dit houdt in dat ook de foutmeldingen die door een evt. API gateway en niet door de applicatie implementatie (bv. 401, 403, 429, 503) worden gegenereerd, onderdeel zijn van de API specificatie.

Foutmeldingen kunnen door een API gateway of in de applicatie (implementatie) zelf worden ondersteund.

**Comment by fsamwel** [comment]
@rhengeveld zou je kunnen aangeven welke http responsecodes door de applicatie en door jullie gateway geleverd kunnen worden?

Van een aantal betwijfel ik namelijk of die wel gebruikt worden, zoals 409, 415 en 429

**Comment by rhengeveld** [comment]
Momenteel kan de applicatie de volgende HTTP status codes geven:
* 200 OK
* 400 Bad Request
* 404 Not Found
* 406 Not Acceptable
* 410 Gone
* 500 Internal Server Error

Wat de gateway kan leveren weet ik niet, ik zal dat navragen.

**Comment by JohanBoer** [comment]
Check bij de BAG welke foutcodes de gateway ondersteunt. Foutcodes die niet ondersteunt worden worden uit de specificatie gehaald.
