### ISSUE TITLE
huisnummerToevoeging of huisnummertoevoeging

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#542]
In een adres (nummeraanduiding in BAG zit property "huisnummertoevoeging". In BRK adres (personen en in v1.2 ook in onroerende zaak) zit "huisnummerToevoeging".

Zou goed zijn dit gelijk te trekken. in imKad is het trouwens ook "huisnummertoevoeging", dus één woord.

Dit is een breaking change, dus die moet met spoed worden opgelost in v1.1

**Comment by fsamwel** [comment]
correctie doorgevoerd in specificaties met pull request #543

**Comment by rhengeveld** [comment]
Ik had dit 2 dagen terug niet expliciet vermeld: doorgevoerd en beschikbaar met volgende oplevering ✔️
