### ISSUE TITLE
api-version en content-crs header ontbreken in response

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#544]
in elk responsebericht moet de version header zijn opgenomen.

De API-version is nu echter nooit opgenomen. (niet in 200 response en ook niet bij foutberichten)

Bijvoorbeeld in:
/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000
/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000?fields=bestaatniet

Ook de Content-Crs header moet bij een response worden meegeleverd, wanneer er geometrie in het antwoord zit. Dit ontbreekt nu ook. Bijvoorbeeld in /kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000

N.B. volgens mij werd die voorheen wel meegeleverd

**Comment by rhengeveld** [comment]
@fsamwel heb je de volledige URL voor mij? Ik ben nog niet helemaal thuis in de omgevingen die we gebruiken 😅 en weet niet zeker of ik nu de correcte heb gevonden. Dan kan ik het testen en verder navragen.

**Comment by fsamwel** [comment]
Correcte request (200 response) die api-version en content-crs headers zou moeten hebben:
https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000

Fout request (400 response) die api-version header zou moeten hebben:
https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/NL.IMKAD.KadastraalObject.76870487970000?fields=bestaatniet

**Comment by rhengeveld** [comment]
Bedankt. Ik kan bevestigen dat de headers intern aangeboden worden, maar 'kwijt' zijn na de gateway. We zoeken het nader uit.

**Comment by rhengeveld** [comment]
@fsamwel kan je het opnieuw testen? De configuratie van de gateway is aangepast, zoals ik het zie werkt het nu 😄 
![image](https://user-images.githubusercontent.com/1228038/85590614-d8d39e00-b644-11ea-8764-f314f126ebf1.png)
