### ISSUE TITLE
Impliciet fields meeleveren benodigd voor URI templating

### ISSUE THREAD

**Issue by rhengeveld** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#550]
In #467 is URI templating toegepast. Naar aanleiding van [deze opmerking](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/467#issuecomment-647623606) (zie hieronder) maak ik dit issue aan, voor verdere uitwerking van de interactie tussen _URI templating_ en _fields_.

---

De vraag was wat we doen met onderstaande voorbeeld, als vervolgens enkel de links d.m.v. _field_ parameter worden opgevraagd. In dat geval is het voor de gebruiker namelijk niet mogelijk om het templated `{zakelijkGerechtigdeIdentificaties}` te vullen.  

![ESD-177-templating1](https://user-images.githubusercontent.com/1228038/84233583-e3455200-aaf2-11ea-8313-706be2d932a2.png)

In #467 staan we nog toe dat de gebruiker zichzelf hiermee in de voet schiet, omdat de benodigde _kadastraalOnroerendeZaakIdentificaties_ niet geselecteerd zijn.

⚠️ **Dit willen we nu oplossen door deze benodigde velden impliciet mee te leveren, op het moment dat de betreffende link met templating wordt opgevraagd.** ⚠️  

Dat betekent dat in bovenstaande voorbeeld het veld _zakelijkGerechtigdeIdentificaties_ ook wordt geleverd, ondanks dat d.m.v. fields enkel de _links_ zijn geselecteerd voor weergave.

**Comment by rhengeveld** [comment]
In [deze opmerking](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/467#issuecomment-641752906) van #467 staat beschreven in welke situaties _templates links_ gebruikt worden. Ik heb de implementatie aangepast om voor deze situaties de impliciete velden mee te leveren. Ik kan dit voor v1.1 opleveren of hiermee wachten tot v1.2.

---

1. **ZakelijkGerechtigden onroerende zaak**  
* Voorbeeld templated link `/kadastraalonroerendezaken/76870487970000/zakelijkgerechtigden/{zakelijkGerechtigdeIdentificaties}`
* Templated link property: `links.zakelijkGerechtigden`
* Templated link afhankelijk van properties: `zakelijkGerechtigdeIdentificaties`  

|Requested field|Fields present^|
|---|---|
| - |`links.zakelijkGerechtigden`, `zakelijkGerechtigdeIdentificaties`|
|`links`|`links.zakelijkGerechtigden`, `zakelijkGerechtigdeIdentificaties`|
|`links.zakelijkGerechtigden`|`links.zakelijkGerechtigden`, `zakelijkGerechtigdeIdentificaties`|
|`links.self`|`links.self`|
|`zakelijkGerechtigdeIdentificaties`|`zakelijkGerechtigdeIdentificaties`|

2. **KadastraalOnroerendeZaken natuurlijk persoon**  
* Voorbeeld templated link `/kadastraalonroerendezaken/{kadastraalOnroerendeZaakIdentificaties}`
* Templated link property: `links.kadastraalOnroerendeZaken`
* Templated link afhankelijk van properties: `kadastraalOnroerendeZaakIdentificaties`  

|Requested field|Fields present^|
|---|---|
| - |`links.kadastraalOnroerendeZaken`, `kadastraalOnroerendeZaakIdentificaties`|
|`links`|`links.kadastraalOnroerendeZaken`, `kadastraalOnroerendeZaakIdentificaties`|
|`links.kadastraalOnroerendeZaken`|`links.kadastraalOnroerendeZaken`, `kadastraalOnroerendeZaakIdentificaties`|
|`links.self`|`links.self`|
|`links.woonAdres`|`links.woonAdres`|
|`links.postAdres`|`links.postAdres`|
|`links.zakelijkGerechtigden`|`links.zakelijkGerechtigden`|
|`kadastraalOnroerendeZaakIdentificaties`|`kadastraalOnroerendeZaakIdentificaties`|

3. **KadastraalOnroerendeZaken niet natuurlijk persoon**  
Zie hierboven, vrijwel identiek aan _KadastraalOnroerendeZaken natuurlijk persoon_

_^ Velden "links.self", "identificatie" en "domein" zijn altijd aanwezig, ongeacht verder gevraagde velden_

**Comment by fsamwel** [comment]
> Ik kan dit voor v1.1 opleveren of hiermee wachten tot v1.2.

Als dat kan dan graag met v1.1. Hoe eerder hoe beter :)

**Comment by rhengeveld** [comment]
Code gemerged. Komt mee met de v1.1 oplevering.

**Comment by fsamwel** [comment]
Dit werkt nu nog niet helemaal. Bij /kadastraalonroerendezaken/76870487970000?fields=_links.zakelijkGerechtigden krijg ik de link
      "zakelijkGerechtigden" : [
         {
            "href" : "/kadastraalonroerendezaken/76870487970000/zakelijkgerechtigden/{zakelijkGerechtigdeIdentificaties}",
            "templated" : true
         }
      ]

Maar wordt zakelijkGerechtigdeIdentificaties niet meegeleverd.

Bij /kadasternatuurlijkpersonen/70882239?fields=_links.kadastraalOnroerendeZaken
Krijg ik templated link
       "kadastraalOnroerendeZaken" : [
         {
            "href" : "/kadastraalonroerendezaken/{kadastraalOnroerendeZaakIdentificaties}",
            "templated" : true
         }
      ]

Maar worden de kadastraalOnroerendeZaakIdentificaties niet meegeleverd.

**Comment by rhengeveld** [comment]
Hmm, heb ik deze gemist 🤔 ik zal ernaar kijken

**Comment by rhengeveld** [comment]
Werkt wel met `links` ipv `_links`

**Comment by rhengeveld** [comment]
Opgelost ✔️ in volgende oplevering
