### ISSUE TITLE
Waarom is de content-Crs in de 200 respons een string

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#553]
N.a.v. review-sessie op Versie 1.2.0 .

Gerelateerd hieraan: moet er voor deze endpoints een contenCrs header parameter worden gedefinieerd. 
Die is in versie 1.1 nog nergens gedefinieerd.

**Comment by fsamwel** [comment]
je bedoelt hier content-crs als request header of als response header

als request header is die alleen nodig wanneer in het request geometrie zit. Die hebben we in BRK niet (wel in BAG op /panden?locatie)

als response header is die wel nodig op /kadastraalonroerendezaken en op /zakelijkgerechtigden en is daar ook op gedefinieerd (al in v1.0.0)

**Comment by JohanBoer** [comment]
Als respons header in de 200 respons. Volgens mij kwam de vraag van jou (ben ik niet 100% zeker van) en volgens mij was de vraag waarom dit geen enumeratie was, vergelijkbaar met er Content-Crs request-header in de BAG. 

Ik heb dat net even gechecked en in de common.yaml is de contentCrs header gedefinieerd als enumeratie. Blijkbaar heeft swagger daar een probleem mee om dat weer te geven. In de geresolvde versie staat de enumeratie ook netjes n de component, maar wordt deze in de swaggerhub weergave niet getoond. 

Ik denk dus eigenlijk dat we deze issue direct weer kunnen sluiten.
