### ISSUE TITLE
kadastraalonroerendezaken niet gevonden

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#554]
Een aantal kadastraalonroerendezaken wordt nu niet meer gevonden, die voorheen nog wel beschikbaar waren.

Bijvoorbeeld:
https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/22310827210003
https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/22590043870000
https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/19560032970000
https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/17500393970000
https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/17550448670000
https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/65490485270000

Deze geven een 404 foutmelding.

https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken/22310827210004
Deze geeft een 410 (gone) melding, terwijl die eerder wel werd gevonden.

**Comment by rhengeveld** [comment]
Ik heb misschien per abuis ook de achterliggende dataset vervangen. Ben nu even niet in de gelegenheid dit te verhelpen, zal er straks naar kijken.

**Comment by rhengeveld** [comment]
Oeps, had inderdaad de dataset vervangen. Bovengenoemde kadastraalonroerendezaken worden weer gevonden. Issue opgelost.
