### ISSUE TITLE
server error bij zoeken kadastraalonroerendezaken op adres

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#555]
/kadastraalonroerendezaken?adres__postcode=7361EW en andere zoekopdrachten op adres (postcode + huisnummer) gegeven een 500 server error:

{
   "type" : "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_InternalServerError",
   "title" : "Internal Server Error",
   "status" : 500,
   "detail" : "Internal Server Error",
   "instance" : "/kadastraalonroerendezaken?adres__postcode=7361EW",
   "code" : "Internal Server Error"
}

**Comment by rhengeveld** [comment]
Dataset was vervangen. Request op https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken?adres__postcode=7361EW levert weer resultaat op. Issue opgelost.
