### ISSUE TITLE
zoeken kadastraalonroerendezaken op burgerservicenummer vindt geen zaken

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#556]
/kadastraalonroerendezaken?ingeschrevenpersoon__burgerservicenummer=999991905

vindt geen kadastraalonroerendezaken: _embedded" : { }

Voorheen werden er 3 kadastraalonroerende zaken gevonden, waaronder 76870482570000 (de andere twee lijken niet meer te bestaan, zie #554)

/kadastraalonroerendezaken/76870482570000/zakelijkgerechtigden levert 3 zakelijkgerechtigden, waaronder /kadastraalonroerendezaken/76870482570000/zakelijkgerechtigden/20170718. Deze heeft als persoon.identificatie 999991905. 
Dus had ik verwacht dat op basis van dit burgerservicenummer 999991905 ook deze kadastraalonroerendezaak zou worden gevonden. Tot de vorige oplevering werd deze ook gevonden.

**Comment by rhengeveld** [comment]
Dataset was vervangen. Request op https://api.test.kadaster.nl/esd/gemeenten/brk/kadastraalonroerendezaken?ingeschrevenpersoon__burgerservicenummer=999991905 levert weer resultaat op als voorheen. Issue opgelost.
