### ISSUE TITLE
Buitenlands adres niet getoond

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#557]
/kadasternatuurlijkpersonen/50550743

Deze gaf voorheen een buitenlands woonadres terug:
PRIMA PLEIN 123
LUIK
Wallonië
België

Op dit moment wordt het woonadres niet meer teruggegeven.

**Comment by rhengeveld** [comment]
Dataset was vervangen. Request op https://api.test.kadaster.nl/esd/gemeenten/brk/kadasternatuurlijkpersonen/50550743 levert weer resultaat op als voorheen. Issue opgelost.
