### ISSUE TITLE
Kadasterpersonen die geen zakelijkgerechtigden zijn?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#558]
/kadasternatuurlijkpersonen/50550743
/kadasternatuurlijkpersonen/71303564
/kadasternietnatuurlijkpersonen/71291440
/kadasternietnatuurlijkpersonen/440650207

Deze kadasterpersonen hebben wel een relatie naar een kadastraal onroerende zaak, maar geen zakelijkgerechtigden.  _links.zakelijkGerechtigden ontbreekt bij deze resources.

In de vorige oplevering hadden deze kadasterpersonen nog wel een link naar zakelijkGerechtigden

**Comment by rhengeveld** [comment]
Dataset was vervangen, levert nu weer data op als voorheen. Issue opgelost.

**Comment by fsamwel** [comment]
probleem is weer terug.

/kadasternatuurlijkpersonen/70882239 bevat in het antwoord wel
   "kadastraalOnroerendeZaakIdentificaties" : [
      "76870487970000",
      "76870482670000"
   ],

maar geen zakelijkGerechtigden.

Voor beide onroerende zaken levert zakelijkgerechtigden een zakelijkGerechtigde met deze persoon

**Comment by rhengeveld** [comment]
Dataset teruggezet. Response bevat weer zakelijkgerechtigden als verwacht:
![image](https://user-images.githubusercontent.com/1228038/87126105-ebc4b000-c28b-11ea-9b00-03c9eca9222f.png)
