### ISSUE TITLE
Hergebruik maken van de BAG definitie van Adres

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#561]
Als de specificatie versie 1.0.0 van de BAG-bevragen API beschikbaar is kunnen we hergebruik maken van de Adres definitie van de BAG en die uitbreiden met de properties die wel nodig zijn, maar niet in de Adres definitie van de BAG zijn opgenomen.

**Comment by JohanBoer** [comment]
Check of de huidige definitie van Adres inderdaad overeenkomt met die van de BAG. Zo ja vervang deze dan door een $ref naar versie 1.0

**Comment by kad-hebbim** [comment]
`Adres` hernoemen naar `AdresUitgebreid`, zodat in genereer variant er geen `Adres_2` component komt te staan.

**Comment by rhengeveld** [comment]
#714 is gemerged, **implementatie aangepast [en acceptatieomgeving update volgt later]**

**Comment by fsamwel** [comment]
@kad-hebbim ik heb nu geen testgeval voor kadastraalonroerendezaken met een adres met huisnummertoevoeging. Kan je die toevoegen? Dan kan ik ook zien hoe die in adresregel1 terechtkomt

**Comment by kad-hebbim** [comment]
@fsamwel huisnummertoevoeging met waarde 1 toegevoegd aan 1 van de adressen van onroerendezaak 24780711870000

**Comment by fsamwel** [comment]
dank je.
