### ISSUE TITLE
property mandeligheid.identificatie verwijderen ? 

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#562]
Frank stelt dat voor het bevragen van de kadastraal Onroerende Zaak of de ZaeklijkGerechtigde de identificatie van de mandeligheid geen toegevoegde waarde heeft en verwijder kan worden.

**Comment by MelvLee** [comment]
Als er geen endpoint komt om mandeligheid op te kunnen halen of om er andere resources mee te kunnen vinden, dan is het inderdaad niet nodig

**Comment by fsamwel** [comment]
moet verwijderen worden

**Comment by fsamwel** [comment]
mandeligheid is inmiddels in zijn geheel verwijderd uit de zakelijk gerechtigde
