### ISSUE TITLE
vragen om json mag geen fout geven

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#563]
Wanneer een request wordt gedaan met Accept: application/json levert dit nu een 406 fout op, overigens zonder response body (geen problem+json).

Het is niet terecht dat hier een fout komt. hal+json is immers ook json.

**Comment by rhengeveld** [comment]
Ok, dus:
1. `accept: application/json` mag geen 406 opleveren
2. Als we dan een 406 opleveren, dienen we in de payload een lijst van geaccepteerde waarden terug te geven ([bron](https://httpstatuses.com/406))

**Comment by rhengeveld** [comment]
#### Betreffende 1
_Kort antwoord: Ja, dit kan, mits de OpenApi specificatie wordt aangepast._

Op basis van de OpenApi specificatie wordt een api interface gegenereerd, met daarop code als:
```java
    @RequestMapping(value = "/kadasternatuurlijkpersonen/{kadasternatuurlijkpersoonidentificatie}",
        produces = { "application/hal+json", "application/problem+json" }, 
        method = RequestMethod.GET)
```
Vervolgens implementeer ik deze interface. In deze `@RequestMapping` staat (zoals je kan zien) vastgelegd dat alleen `application/hal+json` en `application/problem+json` als response geleverd worden. Als het verzochte type niet door de server geleverd kan worden dan levert dat een 406 op, standaard Spring REST framework gedrag. Gezien `application/json` niet gespecificeerd is levert dat dus een 406 op.

Ik kan deze `@RequestMapping` in mijn implementatie overschrijven, maar dat moet ik voor _alle_ requests doen, waarmee het voordeel van automatisch gegenereerde code teniet wordt gedaan. Tevens is dit zeer fragiel, gezien aanpassingen in de specificatie niet meer automatisch terugkomen in de code.

De enige optie die ik heb gevonden, welke ook op de lange termijn werkbaar is, is het aanpassen van de OpenApi speciatie.  

Van:
```json
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/KadasterNatuurlijkPersoonHal'
```
Naar:
```json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KadasterNatuurlijkPersoonHal'
            application/hal+json:
              schema:
                $ref: '#/components/schemas/KadasterNatuurlijkPersoonHal'
```
Dit moet dan in de gehele specificatie gebeuren. Op basis daarvan verandert ook de gegeneerde interface code:
```java
    @RequestMapping(value = "/kadasternatuurlijkpersonen/{kadasternatuurlijkpersoonidentificatie}",
        produces = { "application/json", "application/hal+json", "application/problem+json" }, 
        method = RequestMethod.GET)
```
Nu wordt `applicaton/json` wel geaccepteerd. Overigens is de response nog steeds `Content-Type: application/hal+json`.

---

#### Betreffende 2
Ik kan de 406 response een payload geven, maar in wat voor format willen we dat dan? Is daar een voorbeeld van?

**Comment by rhengeveld** [comment]
In overleg besloten:
* Punt 1 gaan we op dit moment niet oplossen. Heeft teveel impact en als de client de specificatie volgt is het geen issue.
* Punt 2 ga ik aanpassen.

**Comment by fsamwel** [comment]
besproken in overleg. voorlopig lossen we dit niet op. gebruikers die geen accept meegeven, en gebruikers die vanuit gegenereerde code werken hebben hier geen last van. Alleen correcte inhoud van foutmelding wel oplossen. Dat zit in #231.

**Comment by rhengeveld** [comment]
Voorbeeld oplossing punt 2:
```
{
    "type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?view=netcore-3.1#System_Net_HttpStatusCode_NotAcceptable",
    "title": "Gevraagde contenttype wordt niet ondersteund.",
    "status": 406,
    "detail": "Ondersteunde contenttypes: 'application/hal+json', 'application/problem+json'",
    "instance": "/kadasternatuurlijkpersonen/70882239?fields=kadastraalOnroerendeZaakIdentificaties",
    "code": "notAcceptable"
}
```
Het stond niet expliciet beschreven, dus ik heb ervoor gekozen om in de _details_ de ondersteunde contenttypes ("Accept") terug te geven.

**Comment by fsamwel** [comment]
@rhengeveld waarom is in detail ook problem+json opgenomen? Kan iemand daarom vragen? Ik zou denken dat je alleen de ondersteunde types voor de 200 OK response wilt noemen.

**Comment by rhengeveld** [comment]
@fsamwel dat is waar. Momenteel geef ik alle 'supported' types terug, waarbij de `application/problem+json` vanuit de 404 komt:
```json
        "400":
          description: Bad Request
          headers:
            api-version:
              $ref: '#/components/headers/api_version'
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/BadRequestFoutbericht'
```

Ik zal deze eruit filteren, zodat dat we alleen `application/hal+json` behouden.

**Comment by fsamwel** [comment]
> Ik zal deze eruit filteren, zodat dat we alleen application/hal+json behouden.
>
> UPDATE Aangepast ✔️

Ik krijg die nog. /kadastraalonroerendezaken/76870487970000 met Accept: application/json levert:
{
   "type" : "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?view=netcore-3.1#System_Net_HttpStatusCode_NotAcceptable",
   "title" : "Gevraagde contenttype wordt niet ondersteund.",
   "status" : 406,
   "detail" : "Ondersteunde contenttypes: 'application/hal+json', 'application/problem+json'",
   "instance" : "/kadastraalonroerendezaken/76870487970000",
   "code" : "notAcceptable"
}

ik had hier bij detail verwacht:
"detail" : "Ondersteunde contenttypes: 'application/hal+json'",

**Comment by rhengeveld** [comment]
Vreemd, ik dacht dat ik dit had opgelost. Zal het nakijken

**Comment by rhengeveld** [comment]
Opgelost ✔️ in volgende oplevering

**Comment by rhengeveld** [comment]
Beschikbaar op de testomgeving ✔️
