### ISSUE TITLE
Moeten de parameternamen van /KadastraalOnroerendeZaak aangepast worden n.a.v. het opnemen van Adres

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#568]
In de vorige versie (1.0 en 1.1) maakte het adres zelf geen onderdeel uit van de resource KadastraalOnroerendeZaak. Er kan echter wel op postcode huinummer etc gezocht worden. Conform de naamgevingsconventie hebben wij de betreffende parameters voorzien van een prefix adres__ omdat er op properties van een gerelateerde resource gezocht werd. 

In versie 1.2 nemen we het adres als "comfort-gegeven" op bij de KadastraalOnroerendeZaak. 
Daarmee vervalt de reden om de genoemde parameters als prefix te gebruiken. 

Het verwijderen van deze prefixes levert echter een breaking change op.

**Comment by fsamwel** [comment]
Volgens mij gebruiken we de prefix (ook) wanneer een property in een groep zit. Wanneer we willen filteren op adressen.postcode, dan heeft de queryparameter adressen__postcode.

Zo hebben we dat ook gedaan bij BRP. Bijvoorbeeld verblijfplaats__postcode. Daar is de verblijfplaats een gegevensgroep binnen de resource, geen relatie naar een (sub of andere)resource.

Dit hebben we destijds zo overgenomen van het [Gemma-zaken project](https://vng-realisatie.github.io/gemma-zaken/themas/achtergronddocumentatie/ontwerpkeuzes) (poging tot consistentie tussen verschillende API's):
> Om relaties zowel naar een andere resource (zoals status) als naar een genest attribuut (zoals kenmerken) te gebruiken binnen query parameters, wordt de __ (dubbele underscore) gebruikt tussen de attribuutnamen.

Laten we dat los en gebruiken alleen de propertynaam (zonder pad in resource)?

N.B. ik ben daar niet tegen hoor. Alleen wanneer zelfde propertynaam meerdere plekken in resource voorkomt is dat nodig.

**Comment by fsamwel** [comment]
Besproken, met als conclusie:
weghalen adres__ prefix en ook ingeschrevenPersoon__burgerservicenummer wordt burgerservicenummer.
