### ISSUE TITLE
consequent toepassing van Casing in parameternamen

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#569]
In de issue https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen/issues/241 van de BAG is een voorstel gedaan hoe om te gaan met Casing voor parameters. 

Dit voorstel is voor de BAG geaccepteerd en wordt zo doorgevoerd. Lijkt mij ook een goed idee om deze conventie ook toe te passen voor de BRK, maar het is wel wat laat dag.

@ team : Gaan we deze manier van Casing ook voor de BRK toepassen ? (Heeft nu wel breaking impact, maar er zijn nog geen consumers....)

@rhengeveld , @mhebbink-kad  Als we de specifIcaties  snel opleveren is dat nog te doen dan ?

**Comment by fsamwel** [comment]
Het betreft:
/kadastraalonroerendezaken
- kadastraleaanduiding
- persoon_kadasterpersoonidentificatie
- zakelijkgerechtigde__typegerechtigde

/kadastraalonroerendezaken/{kadastraalonroerendezaakidentificatie}/zakelijkgerechtigden
- typegerechtigde: deze is so-wie-so vervelend, want in de resource heet het gegeven "type". De parameter moet dan eigenlijk ook "type" heten

We zijn nu toch een breaking change aan het doen naar v1.1.0, dus waarom niet?

(paar argumenten waarom misschien toch niet: niet aangekondigde en grotere breaking change; impact op bouw kan vertraging oplevering 1.1 geven)

**Comment by rhengeveld** [comment]
@JohanBoer ik denk dat het veranderen van de _case_ geen tot weinig impact heeft, dus als een pull request gemaakt kan worden dan kan ik snel proberen om dit nog mee te nemen 😃 

---

**Toelichting:** Als het alleen om het veranderen van _case_ gaat dan moet ik _misschien_ een paar testen aanpassen, maar volgens mij is dat alles. De implementatie is niet direct gekoppeld aan de naam van een parameter; intern mag deze anders heten. Bijvoorbeeld:
```java
@RequestParam(value = "kadastraleaanduiding", required = false) String dezeParameterHeeftInternEenAndereNaam
```
Daarbij zijn _request_ parameters reeds _case insensitive_; bijvoorbeeld `?=kadaSTRaleaaNDUiding=...` werkt ook.

Als de parameter iets heel anders wordt maakt dat alleen uit voor de testen welke _kadastraleaanduiding_ als parameter gebruikten:
```java
@RequestParam(value = "kadastrale__aanduiding", required = false) String dezeParameterHeeftInternEenAndereNaam
```
