### ISSUE TITLE
Descriptions v1.2

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#570]
- [x] IsGebaseerdOpStukdeelIdentificatie _**(komt op meer plekken voor, graag generiek verwerken. dit is de enkelvoudsvorm)**_
is: De identificatie van het stukdeel waarop deze aantekening is gebaseerd. 
Wordt: De identificatie van het stukdeel (paragraaf in een akte met een rechtsfeit) waarop deze aantekening is gebaseerd.

- [x] isVermeldInStukdeelIdentificaties **_(komt op veel meer plekken voor, graag gereniek verwerken. Dit is de meervoudsvorm)_**
is: De identificaties van het stukdeel waarop deze aantekening is gebaseerd
Wordt: De identificaties van de stukdelen (paragrafen in een akte met een rechtsfeit) waarop deze aantekening is gebaseerd.

- [x] Appartementsrechtsplitsing
is: en appartementsrechtsplitsing is het in appartementsrechten gesplitste Zakelijk recht van 1 of meer kadastrale objecten
wordt: een appartementsrechtsplitsing is het in appartementsrechten gesplitste zakelijk recht van 1 of meer kadastrale objecten

- [x] Bedrag:
Waardelijst: geen description, ook niet voor code en waarde, zie #365. Graag overal in deze versie weghalen (beslag, aard en omschrijving betrokkenrecht etc.)

- [x] Beperkingsgebied: (graag generiek implementeren, beperkingen privaat en publiekrechtelijk)
werkingsgebied 
description wordt: Datgene waarop de beperking van toepassing is. @HildeVos is dat correct?

- [x] gedeeltelijkeBezwaringOudObject
wordt: Indicatie of het object waarop beslag is gelegd gedeeltelijk uit een inmiddels vervallen object bestaat.

- [x] overgangsgrootte
is: De oppervlakte van het gedeelte van de oude Onroerende zaak dat opgegaan is in de nieuwe Onroerende zaak. De overgangsgrootte heeft uitsluitend betrekking op Onroerende zaak van het soort Perceel
wordt: De oppervlakte van het gedeelte van het oude perceel dat is opgegaan in de nieuwe Onroerende zaak.

- [x] Geboorte:
geboorteplaats
was: De geboorteplaats is de plaats of een plaatsbepaling, die aangeeft waar de persoon is geboren
wordt: plaats of plaatsbepaling waar de persoon is geboren.

- [x] datumonvolledig
is: gegevens over de datums die mogelijk niet volledig zijn, maar waarvan de bekende gedeeltes wel moeten kunnen worden uitgewisseld. Als de volledige datum bekend is worden alle elementen gevuld.
wordt: constructie voor het uitwisselen van datum die wel of niet volledig bekend zijn 

- [x] dag
is: De dag. Als de dag van de datum bekend is wordt deze hier ingevuld. Ook als de volledige datum bekend is.
wordt: heeft een waarde als de dag van de datum bekend is. 

- [x] datum
is: De volledige datum die in de date definitie past. Dit element wordt alleen gevuld als de volledige datum bekend is.
wordt: datum die in de date (hypertext) definitie past. Bevat alleen een waarde als de volledige datum bekend is.

- [x] jaar
is: Het jaar van de datum. Als het jaar bekend is wordt dit element gevuld, ook als de volledige datum bekend is.
wordt: heeft een waarde als het jaar van de datum bekend is. 

- [x] maand
is: De maand. Als de maand van een datum bekend is wordt deze hier ingevuld. Ook als de volledige datum is ingevuld.
wordt: heeft een waarde als de maand van de datum bekend is.

- [x] Hypotheek
wordt: Bij een hypotheek op de kadastraal onroerende zaak dient het eigendomsrecht van de hypotheekgever als onderpand voor een geldlening of krediet bij de hypotheeknemer (geldverstrekker). @HildeVos klopt dit?

- [x] Hypotheekhouder (zie #401), description ontbreekt in swagger
wordt: Geldverstrekker die een recht van hypotheek vestigt als zekerheid voor de lening 

- [x] kadastraalOnroerendeZaak:
Landinrichtingsrente
het bedrag waarmee de Onroerende zaak is belast in het kader van de landinrichtingswet. De kosten zijn door het Rijk  voorgeschoten, over de verkavelde percelen omgeslagen, en moeten worden (met rente) worden afbetaald. @HildeVos klopt dat?  

- [x] PubliekrechtelijkeBeperking
is: De privaatrechtelijke beperking is een aantekening op een Kadastraal onroerende zaak of een aantekening op een recht op een kadastraal onroerende zaak
wordt: Beperkingen op een kadastraal onroerende zaak die door de overheid zijn opgelegd. Deze bepalen wat een eigenaar wel of niet mag doen met een woning, een ander gebouw of een stuk grond. Het gaat het bijvoorbeeld om beschermde monumenten, natuurmonumenten, bodembescherming, eisen die binnen de Woningwet worden gesteld, of maatregelen die nodig zijn voor landsverdediging.

- [x] Stukdeel:
TransactieSomLevering
Wordt: de koopsom @HildeVos klopt dit?
bedragVorderingsbeslag
wordt: bedrag waarvoor beslag is gelegd op de kadastraal onroerende zaak. @HildeVos, klopt dit?
bedragZekerheidsstellingenHypotheek
wordt: het bedrag waarvoor een hypotheek is ingeschreven

- [x] Stuk:
Stuktype (graag generiek implementeren)
Is: en appartementsrechtsplitsing is het in appartementsrechten gesplitste Zakelijk recht van 1 of meer kadastrale objecten
wordt: geen description

- [x] Typesplitsing_enum
is: en appartementsrechtsplitsing is het in appartementsrechten gesplitste Zakelijk recht van 1 of meer kadastrale objecten
wordt: geen description

- [x] Verkavelobject
wordt: een onroerende zaak die is betrokken bij een herverkaveling.

- [x] AfwijkingLijstRechthebbenden
wordt: afwijkingen tussen de kadastrale registratie en de lijst van rechthebbenden, bedoeld in artikel 183, eerste lid, van de Landinrichtingswet, artikel 71, tweede lid, van de Wet inrichting landelijk gebied, artikel 68 van de Reconstructiewet Midden-Delfland, dan wel in artikel 53 van de Herinrichtingswet Oost-Groningen en de Gronings-Drentse Veenkoloniën.

- [x] Herverkavelingsgebied:
wordt: gebied waarin onroerende zaken worden samengevoegd, verkaveld en verdeeld door toepassing van de Wet inrichting landelijk Gebied

**Comment by HildeVos** [comment]
Klopt. Geen aanvullingen.

**Comment by fsamwel** [comment]
@JohanBoer op isOvergegaanIn en isOntstaanUit zou je nog kunnen toelichten welke waardelijst is gebruikt voor veld "aard"

**Comment by CathyDingemanse** [comment]
> * [x]  Appartementsrechtsplitsing
>   is: en appartementsrechtsplitsing is het in appartementsrechten gesplitste Zakelijk recht van 1 of meer kadastrale objecten
>   wordt: een appartementsrechtsplitsing is het in appartementsrechten gesplitste zakelijk recht van 1 of meer kadastrale objecten

Deze ontbreekt nog.



> * [x]  datumonvolledig
>   is: gegevens over de datums die mogelijk niet volledig zijn, maar waarvan de bekende gedeeltes wel moeten kunnen worden uitgewisseld. Als de volledige datum bekend is worden alle elementen gevuld.
>   wordt: constructie voor het uitwisselen van datum die wel of niet volledig bekend zijn

Is nog niet gewijzigd. Graag generiek wijzigen in alle API's.

> * [x]  dag
>   is: De dag. Als de dag van de datum bekend is wordt deze hier ingevuld. Ook als de volledige datum bekend is.
>   wordt: heeft een waarde als de dag van de datum bekend is.

Is nog niet gewijzigd. Graag generiek wijzigen in alle API's.


> * [x]  datum
>   is: De volledige datum die in de date definitie past. Dit element wordt alleen gevuld als de volledige datum bekend is.
>   wordt: datum die in de date (hypertext) definitie past. Bevat alleen een waarde als de volledige datum bekend is.

Is nog niet gewijzigd. Graag generiek wijzigen in alle API's.

> * [x]  jaar
>   is: Het jaar van de datum. Als het jaar bekend is wordt dit element gevuld, ook als de volledige datum bekend is.
>   wordt: heeft een waarde als het jaar van de datum bekend is.

Is nog niet gewijzigd. Graag generiek wijzigen in alle API's.

> * [x]  maand
>   is: De maand. Als de maand van een datum bekend is wordt deze hier ingevuld. Ook als de volledige datum is ingevuld.
>   wordt: heeft een waarde als de maand van de datum bekend is.

Is nog niet gewijzigd. Graag generiek wijzigen in alle API's.

> * [x]  Stuk:
Is nog niet goed. Is: Hieraan wordt een Kadasterstuk of een Aangebodenstuk gekoppeld. Een stuk is een brondocument dat aanleiding geeft tot een wijziging van de gegevens in een basisregistratie. Een aangeboden brondocument dat aanleiding geeft tot een wijziging van de gegevens in een basisregistratie.
Wordt: 
Een stuk is een brondocument dat aanleiding geeft tot een wijziging van de gegevens in de basisregistratie.

**Comment by JohanBoer** [comment]
Kan volgens mij naar done, of is er nog een final check nodig ?
