### ISSUE TITLE
Foutmelding voor combinatie van parameters

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#572]
Het combineren van bepaalde parameters is niet toegestaan. Bijvoorbeeld /kadastraalonroerendezaken?adres__postcode=7361EW&kadastraleaanduiding=Beekbergen%20K%204825 levert (terecht) een foutmelding.

Hierbij wordt nu als title "Minimale combinatie van parameters moet worden opgegeven." geleverd. Dat is niet duidelijk/correct, want er is ruimschoots aan de "minimale" combinatie voldaan. Het probleem is juist dat er teveel parameters zijn gebruikt.

Vanuit het BAG team is er voor deze situatie een regel toegevoegd voor de foutafhandeling: wanneer bij een endpoint een combinatie van parameters niet is toegestaan, wordt de volgende foutmelding gegeven in "title": "De combinatie van opgegeven parameters is niet toegestaan."
De bijbehorende code is dan "unsupportedCombi".

**Comment by rhengeveld** [comment]
Wordt ook benoemd in [foutafhandeling.feature](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/master/features/foutafhandeling.feature). Prima, zal ernaar kijken.

**Comment by rhengeveld** [comment]
Aangepast ✔️ komt mee met v1.1  
@fsamwel je kan het testen op de testomgeving 👍
