### ISSUE TITLE
v1.2 Portefeuille ID: Als PO ben ik op zoek naar de user story om dit gegeven te leveren.

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#574]
...zodat ik geen onnodige legacy in de API hoe op te nemen. 

Het object lijkt uit legacy attributen te bestaan. Klopt dat? 
Voorstel: er uit halen, en ik zoek wie dit nodig heeft en waarom.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by JohanBoer** [comment]
Afgesproken dat het portefeuillenummer verwijderd wordt uit de specificatie. 
@mhebbink-kad doet navraag om uit te zoeken . Komt daar op terug.

**Comment by fsamwel** [comment]
@JohanBoer portefeuillenummer is nu verwijderd denk ik, of zit deze er nog wel in (kan het zo gauw niet vinden)

**Comment by JohanBoer** [comment]
Portefeuillenummer (en portfeuilleID) werd gebruikt in Kadasterstuk. Die is nu buiten scope.

**Comment by rhengeveld** [comment]
Volgens mij kan dit issue dan doorgeschreven worden naar `BRK bevragen v1.3`?

**Comment by CathyDingemanse** [comment]
Ik heb de user story niet gevonden. Niet opnemen, kan altijd nog als iemand het nodig heeft.
