### ISSUE TITLE
Omdat het alleen voor de waterschappen interessant is, wil ik als PO onderzoeken of de landinrichtingsrente niet uit de KOZ kan worden gehaald 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#575]
...zodat we niet alle andere afnemers hiermee belasten.

Het is wel zo dat het qua omvang niet zoveel voorstelt. 

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by JohanBoer** [comment]
Vooralsnog wordt de landinrichtingsrente uit de specificatie van versie 1.2.0. verwijderd.

**Comment by CathyDingemanse** [comment]
Ik kan het niet meer vinden :-). Prima dus.

**Comment by JohanBoer** [comment]
Kan naar done
