### ISSUE TITLE
X-Rate headers verwijderen als die niet worden gebruikt

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#579]
Voor de responses zijn nu drie headers gedefinieerd die nu (althans op de testomgeving) niet worden geleverd: X-Rate-Limit-Limit, X-Rate-Limit-Remaining, X-Rate-Limit-Reset.

Als ze nooit worden geleverd, moeten ze denk ik ook niet gedefinieerd worden. Ze kunnen, mocht daar behoefte aan komen, later toegevoegd worden.

De bijbehorende foutmelding 429 is ook niet gedefinieerd (en ook geen default), dus vanuit de huidige specificatie kan deze niet volledig worden toegepast. Foutmelding 429 is verwijderd n.a.v. #541.

**Comment by fsamwel** [comment]
@mhebbink-kad @rhengeveld klopt het dat dit nu ook op productie niet gebruikt wordt?

**Comment by fsamwel** [comment]
@MelvLee klopt het dat we later zonder breaking changes deze headers met bijbehorende functionaliteit (429 foutmelding als er teveel requests zijn) kunnen worden toegevoegd?

**Comment by fsamwel** [comment]
N.B. voor BAG zijn deze headers ook verwijderd: https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen/issues/168

**Comment by mhebbink-kad** [comment]
Deze headers worden momenteel niet gebruikt in productie. Mijns inziens kunnen ze dan inderdaad weggelaten worden uit de specs en weer toegevoegd worden als we deze gaan gebruiken.

**Comment by fsamwel** [comment]
pull request is merged
