### ISSUE TITLE
Als medewerker vergunningen wil ik weten of het eigendom kadastraal is gesplitst of samengevoegd

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#58]
...zodat ik kan bepalen of er sprake is van onderzoeksplicht als ik een aanvraag behandel die buiten het bestemmingsplan valt.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by JohanBoer** [comment]
Volgens mij heeft dit met de filiatie te maken. Dat wil ik graag met Marianne doornemen.

**Comment by MelvLee** [comment]
Loopt inderdaad via de filiatie. Ook de link naar de gerelateerde onroerende zaken wordt dan meegegeven. Deze wordt niet embedded aangeboden i.v.m. de complexe recursiviteit.
