### ISSUE TITLE
fields voor nietnatuurlijkpersonen geconfigureerd voor natuurlijkpersonen?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#581]
/kadasternietnatuurlijkpersonen/71291440?fields=identificatie%2Comschrijving%2Cdomein%2CindicatieNietToonbareDiakriet%2Cbeschikkingsbevoegdheid%2Cwoonadres%2Cpostadres%2CkadastraalOnroerendeZaakIdentificaties%2CstatutaireNaam%2CstatutaireZetel%2Crechtsvorm%2CkvkNummer%2Crsin

Dit geeft een foutmelding op fields met reason "Deel van de parameterwaarde niet correct: statutaireNaam, statutaireZetel, rechtsvorm, kvkNummer, rsin."
Dit zijn de velden die wel in kadasternietnatuurlijkpersonen zitten, maar niet in kadasternatuurlijkpersonen

/kadasternietnatuurlijkpersonen/71291440?fields=geheimhoudingPersoonsgegevens%2ClandWaarnaarVertrokken%2Cgeslachtsaanduiding%2CheeftPartnerschap%2Cnaam%2Cgeboorte%2Coverlijden

Dit geeft geen foutmelding. Deze foutmelding was wel verwacht, want gevraagde velden zitten in kadasternatuurlijkpersonen, niet in kadasternietnatuurlijkpersonen

**Comment by rhengeveld** [comment]
Oh, dat is een goede vondst. Het proces bestaat uit 2 stappen: validatie en verwerking. 
* **Validatie:** Controleer of de gevraagde velden bestaan, zo niet geef een foutmelding
* **Verwerking:** Schrap de velden die niet voorkomen en haal gevraagde waarden op

In dit geval worden alleen de verplichte velden _identificatie_, _domein_ en _links.self_ geselecteerd voor verwerking. Het lijkt erop dat de validatie dan incorrect is gedaan op - vermoedelijk - `KadasterNatuurlijkPersoonHal` ipv `KadasterNietNatuurlijkPersoonHal` 🤔 ik zoek het verder uit.

**Comment by rhengeveld** [comment]
**Opgelost ✔️ en beschikbaar op de testomgeving**

Het request van niet natuurlijke personen werd inderdaad incorrect gelinkt aan de validatie voor `KadasterNatuurlijkPersoonHal`. Nu gelinkt aan `KadasterNietNatuurlijkPersoonHal`. Als gevolg hiervan geeft je 1e request nu een foutmelding:
![image](https://user-images.githubusercontent.com/1228038/87689133-22b52d00-c788-11ea-9406-a26e9b97414c.png)
en het 2e request nu een _200 OK_ met inhoud 🙂

**Comment by fsamwel** [comment]
opgelost, maar helaas zie ik hierdoor nu wel nieuw issue #587
