### ISSUE TITLE
fields=postbusnummer levert fout niet uniek

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#587]
/kadasternietnatuurlijkpersonen/71291440?fields=postbusnummer
dit geeft een foutmelding met:
   "invalidParams" : [
      {
         "name" : "fields",
         "code" : "fields",
         "reason" : "Deel van de parameterwaarde niet uniek: postbusnummer."
      }
   ]

idem bij /kadasternatuurlijkpersonen/70882239?fields=postbusnummer

waar komt postbusnummer nog meer voor dan in postadres?

**Comment by rhengeveld** [comment]
@fsamwel aha, leuke vondst! Het antwoord is _woonadres_; probeer maar eens `fields=woonadres.postbusnummer`  

Dit klopt inderdaad _**niet**_. Hoe het zit:
* Woonadres is een `Adres`; deze heeft _**geen**_ _postbusnummer_
* Postadres is een `Postadres` welke erft van `Adres`; de enige toevoeging is het _postbusnummer_

Wat HaalCentraal doet is alle velden nalopen vanaf - in dit geval - `KadasterNatuurlijkPersoonHal` of `KadasterNietNatuurlijkPersoonHal`. Op basis hiervan wordt een pad gebouwd (bijv. "postadres.postbusnummer") welke gekoppeld is aan een specifiek veld van een specifiek type object. Dit wordt gebruikt bij het filteren op _fields_ of _expand_.  

Nu ben ik het exacte voorbeeld even kwijt, maar er was een veld met een algemeen type (_parent_), welke vervolgens gevuld werd met een specifieker type (_child_). Origineel indexeerde HaalCentraal alleen de properties van de _parent_, waardoor gegevens specifiek van een _child_ 'kwijt' raakten bij het filteren. Dit heb ik toen opgelost door óók alle velden van een _child_ te indexeren en te relateren aan diens _parent_.  
Concreet betekent dit: het veld _woonadres_ van het type `Adres` kan ook een `Postadres` met _postbusnummer_ hebben, dat is immers ook een `Adres`. En ja, in dit geval blijft het ingevulde _postbusnummer_ dan ook behouden. Ik vermoed echter dat dit niet is wat we hier verwachten 😅 **Dus ik denk dat we dit stukje child ▶️ parent indexeren weer moeten uitschakelen** _en nakijken of er velden zijn die daarna niet meer werken_.

**Comment by rhengeveld** [comment]
**Opgelost** ✔️ door de _fields_ van een _child_ niet langer bij diens _parent_ te indexeren. 

"postbusnummer" is nu alleen bekend onder het pad "woonadres.postbusnummer":
![image](https://user-images.githubusercontent.com/1228038/88776081-cb4e8e00-d185-11ea-9c46-791e511209c9.png)

Voorheen werd dit indexeren gedaan vanwege het type `Geometry`, welke verschillende _child_ types kon bevatten. Dat is een tijd terug veranderd met `PointGeoJSON` en `PolygonGeoJSON`, dus ik _hoop_ dat er nu geen situaties zijn waarvan de fields niet meer werken.
