### ISSUE TITLE
Implementeren endpoint: /kadastraalonroerendezaken/{koi}/hypotheken

### ISSUE THREAD

**Issue by kad-hebbim** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#590]
Op basis van openapi.yaml in https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/pull/540

**Comment by fsamwel** [comment]
ook toevoegen /hypotheken/{hypotheekidentificatie}

**Comment by rhengeveld** [comment]
Is geïmplementeerd en als het goed is beschikbaar op de testomgeving.
