### ISSUE TITLE
Implementeren endpoint: /kadastraalonroerendezaken/{koi}/beslagen

### ISSUE THREAD

**Issue by kad-hebbim** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#591]
Op basis van openapi.yaml in https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/pull/540

**Comment by fsamwel** [comment]
ook endpoint /beslagen/{beslagidentificatie} toevoegen

**Comment by rhengeveld** [comment]
Is geïmplementeerd en is als het goed is beschikbaar op de testomgeving.

**Let op:** dit is een _preview_ versie, want de Kadaster testers zijn dit nog aan het testen 😉
