### ISSUE TITLE
embedded publiekrechtelijkeBeperkingen in KadastraalOnroerendeZaak moet ook _links bevatten

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#593]
publiekrechtelijkeBeperkingen in KadastraalOnroerendeZaak_embedded is gedefinieerd met $ref naar PubliekrechtelijkeBeperking. Dit moet zijn PubliekrechtelijkeBeperkingHal, want in een embedded resource moeten ook de HAL _links zijn opgenomen

**Comment by JohanBoer** [comment]
Ziet ernaar uit dat deze naar done kan.
