### ISSUE TITLE
Als PO wil ik de BRK bevragen endpoints over verschillende API's te verdelen en onderlinge afhankelijkheden (versioning) reduceren

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#598]
...zodat de beheersbaarheid van de API's worden verhoogd en nieuwe versies alleen impact hebben op direct gerelateerde endpoints. 

Denk aan een aparte API voor personen, maar ook beslagen, hypotheken, publiekrechtelijke beperkingen.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by fsamwel** [comment]
Besproken in overleg op 13 augustus en zijn daar tot de conclusie gekomen dat het opsplitsen in verschillende API's meer problemen en risico's oplevert dat het oplost. Wel gaan we de yaml opsplitsen zodat dit beter beheerbaar wordt. Dit is gedaan in #610.

@CathyDingemanse mag dit issue gesloten worden?

**Comment by CathyDingemanse** [comment]
Zeker!
