### ISSUE TITLE
paginering toevoegen aan /hypotheken en /beslagen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#599]
Endpoint /hypotheken kan hypotheken zoeken op hypotheekhouder. Dat kan in sommige gevallen (denk aan Rabobank, A.S.R., Florius, enz.) een zeer groot aantal hypotheken opleveren. Paginering kan dan voorkomen dat de response zeer lang duurt en zeer veel resources vraagt op de server.

Endpoint /beslagen kan beslagen zoeken op beslaglegger. Dat is bedoeld voor gemeenten, die hun beslagen kunnen raadplegen. Dat kan, zeker voor grotere gemeenten, zeer veel beslagen opleveren.

Zowel voor hypotheken als beslagen moet paginering worden toegevoegd.

**Comment by CathyDingemanse** [comment]
> Endpoint /hypotheken kan hypotheken zoeken op hypotheekhouder. Dat kan in sommige gevallen (denk aan Rabobank, A.S.R., Florius, enz.) een zeer groot aantal hypotheken opleveren. Paginering kan dan voorkomen dat de response zeer lang duurt en zeer veel resources vraagt op de server.
> 
> Endpoint /beslagen kan beslagen zoeken op beslaglegger. Dat is bedoeld voor gemeenten, die hun beslagen kunnen raadplegen. Dat kan, zeker voor grotere gemeenten, zeer veel beslagen opleveren.
Dat valt wel wel mee hoor....:-)

> 
> Zowel voor hypotheken als beslagen moet paginering worden toegevoegd.
Dat zeker, ivm zoeken op hypotheekhouder.

**Comment by fsamwel** [comment]
> Dat valt wel wel mee hoor....:-)

Maar wel genoeg om paginering nodig te maken? Heb je een indicatie over welke aantallen dit kan gaan?

**Comment by CathyDingemanse** [comment]
> > Dat valt wel wel mee hoor....:-)
> 
> Maar wel genoeg om paginering nodig te maken? Heb je een indicatie over welke aantallen dit kan gaan?

100-200?

**Comment by fsamwel** [comment]
@rhengeveld @mhebbink-kad zoeken uit of ook last link kan leveren

**Comment by JohanBoer** [comment]
Deze wijziging is op branch Versie-1.2.0. gemerged (wat op 7 augustus volstrekt logisch was).
Deze is nu echter niet in Develop terecht gekomen. en waarschijnlijk ook nog niet geïmplementeerd.

**Comment by JohanBoer** [comment]
Niet meer nodig, kan naar done en gesloten worden.

**Comment by JohanBoer** [comment]
@CathyDingemanse @fsamwel @kad-hebbim @rhengeveld 
Er is nog geen paginering toegevoegd aan hypotheken. Wordt dat in versie 1.3 wel gewenst ? En kan dat ook ? Ook de vraag of de "last"-link opgeleverd kan worden staat hierin  nog open. (Marcel, Rik ?)

**Comment by fsamwel** [comment]
dit is m.i. in v1.3 nog niet gewenst. Dit wordt pas relevant wanneer we hypotheken kunnen zoeken op hypotheekhouder. Dan kun je heel veel hypotheken terugkrijgen. Zolang de hypotheken alleen vanuit een kadastraal object kunnen worden gehaald is het aantal hypotheken beperkt (tot het aantal hypotheken op één object).

**Comment by kad-hebbim** [comment]
> dit is m.i. in v1.3 nog niet gewenst. Dit wordt pas relevant wanneer we hypotheken kunnen zoeken op hypotheekhouder. Dan kun je heel veel hypotheken terugkrijgen. Zolang de hypotheken alleen vanuit een kadastraal object kunnen worden gehaald is het aantal hypotheken beperkt (tot het aantal hypotheken op één object).

Inderdaad. Wordt pas interessant als je zou kunnen zoeken op hypotheekhouder.
