### ISSUE TITLE
Als gemeente wil ik kadastrale onroerende zaken kunnen zoeken op de zakelijk gerechtigde ander niet-natuurlijk persoon

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#6]
...zodat ik de gegevens van deze kadastrale onroerende zaken kan gebruiken.

Op basis van de het Naam (van ANDER NIET NATUURLIJK PERSOON als de zakelijk gerechtigde) wordt een verzoekbericht opgesteld om KADASTRALE ONROERENDE ZAAKen te selecteren.

Zoekresultaat: De KADASTRALE ONROERENDE ZAAKen waarvan de naam van een zakelijke gerechtigde ANDER NIET NATUURLIJK PERSOON overeenkomt met het ingevulde zoek-argument uit het verzoekbericht worden opgenomen in het antwoordbericht.

**Acceptatiecriteria**
- [ ]  Het is mogelijk te zoeken (filteren) op de volgende eigenschap van de zakelijk gerechtigde van de kadastraal onroerende zaak:
    * naam
- [ ] Zoeken op de naam kan met een wildcard

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by CathyDingemanse** [comment]
ander natuurlijk persoon is kadaster natuurlijk persoon.
