### ISSUE TITLE
Graag bij beslagen en hypotheken aangeven op welke kadastraal onroerende zaak deze betrekking hebben

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#600]
...zodat invulling kan worden gegeven aan #130 #264 
#BUS6 https://gitlab.com/vng-realisatie/haal-centraal-brk-bevragen-afgeschermd/-/issues/6 
#BUS16 https://gitlab.com/vng-realisatie/haal-centraal-brk-bevragen-afgeschermd/-/issues/16

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by fsamwel** [comment]
@HildeVos @rhengeveld @mhebbink-kad als ik (met mijn veel te beperkte UML kennis) naar de imKad kijk lijkt het zo dat een zekerheidsstelling (hypotheek of beslag) op maximaal 1 kadastraal onroerende zaak kan rusten.
Via de aantekeningKadastraalObject lijkt er wel een 0..* relatie mogelijk

Hoe moet ik dit lezen? Kan het voorkomen dat op bijvoorbeeld één hypotheek een relatie naar meerdere appartementen of meerdere percelen worden geregistreerd?

**Comment by mhebbink-kad** [comment]
> @HildeVos @rhengeveld @mhebbink-kad als ik (met mijn veel te beperkte UML kennis) naar de imKad kijk lijkt het zo dat een zekerheidsstelling (hypotheek of beslag) op maximaal 1 kadastraal onroerende zaak kan rusten.
> Via de aantekeningKadastraalObject lijkt er wel een 0..* relatie mogelijk
> 
> Hoe moet ik dit lezen? Kan het voorkomen dat op bijvoorbeeld één hypotheek een relatie naar meerdere appartementen of meerdere percelen worden geregistreerd?

Een hypotheek rust inderdaad op maximaal 1 kadastraal onroerende zaak. 
Daarnaast bestaan er binnen de registratie Aantekening objecten die door bewaarders toegevoegd kunnen worden aan **of** 1 of meerdere onroerendezaken (middels de aantekeningKadastraalObject) **of** 1 of meer hypotheken/beslagen (middels de aantekeningZekerheidsstelling) **of** 1 of meer tenaamstellingen.

**Comment by fsamwel** [comment]
doorgevoerd in versie 1.2.0 specificaties met #606
