### ISSUE TITLE
Graag hypotheken en beslagen als resource ontsluiten

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#601]
...zodat identificaties in een dossier kunnen worden opgeslagen, en invulling kan worden gegeven aan user stories
https://gitlab.com/vng-realisatie/haal-centraal-brk-bevragen-afgeschermd/-/issues/16
https://gitlab.com/vng-realisatie/haal-centraal-brk-bevragen-afgeschermd/-/issues/6
https://gitlab.com/vng-realisatie/haal-centraal-brk-bevragen-afgeschermd/-/issues/7
https://gitlab.com/vng-realisatie/haal-centraal-brk-bevragen-afgeschermd/-/issues/18

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by CathyDingemanse** [comment]
Besluit 10/8: er komt een endpoint voor beide resources met een padparameter

**Comment by JohanBoer** [comment]
Maak een nieuwe issue om de nog niet geïmplementeerde maar wel gewenste functionaliteit in te borgen voor versie 1.3

**Comment by JohanBoer** [comment]
Ik heb deze issue het label  BRK bevragen 1.3 gegeven en terug gezet op ready maken.
