### ISSUE TITLE
Als medewerker wkpb wil een publiekrechtelijke beperking kunnen raadplegen

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#603]
...zodat ik kan bekijken welke andere kadastraal onroerende zaken bij de beperking betrokken zijn.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by fsamwel** [comment]
@CathyDingemanse is dit anders dan VNG-Realisatie/Haal-Centraal-BRK-bevragen#600 (die gaat over toevoegen gerelateerde onroerende zaken op een beslag)? 

Bedoel je hier raadplegen op beslagidentificatie en zonder kadastraalOnroerendeZaakIdentificatie (raadplegen enkele resource op uri)?

Dus /beslagen/{beslagidentificatie}

**Comment by CathyDingemanse** [comment]
Ik bedoel dat ik een publiekrechtelijke beperking als resource wil kunnen raadplegen, dus niet alleen via of als onderdeel van een kadastraal onroerende zaak. Omdat de beperking betrekking kan hebben op meer dan 1 KOZ, wil de gemeente weten welke dat zijn.

**Comment by fsamwel** [comment]
Ik denk dat de volgende toevoegingen nodig zijn om dit te realiseren:

1. Endpoint /publiekrechtelijkebeperkingen/{publiekrechtelijkebeperkingidentificatie} toevoegen

2. in _links van publiekrechtelijkebeperkingen toevoegen link "beperktOnroerendeZaken" en in resource property onroerendeZaakIdentificaties

**Comment by fsamwel** [comment]
@CathyDingemanse moeten we dan twee endpoints hebben voor het raadplegen van een publiekrechtelijke beperking?
- /kadastraalonroerendezaken/{kadastraalonroerendezaakidentificatie}/publiekrechtelijkebeperkingen/{publiekrechtelijkebeperkingidentificatie}
-  /publiekrechtelijkebeperkingen/{publiekrechtelijkebeperkingidentificatie}

Of kan de eerste vervallen?

**Comment by fsamwel** [comment]
/kadastraalonroerendezaken/{kadastraalonroerendezaakidentificatie}/publiekrechtelijkebeperkingen/{publiekrechtelijkebeperkingidentificatie}

dit vervalt. Wordt functioneel ingevuld met 
/publiekrechtelijkebeperkingen?kadastraalOnroerendeZaakIdentificatie={kadastraalOnroerendeZaakIdentificatie}
