### ISSUE TITLE
Waarom is werkingsgebied een groep in beperkingsgebied?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#609]
Beperkingsgebied is nu gedefinieerd met een identificatie en een werkingsgebied.
```
  "beperkingsgebied": {
    "identificatie": "string",
    "werkingsgebied": {
      "bgtObjectIdentificatie": "string",
      "bagObjectIdentificatie": "string",
      "kadastraalObjectIdentificatie": "string",
      "vrijeContour": { ... }
    }
```

1. Is er werkelijk behoefte aan de identificatie van een beperkingsgebied?

2. is het nodig onderscheid te maken tussen beperkingsgebied en werkingsgebied? (ik snap het onderscheid niet)

3. Ik begrijp nu niet wat beperkingsgebied en werkingsgebied zijn
    - In #570 is de definitie van werkingsgebied "Datgene waarop de beperking van toepassing is." Beperkingsgebied heeft geen description. Volgens imKad is werkingsgebied gekoppeld via relatie "isOntleendAan". Dat klinkt als iets anders dan "waarop ..van toepassing is".
    - Er zit maximaal 1 kadastraalObjectIdentificatie in. Dit suggereert dan dat een beperking op maximaal 1 object van toepassing is. 
    - We hebben in #603 juist onroerendeZaakIdentificaties toegevoegd om de verbinding te leggen met de (meerdere) objecten die hierdoor geraakt worden. Wat is werkingsgebied.kadastraalObjectIdentificatie ten wat is onroerendeZaakIdentificaties, dus wanneer wordt welke gevuld en wat betekent dat? 

4. de identificaties in werkingsgebied kunnen nu maximaal 1 keer voorkomen. Volgens imKad hebben deze een kardinaliteit 1 .. * (dus kunnen meerdere keren voorkomen)

**Comment by fsamwel** [comment]
@CathyDingemanse @HildeVos @mhebbink-kad kunnen jullie hier iets over zeggen?

**Comment by CathyDingemanse** [comment]
> Beperkingsgebied is nu gedefinieerd met een identificatie en een werkingsgebied.
> 
> ```
>   "beperkingsgebied": {
>     "identificatie": "string",
>     "werkingsgebied": {
>       "bgtObjectIdentificatie": "string",
>       "bagObjectIdentificatie": "string",
>       "kadastraalObjectIdentificatie": "string",
>       "vrijeContour": { ... }
>     }
> ```
> 
> 1. Is er werkelijk behoefte aan de identificatie van een beperkingsgebied?

Niet vanuit het gebruikersperspectief (nog nooit iemand over gehoord).

> 2. is het nodig onderscheid te maken tussen beperkingsgebied en werkingsgebied? (ik snap het onderscheid niet)

Ik denk het niet. Maar om daar zeker van te zijn moet ik eerst weten wat het verschil is. Misschien kan @HildeVos daar iets over zeggen.

> 3. Ik begrijp nu niet wat beperkingsgebied en werkingsgebied zijn

zie boven 

>    
>    * In #570 is de definitie van werkingsgebied "Datgene waarop de beperking van toepassing is." Beperkingsgebied heeft geen description. Volgens imKad is werkingsgebied gekoppeld via relatie "isOntleendAan". Dat klinkt als iets anders dan "waarop ..van toepassing is".
>    * Er zit maximaal 1 kadastraalObjectIdentificatie in. Dit suggereert dan dat een beperking op maximaal 1 object van toepassing is.

Dat lijkt mij niet correct. @HildeVos kun jij hier iets over zeggen?

We hebben in #603 juist onroerendeZaakIdentificaties toegevoegd om de verbinding te leggen met de (meerdere) objecten die hierdoor geraakt worden. Wat is werkingsgebied.kadastraalObjectIdentificatie ten wat is onroerendeZaakIdentificaties, dus wanneer wordt welke gevuld en wat betekent dat?

@HildeVos kun jij hier iets over zeggen?

> 4. de identificaties in werkingsgebied kunnen nu maximaal 1 keer voorkomen. Volgens imKad hebben deze een kardinaliteit 1 .. * (dus kunnen meerdere keren voorkomen)

**Comment by fsamwel** [comment]
@JohanBoer weet jij nog waarom dit issue op review staat? is er iets gewijzigd n.a.v. dit issue?

werkingsgebied / beperkingsgebied zitten nu niet meer in de API. Kan deze dus gewoon gesloten worden?

**Comment by fsamwel** [comment]
is verwijderd met pull request #668. Issue #670 voor eventueel in de toekomst alsnog toevoegen werkingsgebied / beperkingsgebied
