### ISSUE TITLE
Als medewerker Pandbrigade wil ik weten welke objecten een eigenaar nog meer in eigendom heeft in NL

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#61]
...zodat ik bij constatering van slecht gedrag bezoeken kan inplannen voor de andere objecten.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by JohanBoer** [comment]
Hoe wil je deze persoon identificeren ? Voor een ingeschreven persoon of een ingeschreven bedrijf (NHR) is dit nog te doen als je het BSN of het RSIN tot je beschikking hebt. Echter voor niet ingeschreven personen of niet ingeschreven bedrijven weet je wat hun identificatie is bij het kadaster. Deze userstory zou in 2 delen gesplitst kunnen worden: Op basis van BSN of RSIN opvragen welke objecten een eigenaar nog meer in bezit heeft. 

Daarnaast een zoek-functie op niet-ingeschreven personen en/of bedrijven die bij het kadaster geregistreerd staan en van daar af de objecten ophale waarvan die persoon eigenaar is. In die laatste situatie nog wel afspreken wat dan de identificatie i op basis waarvan die persoon of dat bedrij wordt geïdentificeerd (URI?)
