### ISSUE TITLE
links ontbreken in stukdeel resource

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#611]
De resource stukdeel heeft als response nu StukDeel. Daarin zitten geen _links. Wanneer je een stukdeel ophaalt op stukdeel identificatie, kan je dus niet vervolgens het bijbehorende stuk ophalen, bijvoorbeeld omdat je geïnteresseerd bent in het document (pdf).

Vanuit bijvoorbeeld een publiekrechtelijke beperking is er een verwijzing naar het stukdeel (isGebaseerdOpStukdeelIdentificatie en isVermeldInStukdeelIdentificaties), niet naar het stuk. Om bij het stuk te komen moet er dus een mogelijkheid zijn om vanuit het stukdeel de stukidentificatie en/of link op te halen.

@CathyDingemanse moet het daarnaast niet ook mogelijk zijn om vanuit de publiekrechtelijke beperking direct het stuk op te halen (isGebaseerdOpStukIdentificatie en isVermeldInStukIdentificaties)?

**Comment by CathyDingemanse** [comment]
Ik weet niet zeker of het hele concept "stukdeel" uberhaupt van toepassing is op een publiekrechtelijke beperking. Misschien wel als je vanuit de kadastraal onroerende zaak redeneert, maar ik kan mij voorstellen dat de gehele publiek rechtelijke beperking in een stuk, en niet in een stukdeel wordt vastgelegd. 
@HildeVos , kun jij ons daar meer over vertellen?

**Comment by JohanBoer** [comment]
Inmiddels zijn in de specificatie voor v1.3.0 in het endpoint stukdeel links opgenomen naar stuk en naar kadastraal onroerende zaken.
