### ISSUE TITLE
embedded stukken in publiekrechtelijkebeperkingen, hypotheken, beslagen, privaatrechtelijkebeperkingen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#622]
mogelijkheid toevoegen om stukken te embedden (met expand) op publiekrechtelijkebeperkingen, hypotheken, beslagen, privaatrechtelijkebeperkingen

**Comment by fsamwel** [comment]
moeten stukdelen ook te embedded zijn in de stuk resource? Daarin is nu namelijk wel een expand parameter opgenomen, maar is in het schema geen embedded gedefinieerd.

**Comment by fsamwel** [comment]
@CathyDingemanse moeten stukken ook embedded kunnen worden op privaatrechtelijke beperkingen? Had dat net niet opgeschreven

**Comment by CathyDingemanse** [comment]
Ja!

**Comment by JohanBoer** [comment]
Kunnen stukken en stukdelen wel in versie 1.3 ?

**Comment by JohanBoer** [comment]
- Stukdelen embedded opgenomen in /stukken/{stukidentificatie}
- Stukken embedded opgenomen in /publiekrechtelijkebeperkingen
- Stukken embedded opgenomen in /kadastraalonroerendezaken/{kadastraalonroerendezaakidentificatie}/hypotheken en /kadastraalonroerendezaken/{kadastraalonroerendezaakidentificatie}/hypotheken/{hypotheekidentificatie}
- Stukken embedded toegevoegd aan 
​/kadastraalonroerendezaken​/{kadastraalonroerendezaakidentificatie}​/beslagen en ​/kadastraalonroerendezaken​/{kadastraalonroerendezaakidentificatie}​/beslagen/{beslagidentificatie
- Stukken Embedded toegevoegd aan   /kadastraalonroerendezaken/{kadastraalonroerendezaakidentificatie}/privaatrechtelijkebeperkingen en  /kadastraalonroerendezaken/{kadastraalonroerendezaakidentificatie}/privaatrechtelijkebeperkingen/{privaatrechtelijkebeperkingidentificatie} n.a.v. #622

Stukken komen ook voor in de zakelijk gerechtigde en in de kadastraal onroerende zaak. @CathyDingemanse en @fsamwel Ik veronderstel dat ze daar ook embedded opgenomen moeten worden of zie ik dat verkeerd ? . Ik heb daar de stukken ook embedded opgenomen. Als dat niet gewenst is draai ik dat terug.

**Comment by fsamwel** [comment]
Hebben we in discussie op 17 november (vorige week) niet besloten om stukken niet te embedden? Zo heb ik dat toen opgeschreven. Dus ik dacht dat dit issue daarmee achterhaald is.

@CathyDingemanse Is er werkelijk zoveel behoefte aan het meeladen van stukken (zonder de stukdelen en zonder de blob) in de verschillende resources? We kunnen nu bijvoorbeeld ook geen hypotheken of beslagen meeladen bij een onroerende zaak.

Ik denk trouwens dat het embedden van stukdelen bij een stuk wel logisch is. (en andersom wellicht ook)

**Comment by CathyDingemanse** [comment]
Ja, ik denk dat je gelijk hebt. In de meeste gevallen wil men niet perse een stuk raadplegen. We kunnen het altijd nog toevoegen als daar toch vraag naar blijkt te zijn. @JohanBoer, zou je dit idd kunnen terugdraaien?

**Comment by JohanBoer** [comment]
Even scherp maken. 
- [ ] Ik haal overal het embedden van stukken weer weg. 
- [ ] Bij Stukken blijven de stukdelen wel embedde aanwezig. 
- [ ] Vraag is dan nog of Frank's voorstel om stukken te embedden bij stukdelen gewenst is ? @CathyDingemanse

**Comment by CathyDingemanse** [comment]
Prima!
