### ISSUE TITLE
Geen consequente toepassing van  Accept-Crs en Content-Crs

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#633]
De API heeft nu niet consequente en niet complete definitie op resources/endpoints waarbij er geometrie in de response kan zitten.

Het gaat om:
1. request header Accept-Crs
2. response header Content-Crs
3. response 412 (wanneer geen Accept-Crs wordt meegegeven)

De BRK API werkt anders dan de BAG API op dit onderwerp. In de BAG API is Accept-Crs verplicht wanneer er geo in de response zit, omdat de NL API strategie default anders is dan onze huidige enig ondersteunde variant (RD). In de BRK API is Accept-Crs niet verplicht.
- BAG geeft 412 bij ontbreken Accept-Crs (ziet conform NL API strategie WGS84 als default)
- BRK geeft geen fout bij ontbreken Accept-Crs (gebruikt enige ondersteunde Crs RD als default)

De definitie van accept-Crs en content-crs is niet consequent doorgevoerd in de BRK API specificaties:
| branch | endpoint of resource | Accept-Crs en Content-Crs gespecificeerd |
| --- | --- | --- |
| master | kadastraalonroerendezaken | Ja |
| master | zakelijkgerechtigden | Nee |
| feature/hypotheken | /kadastraalonroerendezaken/{kadastraalonroerendezaakidentificatie}/hypotheken | Nee |
| feature/hypotheken | /hypotheken/{hypotheekidentificatie} | Ja |
| feature/hypotheken | /hypotheken | Nee |
| feature/beslagen | /kadastraalonroerendezaken/{kadastraalonroerendezaakidentificatie}/beslagen | Nee |
| feature/beslagen | /beslagen/{beslagidentificatie} | Ja |
| feature/beslagen | /beslagen | Nee |
| feature/privaat-rechtelijke-beperkingen | privaatrechtelijkebeperkingen | Nee |
| feature/publiek-rechtelijke-beperkingen | publiekrechtelijkebeperkingen | Nee |

Voorstel:
- verschil in verplichten accept-crs nu niet oplossen, want zou breaking change leveren die gebruikers weinig oplevert
- specificeren van Accept-Crs en Content-Crs op alle endpoints waar in de response geometrie kan zitten (zie tabel hierboven)

**Comment by fsamwel** [comment]
alle ontbrekende Accept-Crs en Content-Crs (volgens tabel bovenaan in issue) zijn toegevoegd in pull requests op betreffende feature-branches

**Comment by JohanBoer** [comment]
De huidige stand van zaken is volgens mij als volgt: 

| endpoint of resource | Accept-Crs en Content-Crs gespecificeerd | in 1.2.0 ? | Geo aanwezig in response| 
| --- | --- | --- | --- |
| kadastraalonroerendezaken | Ja | Ja |  Ja |
| kadastraalonroerendezaken/{id} | Ja | Ja |  Ja |
| .../zakelijkgerechtigden | Ja | Ja |  Ja (deprecated) |
| .../zakelijkgerechtigden/{id} | Ja | Ja |  Ja (deprecated |
|.../beslagen | **Ja** | Ja |  Nee |
|.../beslagen/{id}  | **Ja** | Ja |  Nee |
| .../hypotheken | **Ja** | Ja |  Nee |
| .../hypotheken/id} | **Ja** | Ja |  Nee |
| ../privaatrechtelijkebeperkingen | **Ja** | Ja |  Nee |
| ../privaatrechtelijkebeperkingen/{id} | **Ja** | Ja |  Nee |
|publiekrechtelijkebeperkingen | Nee | Nee |  Nee (toekomst wel) |

Bij de kadaster persoon endpoints en bij de stukken en stukdelen is er terecht geen Accept-crs en Content-Crs gespecificeerd.

Vraag is of we nu bij de endpoints waarbij in de resource geen geo hebben zitten, maar wel de Accept-Crs en Conten-Crs hebben gespecificeerd die weg kunnen halen. Als een consumer deze parameter standaard vult wanneer die er is levert weghalen een breaking change op volgens mij. 
Met andere woorden, volgens mij moeten we het laten zoals het nu is. 
@MelvLee @fsamwel @rhengeveld @kad-hebbim Hoe denken jullie daarover ?

**Comment by MelvLee** [comment]
Volgens mij is het weghalen van Accept-Crs geen breaking change. Een oude consumer zou het nog kunnen sturen, maar als de provider idg geen fout gooit, dan blijft die ook gewoon werken.
Het weghalen van de Content-Crs kan wel een breaking change zijn. De consumer zou die uit kunnen lezen, maar ik betwijfel het omdat er nu maar één waarde wordt ondersteund. Maar als we het zeker willen weten, dan moeten we de consumers vragen. We weten wie die zijn, want die hebben allemaal een api-key

**Comment by JohanBoer** [comment]
Nu wordt alleen de content-crs geleverd als er daadwerkelijk geo in de response zit. Dat betekent dat het verwijderen van de accept-crs en de conten-crs bij de endpoints waar geen geo in zit geen breaking cahnge is. 
We halen bij de betreffende endpoints de accept-crs en de content crs weg.
