### ISSUE TITLE
Als PO wil ik een nieuwe versie van de resourcedefinitie op basis van het objecten-user stories overzicht

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#64]
...zodat er een tweede versie van de OAS specificatie kan worden gedefinieerd.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [x] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by JanWillemKooi** [comment]
N,a.v. call van 17 apr: OA spec staat op GitHub

**Comment by JohanBoer** [comment]
Er is een specifieke user story voor Sprint 4 opgevoerd (#93 ) Voor elke volgende sprint leveren we een specifieke user story voor de gewenste content van de OAS3 op.
