### ISSUE TITLE
endpoints /hypotheken /hypotheken/{hypotheekidentificatie moeten uit release 1.2 worden gehaald

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#645]
omdat deze niet op korte termijn geleverd kunnen worden

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by fsamwel** [comment]
/hypotheken/{hypotheekidentificatie moet worden gewijzigd naar 
/kadastraalonroerendezaken/{kadastraalonroerendezaakidentificatie}/hypotheken/{hypotheekidentificatie}

**Comment by kad-hebbim** [comment]
**Stappen:**
- nieuwe branch `openapi-12` aangemaakt o.b.v.  branch `develop`
- deze branch gemerged met branch `feature/hypotheken`
- aanpassingen doorgevoerd voor v1.2.0
