### ISSUE TITLE
Uitzoeken op welke manier hypotheken en beslagen kunnen worden gezocht op hypotheekhouder c.q. beslaglegger

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#646]
...zodat hiervoor de impact kan worden bepaald en in een planning kan worden opgenomen.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by JohanBoer** [comment]
@HildeVos en @kad-hebbim : Volgens mij hebben jullie hier al uitsluitsel op. Zouden jullie dat hier willen opnemen in het commentaar ? Bij mijn beste weten gaat die niet meegenomen worden in versie 1.3 (of welke versie dan ook. omdat het niet kan. 
Dan is dat gedocumenteerd.

**Comment by kad-hebbim** [comment]
Deze informatie wordt niet geregistreerd in de BRK en is dus niet op te vragen.
