### ISSUE TITLE
endpoints /beslagen en /beslagen/{beslagidentificatie} moeten uit versie 1.2 worden verwijderd

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#647]
omdat deze niet op korte termijn kunnen worden geleverd.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by fsamwel** [comment]
/beslagen/{beslagidentificatie} moet worden gewijzigd naar 
/kadastraalonroerendezaken/{kadastraalonroerendezaakidentificatie}/beslagen/{beslagidentificatie}

**Comment by kad-hebbim** [comment]
**Stappen:**
- branch `feature/openapi-12` gemerged met branch `feature/beslagen`
- aanpassingen doorgevoerd voor v1.2.0 in branch `feature/openapi-12`
