### ISSUE TITLE
BedragVordering en bedragZekerheidsstelling toevoegen aan respectievelijk beslag en hypotheek

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#648]
en niet in het stukdeel. Check ook andere informatie in het stukdeel

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by JohanBoer** [comment]
Bedrag zekeheidstelling en hypotheekbedraag gaan we opnemen in de resources beslag en hypotheek. Marcel geeft aan dat dit bedrag opgehaald kan worden bij het stukdeel in de backend.

**Comment by JohanBoer** [comment]
Deze is gekoppeld aan #601. Ook op versie 1.3 gezet en teruggeplaatst naar ready maken.

**Comment by JohanBoer** [comment]
Onterecht op versie 1.3 gezet. Terug naar v1.2

**Comment by fsamwel** [comment]
betreft dus aan /beslagen toevoegen van bedragVordering
en aan /hypotheken toevoegen van bedragZekerheidsstelling

**Comment by rhengeveld** [comment]
Het lijkt erop dat @JohanBoer de velden `bedragVordering` en `bedragZekerheidsstelling` vanuit pull request #692 nog niet gemerged had met branch `develop`. Gezien het een kleine wijziging is heb ik de vrijheid genomen om dit d.m.v. pull request #716 alsnog te mergen met branch `develop`. 

Ik ga deze nieuwe velden implementeren 🙂 

---

➡️ **Het bedrag van beslag zit inderdaad in stukdeel**
![image](https://user-images.githubusercontent.com/1228038/96568567-61e3a480-12c8-11eb-8d63-49756a782757.png)

➡️ **Het bedrag van een hypotheek zit inderdaad ook in stukdeel**
![image](https://user-images.githubusercontent.com/1228038/96568726-8d668f00-12c8-11eb-9fad-25087a4c42ac.png)

_Bron [IMKAD](https://www.kadaster.nl/schemas/review-imkad/20190901/cat/imkad-IMKAD-2-20190901.office.respec.html)_

**Comment by rhengeveld** [comment]
**Geïmplementeerd en beschikbaar op de acceptatieomgeving** ✔️
