### ISSUE TITLE
reden doorhaling teboekstelling uit stukdelen verwijderen  

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#649]
omdat op schepen van toepassing is. Kan worden toegevoegd als we schepen gaan doen

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [x] Open API specificatie
- [x] gegenereerde code
- [x] testgevallen
- [ ] referentie-implementatie

**Comment by JohanBoer** [comment]
redenDoorhalingTeboekstelling is uit de specificatie verwijderd.
