### ISSUE TITLE
selflinks toevoegen bij privaatrechtelijke beperking, beslagen, en hypotheken

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#650]
...zodat het setje endpoint, identificatie en self link compleet is voor deze subresources

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by kad-hebbim** [comment]
**Stappen:**
- aanpassingen doorgevoerd voor de self-links in v1.2.0 in branch `feature/openapi-12`
