### ISSUE TITLE
Uitzoeken hoe lang de migratie publiekrechtelijke bep duurt 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#651]
...zodat we kunnen bepalen of het de moeite waard is om de oude beperkingen te mappen op het nieuwe endpoint.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by HildeVos** [comment]
Antwoord PO Beter Kenbaar: Eind 2020 moeten allen gemeenten over zijn en voor Q1 2021 hebben we de niet gemeenten gepland. M.a.w. Q2 2021 bevat de BRK-PB alle publiekrechtelijke beperkingen en wordt er niets meer ontsloten uit de LV-WKPB of KOERS.

**Comment by fsamwel** [comment]
De API levert nu zowel de oude als de nieuwe, hoeft er niet uit te worden gehaald
