### ISSUE TITLE
stukken en stukdelen uit 1,2 halen

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#653]
...zodat [vul aan].

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by fsamwel** [comment]
Inclusief alle identificaties, links en embedded
In alle 1.2 branches (die wel naar 1.2 gaan):
- feature/hypotheken
- feature/beslagen
- feature/privaat-rechtelijke-beperkingen
- feature/publiek-rechtelijke-beperkingen

**Comment by fsamwel** [comment]
hebben we net niet afgesproken dat @kad-hebbim deze wijziging zal doorvoeren?

**Comment by kad-hebbim** [comment]
Ik wil dit wel oppakken inderdaad. Als @JohanBoer dat uiteraard goed vindt.

**Comment by kad-hebbim** [comment]
**Stappen:**
- aanpassingen doorgevoerd voor verwijderen stukken/stukdelen van privaatrechtelijkebeperkingen in v1.2.0 in branch `feature/openapi-12`
