### ISSUE TITLE
verwijderen parameters nummeraanduidingIdentificatie en locatie uit /publiekrechtelijkebeperkingen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#654]
dit kan nog niet worden geleverd in release 1.2

**Comment by JohanBoer** [comment]
Deze op done en een issue inschieten om de niet geïmplementeerde functionaliteit in versie 1.3. te krijgen ?

**Comment by fsamwel** [comment]
@JohanBoer heb je al gevonden of er een issue is voor parameters nummeraanduidingIdentificatie en locatie in /publiekrechtelijkebeperkingen?

**Comment by JohanBoer** [comment]
Dit punt is geborgd in user story #602

**Comment by kad-hebbim** [comment]
> Dit punt is geborgd in user story #602

@JohanBoer: kan deze dan niet gesloten worden, aangezien dit geborgd is in een andere user story. misschien ook label 1.3 er dan afhalen. We doen hier niks mee in 1.3.
