### ISSUE TITLE
Hypotheeknemer of hypotheekhouder

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#659]
In /kadastraalonroerendezaken/{kadastraalonroerendezaakidentificatie}/hypotheken staat in de description: "(...) met bijbehorende **hypotheekhouder**(s). Een hypotheekhouder vestigt als geldverstrekker een recht van hypotheek als zekerheid voor de lening"

In /kadastraalonroerendezaken/{kadastraalonroerendezaakidentificatie}/hypotheken/{hypotheekidentificatie} staat in de description niks hierover.

In component Hypotheek staat in de description "(...) het eigendomsrecht van de hypotheekgever als onderpand voor een geldlening of krediet bij de hypotheeknemer (geldverstrekker)"
En deze bevat een property "hypotheekhouders", waarbij een description ontbreekt.

Hier wordt dus voor hetzelfde (de geldverstrekker) twee termen gebruikt: hypotheeknemer en hypotheekhouder. Beter is het om één term hiervoor te gebruiken.
@CathyDingemanse heb jij een voorkeur voor hypotheeknemer of hypotheekhouder?

Ook moet m.i. een description worden toegevoegd bij property "hypotheekhouders" (die misschien "hypotheeknemers" wordt)

**Comment by CathyDingemanse** [comment]
hypotheekhouder graag!

**Comment by JohanBoer** [comment]
Kan naar Done
