### ISSUE TITLE
Expanded zakelijkgerechtigden óók filteren op TypeGerechtigde?

### ISSUE THREAD

**Issue by rhengeveld** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#675]
Er zijn tenminste 2 routes beschikbaar voor het opvragen van zakelijkgerechtigden  

(1) in het pad bij een onroerende zaak:
```
"/kadastraalonroerendezaken/76870482570000/zakelijkgerechtigden?type=erfpachter"
```
(2) als _expand_ bij een onroerende zaak:
```
"/kadastraalonroerendezaken?persoon__identificatie=520264111&expand=zakelijkGerechtigden&zakelijkGerechtigde__type=erfpachter"
```

De voorbeelden bevatten ook een filter op het type _"erfpachter"_. In het 1e voorbeeld worden de zakelijkgerechtigden gefilterd op het type _"erfpachter"_; hebben ze niet het type dan komen ze niet in het resultaat.

In het 2e voorbeeld worden enkel de onroerende zaken gefilterd; deze zijn in het resultaat aanwezig als ze tenminste 1 zakelijkgerechtigde bevatten van de gevraagde persoon en het type _"erfpachter"_. **De zakelijkgerechtigden bij de onroerende zaak worden zelf vervolgens niet gefilterd.** Hierdoor is het mogelijk dat het resultaat zakelijkgerechtigden bevat die **_niet_** het gevraagde type hebben. 

**Is dit zoals het hoort of dienen de zakelijkgerechtigden in het 2e voorbeeld óók uit het resultaat gefilterd te worden?**

Voorbeeld met _"eigenaar_" in resultaat van 2e voorbeeld:
```json
{
  "_links": {
    "self": {
      "href": "/kadastraalonroerendezaken?persoon__identificatie=520264111&expand=zakelijkGerechtigden&zakelijkGerechtigde__type=erfpachter"
    }
  },
  "_embedded": {
    "kadastraalOnroerendeZaken": [
      {
        "identificatie": "17620235170000",
        "domein": "NL.IMKAD.KadastraalObject",
        "type": "perceel",
        "_links": {
          "self": {
            "href": "/kadastraalonroerendezaken/17620235170000"
          }
        },
        "_embedded": {
          "zakelijkGerechtigden": [
            {
              "identificatie": "10908153",
              "type": "eigenaar",
              "knip-andere-velden": "<knip>"
            },
            {
              "identificatie": "10908151",
              "type": "erfpachter",
              "knip-andere-velden": "<knip>"
            },
            {
              "identificatie": "10908152",
              "type": "erfpachter",
              "knip-andere-velden": "<knip>"
            }
          ]
        }
      }
    ]
  }
}
```

In het 1e voorbeeld is het mogelijk een onroerende zaak terug te krijgen met tenminste 1 zakelijkgerechtigde die aan het type voldoet én mogelijk andere zakelijkgerechtigden die **niet** aan het type voldoen.

**Comment by rhengeveld** [comment]
Ik heb deze op `v1.2` gezet, omdat ik hier nu mee bezig ben en dit snel genoeg moet kunnen oplossen (als aanpassing nodig is) 🙂

**Comment by fsamwel** [comment]
> In het 2e voorbeeld worden enkel de onroerende zaken gefilterd; deze zijn in het resultaat aanwezig als ze tenminste 1 zakelijkgerechtigde bevatten van de gevraagde persoon en het type "erfpachter". De zakelijkgerechtigden bij de onroerende zaak worden zelf vervolgens niet gefilterd. Hierdoor is het mogelijk dat het resultaat zakelijkgerechtigden bevat die niet het gevraagde type hebben.

> Is dit zoals het hoort of dienen de zakelijkgerechtigden in het 2e voorbeeld óók uit het resultaat gefilterd te worden?

Dit is hoe het hoort. Bij de resource /kadastraalonroerendezaken werkt de query parameter zakelijkGerechtigde__type alleen op de selectie van kadastraalonroerendezaken.

**Comment by rhengeveld** [comment]
Prima, bedankt voor de verduidelijking, dan laat ik het zo 👍
