### ISSUE TITLE
identificatie hypotheekhouders bevat domein

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#676]
/kadastraalonroerendezaken/76870487970000/hypotheken
bevat in het antwoord:
```
"hypotheekhouders": [
  {
    "identificatie": "NL.IMKAD.Persoon.71291440",
```

hier had ik verwacht:
```
"hypotheekhouders": [
  {
    "identificatie": "71291440",
```

**Comment by fsamwel** [comment]
idem voor beslagleggers: /kadastraalonroerendezaken/17150075470000/beslagen/95377751

 ```
"beslagleggers": [
  {
    "identificatie": "NL.IMKAD.Persoon.71291493",
```

**Comment by rhengeveld** [comment]
Opgelost en beschikbaar op acceptatie ✔️ 

* Identificatie bevat geen domein
* BSN is identificatie bij type "ingeschreven_natuurlijk_persoon"
* RSIN is identificatie bij type "ingeschreven_niet_natuurlijk_persoon"
