### ISSUE TITLE
links vanuit kadastraalonroerendezaken naar hypotheken, beslagen, privaatrechtelijkebeperkingen ontbreken

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#677]
/kadastraalonroerendezaken/76870487970000/hypotheken geeft 1 hypotheek terug (35052041)
/kadastraalonroerendezaken/76870487970000 bevat in _links geen hypotheken en bevat geen hypotheekIdentificaties.

/kadastraalonroerendezaken/17150075470000/beslagen geeft 1 beslag terug (95377751)
/kadastraalonroerendezaken/17150075470000 bevat in _links geen beslagen en bevat geen beslagIdentificaties

/kadastraalonroerendezaken/76870488070000/privaatrechtelijkebeperkingen geeft 1 privaatrechtelijkeBeperking (30336966)
/kadastraalonroerendezaken/76870488070000 bevat in _links geen privaatrechtelijkeBeperkingen en bevat geen privaatrechtelijkeBeperkingIdentificaties

**Comment by rhengeveld** [comment]
Goed punt! Ik zal kijken of ik deze in de _links_ van een kadastraal onroerende zaak kan krijgen

**Comment by rhengeveld** [comment]
Opgelost en staat op acceptatie ✔️ 

```
/kadastraalonroerendezaken/17150075470000?fields=links
```
```json
{
    "identificatie": "17150075470000",
    "domein": "NL.IMKAD.KadastraalObject",
    "type": "perceel",
    "zakelijkGerechtigdeIdentificaties": [
        "1002195641"
    ],
    "hypotheekIdentificaties": [
        "15479389"
    ],
    "beslagIdentificaties": [
        "95377751"
    ],
    "_links": {
        "self": {
            "href": "/kadastraalonroerendezaken/17150075470000?fields=links"
        },
        "zakelijkGerechtigden": [
            {
                "href": "/kadastraalonroerendezaken/17150075470000/zakelijkgerechtigden/{zakelijkGerechtigdeIdentificaties}",
                "templated": true
            }
        ],
        "hypotheken": [
            {
                "href": "/kadastraalonroerendezaken/17150075470000/hypotheken/{hypotheekIdentificaties}",
                "templated": true
            }
        ],
        "beslagen": [
            {
                "href": "/kadastraalonroerendezaken/17150075470000/beslagen/{beslagIdentificaties}",
                "templated": true
            }
        ]
    }
}
```
