### ISSUE TITLE
omschrijving hypotheekhouder wijkt af

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#678]
/kadastraalonroerendezaken/76870487970000/hypotheken/35052041
geeft:
```
                "hypotheekhouders": [
                    {
                        "identificatie": "71291440",
                        "omschrijving": "Bankbedrijf ROTTERDAM",
                        "type": "kadaster_niet_natuurlijk_persoon"
                    }
                ],
```

/kadasternietnatuurlijkpersonen/71291440
geeft:
```
    "identificatie": "71291440",
    "omschrijving": "Bankbedrijf",
```

de omschrijving van de niet-natuurlijk persoon in hypotheekhouders is dus anders dan de omschrijving bij het raadplegen van deze persoon zelf.
zo te zien wordt de statutaire zetel eraan toegevoegd. Ik zie dat dit nu ook bij zakelijkgerechtigden in persoon gebeurt (nieuw t.ov. release 1.1)

**Comment by rhengeveld** [comment]
De statutaire zetel is inderdaad een toevoeging sinds 1.1. Dit werd opgemerkt als een mapping _bug_ bij hypotheekhouders en beslagleggers. Je hebt gelijk dat de mapping op dit punt inconsistent is 🤔 

**`PersoonBeperkt`** volgens [interne] mapping specificatie:
![image](https://user-images.githubusercontent.com/1228038/94930240-66d1e700-04c6-11eb-945f-13e27d28c127.png)

De zetel zie ik echter _**niet**_ in de mapping specificatie van **`KadasterNietNatuurlijkPersoon`**:
![image](https://user-images.githubusercontent.com/1228038/94930176-5883cb00-04c6-11eb-9f89-6ea3982a78e3.png)

Ik zal met @kad-hebbim overleggen wat correct is en dit corrigeren

**Comment by kad-hebbim** [comment]
De mapping van PersoonBeperkt is niet correct. Statutaire zetel moet niet getoond worden inderdaad (zoals het al is in 1.1). Zal onze interne documentatie hierop aanpassen.

**Comment by rhengeveld** [comment]
Ok, dan zal ik de implementatie hierop aanpassen 👍

**Comment by rhengeveld** [comment]
Implementatie aangepast ... [acceptatieomgeving update komt eraan]
