### ISSUE TITLE
grondslag publiekrechtelijkebeperking is geen waarde uit waardelijst

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#679]
/publiekrechtelijkebeperkingen?kadastraalOnroerendeZaakIdentificatie=76870487970000

geeft publiekrechtelijke beperking 3394 met als grondslag:
```
"grondslag": {
  "code": "GG",
  "waarde": "Aanwijzing gemeentelijk monument (voorbescherming, aanwijzing, afschrift)"
}
```

Volgens het imKad wordt grondslag gevuld uit de waardelijst https://www.kadaster.nl/schemas/waardelijsten/AardAantekening/

Hierin komt de waarde "GG" niet voor.

**Comment by rhengeveld** [comment]
Ik doe geen transformatie van [tenminste deze] codes en waardes; dit komt direct vanuit de bron 😇 

Het lijkt er echter erop dat waardelijst [GrondslagBRK-PB](https://www.kadaster.nl/schemas/waardelijsten/GrondslagBRK-PB/index.html) wordt gebruikt. Is dat een issue @fsamwel en kan jij dit bevestigen @kad-hebbim?

**Comment by fsamwel** [comment]
In de [imKad](https://developer.kadaster.nl/schemas/imkad/20200130/cat/imkad-IMKAD-2-20190901.office.respec.html#global_class_PubliekrechtelijkeBeperking_GrondslagBRKPB), wat volgens mij dezelfde versie is die jij noemt, zie ik een verwijzing naar een andere tabel, namelijk [AardAantekening](http://www.kadaster.nl/schemas/waardelijsten/AardAantekening).

Dat wordt ook bevestigd bij een andere publiekrechtelijke beperking (90043914), die ik krijg met /publiekrechtelijkebeperkingen?kadastraalOnroerendeZaakIdentificatie=22310827210003. Daar zie ik:
```
"grondslag": {
  "code": "173",
  "waarde": "Besluit op basis van Monumentenwet 1988"
},
```

Het lijkt er dus op dat in de ene publiekrechtelijke beperking grondslag is gevuld uit een andere tabel dan in de andere publiekrechtelijke beperking.

**Comment by kad-hebbim** [comment]
Dit klopt ook aangezien de PBs op dit moment nog via twee wegen gevuld kunnen zijn:
1. Op de 'oude' manier via een Aantekening welke als grondslag een verwijzing heeft naar de tabel [AardAantekening](https://www.kadaster.nl/schemas/waardelijsten/AardAantekening/).
2. Op de 'nieuwe' manier (waar elke gemeente begin volgend jaar op aangesloten zullen zijn) via een PubliekrechtelijkeBeperking welke als grondslag een verwijzing heeft naar de tabel [Grondslag](https://www.kadaster.nl/schemas/waardelijsten/GrondslagBRK-PB/)

Overigens komen de waarden in deze twee waardenlijsten wel overeen.

**Comment by kad-hebbim** [comment]
Wel zie ik dat er voor dit testgeval nog gebruik gemaakt is van een waarde die niet meer geldig is; dit zal ik aanpassen.
