### ISSUE TITLE
persoon waarnaar verwezen wordt in link bestaat niet

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#680]
/kadastraalonroerendezaken/56020234070000/hypotheken/55224371
geeft een link:
                    "hypotheekhouders": [
                        {
                            "href": "/kadasternietnatuurlijkpersonen/24268006"
                        }
                    ]

Deze persoon is een "ingeschreven_niet_natuurlijk_persoon", maar aangezien er nog geen link naar het HR kan worden gegeven, wordt terecht een link naar de kadasternietnatuurlijkpersonen gegeven.

/kadasternietnatuurlijkpersonen/24268006 echter geeft een 404:
```
{
    "type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_NotFound",
    "title": "Opgevraagde resource bestaat niet.",
    "status": 404,
    "detail": "Not Found.",
    "instance": "/kadasternietnatuurlijkpersonen/24268006",
    "code": "notFound"
}
```

**Comment by kad-hebbim** [comment]
Mapping ontbrak. 
Aangepast.

**Comment by fsamwel** [comment]
Er zijn nog meer personen waarnaar wel wordt verwezen vanuit zakelijkgerechtigden, maar die niet bestaan als persoon:
/kadasternatuurlijkpersonen/71303567 (/kadastraalonroerendezaken/65490485370000/zakelijkgerechtigden/150561361)
/kadasternatuurlijkpersonen/71303568 (/kadastraalonroerendezaken/65490485370000/zakelijkgerechtigden/150561360)
/kadasternatuurlijkpersonen/71303569 (/kadastraalonroerendezaken/24780711870000/zakelijkgerechtigden/91205343)
/kadasternatuurlijkpersonen/71303570 (/kadastraalonroerendezaken/17150075470000/zakelijkgerechtigden/1002195641)
/kadasternatuurlijkpersonen/71303573 (/kadastraalonroerendezaken/17500393970000/zakelijkgerechtigden/10848244)
/kadasternatuurlijkpersonen/71303576 (/kadastraalonroerendezaken/22360467970000/zakelijkgerechtigden/90317712)
/kadasternatuurlijkpersonen/71303577 (/kadastraalonroerendezaken/19560032970000/zakelijkgerechtigden/11225310)
/kadasternatuurlijkpersonen/71303578 (/kadastraalonroerendezaken/17550448670000/zakelijkgerechtigden/10872286)

kan de mappen hiervoor ook aangelegd worden

**Comment by kad-hebbim** [comment]
> Er zijn nog meer personen waarnaar wel wordt verwezen vanuit zakelijkgerechtigden, maar die niet bestaan als persoon:
> /kadasternatuurlijkpersonen/71303567 (/kadastraalonroerendezaken/65490485370000/zakelijkgerechtigden/150561361)
> /kadasternatuurlijkpersonen/71303568 (/kadastraalonroerendezaken/65490485370000/zakelijkgerechtigden/150561360)
> /kadasternatuurlijkpersonen/71303569 (/kadastraalonroerendezaken/24780711870000/zakelijkgerechtigden/91205343)
> /kadasternatuurlijkpersonen/71303570 (/kadastraalonroerendezaken/17150075470000/zakelijkgerechtigden/1002195641)
> /kadasternatuurlijkpersonen/71303573 (/kadastraalonroerendezaken/17500393970000/zakelijkgerechtigden/10848244)
> /kadasternatuurlijkpersonen/71303576 (/kadastraalonroerendezaken/22360467970000/zakelijkgerechtigden/90317712)
> /kadasternatuurlijkpersonen/71303577 (/kadastraalonroerendezaken/19560032970000/zakelijkgerechtigden/11225310)
> /kadasternatuurlijkpersonen/71303578 (/kadastraalonroerendezaken/17550448670000/zakelijkgerechtigden/10872286)
> 
> kan de mappen hiervoor ook aangelegd worden

@fsamwel: dit zijn toch allemaal ingeschreven natuurlijk personen die niet raadpleegbaar zijn via /kadasternatuurlijkpersoon/{id}. Daarvoor moet men naar de BRP.

**Comment by fsamwel** [comment]
@kad-hebbim 
> dit zijn toch allemaal ingeschreven natuurlijk personen die niet raadpleegbaar zijn via /kadasternatuurlijkpersoon/{id}

in het antwoord is deze link opgenomen. Als de persoon niet op die url raadpleegbaar is, moet de link ook niet worden opgenomen.

Soms werkt deze link wel. Bijvoorbeeld /kadastraalonroerendezaken/76870482570000/zakelijkgerechtigden/20170718
bevat:
```
    "persoon": {
        "identificatie": "999991905",
        "omschrijving": "Linda Haglund",
        "type": "ingeschreven_natuurlijk_persoon"
    },
    "_links": {
        "self": {
            "href": "/kadastraalonroerendezaken/76870482570000/zakelijkgerechtigden/20170718"
        },
        "persoon": {
            "href": "/kadasternatuurlijkpersonen/71303565"
        }
    }
```
En die link persoon "/kadasternatuurlijkpersonen/71303565" volgen levert wel een persoon. 

Uit het feit dat er bij de genoemde personen een url is, met daarin een kadasterpersoon identificatie, zou  ik verwachten dat de kadasterpersoon ook bestaat.

**Comment by kad-hebbim** [comment]
@fsamwel: Blijkbaar is daar nog wel mapping voor gemaakt in een grijs verleden. Zal dit rechttrekken, zodat een ingeschreven natuurlijkpersoon niet meer raadpleegbaar is via zijn kadasterpersoonidentificatie. Dit, om verwarring te voorkomen.
 
@rhengeveld: zou jij ervoor kunnen zorgen dat de link naar een ingeschreven persoon niet getoond wordt in het bericht. Zoals het voorheen eigenlijk al werkte.

**Comment by rhengeveld** [comment]
Gewijzigd, acceptatieomgeving update komt eraan
