### ISSUE TITLE
Zelfde hypotheekhouder heeft twee hypotheken op volledige object

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#681]
/kadastraalonroerendezaken/19560032970000/hypotheken

Dit levert twee hypotheken, beide met als hypotheekhouder "Bankbedrijf van vrucht GRAVE", en beide met aandeelInBetrokkenRecht 1/1 en beide met omschrijvingBetrokkenRecht "Eigendom"

Dat kan denk ik niet? Wordt hier een historische hypotheek getoond?

**Comment by kad-hebbim** [comment]
Fout in de mapping waardoor deze hypotheekhouder 2 hypotheken kreeg ipv 1. 
Aangepast.

**Comment by fsamwel** [comment]
het verwijst nu naar twee verschillende hypotheekhouders. Maar het blijft vreemd dat er twee hypotheken zijn die beide rusten op 100% van het eigendom. Technisch wellicht niet fout, maar als testwaarde voor aansluiters denk ik ingewikkeld om te begrijpen.

**Comment by fsamwel** [comment]
@kad-hebbim kan je nog iets met mijn bovenstaande opmerking? Of is dit een realistische situatie?

**Comment by kad-hebbim** [comment]
@fsamwel: dit is een voorbeeldsituatie uit productie. Heb de vraag bij Thijs neergelegd hoe dit nu precies geïnterpreteerd moet worden. Ze hebben immers alletwee wel een ander bedrag hangen aan de hypotheek (dit zie je nu alleen nog niet, aangezien dit in een stukdeel staat).

**Comment by kad-hebbim** [comment]
@fsamwel: Antwoord van Thijs:

_"Aandeel in betrokken recht geeft aan voor welk deel van het object de hypotheek geldig is.
Dus in dit geval heeft iemand 2 hypotheken op zijn perceel zitten, en allebei de hypotheken zijn afgesloten voor het gehele object._

_Hoe werkt dat dan in de praktijk?
2 opties:_

_1. Meerdere hypotheken van dezelfde hypotheekgever (=eigenaar van het object).
Als je je meer dan 1 hypotheek hebt dan krijgen de hypotheken een rang mee (in dit geval heeft 1 de 1ste en 1 de 2de rang. 
D.w.z. dat wanneer de hypotheekgever zijn schuld niet kan aflossen en bijvoorbeeld failliet gaat dat eerst de 1ste rang hypotheek wordt afbetaald door een curator/bewindvoerder en daarna pas de 2de rang hypotheek._

_2. Nieuwe hypotheek van nieuwe eigenaar is ingeschreven vóórdat de oude hypotheek (van de vorige eigenaar) is doorgehaald.
Dit komt bijna altijd tijdelijk voor na een overdracht, meestal duurt het 1-30 dagen voordat een hypotheek wordt doorgehaald.
Die vertraging komt doordat notarissen doorhalingen van hypotheken bundelen in 1 grotere akte (dat scheelt tijd en geld voor de notaris), en die schrijven ze eens per zoveel tijd in._

_Beide komen regelmatig voor."_
