### ISSUE TITLE
Geen foutmelding bij zoeken hypotheken bij niet-gevonden koz id

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#682]
/kadastraalonroerendezaken/1234567890123456/hypotheken

Levert een statuscode 200 zonder hypotheken:
```
{
    "_links": {
        "self": {
            "href": "/kadastraalonroerendezaken/1234567890123456/hypotheken"
        }
    },
    "_embedded": {}
}
```

Maar de opgegeven kadastraalOnroerendeZaakIdentificatie bestaat niet, dus had ik een 404 verwacht, net als ik die krijg bij /kadastraalonroerendezaken/1234567890123456 en /kadastraalonroerendezaken/1234567890123456/zakelijkgerechtigden

**Comment by fsamwel** [comment]
N.B. ik krijg wel een 404 wanneer de kadastraalonroerendezaakidentificatie niet uit 16 cijfers bestaat, bijvoorbeeld /kadastraalonroerendezaken/12345onjuist/hypotheken

**Comment by rhengeveld** [comment]
De 404 voor `/kadastraalonroerendezaken/12345onjuist/hypotheken` is te verklaren doordat `12345onjuist` niet een NEN3610 identificatie is. Wetende dat mijn achterliggende datasource een NEN3610 identificatie verwacht (`NL.IMKAD.KadastraalObject.1234` of `1234`) en hierop nooit een succes response kan geven wordt `12345onjuist` snel afgeschoten als een _404 Not Found_. 

Zo te zien ben ik voor scenario `/kadastraalonroerendezaken/1234567890123456/hypotheken` echter iets vergeten. Ik pak het op 🙂

**Comment by rhengeveld** [comment]
Opgelost
