### ISSUE TITLE
self link in collection item bevat ook fields

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#683]
Bijvoorbeeld /kadastraalonroerendezaken/17150075470000/hypotheken?fields=aandeelInBetrokkenRecht,hypotheekhouders.omschrijving,toelichtingBewaarder

Dan is _links.self.href terecht gelijk aan dit request.

Maar moet dit niet opgenomen zijn in de _links.self.href van een gevonden hypotheek.

Nu is _embedded.hypotheken[0]._links.self.href: "/kadastraalonroerendezaken/17150075470000/hypotheken/15479389?fields=aandeelInBetrokkenRecht,hypotheekhouders.omschrijving,toelichtingBewaarder"
hier had ik "/kadastraalonroerendezaken/17150075470000/hypotheken/15479389" verwacht (dus zonder de fields toevoeging).

N.B. dit is niet consequent gedaan binnen de API.
- /kadastraalonroerendezaken: geen parameters in item self link
- /kadastraalonroerendezaken/{kadastraalonroerendezaakidentificatie}/zakelijkgerechtigden: wel parameters in item self link
- /kadasternatuurlijkpersonen: geen parameters in item self link
- /kadasternietnatuurlijkpersonen: geen parameters in item self link
- /kadastraalonroerendezaken/{kadastraalonroerendezaakidentificatie}/hypotheken: wel parameters in item self link
- /kadastraalonroerendezaken/{kadastraalonroerendezaakidentificatie}/beslagen: wel parameters in item self link
- /kadastraalonroerendezaken/{kadastraalonroerendezaakidentificatie}/privaatrechtelijkebeperkingen: geen parameters in item self link

**Comment by rhengeveld** [comment]
Ok, dus geen parameters / fields in de _self_ link. Ik zal het aanpassen!

**Comment by fsamwel** [comment]
> Ok, dus geen parameters / fields in de self link. Ik zal het aanpassen!

Voor de zekerheid: ligt eraan welke self link je bedoelt. De self link op het hoogste niveau in het bericht met een waarde hebben identiek aan het request. De gebruiker kan dan een asynchroon request doen en aan de self-link herkennen dat dit het juiste bericht is.

Dus:
- de self-link in een collection is identiek aan het request (inclusief query parameters)
- de self-link in een resource is identiek aan het request (inclusief query parameters)
- de self-link in een resource in een collection is de uri die verwijst naar de resource (dus zonder query parameters)

**Comment by rhengeveld** [comment]
Ik heb de _self_ links aangepast (_fields_ verwijderd) voor:
* Hypotheken
* Beslagen
* ZakelijkGerechtigden

Ik hoop dat het daarmee klopt 🙂 **update is beschikbaar op de acceptatieomgeving**
