### ISSUE TITLE
Wat is indicatieOorspronkelijkObject voor een privaatrechtelijke beperking?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#684]
In PrivaatrechtelijkeBeperking (vanuit Aantekening) zit property indicatieOorspronkelijkObject.

Hierbij is geen description opgenomen, dus mij is het niet duidelijk waar dit over gaat.

In imKad zie ik in Aantekening geen gegeven die hier op lijkt of waarvan dit zou kunnen zijn afgeleid.

**Comment by JohanBoer** [comment]
In de vorige draft van IMKAD zat dit attribuut nog in de Aantekening. Daar komt het vandaan. In de final draft IMKAD 2.3 is dit attribuut niet meer terug te vinden. Ik zie nergen in wijzigingenoverzichten of release-notes waarom dit is verwijderd of dat het is hernoemd.

Ik zal deze property verwijderen uit de yaml. 


![image](https://user-images.githubusercontent.com/18071357/95190610-e2d27480-07cf-11eb-829a-60c3a7b4170a.png)

**Comment by fsamwel** [comment]
alleen zit deze ook al in release 1., namelijk in zakelijkgerechtigden.tenaamstelling.aantekeningen
Dat zou denk ik een breaking change betekenen, hoewel ik me afvraag of dit gegeven in v1.1 wel geleverd wordt (heb geen testdata gezien met dit gegeven). @kad-hebbim @rhengeveld wordt indicatieOorspronkelijkObject ooit gevuld (op zakelijk gerechtigde tenaamstelling aantekeningen)? 
@MelvLee hoe denk jij hierover, kunnen we dit verwijderen zonder dat aansluiters op v1.1 hier last van hebben?

**Comment by JohanBoer** [comment]
> @MelvLee hoe denk jij hierover, kunnen we dit verwijderen zonder dat aansluiters op v1.1 hier last van hebben?

Misschien is depricated verklaren dan een betere oplossing. Er gaat niets stuk omdat consumers deze waarschijnlijk nooit geleverd gekregen hebben, maar bij code genereren verander er wel een object als we deze property verwijderen.

**Comment by MelvLee** [comment]
> 
> 
> > @MelvLee hoe denk jij hierover, kunnen we dit verwijderen zonder dat aansluiters op v1.1 hier last van hebben?
> 
> Misschien is depricated verklaren dan een betere oplossing. Er gaat niets stuk omdat consumers deze waarschijnlijk nooit geleverd gekregen hebben, maar bij code genereren verandert er wel een object als we deze property verwijderen.

Ik zou het inderdaad depricated maken. Je weet niet of een consumer het in code al gebruikt. Met depricated weet hij dan dat het in een toekomstige versie wordt verwijderd
