### ISSUE TITLE
Accept-Crs ontbreekt in specificaties privaatrechtelijke beperkingen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#686]
Bij privaatrechtelijke beperkingen kan er geometrie in het antwoord zitten. Maar request header acceptCrs ontbreekt en ook (erger) response header contenters.

Dit zou zijn opgelost met https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/pull/637, vanuit issue #633, maar die is gesloten. Pull request moet opnieuw worden ingediend.

**Comment by rhengeveld** [comment]
@fsamwel het staat misschien nog niet in de laatste `openapi.yaml` op de `develop` branch, maar ik heb in ieder geval al geïmplementeerd dat de `Content-Crs` word toegevoegd bij (embedded) privaatrechtelijke beperkingen die geografische gegevens hebben (veld `begrenzing`). 

**Beschikbaar op de acceptatieopgeving** 😉

**Comment by fsamwel** [comment]
@rhengeveld @kad-hebbim dit is nu niet testbaar, want ik ken geen enkele privaatrechtelijke beperking met begrenzing. Kan er een testgeval worden toegevoegd/gewijzigd zodat ik wel begrenzing heb en dus de contentCrs header krijg?

**Comment by fsamwel** [comment]
begrenzing wordt nooit gevuld in een aantekening. zie #720
