### ISSUE TITLE
Als medewerker Pandbrigade wil ik weten hoe het eigendom van een object is verdeeld (eigendom, VVE, splitsingen/samenvoegingen)

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#69]
...zodat ik de eigenaren kan aanschrijven en een invordering correct over eigenaren kan verdelen. 

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by JohanBoer** [comment]
De enpoint voor de blob hebben we toch nog niet ? Volgens mij was die ook niet gepland voor versie 1.3. Alle andere informatie wordt wel geleverd. Voorstel om deze user story af te sluiten en een nieuwe user story op te voeren om de blob op te kunnen vragen.

**Comment by CathyDingemanse** [comment]
Done, aktes hier uit gehaald en issue #775 aangemaakt.
