### ISSUE TITLE
onverwacht 404 fout bij onjuiste kadastraalOnroerendeZaakIdentificatie

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#698]
Wanneer ik een kadastraalOnroerendeZaakIdentificatie van 16 cijfers gebruik bij /publiekrechtelijkebeperkingen krijg ik antwoord met een lege _embedded.
Ook wanneer ik een kadastraalOnroerendeZaakIdentificatie van 15 cijfers geef, krijg ik een lege _embedded.
```
{
    "_links": {
        "self": {
            "href": "/publiekrechtelijkebeperkingen?kadastraalOnroerendeZaakIdentificatie=123456789012345"
        }
    },
    "_embedded": {}
}
```

Wanneer ik een kadastraalOnroerendeZaakIdentificatie met ook letters gebruik, krijg ik een 404 fout.
```
{
    "type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_NotFound",
    "title": "Opgevraagde resource bestaat niet.",
    "status": 404,
    "detail": "Not Found",
    "instance": "/publiekrechtelijkebeperkingen?kadastraalOnroerendeZaakIdentificatie=123456789012345x",
    "code": "notFound"
}
```

Vanuit gebruikersperspectief zijn deze 3 situaties gelijk. We hebben in de specificaties geen eisen gesteld aan de mogelijke vulling van kadastraalOnroerendeZaakIdentificatie, alleen dat het een string is. En de fout zit in een query-parameter, dat mag nooit een 404 veroorzaken.

**Comment by rhengeveld** [comment]
Dit komt voort uit een poging om `123456789012345x` in een NEN3610 formaat te proppen. Dat mislukt, wat wordt teruggegeven als 404. Dat klopt als het een path-parameter is, maar niet in dit geval met een query-parameter. Goede vondst, ik pas het aan 🙂

**Comment by rhengeveld** [comment]
**Opgelost en [update acceptatieomgeving komt eraan]** ✔️ 

Nu lege response op `/publiekrechtelijkebeperkingen?kadastraalOnroerendeZaakIdentificatie=76870487970000a`
```json
{"_links":{"self":{"href":"/publiekrechtelijkebeperkingen?kadastraalOnroerendeZaakIdentificatie=76870487970000a"}},"_embedded":{}}
```

Nu lege response op `/kadastraalonroerendezaken/?persoon__identificatie=520264111a`
```json
{"_links":{"self":{"href":"/kadastraalonroerendezaken/?persoon__identificatie=520264111a"}},"_embedded":{}}
```
