### ISSUE TITLE
Als gemeente wil ik kadastrale onroerende zaken kunnen zoeken op nummeraanduiding

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#7]
...zodat ik de gegevens van deze kadastrale onroerende zaken kan gebruiken.

Op basis van een Nummeraanduiding kan een benoemd object opgehaald worden vervolgens kan via de relatie “heeftOverlapMet” de bijbehorende KADASTRALE ONROERENDE ZAAKen opgehaald worden.

Raadpleegresultaat: De NUMMERAANDUIDING waarvan de identificatie overeenkomt met het ingevulde zoek-argument uit het verzoekbericht wordt opgenomen in het antwoordbericht.

**Acceptatiecriteria**
- [ ] Het is mogelijk te zoeken op de volgende eigenschap :
    * adresseerbaarObjectAanduidingIdentificatie

**Definition of done**
- [ ] Inhoud resource bepaald
- [ ] BDD- functionele specificatie
- [ ] Open API specificatie
- [ ] Bruikbaarheid (gegenereerde code + constructies + naamgeving)
- [ ] Implementatie Provider
- [ ] Implementatie consumer

**Comment by fsamwel** [comment]
gaat het hier om de BAG-idof om de uri van het adresseerbaar object?

**Comment by ArjanKloosterboer** [comment]
In aanvulling op het voorgaande comment, in het ZDS2-project specificeren we userstory's vanuit specifieke praktijksituaties: wie wil wat weten of kunnen in welke situatie? Die 'wie' en die 'stuatie' is een gemeentelijke medewerker in zijn/haar rol of functie, dus een belasingstingmedewerker die bezwaarschriften behandelt, een vergunningenmedewerker die de ontvankelijkheid van aanvragen toetst, et cetera. Zo specifiek moet een userstory zijn om er achter te komen wat vanuit de praktijk echt nodig is. 
.

> ..zodat ik de gegevens van deze kadastrale onroerende zaken kan gebruiken.

Om de userstory specifek te maken is ten eerste van belang te weten wie 'ik' is: welke medewerker in welke rol? Ten tweede is van belang om er achter te komen waarvoor hij/zij 'de gegevens van deze kadastrale onroerende zaken [wil] gebruiken'. Pas  als daarvoor een functionele reden is gevonden heeft deze userstory zin en kan die geherformuleerd worden. Zo niet, n.v.t.

**Comment by JohanBoer** [comment]
@ArjanKloosterboer en @Debatse 
Het doel van dit project is om een API op te leveren waarmee het kadaster die BRK-gegevens ontsluit die van belang zijn voor gemeenten.  

Dan is het van belang dat je weet welke gegevens relevant zijn voor gemeenten. Die inventarisatie is gedaan met het opstellen van het RSGB. Het feit dat we nu het IMKAD als informatiemodel gebruiken neemt niet weg dat we alleen die objecttypen en elementen gaan gebruiken die voor een gemeente relevant zijn en die nu dus zijn opgenomen in het RSGB. Uiteraard kunnen daar ook nog aanpassingen op plaatsvinden op basis van dit project. Ergo, Deze API moet de set BRK-gegevens ontsluiten die voor gemeenten van belang is. 

Hoe - en in welke processen - die gegevens dan gebruikt gaan worden is aan de gemeenten zelf om in te richten en voor dit specifieke project niet van belang. Ergo, de functionele behoefte in kaart brengen met zeer specifieke userstories valt buiten de scope van dit project.
