### ISSUE TITLE
onterecht acceptCrs en contentCrs in publiekrechtelijkebeperkingen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#700]
Met het verwijderen van beperkingsgebied uit publiekrechtelijke beperkingen (#668) zit er geen geometrie meer in publiekrechtelijke beperkingen. Dus zijn acceptCrs en contentCrs niet meer nodig. Deze moeten worden verwijderd.

**Comment by rhengeveld** [comment]
Heb dit ondertussen verwerkt, is beschikbaar op de acceptatieomgeving ✔️
