### ISSUE TITLE
Tenminste één parameter moet worden opgegeven

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#701]
/publiekrechtelijkebeperkingen?fields=waarde

Dit levert:
```
{
    "_links": {
        "self": {
            "href": "/publiekrechtelijkebeperkingen?fields=waarde"
        }
    },
    "_embedded": {}
}
```

Dit is m.i. niet terecht. Query parameters (behalve fields, expand en page) beperken het aantal resultaten. Wanneer er dus geen query parameter is, is er ook geen beperking.

In dit geval is dat onhandig, want dat zou betekenen dat er enorm veel publiekrechtelijkebeperkingen worden geleverd. Eigenlijk met er ten minste één query parameter worden opgegeven.

Op dit moment is er maar één query parameter: kadastraalOnroerendeZaakIdentificatie. Deze is niet gedefinieerd als required, wellicht omdat we in de nabije toekomst graag ook andere parameters hopen toe te kunnen voegen.

@MelvLee kunnen we voor nu kadastraalOnroerendeZaakIdentificatie required maken, en deze later optioneel maken zodra er ook een andere parameters worden toegevoegd, zonder dat dat dan een breaking change oplevert voor gebruikers?

Vergelijkbaar hiermee is de situatie bij kadastraalonroerendezaken. Wanneer daar geen enkele parameter (behalve evt. fields of expand) wordt opgegeven, komt daar nu een foutmelding:
```
{
    "type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_BadRequest",
    "title": "Minimale combinatie van parameters moet worden opgegeven.",
    "status": 400,
    "detail": "Voor gekozen zoekingang zijn niet alle parameters (goed) ingevuld.",
    "instance": "/kadastraalonroerendezaken?fields=koopsom",
    "code": "paramsCombination"
}
```

In de descriptions of specificatie staat nergens dat ten minste één van de parametercombinaties moet worden gebruikt, alleen dat "combineren van parameters uit verschillende categorieën is niet toegestaan".

Dit moet m.i. worden toegevoegd. En de foutmelding zou dan moeten zijn "Ten minste één parameter moet worden opgegeven."

Kiezen we dan voor publiekrechtelijkebeperkingen dezelfde oplossing (in description) of kunnen we daar kadastraalOnroerendeZaakIdentificatie required maken?

**Comment by MelvLee** [comment]
@fsamwel, het is geen breaking change als een required parameter optioneel wordt gemaakt. Clients die nog niet over zijn gegaan naar de nieuwe situatie, sturen nog steeds de parameter. Je kan er ook voor kiezen om paging te ondersteunen of als provider het resultaat beperken als de kozid niet is opgegeven

**Comment by fsamwel** [comment]
@CathyDingemanse en @JohanBoer wat vindt jij hoe moet worden opgegaan met het zoeken van kadastraalonroerendezaken of publiekrechtelijkebeperkingen als er geen zoekparameter is opgegeven?
- foutmelding geven
- alles teruggeven (met paginering)

**Comment by CathyDingemanse** [comment]
Ik neig naar de foutmelding. Beperkt alles teruggeven levert geen bruikbaar resultaat op voor de gebruiker, en die heeft langer nodig om te beseffen wat er niet goed is gegaan en wat men moet doen om wel een bruikbaar resultaat te krijgen.
Nu required maken en later optioneel maken levert geen breaking change op, dus ik zou zeggen ga er voor.

De description:
"Ten minste één parameter moet worden opgegeven." graag veranderen in "Geef tenminste één parameter op."

**Comment by fsamwel** [comment]
Hoi Cathy, de description van de foutmelding wijzigen zou in de feature moeten die in common zit. Deze feature is ook al in BAG toegepast, waardoor het niet hetzelfde is in BAG en in BRK. Wordt dan ook een versie 1.3 van HC common waarnaar dan verwezen moet worden. 
Wil je dit desondanks graag aangepast zien?

**Comment by fsamwel** [comment]
@JohanBoer kan jij deze wijziging doorvoeren?
1. bij /kadastraalonroerendezaken wijzigen/toevoegen aan description dat exact één van de zoekcategorieën moet worden gebruikt
2. bij /publiekrechtelijkebeperkingen parameter kadastraalOnroerendeZaakIdentificatie required maken

Wanneer dat doorgevoerd is, moet dit issue aan @rhengeveld en @kad-hebbim worden toegewezen en in project Implementatie BRK op To Do worden gezet

**Comment by MelvLee** [comment]
> 
> 
> Hoi Cathy, de description van de foutmelding wijzigen zou in de feature moeten die in common zit. Deze feature is ook al in BAG toegepast, waardoor het niet hetzelfde is in BAG en in BRK. Wordt dan ook een versie 1.3 van HC common waarnaar dan verwezen moet worden.
> Wil je dit desondanks graag aangepast zien?

Bij mij gaan hier wel wat alarmbellen af. Is dit wat we willen? Is het verbeteren van documentatie ook een functionele wijziging? Gaan we documentatie (foutmeldingen zijn m.i. ook documentatie) niet verbeteren omdat een andere H.C. API het al gebruikt? Dat lijkt mij geen goed idee

**Comment by JohanBoer** [comment]
> @CathyDingemanse en @JohanBoer wat vindt jij hoe moet worden opgegaan met het zoeken van kadastraalonroerendezaken of publiekrechtelijkebeperkingen als er geen zoekparameter is opgegeven?
> 
> * foutmelding geven
> * alles teruggeven (met paginering)

Met Cathy eens om een foutmelding terug te geven. Als er geen functionele behoefte is om alle kadastraalonroerendezaken of alle publiekrechtelijkebeperkingen in 1 call op te halen kan je er vanuit gaan dat dit een foutsituatie is. 

> De description:
> "Ten minste één parameter moet worden opgegeven." graag veranderen in "Geef tenminste één parameter op."

Dit moeten we nu niet willen. Deze feature is in productie in gebruik. Fouten en problemen moet je oplossen m.i. maar dit is een cosmetische wijziging. We kunnen dit wel op de backlog van Common zetten om mee te nemen als we ooit weer  een nieuwe versie van common uit moeten brengen. Als we voor deze categorie ook nieuwe versie van common uit gaan brengen zitten we in no time op versie 1.89.0

> 1. bij /kadastraalonroerendezaken wijzigen/toevoegen aan description dat exact één van de zoekcategorieën moet worden gebruikt

Bij /kadastraalonroerendezaken staat nu in de description : 
          _Het zoeken van kadastraal onroerende zaken door een of meer parameters op te geven uit de categorieën kadastrale aanduiding, ingeschreven persoon, kadasterpersoon of Adres. Het combineren van parameters uit verschillende categorieën is niet toegestaan._

Dat dekt de lading toch ? 

> 2\. bij /publiekrechtelijkebeperkingen parameter kadastraalOnroerendeZaakIdentificatie required maken

Dat kan ik wel denk ik.

**Comment by CathyDingemanse** [comment]
> Hoi Cathy, de description van de foutmelding wijzigen zou in de feature moeten die in common zit. Deze feature is ook al in BAG toegepast, waardoor het niet hetzelfde is in BAG en in BRK. Wordt dan ook een versie 1.3 van HC common waarnaar dan verwezen moet worden.
> Wil je dit desondanks graag aangepast zien?

@JohanBoer @fsamwel 
Zou je dit dan direct een versie 1.3 moeten noemen? Kunnen we niet gewoon versie 1.2 behouden met een ander tekstje? Het gaat toch niet een om een functionele wijziging? Het is toch nog steeds dezelfde versie, omdat er niets verandert aan de capabilities van de API? Ik hoor Melvin zeggen dat het hier eigenlijk om een "hot-fix" gaat (of zelfs nog minder dat dat). Ik vraag alleen maar tekstuele verbetering, waar geen logica geïmplementeerd toch?

De echte vraag is hier dus: kunnen we kunnen we zelfs geen tekstuele aanpassingen meer doen zonder een nieuwe versie uit te brengen? En: Is een tekstuele verandering een requirement als het in een feature file staat, ook al wijzigt het in de feature file beschreven gedrag niet?

Ik vind dat persoonlijk wat (te) ver gaan. Net als design decisions die rules worden :-). Het maakt ons iig veel minder agile.
 
Kunnen we dit niet iets meer loosy definiëren in een test? Bijvoorbeeld: de description moet gevuld zijn i.p.v. de description bevat deze tekst ".........."?

**Comment by rhengeveld** [comment]
> In dit geval is dat onhandig, want dat zou betekenen dat er enorm veel publiekrechtelijkebeperkingen worden geleverd. Eigenlijk met er ten minste één query parameter worden opgegeven.

Nu is mijn datasource beperkt en heeft deze minimaal een `kadastraalOnroerendeZaakIdentificatie` nodig om überhaupt resultaten te kunnen leveren. In zekere zin is de parameter daarmee reeds _required_; bij het weglaten van deze parameter krijg je nu altijd een leeg resultaat. Kan mij wel voorstellen dat minder duidelijk is voor een client, waarom je een leeg resultaat krijgt zonder parameter. Dus ik zou dit ook graag toegevoegd zien in 1.2 😉

**Comment by JohanBoer** [comment]
> De echte vraag is hier dus: kunnen we kunnen we zelfs geen tekstuele aanpassingen meer doen zonder een nieuwe versie uit te brengen? En: Is een tekstuele verandering een requirement als het in een feature file staat, ook al wijzigt het in de feature file beschreven gedrag niet?

Deze tekstuele wijziging die door de provider geretourneerd wordt aan de consumer is nu expliciet beschreven. Als we deze aanpassen zonder een release aan te passen dan weten providers die reeds geïmplementeerd hebben niet dat er iets gewijzigd is. Dus BRK geeft netjes de nieuwste melding terug en BRP en BAG geven de oude melding terug. Dat lijkt mij niet consistent. 

Als je een nieuwe patch release uitbrengt (1.2.1)  en daarbij documenteert ( in de releasenotes) dat je alleen deze tekst hebt aangepast geef je providers de keuze om dit al dan niet direct door te voeren. Dat is super-agile. 

De werking veranderd niet, dus ze kunnen zelf die beslissing nemen. Maar ik zou dus voor iedere wijziging (ook documentatie) op zijn minst een patch-release uitbrengen om duidelijk en transparant te zijn in wat we doen. 

> Ik vind dat persoonlijk wat (te) ver gaan. Net als design decisions die rules worden :-). Het maakt ons iig veel minder agile.
> 
> Kunnen we dit niet iets meer loosy definiëren in een test? Bijvoorbeeld: de description moet gevuld zijn i.p.v. de description bevat deze tekst ".........."?

Over dit onderwerp is het een kwestie van kiezen:  Hoe specifiek wil je zaken beschrijven. Als we naar de aanleiding van deze issue kijken moeten we ons afvragen of het sop de kool waard is. Je zou dus inderdaad zaken wat meer "loosy" kunnen beschrijven en dan heb je dus te maken met de interpretatie van de partij die implementeert.

**Comment by fsamwel** [comment]
> Kunnen we dit niet iets meer loosy definiëren in een test? Bijvoorbeeld: de description moet gevuld zijn i.p.v. de description bevat deze tekst ".........."?

Mee eens. We lopen hier tegen drie problemen aan op de manier hoe we tot nu gespecificeerd hebben:
1. behoorlijk vergaande (standaardisering in) specificaties/features, bijvoorbeeld welke foutteksten moeten worden geleverd.
2. combineren technische specificaties en documentatie in dezelfde documenten. Bijvoorbeeld descriptions in de OAS en foutteksten in de features.
3. combineren van specificaties voor de provider (de meeste features) en interfacespecificaties voor de clients

Aangezien de technische foutmelding is voorgeschreven in een feature ontkom je er denk ik niet aan dat het wijzigen daarvan tot een (minor) release leidt. De wijziging ervan leidt namelijk tot wijziging in de implementatie van de provider.
Maar wenselijk is dat denk ik niet

**Comment by rhengeveld** [comment]
Gezien #713 gemerged is, heb ik dit ondertussen in de code **aangepast [en acceptatieomgeving update volgt later]**

**Comment by fsamwel** [comment]
bij /publiekrechtelijkebeperkingen wordt nu de foutmelding "Ten minste één parameter moet worden opgegeven." en is invalidParams niet opgenomen.

bij /publiekrechtelijkebeperkingen?kadastraalOnroerendeZaakIdentificatie=  wordt ook de foutmelding "Ten minste één parameter moet worden opgegeven." en is invalidParams wel opgenomen:
```
    "invalidParams": [
        {
            "name": "kadastraalOnroerendeZaakIdentificatie",
            "code": "required",
            "reason": "Parameter is verplicht."
        }
    ]
```

idem bij kadasternatuurlijkpersonen

Waarom onderscheid tussen niet sturen van een verplichte parameter en sturen van een verplichte parameter met een lege waarde? In beide gevallen ontbreekt een waarde voor een verplichte parameter.

**Comment by rhengeveld** [comment]
Goed punt, ik vermoed dat dit 2 losse paden zijn:
* Op basis van specificatie automatisch gegenereerde controle op verplichte parameter
* Daarna doe ik nog een controle of de verplichte parameter wel gevuld is

Ik ga kijken of ik dit kan aanpassen 🙂

**Comment by rhengeveld** [comment]
Waren inderdaad 2 verschillende foutafhandeling paden. Heb ze weten te combineren; bij afwezigheid verplichte parameter wordt de _"invalidParams"_ nu ook gevuld. Dus de response is nu hetzelfde (URL lichtelijk anders) 😄 

**Opgelost en beschikbaar op de acceptatieomgeving** ✔️

**Comment by fsamwel** [comment]
@rhengeveld de eerste opmerking van dit issue is nu niet opgelost:
```
{
    "type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_BadRequest",
    "title": "Minimale combinatie van parameters moet worden opgegeven.",
    "status": 400,
    "detail": "Voor gekozen zoekingang zijn niet alle parameters (goed) ingevuld.",
    "instance": "/kadastraalonroerendezaken?fields=koopsom",
    "code": "paramsCombination"
}
```

Als title had ik dus verwacht "Geef tenminste één parameter op." (zie https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/master/features/foutafhandeling.feature en https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/master/docs/foutmeldingen.json)

**Comment by fsamwel** [comment]
Bij /publiekrechtelijkebeperkingen?fields=waarde wordt nog de oorspronkelijke fouttekst gebruikt (@CathyDingemanse verzocht andere tekst te gebruiken):
```
{
    "type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_BadRequest",
    "title": "Ten minste één parameter moet worden opgegeven.",
    "status": 400,
    "detail": "The request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modification.",
    "instance": "/publiekrechtelijkebeperkingen?fields=waarde",
    "code": "paramsRequired",
    "invalidParams": [
        {
            "name": "kadastraalOnroerendeZaakIdentificatie",
            "code": "required",
            "reason": "Parameter is verplicht."
        }
    ]
}
```

**Comment by fsamwel** [comment]
Idem bij /kadasternatuurlijkpersonen en /kadasternietnatuurlijkpersonen

Bij /publiekrechtelijkebeperkingen, /kadasternatuurlijkpersonen en /kadasternietnatuurlijkpersonen was eigenlijk de foutsituatie paramsValidation (Een of meerdere parameters zijn niet correct.) juist geweest, want hier is een required parameter niet aanwezig.

**Comment by rhengeveld** [comment]
**(1)** Betreffende opmerking https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/701#issuecomment-715411712 - bij `/kadastraalonroerendezaken` zijn er meerdere parameter combinatiemogelijkheden:
* Keuze uit verplichte parameters `postcode`, `kadastraleAanduiding`, `persoon__identificatie` en `burgerservicenummer` 
* Er zijn een aantal aanvullende optionele parameters `huisnummer`, `huisletter`, `huisnummertoevoeging` en `zakelijkGerechtigde__type` 

Op basis hiervan is toen gekozen voor _"paramsCombination"_, welke prima leek te zijn tijdens #572.  

Zal ik het specifiek voor deze zoekingang aanpassen naar het volgende @fsamwel? Of wil je een andere tekst in `title` of `detail`? Het `detail` veld is hier afwijkend en zelfs enigszins conflicterend met de _"tenminste"_ van `title`, maar dit lijkt het enige veld in de specificatie te zijn met enige vrije invulling.
```
{
    "type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_BadRequest",
    "title": "Geef tenminste één parameter op.",
    "status": 400,
    "detail": "Geef precies één van de verplichte parameters op",
    "instance": "/kadastraalonroerendezaken?fields=koopsom",
    "code": "paramsRequired",
    "invalidParams": [
        {
            "name": "postcode",
            "code": "required",
            "reason": "Parameter is verplicht."
        },
        {
            "name": "kadastraleAanduiding",
            "code": "required",
            "reason": "Parameter is verplicht."
        },
        {
            "name": "persoon__identificatie",
            "code": "required",
            "reason": "Parameter is verplicht."
        },
        {
            "name": "burgerservicenummer",
            "code": "required",
            "reason": "Parameter is verplicht."
        }
    ]
}
```

---

**(2)** Ah in https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/701#issuecomment-715413725 doel je op https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/701#issuecomment-705576353. Prima! Ik zal dit aanpassen:
> "Ten minste één parameter moet worden opgegeven." graag veranderen in "Geef tenminste één parameter op."

---

**(3)** Tot slot zal ik kijken of ik kan aanpassen naar wat je als laatste noemt in https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/701#issuecomment-

**Comment by rhengeveld** [comment]
**(1)** Is aangepast naar het voorbeeld hierboven

**(2)** Is aangepast

**(3)** Volgens mij hoeft hier niks gewijzigd te worden:
* Voor `/kadasternatuurlijkpersonen` met of zonder `/` is er keuze uit `/kadasternatuurlijkpersonen/{kpi}` en `/kadasternatuurlijkpersonen?q={query}`. Ik heb geen invloed op welke gekozen wordt, dit is altijd het "kortste pad" met query parameters (zie ook de foutmelding), dus _"paramsRequired"_ is correct.
* Ditzelfde geldt ook voor `/kadasternietnatuurlijkpersonen`
* Ditzelfde geldt ook voor `/publiekrechtelijkebeperkingen` met verplichte parameter _"kadastraalOnroerendeZaakIdentificatie"_

**Aanpassingen zijn beschikbaar op de acceptatieomgeving** ✔️

**Comment by fsamwel** [comment]
@MelvLee vind jij de foutmelding hierboven duidelijk, waarbij je één van 4 parameters moet opnemen en alle vier in de foutmelding zitten met code "required"? Die melding zou je naar mijn idee ook kunnen interpreteren als zouden alle vier verplicht zijn (dus moet je ze alle vier sturen met een waarde).

**Comment by MelvLee** [comment]
> 
> 
> @MelvLee vind jij de foutmelding hierboven duidelijk, waarbij je één van 4 parameters moet opnemen en alle vier in de foutmelding zitten met code "required"? Die melding zou je naar mijn idee ook kunnen interpreteren als zouden alle vier verplicht zijn (dus moet je ze alle vier sturen met een waarde).

Als in een UI op de fout wordt geprogrammeerd, dan zou je nu die vier verplichte velden zien oplichten. Dat kan mogelijk verwarrend zijn, maar dat kan een UX designer beter beoordelen. Ik zou het voor nu zo laten

**Comment by rhengeveld** [comment]
@fsamwel volgens mij is dit issue dan klaar?

Oh, er is nog wel een laatste punt. [Een stuk hierboven](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/701#issuecomment-705576353) zei Cathy:
> _"Ten minste één parameter moet worden opgegeven." graag veranderen in "Geef tenminste één parameter op."_

Dit heb ik aangepast, maar de originele tekst komt uit [foutafhandeling.feature](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/master/features/foutafhandeling.feature). Klopt dat dan wel of moet dit dan ook in de feature veranderd worden?

**Comment by rhengeveld** [comment]
Verplaatst naar 1.3 en scrumboard om hier hopelijk een antwoord op te krijgen. Anders sluiten.
