### ISSUE TITLE
Diverse objecten zijn nog inline gedefinieerd

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#702]
BeslagHalCollectie heeft nog bij embedded een inline object gedefinieerd. Maak daar een schema component met een $ref van. 

Dit geldt ook voor HypotheekHalCollectie.

Alle Yaml bestanden hierop checken.

**Comment by JohanBoer** [comment]
Tevens de underscoers uit schemanamen en enumeratie-namen verwijderd.

**Comment by rhengeveld** [comment]
**Aangepast [en acceptatieomgeving update volgt later]**
