### ISSUE TITLE
identificatie embedded privaatrechtelijkeBeperking bevat domein

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#706]
/kadastraalonroerendezaken/22590043870000?expand=privaatrechtelijkeBeperkingen

levert:
```
    "_embedded": {
        "privaatrechtelijkeBeperkingen": [
            {
                "identificatie": "NL.IMKAD.Aantekening.91074411",
```

domein is een apart property en moet niet in de identificatie worden opgenomen

**Comment by rhengeveld** [comment]
**Opgelost en [binnenkort beschikbaar op de acceptatieomgeving]**

**Tevens opgelost:** het veld _domein_ van de privaatrechtelijkeBeperking was nog niet vereist, dus met request `expand=privaatrechtelijkeBeperkingen.omschrijving` werden (naast omschrijving) enkel _identificatie_ en _links.self_ teruggegeven. Nu is _domein_ hier ook aan toegevoegd.
