### ISSUE TITLE
Achternaam in omschrijving moet ook adellijke titel of predicaat bevatten

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#708]
In aanschrijfwijze, aanhef en gebruikInLopendeTekst wordt de achternaam samengesteld met de adellijke titel, voorvoegsel en geslachtsnaam, plus eventueel voorvoegsel en geslachtsnaam van de partner (zie #375)

De omschrijving, zoals die nu wordt opgenomen in bijvoorbeeld zakelijkgerechtigden.persoon.omschrijving en in de natuurlijkpersoon, gebruikt nu niet de adellijke titel en ook niet de geslachtsnaam van de partner.

Bijvoorbeeld:
```
    "omschrijving": "Susan in het Veld",
    "naam": {
        "geslachtsnaam": "Veld",
        "voornamen": "Susan",
        "voorvoegsel": "in het",
        "aanschrijfwijze": "S. in het Veld-van Velzen",
        "aanhef": "Geachte mevrouw In het Veld-van Velzen",
        "gebruikInLopendeTekst": "mevrouw In het Veld-van Velzen"
    },
```
Hier zou ik "omschrijving": "Susan in het Veld-van Velzen" logischer vinden

En:
```
    "omschrijving": "Jan-Jaap de Vierde",
    "naam": {
        "geslachtsnaam": "Vierde",
        "voornamen": "Jan-Jaap",
        "voorvoegsel": "de",
        "aanschrijfwijze": "J. baron de Vierde",
        "aanhef": "Hoogwelgeboren heer",
        "gebruikInLopendeTekst": "baron De Vierde"
    },
```
Hier zou ik "omschrijving": "Jan-Jaap baron de Vierde" logischer vinden

**Comment by fsamwel** [comment]
@CathyDingemanse mee eens? Of is het wel goed hoe het nu is gebouwd?

**Comment by fsamwel** [comment]
Wanneer dit moet worden doorgevoerd, moet hier wellicht een feature voor gemaakt worden (kan grotendeels gebaseerd worden op de bestaande naamgeving features).

**Comment by CathyDingemanse** [comment]
De omschrijving moet overeenkomen met iemands officiële naam. Dus zonder naamgebruik en met adellijke titel of predicaat.

**Comment by fsamwel** [comment]
@kad-hebbim @rhengeveld de omschrijving van een natuurlijk persoon moet ook de adellijke titel of het predicaat bevatten. Dit is namelijk onderdeel van de achternaam.

Dus moet omschrijving worden samengesteld als: PK VN AT VV GN
Waarbij:
  - VN = naam.voornamen
  - VV = naam.voorvoegselsgeslachtsnaam
  - GN = naam.geslachtsnaam
  - PK = Predikaat (adellijkeTitelOfPredikaat is "JV" of "JH")
  - AT = adellijke titel (adellijkeTitelOfPredikaat anders dan "JV" of "JH")

**Comment by rhengeveld** [comment]
@fsamwel geldt dit ook voor `PersoonBeperkt` (bijv. hypotheekhouders) met type _"ingeschreven_natuurlijk_persoon"_ of _"kadaster_natuurlijk_persoon"_? Of enkel voor een `KadasterNatuurlijkPersoon`?

**Comment by fsamwel** [comment]
@rhengeveld dit geldt ook voor de PersoonBeperkt

**Comment by rhengeveld** [comment]
@fsamwel hierboven had je geschreven:
> Hier zou ik "omschrijving": "Susan in het Veld-van Velzen" logischer vinden

Hierbij speelt ook de naam van de partner een rol, wat weer afhankelijk is van de aanduiding naamgebruik. Volgens mij is het format `PK VN AT VV GN` daarmee dus niet afdoende?

Gecombineerd met het andere voorbeeld van _"Jan-Jaap baron de Vierde"_ ben ik geneigd om de definities van aanschrijfwijze te hanteren, maar in plaats van voorletters gebruik je de voornamen. Toch?

**Comment by CathyDingemanse** [comment]
Ha Rik @rhengeveld, de manier waarop je wil worden aangeschreven is niet je officiële naam.  Ik kan mij wel aan laten spreken met naam van mijn echtgenoot, maar mijn naam is nog steeds de naam die ik bij mijn geboorte heb gekregen. Daar verandert niks aan. Adellijke titels en predicaten horen daar wel bij.

**Comment by rhengeveld** [comment]
Duidelijk, dan was het voorbeeld gewoon minder goed 😉 dan hou ik formaat `PK VN AT VV GN` aan

**Comment by fsamwel** [comment]
> Duidelijk, dan was het voorbeeld gewoon verwarrend

Het voorbeeld in de eerste comment is gewoon niet correct. Ik ging er eerst ook vanuit dat de samengestelde naam moest worden opgenomen. Cathy gaf aan dat dit de officiële naam moet zijn. Dus het eerste voorbeeld, en vooral mijn verwachting daarbij, is niet correct. Alleen toevoegen van adellijke titel of predicaat blijft over.

**Comment by rhengeveld** [comment]
@fsamwel ik heb geïmplementeerd, het is beschikbaar op de acceptatieomgeving ✔️
