### ISSUE TITLE
Als medewerker vergunningen wil ik bij een kadastrale onroerende zaak het adres zien

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#711]
...zodat ik een vergunningsaanvraag kan behandelen.

afgeleid van #38 

**Acceptatiecriteria**
- de adressen van een kadastraal onroerende zaak worden getoond
- elk adres bevat dezelfde gegevens en structuur als een adres in BAG en in kadasterpersonen

**Definition of done**
- [X] Open API specificatie
- [ ] implementatie

**Comment by fsamwel** [comment]
adres zit al in specificaties voor v1.2

**Comment by rhengeveld** [comment]
Voor de duidelijkheid: de adressen bij een onroerende zaak kunnen alleen binnenlandse adressen zijn.

**(1) Want alleen binnenlandse adressen hebben een _koppelingswijze_**
![Koppelingswijze](https://user-images.githubusercontent.com/1228038/96472073-547adb80-1230-11eb-8cc4-6f748b6d410b.png)

**(2) Want een _LocatieKadastraalObject_ heeft altijd 1 binnenlands adres**
![LocatieKadastraalObject](https://user-images.githubusercontent.com/1228038/96472098-5e044380-1230-11eb-95d2-40b7b131e401.png)

_Zie ook het [IMKAD](https://www.kadaster.nl/schemas/review-imkad/20190901/cat/imkad-IMKAD-2-20190901.office.respec.html) model_

**Comment by fsamwel** [comment]
Dus eigenlijk zou adresregel3 en land niet in het adres van een kadastraalonroerendezaak moeten zitten, is dat de conclusie?

**Comment by rhengeveld** [comment]
`adresregel3` wordt alleen gevuld bij buitenlandse adressen (met regio) - zoals in de beschrijving staat:
> _"Het derde deel van een adres is optioneel een of meer geografische gebieden van het adres in het buitenland"_

Dus ja, blijft in dit geval altijd leeg. Lege velden komen echter niet terug in de response, dus behalve dat het in de algemene specificatie van `AdresUitgebreid` staat maakt het niet veel uit. Denk dat het geen meerwaarde heeft dit aan te passen 🙂

**Comment by rhengeveld** [comment]
Overigens is dit ondertussen **geïmplementeerd [en acceptatieomgeving update volgt later]**

**Comment by fsamwel** [comment]
@JohanBoer 
> Voor de duidelijkheid kan aan de adresssen van KadastraalOnroerendeZaak een omschrijving toegevoegd worden dat het alleen om binnenlandse adressen gaat

Ben je het hiermee eens? Voer jij dit door?

**Comment by rhengeveld** [comment]
Ik heb een voorzet gemaakt in pull request #718 🙂

**Comment by kad-hebbim** [comment]
@fsamwel @CathyDingemanse @JohanBoer : momenteel wordt als land nu standaard (code:6030, waarde:Nederland) ingevuld bij een binnenlands adres. Ik weet even niet meer waarom dit zo is doorgevoerd. Jullie een idee?

**Comment by fsamwel** [comment]
6030 is de code voor Nederland in de waardelijst

Ik denk dat land alleen opgenomen hoeft te worden wanneer het niet in Nederland is. @CathyDingemanse hoe zie jij dit?

**Comment by CathyDingemanse** [comment]
> 6030 is de code voor Nederland in de waardelijst
> 
> Ik denk dat land alleen opgenomen hoeft te worden wanneer het niet in Nederland is. @CathyDingemanse hoe zie jij dit?

Dat komt toch niet voor? Een kadastraal onroerende zaak uit de BRK (in Nederland dus) heeft toch nooit een buitenlands adres?
Zullen we het gewoon helemaal niet opnemen?

**Comment by fsamwel** [comment]
@JohanBoer kan jij die wijziging in BRK op je nemen?

Ik denk dat er dan vier adrescomponenten moeten zijn:

1. BinnenlandsAdres: BAG/Adres + nummeraanduidingIdentificatie + adresregel1 + adresregel2
2. AdresUitgebreid: BinnenlandsAdres + adresregel3 + land
3. Postadres: AdresUitgebreid + postbusnummer
4. LocatieKadastraalObject: BinnenlandsAdres + koppelingswijze

**Comment by fsamwel** [comment]
of @MelvLee is dat niet handig en wil je liever AdresUitgebreid waarin we de buitenland adresvelden (adresregel3 + land) nooit vullen?

**Comment by fsamwel** [comment]
@kad-hebbim heb je misschien een kadastraal onroerende zaak met een huisnummertoevoeging in het adres?

**Comment by rhengeveld** [comment]
Ik heb even gezocht en [hier](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/452#issuecomment-621079838) lijkt de keuze gemaakt te zijn om altijd Nederland in te vullen op binnenlandse adressen. 

Vanuit de bron wordt onderscheid gemaakt tussen een adres binnenland of buitenland, dus wat dat betreft kunnen we het land (Nederland) gewoon weglaten als het om een binnenlands adres gaat. Dat komt ook overeen met wat in [adres.feature](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/master/features/adres.feature) staat:
> _Veld "land" wordt alleen opgenomen wanneer het een buitenlands adres betreft._

**Comment by JohanBoer** [comment]
> @JohanBoer kan jij die wijziging in BRK op je nemen?

@fsamwel Dat kan zeker, maar je stelt nog een vraag aan @Melvin . Ik pak dit op als de discussie is uitgetrild.

**Comment by fsamwel** [comment]
Klopt, ik zie dat inderdaad in de implementatie. Op zich zou je nog het argument kunnen maken dat bij een persoon dat relevant is, omdat die ook een buitenlands adres kan hebben, terwijl een kadastraalonroerendezaak geen buitenlands adres kan hebben.
@MelvLee en @CathyDingemanse wat willen jullie?

**Comment by fsamwel** [comment]
@MelvLee @JohanBoer wat is nu de status van mijn bovenstaande vragen aan jullie?

Ik zie in de description van de k0Z.adressen staan dat het Binnenlandse adressen zijn. Dat stuk van de oplossing is doorgevoerd (of was dat al zo?).

Zijn jullie akkoord met hoe het nu gemodelleerd is en werkt? In een kadastraalonroerendezaak heeft adressen
1. veld adresregel3 in de specificaties, maar die zal nooit worden opgenomen in een response
2. veld land in de specificaties, en zal die altijd worden gevuld met code 6030 en waarde "Nederland"

**Comment by rhengeveld** [comment]
@fsamwel we (@kad-hebbim en ik) waren er eigenlijk vanuit gegaan op basis van de [opmerking van Cathy](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/711#issuecomment-714502734) dat Nederland niet meer in binnenlandse adressen hoeft te zitten. Er wordt _**nu**_ een versie op de acceptatieomgeving gezet waarbij dit is aangepast. Als Nederland toch standaard gevuld moet zijn dan kan dat weer zo teruggezet worden 😂

**Comment by MelvLee** [comment]
> 
> 
> @MelvLee @JohanBoer wat is nu de status van mijn bovenstaande vragen aan jullie?
> 
> Ik zie in de description van de k0Z.adressen staan dat het Binnenlandse adressen zijn. Dat stuk van de oplossing is doorgevoerd (of was dat al zo?).
> 
> Zijn jullie akkoord met hoe het nu gemodelleerd is en werkt? In een kadastraalonroerendezaak heeft adressen
> 
>     1. veld adresregel3 in de specificaties, maar die zal nooit worden opgenomen in een response
> 
>     2. veld land in de specificaties, en zal die altijd worden gevuld met code 6030 en waarde "Nederland"

Ik ben akkoord

**Comment by fsamwel** [comment]
Ik zie nu dat land niet meer meegeleverd wordt bij de KOZ adressen. Nog beter denk ik

**Comment by JohanBoer** [comment]
> @MelvLee @JohanBoer wat is nu de status van mijn bovenstaande vragen aan jullie?
> 
> Ik zie in de description van de k0Z.adressen staan dat het Binnenlandse adressen zijn. Dat stuk van de oplossing is doorgevoerd (of was dat al zo?).
> 
> Zijn jullie akkoord met hoe het nu gemodelleerd is en werkt? In een kadastraalonroerendezaak heeft adressen
> 
> 1. veld adresregel3 in de specificaties, maar die zal nooit worden opgenomen in een response
> 2. veld land in de specificaties, en zal die altijd worden gevuld met code 6030 en waarde "Nederland"

Deze oplossing is vorige week door Rik in de specificaties aangebracht (#711). Ik vind dat een uitstekende oplossing. 

Volgens mij zijn we akkoord met deze oplossing en gaan we de specificaties niet meer aanpassen om een component BinnenlandsAdres te introduceren zoals eerder voorgesteld. 

@fsamwel Wat mij betreft is deze Done en kan gesloten worden. Als je het daarmee eens bent wil jij dat dan doen ?

**Comment by rhengeveld** [comment]
En laat dan ook meteen maar weten of we Nederland nu wél of niet in het binnenlandse adres willen, dan is dat ook duidelijk en zal ik (als dat nog nodig is) de implementatie hierop aanpassen 😉

**Comment by kad-hebbim** [comment]
Voor versie 1.2.0 wordt Nederland nu niet in het binnenlands adres teruggegeven. Mochten we dit toch nog anders willen, kunnen we dat wel in een 1.2.x versie aanpassen.
