### ISSUE TITLE
Aanpassingen n.a.v. testgevallen. 

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#720]
Heb antwoord gekregen van Thijs op de lijst met ontbrekende gegevens bij de verschillende testgevallen en hieruit zijn 4 dingen gekomen:

-	Het veld beschikkingsbevoegdheid kan niet gevuld worden voor een nietnatuurlijkpersoon; heeft alleen betrekking op een natuurlijkpersoon.

-- In KadasterNietNatuurlijkPersoon wordt de description aangepast. Beschikkingbevoegdheid uit de waardelijst en opnemen in de description dat deze property nooit gevuld wordt bij de niet natuurlijk persoon. 

-	Het veld begrenzing wordt helemaal niet gevuld bij een aantekening en die zou weggelaten kunnen worden.

-- Property "begrenzing" in Aantekening deprecated verklaren. 

-	De velden einddatum en einddatumRecht kunnen niet gevuld worden voor een aantekening die gelinkt is aan een hypotheek/beslag.

Er komen 3 typen aantekeningen. 1 Zonder begrenzing eindatum en einddatumrecht. (hypotheek en beslag)  Aantekenin zonder begrenzing (privaatrechtelijke beperking) en 1 met einddatum en einddatumRecht en begrenzing  is deprecated.  (tenaamstelling. 

-	Het veld indicatieOorspronkelijkObject bij een aantekening zit niet meer in het model.

--  Deze property is al deprecated verklaard.

**Comment by fsamwel** [comment]
Hadden we eerder niet ook al eens geconstateerd dat identificatie en domein van een aantekening niet relevant is? Die hebben we, als ik het me goed herinner, er oorspronkelijk ingestopt t.b.v. het kunnen synchroniseren (voorloper van de event sourcing).
Dus volgens mij kunnen die ook op/naar depricated

Alleen in privaatrechtelijkebeperking is de identificatie (en bijbehorende domein) uiteraard wel nodig.

Nu we toch aparte aantekeningen componenten hebben en dingen depricated maken, zouden we deze ook mee kunnen nemen.

**Comment by fsamwel** [comment]
In de nieuwe structuur voor aantekening vind ik de componentnaam "AantekeningDeprecated" niet zo handig. Suggereert dat het gaat om een depricated aantekening. Waarom niet "AantekeningTenaamstelling"? Dat is namelijk de (enige) plek waar deze gebruikt wordt.

**Comment by rhengeveld** [comment]
Ondertussen heb ik de wijzigingen gemaakt in #722 geïmplementeerd. **Dit is beschikbaar op de acceptatieomgeving.** ✔️ 
Mochten componentnamen wijzigen dan pas ik dat wel weer aan 😉

**Comment by JohanBoer** [comment]
> In de nieuwe structuur voor aantekening vind ik de componentnaam "AantekeningDeprecated" niet zo handig. Suggereert dat het gaat om een depricated aantekening. Waarom niet "AantekeningTenaamstelling"? Dat is namelijk de (enige) plek waar deze gebruikt wordt.

In feite is deze ook deprecated. Het is een extensie op Aantekening met 2 deprecated properties. Je wilt niet dat dit component in in de toekomst ergens anders wordt toegepast. Sterker nog, je wilt hem in de toekomst ook niet meer in de Tenaamstelling gebruiken. Dat doen we nu alleen om een breaking change te voorkomen.

Maar als jullie het niet met me eens zijn, geef maar een seintje, dan pas ik hem aan.

**Comment by JohanBoer** [comment]
> Alleen in privaatrechtelijkebeperking is de identificatie (en bijbehorende domein) uiteraard wel nodig.
> 
> Nu we toch aparte aantekeningen componenten hebben en dingen depricated maken, zouden we deze ook mee kunnen nemen.

Dat betekent dat ik deze verplaats van AantekeningBasis naar Aantekening en ze niet deprecated verklaar. 

Of zijn ze eigenlijk in privaatrechtelijkeBerperking ook niet nodig en moet ik ze verplaatsen én deprecated verklaren ?

**Comment by MelvLee** [comment]
> 
> 
> In de nieuwe structuur voor aantekening vind ik de componentnaam "AantekeningDeprecated" niet zo handig. Suggereert dat het gaat om een depricated aantekening. Waarom niet "AantekeningTenaamstelling"? Dat is namelijk de (enige) plek waar deze gebruikt wordt.

Ik ben het met Frank eens om een andere naam te gebruiken dan AantekeningDeprecated. Je krijgt dan een class met deze naam. Als een consumer in zijn development proces een check heeft dat nieuwe code geen deprecated code mag aanroepen, dan kan hij geen nieuwe code meer committen die deze class gebruiken

**Comment by fsamwel** [comment]
@JohanBoer @MelvLee weten jullie nog hoe het zat met aantekening identificatie en domein? Was die ergens voor nodig of kan die er ook uit (behalve als depricated bij tenaamstelling)

**Comment by JohanBoer** [comment]
> @JohanBoer @MelvLee weten jullie nog hoe het zat met aantekening identificatie en domein? Was die ergens voor nodig of kan die er ook uit (behalve als depricated bij tenaamstelling)

Ik kan me geen discussie over identifcatie en domein herinneren in relatie tot de privaatrechtelijke aantekening. Mischien kan @HildeVos hier uitsluitsel (laten) geven ?

**Comment by rhengeveld** [comment]
Er staat mij iets bij dat we aantekeningen gekoppeld aan een onroerende zaak niet direct vanuit de bron kunnen ophalen, enkel via de onroerende zaak. Een aantekening met identificatie en _self_ link heeft dan dus erg weinig zin. 
Ik durf echter niet met zekerheid te stellen dat privaatrechtelijke beperkingen hier een uitzondering op zijn ivm het nieuwe IMKAD model type. Ik denk wel dat @kad-hebbim uitsluitsel kan geven op dit aantekening-identificatie verhaal 😉

**Comment by kad-hebbim** [comment]
Het klopt inderdaad dat we deze privaatrechtelijkebeperkingen alleen via de onroerendezaak kunnen ophalen. 

De identificatie van een Aantekening moet denk ik wel behouden blijven, aangezien we een privaatrechtelijkebeperking (welke een allOf relatie heeft naar een Aantekening) ook los kunnen bevragen middels het endpoint: `/kadastraalonroerendezaken/{kadastraalobjectidentificatie}/privaatrechtelijkebeperkingen/{id}`
