### ISSUE TITLE
waarde voor koppelingswijze komt niet overeen met waarde volgens gepubliceerde tabel

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#723]
/kadastraalonroerendezaken/76870487970000 bevat in het antwoord:
```
"adressen" {
            "koppelingswijze": {
                "code": "ADM_GEO",
                "waarde": "administratiefgeometrisch"
            }
}
```

Volgens https://www.kadaster.nl/schemas/waardelijsten/Koppelingswijze/ hoort bij de code "ADM_GEO" de waarde "administratief en geometrisch"

**Comment by rhengeveld** [comment]
Ik vermoed dat dit aan de bron ligt, gezien ontvangen codes en waardes van waardelijsten 1 op 1 worden overgenomen van de bron. @kad-hebbim kan jij hiernaar kijken?

**Comment by kad-hebbim** [comment]
Aangepast.
