### ISSUE TITLE
naamvelden niet correct gevuld bij zoeken

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#725]
/kadasternatuurlijkpersonen/50550743 levert:
```
    "naam": {
        "geslachtsnaam": "Jansens",
        "voornamen": "Sidonia",
        "aanschrijfwijze": "S. Jansens",
        "aanhef": "Geachte mevrouw Jansens",
        "gebruikInLopendeTekst": "mevrouw Jansens"
    },
```

/kadasternatuurlijkpersonen?q=Sidonia%20jansens levert dezelfde persoon, maar de naamvelden zijn anders gevuld:
```
                "naam": {
                    "geslachtsnaam": "Jansens",
                    "voornamen": "Sidonia",
                    "aanhef": "Geachte S.",
                    "gebruikInLopendeTekst": "S."
                },
```

1. aanschrijfwijze ontbreekt
2. aanhef en gebruikInLopendeTekst zijn niet volledig samengesteld (geslacht en geslachtsnaam ontbreken)

**Comment by fsamwel** [comment]
ook het voorvoegsel ontbreekt in de naamvelden:
```
                "naam": {
                    "geslachtsnaam": "Goede",
                    "voornamen": "Christiaan",
                    "voorvoegsel": "de",
                    "aanhef": "Geachte C.",
                    "gebruikInLopendeTekst": "C."
                },
```

**Comment by rhengeveld** [comment]
Hmmm 🤔 ik dacht dat ik nog maar 1 plek waar _aanschrijfwijze_, _aanhef_ en _gebruikInLopendeTekst_ bepaald worden. 
Dus ik vermoed dat dit te maken heeft met een verschil in _"aanduiding naamgebruik"_ vanuit de bron. Ik ga het uitzoeken.

**Comment by fsamwel** [comment]
Net zoiets gebeurt bij de adressen velden in zoekresultaten. Daarin ontbreekt straat en woonplaats. Krijg je die ook niet uit je bron voor zoeken?

Bijv. /kadasternatuurlijkpersonen?q=Christiaan%20de%20Goede:
```
                "woonadres": {
                    "huisnummer": 2,
                    "postcode": "6466VR",
                    "adresregel1": "2",
                    "adresregel2": "6466VR",
                    "land": {
                        "code": "6030",
                        "waarde": "Nederland"
                    }
                },
```

**Comment by rhengeveld** [comment]
Ok, dit ligt aan een 2-tal factoren:
1. De bron die we in dit geval voor persoonsgegevens gebruiken levert geen _"aanduidingNaamgebruik"_
2. Er blijkt nu dat ik vergeten was de geslachtsaanduiding vanuit de bron over te nemen

Voor (1) wordt nu standaard _"Eigen geslachtsnaam"_ gebruikt bij het zoeken naar personen en voor (2) wordt nu het geslacht overgenomen. Daarmee krijgen we:
```json
                "geslachtsaanduiding": "vrouw",
                "naam": {
                    "geslachtsnaam": "Jansens",
                    "voornamen": "Sidonia",
                    "aanschrijfwijze": "S. Jansens",
                    "aanhef": "Geachte mevrouw Jansens",
                    "gebruikInLopendeTekst": "mevrouw Jansens"
                },
```

Standaard _"Eigen geslachtsnaam"_ gebruiken is uiteraard op de lange termijn niet wenselijk. Gelukkig werken we in de achtergrond al aan een update van onze bron van onroerende zaken. Naast dat we daarmee binnenkort in 1 response makkelijk _**alle**_ onroerende zaken van een persoon kunnen opvragen, bevat deze response óók alle persoonsgegevens inclusief _"aanduidingNaamgebruik"_. Standaard _"Eigen geslachtsnaam"_ is dan niet meer nodig bij het zoeken naar personen 😊

**Comment by fsamwel** [comment]
@CathyDingemanse de zoekresultaten van Kadasterpersonen bevat nu ook de naamvelden zoals aanschrijfwijze. Maar bij zoeken komt aanduiding naamgebruik niet geleverd door de bron. Vind je dat we de aanschrijfwijze dan moeten leveren op basis van de aanname dat het "eigen" is (geen partnernaam opgenomen), met als risico dat zoeken van een persoon een andere aanschrijfwijze levert dan raadplegen van dezelfde persoon? Of moeten we het gegeven dan helemaal niet leveren?
(bij BRP had ik niet getwijfeld, maar hier gaat het om "comfortgegevens" die toch al niet authentiek en actueel zijn)

N.B. nu is het zo gebouwd dat er altijd de aanschrijfwijze wordt geleverd met aanname aanduiding naamgebruik is "eigen"

**Comment by fsamwel** [comment]
@rhengeveld @kad-hebbim hebben jullie ook gekeken naar de mappen van de adressen bij zoeken? Straat en woonplaats ontbreken daarin. Worden die ook niet geleverd door de bron?

**Comment by rhengeveld** [comment]
Straat kan ik zo snel niet vinden, woonplaats wel. Pakken we op voor v1.2.1.x 🙂

**Comment by rhengeveld** [comment]
Release 1.2.1.x staat op productie, dus dit is als het goed is opgelost. Kan je hier naar kijken @fsamwel?
