### ISSUE TITLE
IMPEDIMENT:  Verschil tussen genereervariant en domain.yaml.

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#728]
Waarschijnlijk is de genereervariant niet automatisch gegenereerd nadat ik #724 heb gemerged op develop (is mij niet opgevallen. 

Ik zie nu op de develop dat in de domain.yaml een component AantekeningTenaamstelling is opgenomen terwijl dit in de genereervariant nog AantekeningDeprecated heet. 

Dat maakt me een beetje zenuwachtig. 

@ Melvin, kan jij  de genereerstap op develop aanschoppen zodat de genereervariant aangemaakt is. 
@kad-hebbim en @rhengeveld Kunnen jullie checken of er meer verschillen zitten tussen de yaml waar jullie op gewerkt hebben en de genereervariant die Melvin straks klaar zet op develop ?

**Comment by rhengeveld** [comment]
Gelukkig heb ik de specificatie redelijk vaak bijgehouden, de enige wijzigingen die ik nog te verwerken had:
* `AantekeningDeprecated` hernoemd naar `AantekeningTenaamstelling`
* Velden _domein_ en _identificatie_ zijn verplaatst van `AantekeningBasis` naar `Aantekening`

Tevens kwam ik er bij toeval achter dat de aantekeningen bij een hypotheek onvolledige mapping hadden en daardoor velden mistten, dit is ook meteen opgelost. **Deze wijzigingen komen zometeen naar de acceptatieomgeving.**
