### ISSUE TITLE
De description van 'overgangsgrootte' in 'filliatie' voldoet niet voor een samenvoeging

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#740]
De description van 'overgangsgrootte' binnen het component 'filliatie' is volgens mij alleen correct voor een splitsing. Voor een samenvoeging is deze denk ik niet correct. Wellicht kun je dit wel heel eenvoudig oplossen door er:

_'De oppervlakte van het (gedeelte van het) oude perceel dat is opgegaan in de nieuwe Onroerende zaak.'_

van te maken.

**Comment by JohanBoer** [comment]
@CathyDingemanse : Jij gaat over de descriptions. Zie voorstel Robert.

**Comment by CathyDingemanse** [comment]
@HildeVos, kunnen wij hier even samen naar kijken? Het gaat toch niet altijd over een perceel?
Voorstel: "De oppervlakte van (het gedeelte van) de oude kadastraal onroerende zaak die is opgegaan in de nieuwe onroerende zaak."
