### ISSUE TITLE
Pas releasenotes aan en voeg gerelateerd issue toe 

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#760]
Check ook of er known issues (problemen die in deze release wel een probleem opleveren maar nog niet opgelost zijn.) zijn.

**Comment by JohanBoer** [comment]
Ik ben mij niet bewust van known issues die in de releasenotes moeten worden opgenomen. Wie wel ?

**Comment by fsamwel** [comment]
nog niet. release 1.3 moet nog worden opgeleverd en getest. Pas als dat is afgerond weten we of we known issues meenemen naar productie
