### ISSUE TITLE
description bij /kadastraalonroerendezaken niet correct

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#762]
>Het zoeken van kadastraal onroerende zaken door exact één van de volgende categorieën parameters op te geven. Het combineren van parameters uit verschillende categorieën is niet toegestaan.
>
>- Kadastrale aanduiding
>- Ingeschreven persoon als zakelijk gerechtigde
>    - burgerservicenummer (verplicht)
>    - typegerechtigde (optioneel)
>- Niet ingeschreven persoon of niet natuurlijk persoon als zakelijk gerechtigde
>    - kadasterpersoonidentificatie (verplicht)
>    - typegerechtigde (optioneel)
>- Adres
>    - postcode (verplicht)
>    - huisnummer (optioneel)
>    - huisletter (optioneel)
>    - huisnummertoevoeging (optioneel)
>
>Met gebruik van de parameter expand kunnen zakelijkgerechtigden direct worden meegeladen.

Hierin staan veldnamen die niet meer correct zijn:
- typegerechtigde : zakelijkGerechtigde__type
- kadasterpersoonidentificatie : persoon__identificatie

Ook de toelichting op expand is niet meer compleet. Naast zakelijkGerechtigden kunnen ook privaatrechtelijkeBeperkingen worden meegeladen.

**Comment by JohanBoer** [comment]
Ook de nummeraanduidingIdentificatie was nog niet opgenomen in deze description.

**Comment by CathyDingemanse** [comment]
de toelichting was:
Met gebruik van de parameter expand kunnen zakelijkgerechtigden direct worden meegeladen.

De toelichting wordt:
Als je de expand parameter gebruikt kun je zakelijkGerechtigden en privaatrechtelijkeBeperkingen direct meeladen.
