### ISSUE TITLE
Overzicht appartementsrechten

### ISSUE THREAD

**Issue by IrenaDro** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#763]
Als GIS specialist wil ik een perceel in de kaart kunnen selecteren (wordt via WFS van PDOK gedaan) en indien het recht gesplitst is in appartementsrechten alle appartementsrechten behorend bij het geselecteerde perceel kunnen inzien zodat van de afzonderlijke appartementsrechten via identificatie of kadastrale aanduiding de overige informatie via BRK Bevragen API kan worden opgevraagd. 

**Acceptatiecriteria**
- in de BRK API dient een mogelijkheid te zijn om via de identificatie of de kadastrale aanduiding van een perceel dat gesplitst is in appartementsrechten deze appartementsrechten op te vragen. Op dit moment kan de raadpleger slechts via adres of kadastrale aanduiding de informatie van een appartementsrecht raadplegen. De wens is om dit te kunnen doen door een klik in de kaart. De huidige WFS geeft bij een klik in de kaart slecht de kadastrale aanduiding/identificatie van het grondperceel. 

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by CathyDingemanse** [comment]
Beste Irena, in versie 1.3 leveren we de appartementsrechten op die bij ieder grondperceel ohoren en leveren we bij ieder appartementsrecht het bijbehorend grondperceel. Ook beogen wij via via voor- en achterwaartse filiatie "vervallen" percelen raadpleegbaar te maken.
Kijk je met ons mee of dit jouw vraag beantwoord?

Wat nog op de backlog staat is het raadplegen van kadastrale objecten objecten via de kaart. Dat staat voor volgend jaar op de realisatieagenda.

**Comment by IrenaDro** [comment]
Beste Cathy, 
Dank je voor de snelle reactie. Als ik de roadmap goed heb gelezen, zal versie 1.3 begin 2021 beschikbaar komen. Klopt dat? 
We kijken met belangstelling uit naar deze versie. Zullen deze zeker ook goed testen. 

Voor het raadplegen van de objecten op de kaart gebruiken wij nu de PDOK services. De informatie uit die services hanteren we dan als input voor de BRK Bevragen API call.

**Comment by CathyDingemanse** [comment]
Als ik de roadmap goed heb gelezen, zal versie 1.3 begin 2021 beschikbaar komen. Klopt dat?


> Dank je voor de snelle reactie. Als ik de roadmap goed heb gelezen, zal versie 1.3 begin 2021 beschikbaar komen. Klopt dat?

Ja dat is idd de planning!
