### ISSUE TITLE
hoe vormgeven links naar stukdelen en stukken in zakelijkGerechtigde

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#766]
zakelijkGerechtigde heeft op 3 plekken in de resource stukdelen (vermeld in en gebaseerd op) en stukken. In _links staat het op één plek. hoe moeten deze worden opgenomen in _links?
Eén template met generieke verwijzing naar de identificatie of array met meerdere templates of meerdere links?

**Comment by fsamwel** [comment]
in [feature url-templating](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/master/features/uri-templating.feature) staat hierover:
```
    - gebruik {propertynaam} als placeholder in een resource path. propertynaam is:
      - de naam van een property van de resource of
      - de naam van een property van een gegevensgroep van de resource.
        Gebruik in dit geval de naam van de gegevensgroep gevolgd door een punt als prefix, bijv. persoon.identificatie, woonadres.adresIdentificatie
```

**Comment by fsamwel** [comment]
voor een onroerende zaak zien de links er op dit moment bijvoorbeeld zo uit:
 ```
   "_links": {
        "self": {
            "href": "/kadastraalonroerendezaken/76870487970000"
        },
        "zakelijkGerechtigden": [
            {
                "href": "/kadastraalonroerendezaken/76870487970000/zakelijkgerechtigden/{zakelijkGerechtigdeIdentificaties}",
                "templated": true
            }
        ],
        "privaatrechtelijkeBeperkingen": [
            {
                "href": "/kadastraalonroerendezaken/76870487970000/privaatrechtelijkebeperkingen/{privaatrechtelijkeBeperkingIdentificaties}",
                "templated": true
            }
        ],
        "hypotheken": [
            {
                "href": "/kadastraalonroerendezaken/76870487970000/hypotheken/{hypotheekIdentificaties}",
                "templated": true
            }
        ]
    }
```

**Comment by fsamwel** [comment]
mogelijke modellering: alleen links "stukdelen" en "stukken" opnemen. De gebruiker moet dan zelf bedenken hoe de parameter in de template moet worden gevuld:
```
    "_links": {
        "self": {
            "href": "/kadastraalonroerendezaken/76870487970000/zakelijkgerechtigden/30493367"
        },
        "persoon": {
            "href": "/kadasternatuurlijkpersonen/70882239"
        },
        "betrokkenPartner": {
            "href": "/kadasternatuurlijkpersonen/50550743"
        },
        "betrokkenSamenwerkingsverband": {
            "href": "/kadasternietnatuurlijkpersonen/71291440"
        },
        "betrokkenGorzenEnAanwassen": {
            "href": "/kadasternietnatuurlijkpersonen/71291493"
        },
        "stukdelen": "/stukdelen/{stukdeelIdentificatie}",
        "stukken": "/stukken/{stukIdentificatie}"
    }
```

**Comment by fsamwel** [comment]
mogelijke modellering: verschillende varianten links met elk mogelijk meerdere templates:
```
    "_links": {
        "self": {
            "href": "/kadastraalonroerendezaken/76870487970000/zakelijkgerechtigden/30493367"
        },
        "persoon": {
            "href": "/kadasternatuurlijkpersonen/70882239"
        },
        "betrokkenPartner": {
            "href": "/kadasternatuurlijkpersonen/50550743"
        },
        "betrokkenSamenwerkingsverband": {
            "href": "/kadasternietnatuurlijkpersonen/71291440"
        },
        "betrokkenGorzenEnAanwassen": {
            "href": "/kadasternietnatuurlijkpersonen/71291493"
        },
        "stukken":  {
            "href": "/stukken/{zakelijkRecht.stukIdentificaties}",
            "templated": true
        },        
        "stukdelen":  [{
              "href": "/stukken/{zakelijkRecht.isGebaseerdOpStukdeelIdentificatie}",
              "templated": true
            }, {
              "href": "/stukken/{zakelijkRecht.isVermeldInStukdeelIdentificaties}",
              "templated": true
            },{
              "href": "/stukken/{tenaamstelling.isGebaseerdOpStukdeelIdentificaties}",
              "templated": true
            }, {
              "href": "/stukken/{tenaamstelling.isVermeldInStukdeelIdentificaties}",
              "templated": true
            },{
              "href": "/stukken/{erfpachtCanon.isGebaseerdOpStukdeelIdentificaties}",
              "templated": true
            }, {
              "href": "/stukken/{erfpachtCanon.isVermeldInStukdeelIdentificaties}",
              "templated": true
            }]
    }
```

**Comment by fsamwel** [comment]
mogelijke modellering: specifieke links:
    "_links": {
        "self": {
            "href": "/kadastraalonroerendezaken/76870487970000/zakelijkgerechtigden/30493367"
        },
        "persoon": {
            "href": "/kadasternatuurlijkpersonen/70882239"
        },
        "betrokkenPartner": {
            "href": "/kadasternatuurlijkpersonen/50550743"
        },
        "betrokkenSamenwerkingsverband": {
            "href": "/kadasternietnatuurlijkpersonen/71291440"
        },
        "betrokkenGorzenEnAanwassen": {
            "href": "/kadasternietnatuurlijkpersonen/71291493"
        },
        "zakelijkRechtIsGebaseerdOpStukdeel": {
            "href": "/stukken/{zakelijkRecht.isGebaseerdOpStukdeelIdentificatie}",
            "templated": true
        },
        "zakelijkRechtIsVermeldInStukdeel": {
            "href": "/stukken/{zakelijkRecht.isVermeldInStukdeelIdentificatie}",
            "templated": true
        },
        "zakelijkRechtStukken":  {
            "href": "/stukken/{zakelijkRecht.stukIdentificaties}",
            "templated": true
        }
        "tenaamstellingIsGebaseerdOpStukdeel": {
            "href": "/stukken/{tenaamstelling.isGebaseerdOpStukdeelIdentificatie}",
            "templated": true
        },
        "tenaamstellingIsVermeldInStukdeel": {
            "href": "/stukken/{tenaamstelling.isVermeldInStukdeelIdentificatie}",
            "templated": true
        },
        "erfpachtCanonIsGebaseerdOpStukdeel": {
            "href": "/stukken/{erfpachtCanon.isGebaseerdOpStukdeelIdentificatie}",
            "templated": true
        },
        "erfpachtCanonIsVermeldInStukdeel": {
            "href": "/stukken/{erfpachtCanon.isVermeldInStukdeelIdentificatie}",
            "templated": true
        },
    }

**Comment by fsamwel** [comment]
- we kiezen voor de eerste variant: links "stukken" en "stukdelen"
- reden: dit is het eenvoudigst, meest duidelijk en minste werk voor de gebruikers
(variant 2 is onduidelijk welke template waarvoor is, variant 3 levert veel links met veel werk voor developer om te interpreteren welke waarvoor is)
- bij ZakelijkGerechtigdeLinks voegen we description toe met korte toelichting
- feature wordt aangepast, zodat deze variant wordt toegevoegd
(vervangen van gegevensgroep-optie kan niet, want die wordt al gebruikt in BAG API)

Frank maakt pull request voor specificaties
Melvin maakt pull request voor de feature

**Comment by JohanBoer** [comment]
We hebben het niet expliciet besproken, maar volgens mij is het verwarrend als de links naar stukdelen bij andere onderdelen anders worden toegepast dan in Zakelijkgerechtigde. Ik heb dus overal de 2 links naar "isGebaseerdOpStukdelen" en "IsVermeldInStukdelen" aangepast naar "stukdelen". @fsamwel en @MelvLee  zijn jullie het daarmee eens ?

**Comment by fsamwel** [comment]
ik vind je voorstel goed
