### ISSUE TITLE
Is overgangsgrootte bij de filiatie te leveren ? 

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#771]
Marcel zoekt uit of het kadaster de overgangsgrootte bij filiatie kan leveren. 

In het IMKAD is dit element terug te vinden in de objecttypen "OnroerendeZaakFiliatie" en "VoorwaartseOnroerendeZaakFiliatie".

Afspraak: Release 1.3 wordt pas definitief als deze vraag beantwoordt en verwerkt is.

**Comment by kad-hebbim** [comment]
Overgangsgrootte wordt niet uitgeleverd door onze bron en kunnen we dus ook niet leveren.
