### ISSUE TITLE
Implementeren endpoint : /stukken/{stukidentificatie}

### ISSUE THREAD

**Issue by kad-hebbim** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#776]

**Comment by fsamwel** [comment]
@kad-hebbim @rhengeveld ik heb in alle testgevallen geen data op stukken voor de volgende velden:

- aard
- bewaardersVerklaring
- equivalentieVerklaarder
- indicatieTekeningBijgevoegd
- kadasterverzoeken
- status
- toelichtingBewaarder

kan je deze nog toevoegen? Of komen hier ook in productie geen waarden op voor?

**Comment by kad-hebbim** [comment]
@fsamwel Heb deze vraag intern uitgezet voor voorbeelden vanuit productie om te kijken of bepaalde velden uberhaupt wel gevuld worden...

**Comment by fsamwel** [comment]
@kad-hebbim is er al wat meer duidelijk over deze properties waar geen testdata voor is?

**Comment by kad-hebbim** [comment]
Is doorgevoerd voor:
TerinschrijvingAangebodenStuk: 18020223007191

**Comment by fsamwel** [comment]
@kad-hebbim moet dit al zichtbaar zijn voor mij op de acceptatieomgeving?

Ik krijg nog:
```
{
    "identificatie": "18020223007191",
    "stukType": "Aangebodenstuk",
    "domein": "NL.IMKAD.TIAStuk",
    "stukdeelIdentificaties": [
        "1000854514"
    ],
    "tijdstipAanbieding": "1998-12-31T00:00:00+01:00",
    "_links": {
        "self": {
            "href": "/stukken/18020223007191"
        },
        "stukdelen": [
            {
                "href": "/stukdelen/{stukdeelIdentificaties}",
                "templated": true
            }
        ]
    }
}
```

**Comment by kad-hebbim** [comment]
> @kad-hebbim moet dit al zichtbaar zijn voor mij op de acceptatieomgeving?
> 
> Ik krijg nog:
> 
> ```
> {
>     "identificatie": "18020223007191",
>     "stukType": "Aangebodenstuk",
>     "domein": "NL.IMKAD.TIAStuk",
>     "stukdeelIdentificaties": [
>         "1000854514"
>     ],
>     "tijdstipAanbieding": "1998-12-31T00:00:00+01:00",
>     "_links": {
>         "self": {
>             "href": "/stukken/18020223007191"
>         },
>         "stukdelen": [
>             {
>                 "href": "/stukdelen/{stukdeelIdentificaties}",
>                 "templated": true
>             }
>         ]
>     }
> }
> ```

Jij bent snel :) 
Is nu net zichtbaar op de acceptatieomgeving.

**Comment by fsamwel** [comment]
@kad-hebbim zie het nu inderdaad. Dank!

Bij kadasterverzoeken.redenenVerzoek krijg ik nu:
```
            [
                {
                    "redenOmschrijving": "Extra uitleg",
                    "reden": {
                        "code": "23",
                        "waarde": "Situatieschets tbv vorming administratieve grens onduidelijk"
                    }
                },
                {
                    "reden": {
                        "code": "31",
                        "waarde": "Andere reden"
                    }
                }
            ]
```

hier heeft dus de reden met code 23 een redenOmschrijving, terwijl de reden met code 31 (Andere reden) geen redenOmschrijving.
De specificaties zeggen bij redenOmschrijving "De omschrijving van de reden voor een kadasterverzoek die afwijkt van de standaard redenen die kunnen worden opgegeven. Bij opgave van de reden is voor overig gekozen."

De data zoals ik die nu krijg mag dus eigenlijk niet. Of staat het verkeerd in de specificaties?

**Comment by fsamwel** [comment]
Hoe kan het trouwens zijn dat de andere stukken geen status hebben? Bovengenoemde stuk heeft status "ingeschreven". Zijn de andere stukken niet ingeschreven?

**Comment by kad-hebbim** [comment]
Bovenstaande is aangepast.

**Comment by fsamwel** [comment]
@kad-hebbim /stukken/18020223007191 geeft nu:
```
    "kadasterverzoeken": [
        {
            "aard": {
                "code": "1",
                "waarde": "Attendering CRL vermelding"
            },
            "redenenVerzoek": [
                {
                    "reden": {
                        "code": "23",
                        "waarde": "Situatieschets tbv vorming administratieve grens onduidelijk"
                    }
                },
                {
                    "reden": {
                        "code": "31",
                        "waarde": "Andere reden"
                    }
                }
            ]
        }
    ],
```

redenOmschrijving ontbreekt dus denk ik nog bij de "Andere reden"

**Comment by kad-hebbim** [comment]
> @kad-hebbim /stukken/18020223007191 geeft nu:
> 
> ```
>     "kadasterverzoeken": [
>         {
>             "aard": {
>                 "code": "1",
>                 "waarde": "Attendering CRL vermelding"
>             },
>             "redenenVerzoek": [
>                 {
>                     "reden": {
>                         "code": "23",
>                         "waarde": "Situatieschets tbv vorming administratieve grens onduidelijk"
>                     }
>                 },
>                 {
>                     "reden": {
>                         "code": "31",
>                         "waarde": "Andere reden"
>                     }
>                 }
>             ]
>         }
>     ],
> ```
> 
> redenOmschrijving ontbreekt dus denk ik nog bij de "Andere reden"

Opgelost

**Comment by fsamwel** [comment]
> Hoe kan het trouwens zijn dat de andere stukken geen status hebben? Bovengenoemde stuk heeft status "ingeschreven". Zijn de andere stukken niet ingeschreven?

@kad-hebbim hoe zit dit? Kan (in productie) een stuk geen status hebben? Wat betekent dat voor een gebruiker?

**Comment by fsamwel** [comment]
heropend, want de lege statussen vraag staat nog open

**Comment by kad-hebbim** [comment]
> > Hoe kan het trouwens zijn dat de andere stukken geen status hebben? Bovengenoemde stuk heeft status "ingeschreven". Zijn de andere stukken niet ingeschreven?
> 
> @kad-hebbim hoe zit dit? Kan (in productie) een stuk geen status hebben? Wat betekent dat voor een gebruiker?

Dit kan in productie niet voorkomen. Daar heeft een stuk altijd een status.

**Comment by fsamwel** [comment]
@kad-hebbim voeg je de statussen nog toe aan dit stuk? 

Helemaal leuk wanneer we verschillende statussen hebben in de verschillende stukken. Of kan dat niet realistisch, omdat de andere statussen varianten zijn op "voorlopig of nog niet ingeschreven" (1 en 4) en "gesloten" (de rest). M.a.w. kan een stuk dat genoemd is in stukIdentificaties of via een stukdeel in isGebaseerdOpStukdeelIdentificaties/isVermeldInStukdeelIdentificaties in onze resources niet een dergelijke status hebben? Dus kunnen in stukIdentificaties/isGebaseerdOpStukdeelIdentificaties/isVermeldInStukdeelIdentificaties ook voorlopige of vervallen stukken worden genoemd?

**Comment by fsamwel** [comment]
@kad-hebbim stuk 20170102999999 heeft geen status (kan begrijp ik niet in productie voorkomen dus is niet-valide data), alle overige stukken hebben status 3 "Ingeschreven". Kan een stuk (waar wij een identificatie/link naartoe leveren in een van de andere endpoints) ook een andere status hebben dan "Ingeschreven"? Dan zou ik die graag ook in de testdata hebben. 
Zo niet, wat is het nut dan van de status meeleveren?

**Comment by kad-hebbim** [comment]
20170102999999 betreft een Kadasterstuk en moet niet teruggegeven worden.
Opgelost in testgeval.

**Comment by MelvLee** [comment]
opgelost
