### ISSUE TITLE
Implementeren endpoint: /stukdelen/{stukdeelidentificatie}

### ISSUE THREAD

**Issue by kad-hebbim** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#777]

**Comment by fsamwel** [comment]
@kad-hebbim in /kadastraalonroerendezaken/22590043870000/zakelijkgerechtigden/90495201 is erfpachtCanon.isGebaseerdOpStukdeelIdentificatie==tenaamstelling.aantekeningen.isGebaseerdOpStukdeelIdentificatie
Is dat een mappingfout? Of gewoon iets minder handige testdata?

**Comment by fsamwel** [comment]
@kad-hebbim @rhengeveld ik heb in alle testgevallen geen data op stukdelen voor de volgende velden:

- bedragTransactiesomLevering
- omschrijvingKadastraleObjecten
- omschrijvingTopografischeMutatie
- _links.kadastraalOnroerendeZaken

kan je deze nog toevoegen?

Op _links.kadastraalOnroerendeZaken had ik in ieder geval resultaten verwacht, want we hebben kadastraalonroerendezaken en zakelijkgerechtigden met stukdelen in het antwoord.

**Comment by kad-hebbim** [comment]
Deze vraag ook intern uitgezet. Zie #776 voor reden.

**Comment by fsamwel** [comment]
@kad-hebbim is er al wat meer duidelijk over deze properties waar geen testdata voor is? zelfde als voor #776)

**Comment by kad-hebbim** [comment]
Doorgevoerd in Stukdeel met id: 
1000854514

_De kadastraalOnroerendeZaken kunnen we niet leveren en dit veld zou op deprecated gezet moeten worden._

**Comment by fsamwel** [comment]
> De kadastraalOnroerendeZaken kunnen we niet leveren en dit veld zou op deprecated gezet moeten worden.

@kad-hebbim heb gaat hier om kadastraalOnroerendeZaken in een stukdeel, toch? Die is nieuw in v1.3 en kan dus verwijderd worden. Hoeft niet depricated. Of bedoel je kadastraalOnroerendeZaken op een andere plek?

@JohanBoer kan jij "kadastraalOnroerendeZaken: verwijderen uit StukdeelLinks?

**Comment by fsamwel** [comment]
> @kad-hebbim in /kadastraalonroerendezaken/22590043870000/zakelijkgerechtigden/90495201 is erfpachtCanon.isGebaseerdOpStukdeelIdentificatie==tenaamstelling.aantekeningen[0].isGebaseerdOpStukdeelIdentificatie==tenaamstelling.isGebaseerdOpStukdeelIdentificaties[0]
Is dat een mappingfout? Of gewoon iets minder handige testdata?

@kad-hebbim hier is nog niks aan veranderd. Is dit logische testdata, dus dat in productie ook beide vaak gelijk zijn? vanuit testperspectief is dat namelijk niet handig. Nu kan je het verschil niet zien tussen beide stukdeelidentificaties en dus niet zien of er goed gemaakt wordt

**Comment by kad-hebbim** [comment]
> 22590043870000

Stukdeel aangepast voor erfpachtcanon

**Comment by kad-hebbim** [comment]
> > @kad-hebbim in /kadastraalonroerendezaken/22590043870000/zakelijkgerechtigden/90495201 is erfpachtCanon.isGebaseerdOpStukdeelIdentificatie==tenaamstelling.aantekeningen[0].isGebaseerdOpStukdeelIdentificatie==tenaamstelling.isGebaseerdOpStukdeelIdentificaties[0]
> > Is dat een mappingfout? Of gewoon iets minder handige testdata?
> 
> @kad-hebbim hier is nog niks aan veranderd. Is dit logische testdata, dus dat in productie ook beide vaak gelijk zijn? vanuit testperspectief is dat namelijk niet handig. Nu kan je het verschil niet zien tussen beide stukdeelidentificaties en dus niet zien of er goed gemapt wordt

Stukdeel aangepast voor erfpachtcanon
