### ISSUE TITLE
Inconsistentie param namen

### ISSUE THREAD

**Issue by KayodeBakker** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#779]
In de BRK 1.2.0 en ook de toekomstige 1.3.0 versie zie ik dat de publiekrechtelijke beperking endpoint een andere casing heeft voor "kadastraalOnroerendeZaakIdentificatie" dan bij andere endpoints die namelijk "kadastraalonroerendezaakidentificatie". Wanneer een leverancier bevragingsmodellen wil hergebruiken (een groot aantal heeft immers alleen fields en kadastraalonroerendezaakidentificatie) dan dienen de params ook altijd dezelfde casing te hebben.

Graag verzoek ik om dit recht te zetten aangezien wij nu zelf een fix hiervoor moeten implementeren terwijl we liever herbruikbaar werken.

**Comment by fsamwel** [comment]
Dit is het gevolg van een gewijzigde keuze voor casino van parameters (vanuit de NL API strategie). Daarin is gezegd dat parameters camelCase moeten zijn. Dit hebben we doorgevoerd (gewijzigd) in de queryparameters, niet in de path-parameters (ik denk vanuit de aanname dat het niet uitmaakt hoe path-parameters geschreven worden, want die komen niet terug in daadwerkelijke requests of responses, alleen in de specificaties en (daardoor) in (gegenereerde) locale code).

@MelvLee en @kad-hebbim wat is de impact wanneer we dat nu in de specificaties aanpassen?

Ik denk dat dit niet een breaking change is. Klopt dat?

**Comment by MelvLee** [comment]
Het wijzigen van de casing in de naam van een path parameter introduceert geen breaking changes in de gegenereerde code

**Comment by JohanBoer** [comment]
> Het wijzigen van de casing in de naam van een path parameter introduceert geen breaking changes in de gegenereerde code

@MelvLee Introduceert dit ook geen changes voor de provider-implmentatie ? Ik denk het niet toch, dan is dit alleen maar ter documentatie....

@allen Gaan we dan ook de design decision aanpassen en en in alle andere API's de path-parameters in camelcase opnemen ?
Lijkt mij een klusje om in alle API's bij de eerstvolgende wijziging door te voeren, maar is dit een ABC-tje of moeten we het hier maandag even over hebben ?

**Comment by JohanBoer** [comment]
@kad-hebbim Zijn jullie met versie 1.3 het punt al gepasseerd dat dit nog mee kan of is dit nog te realiseren om mee te nemen in deze versie ? Als het mee kan zorg ik dat vandaag de spec aangepast wordt.

**Comment by KayodeBakker** [comment]
> Dit is het gevolg van een gewijzigde keuze voor casino van parameters (vanuit de NL API strategie). Daarin is gezegd dat parameters camelCase moeten zijn. Dit hebben we doorgevoerd (gewijzigd) in de queryparameters, niet in de path-parameters (ik denk vanuit de aanname dat het niet uitmaakt hoe path-parameters geschreven worden, want die komen niet terug in daadwerkelijke requests of responses, alleen in de specificaties en (daardoor) in (gegenereerde) locale code).
> 
> @MelvLee en @kad-hebbim wat is de impact wanneer we dat nu in de specificaties aanpassen?
> 
> Ik denk dat dit niet een breaking change is. Klopt dat?

Mogelijk is dat de reden maar ik denk eerder dat het komt omdat dat endpoint compleet afwijkt in opzet ten opzichten van de rest. Alle andere zoek endpoints hebben het als path param terwijl dit voorheen niet zo was. 

In beide gevallen ietwat nalatig.

**Comment by kad-hebbim** [comment]
> @kad-hebbim Zijn jullie met versie 1.3 het punt al gepasseerd dat dit nog mee kan of is dit nog te realiseren om mee te nemen in deze versie ? Als het mee kan zorg ik dat vandaag de spec aangepast wordt.

Dit kunnen we nog wel meenemen in versie 1.3. We zien de specs tegemoet.
