### ISSUE TITLE
erfpachtcanon stukIdentificaties niet gevuld

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#782]
/kadastraalonroerendezaken/76870482570000/zakelijkgerechtigden/20170717 bevat in erfpachtCanon: "isGebaseerdOpStukdeelIdentificatie": "1006561006"

Dan had ik in erfpachtCanon ook stukIdentificaties verwacht. Maar deze ontbreekt.

N.B. /stukdelen/1006561006" geeft een 404

**Comment by fsamwel** [comment]
/kadastraalonroerendezaken/22590043870000/zakelijkgerechtigden/90495201 levert in erfpachtCanon wel zowel het stukdeel als het stuk.
Vreemd dat het stuk bij /kadastraalonroerendezaken/76870482570000/zakelijkgerechtigden/20170717 ontbreekt

**Comment by kad-hebbim** [comment]
@fsamwel erfpachtcanon linkte niet naar het correcte stukdeel in de testdata. Dit is aangepast.
