### ISSUE TITLE
Toevoegen testdata gerelateerde stukken en stukdelen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#783]
Ik heb niet voor alle stukken of stukdelen relaties geschikte data gevonden. Is die er wel of kan die toegevoegd worden?

- zakelijkgerechtigden..tenaamstelling.aantekeningen.isVermeldInStukdeelIdentificaties
- zakelijkgerechtigden..erfpachtCanon.isVermeldInStukdeelIdentificaties
- zakelijkgerechtigden..zakelijkRecht.isVermeldInStukdeelIdentificaties
- beslagen..isVermeldInStukdeelIdentificaties
- privaatrechtelijkebeperkingen..isVermeldInStukdeelIdentificaties

**Comment by kad-hebbim** [comment]
Aan elk element is een tiastuk met 2 stukdelen toegevoegd.
