### ISSUE TITLE
Valuta bij Beslag bedragVordering

### ISSUE THREAD

**Issue by KayodeBakker** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#784]
Bij een response voor een beslag bevraging wordt bedragVordering meegeleverd. Deze bevat valuta(wat een waardelijst is) en kenmerkt over welk code/omschrijving het gaat. Tot zover heb ik echter nog geen voorbeeld gezien waar het niet neerkomt op de Euro. Mijn vraag o.a. is of het mogelijk is om iets anders dan Euro te krijgen en zo nee, waarom dit wordt opgenomen.

Daarnaast mocht dit wel kunnen, dan is het apart dat de koopsom van een kadastraalOnroerendeZaak geen valuta kenmerk bevat en alleen maar een som en jaar.

Graag hoor ik hier meer informatie over aangezien dit wat inconsistent of onnodig lijkt.

**Comment by KayodeBakker** [comment]
@fsamwel Wellicht voor jou ook interessant?

**Comment by fsamwel** [comment]
@kad-hebbim @HildeVos kunnen jullie dit beantwoorden?

**Comment by kad-hebbim** [comment]
@fsamwel Heb deze vraag intern uitgezet.

**Comment by KayodeBakker** [comment]
@kad-hebbim Is hier al meer duidelijkheid over?

**Comment by kad-hebbim** [comment]
@KayodeBakker & @fsamwel:
Heb antwoord gekregen:

> De koopsom zal altijd in euro’s zijn, de instructie intern is dat bedragen in andere valuta in de akte worden omgerekend naar euro’s bij de registratie.
 
> Het bedrag bij hypotheken of beslagen worden wel in andere valuta geregistreerd.

Wellicht dat we nog bij de koopsom kunnen vermelden dat de koopsom altijd in euro's is.

**Comment by fsamwel** [comment]
het is dan denk ik ook wel handig als we een testgeval hebben met hypotheek en beslag met bedrag in andere valuta.  Dan kunnen we aan client kant ook controleren dat deze (afwijkende) valuta correct getoond wordt.

**Comment by kad-hebbim** [comment]
@KayodeBakker & @fsamwel:
Testgevallen geupdated:
- hypotheek met andere valuta in object: 19560032970000
- beslag met andere valuta in object: 17150075470000
