### ISSUE TITLE
zoeken kadastraalonroerendezaken op burgerservicenummer geeft 404

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#785]
https://api.brk.acceptatie.kadaster.nl/esd/bevragen/v1/kadastraalonroerendezaken?burgerservicenummer=999991905

dit levert een 404:
```
{
    "type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_NotFound",
    "title": "Opgevraagde resource bestaat niet.",
    "status": 404,
    "detail": "Not Found",
    "instance": "/kadastraalonroerendezaken?burgerservicenummer=999991905",
    "code": "notFound"
}
```

exact hetzelfde endpoint, maar met andere query parameter (bijvoorbeeld postcode) levert wel antwoord (200) met kadastraalonroerendezaken.
Ik had dit hier ook verwacht, namelijk zaken 22310827210003, 76870482570000 en 65490485270000

Bijvoorbeeld /kadastraalonroerendezaken/22310827210003/zakelijkgerechtigden/90283613 heeft:           
```
                "persoon": {
                    "identificatie": "999991905",
                    "omschrijving": "Linda Haglund",
                    "type": "ingeschreven_natuurlijk_persoon"
                },
```

**Comment by kad-hebbim** [comment]
Opgelost.
