### ISSUE TITLE
Internal server error bij endpoint https://api.brk.acceptatie.kadaster.nl/esd/bevragen/v1

### ISSUE THREAD

**Issue by KayodeBakker** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#788]
Al enige paar uren vandaag kan ik geen bevragingen meer uitvoeren van het endpoint https://api.brk.acceptatie.kadaster.nl/esd/bevragen/v1 en de resources daarvan. Telkens krijg ik een internal server error terug.

Kan hier z.s.m. naar gekeken worden aangezien dit de ontwikkeling voor aansluiting in de weg zit?

Bedankt!

**Comment by KayodeBakker** [comment]
@JohanBoer 
@MelvLee 
@fsamwel 
@kad-hebbim

**Comment by kad-hebbim** [comment]
@KayodeBakker: ben er naar aan het kijken.

**Comment by KayodeBakker** [comment]
> @KayodeBakker: ben er naar aan het kijken.

Top!

**Comment by kad-hebbim** [comment]
@KayodeBakker: 
Als het goed is draait hij weer. Kun je dit bevestigen?
Bedankt!

**Comment by fsamwel** [comment]
bij mij doet hij het weer

**Comment by KayodeBakker** [comment]
Idem!
Dank je wel.
