### ISSUE TITLE
Als tester van een client wil ik extra testdata

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#789]
zodat ik kan testen dat de gegevens correct door mijn applicatie worden verwerkt en getoond op het scherm

kadasternatuurlijkpersonen:
- indicatieNietToonbareDiakriet
- postadres.adresregel3 en postadres.land
- postadres.postbusnummer
- geheimhoudingPersoonsgegevens
- heeftPartnerschap.datumSluiting
- heeftPartnerschap.datumOntbinding
- overlijden

kadaster niet-natuurlijk personen:
- beschikkingsbevoegdheid
- indicatieNietToonbareDiakriet
- postadres.huisletter
- postadres.adresregel3 en postadres.land
- woonadres.adresregel3 en postadres.land

ook zijn er relaties naar niet-natuurlijk personen /kadasternietnatuurlijkpersonen/71291493 en /kadasternietnatuurlijkpersonen/24268006 die nu een 404 opleveren. Is het mogelijk deze toe te voegen, of de relaties te laten verwijzen naar personen die wel bestaan?

publiekrechtelijke beperkingen:
- een beperking die meerdere onroerende zaken betreft
- 
hypotheken:
- aantekeningen.betreftGedeelteVanPerceel
- meer dan één aantekening
- meer dan één hypotheekhouders

beslagen:
- aantekeningen.betreftGedeelteVanPerceel
- meer dan één aantekening
- meer dan één beslagleggers

**Comment by fsamwel** [comment]
@kad-hebbim ik heb dit op (zeer) korte termijn nodig. We kunnen de applicatie die de API gebruikt nu niet volledig testen.

**Comment by kad-hebbim** [comment]
@fsamwel: de testomgeving is geupdated; zie hieronder:

**kadasternatuurlijkpersonen:**
•	indicatieNietToonbareDiakriet -> toegevoegd aan 50550743
•	postadres.adresregel3 en postadres.land -> toegevoegd aan 50550743
•	postadres.postbusnummer -> persoon met id=70882250 gecreeerd en daaraan toegevoegd
•	geheimhoudingPersoonsgegevens -> weg uit spec; persoon is afgeschermd, dus kunnen we niet raadplegen
•	heeftPartnerschap.datumSluiting -> krijgen we niet vanuit de bron; weg uit spec
•	heeftPartnerschap.datumOntbinding -> krijgen we niet vanuit de bron; weg uit spec
•	overlijden -> toegevoegd aan 70882250

**publiekrechtelijke beperkingen:**
•	een beperking die meerdere onroerende zaken betreft -> pb met id 3394 geldt nu voor onroerendezaken: 76870487970000 & 76870488070000 

**niet-natuurlijk personen:**
•	beschikkingsbevoegdheid -> toegevoegd aan 440650207
•	indicatieNietToonbareDiakriet -> toegevoegd aan 440650207
•	postadres.huisletter -> toegevoegd aan 440650207
•	postadres.adresregel3 en postadres.land
•	woonadres.adresregel3 en postadres.land

**hypotheken:**
•	aantekeningen.betreftGedeelteVanPerceel -> toegevoegd aan 17150075470000 met zhsid = 15479389
•	meer dan één aantekening -> 3 aantekeningen toegevoegd aan 17150075470000 met zhsid=15479389
•	meer dan één hypotheekhouders -> 71291493 toegevoegd als hypotheekhouder bij 17150075470000 met zhsid=15479389

**beslagen:**
•	aantekeningen.betreftGedeelteVanPerceel -> geldt alleen voor hypotheek; weg uit spec
•	meer dan één aantekening -> aantekening 140707594 toegevoegd aan zhsid=95377750
•	meer dan één beslagleggers -> 71291493 toegevoegd als beslaglegger bij 17150075470000 met zhsid=95377750

**Wat nog open staat:**
**niet-natuurlijk personen:**
•	postadres.adresregel3 en postadres.land
•	woonadres.adresregel3 en postadres.land

aanpassen van de specificaties; zal ik deze week pull request voor aanleveren.

**Comment by fsamwel** [comment]
@kad-hebbim super bedankt voor de testdata.

Op /kadastraalonroerendezaken/17150075470000/hypotheken/15479389 zie ik nu wel 3 aantekeningen, maar in geen daarvan zie ik betreftGedeelteVanPerceel.

```
    "aantekeningen": [
        {
            "aard": {
                "code": "39",
                "waarde": "Raadpleeg brondocument"
            },
            "omschrijving": "omschrijving over de hypotheek"
        },
        {
            "aard": {
                "code": "39",
                "waarde": "Raadpleeg brondocument"
            },
            "omschrijving": "en de tweede omschrijving over de hypotheek"
        },
        {
            "aard": {
                "code": "39",
                "waarde": "Raadpleeg brondocument"
            },
            "omschrijving": "en de derde omschrijving over de hypotheek"
        }
    ],
```

**Comment by fsamwel** [comment]
@kad-hebbim
**niet-natuurlijk personen:**
• beschikkingsbevoegdheid -> toegevoegd aan 440650207 --> ik zie nu in de specificaties staan, toegevoegd n.a.v. #720, dat "De property beschikkingsbevoegdheid is bij een KadasterNietNatuurlijkPersoon nooit gevuld." Is die opmerking toch onterecht? Of hebben we nu ten onrechte een testwaarde toegevoegd?
• postadres.adresregel3 en postadres.land --> heeft nog geen waarde in een van de testgevallen
• woonadres.adresregel3 en postadres.land --> heeft nog geen waarde in een van de testgevallen

**Comment by kad-hebbim** [comment]
> @kad-hebbim
> **niet-natuurlijk personen:**
> • beschikkingsbevoegdheid -> toegevoegd aan 440650207 --> ik zie nu in de specificaties staan, toegevoegd n.a.v. #720, dat "De property beschikkingsbevoegdheid is bij een KadasterNietNatuurlijkPersoon nooit gevuld." Is die opmerking toch onterecht? Of hebben we nu ten onrechte een testwaarde toegevoegd?
> • postadres.adresregel3 en postadres.land --> heeft nog geen waarde in een van de testgevallen
> • woonadres.adresregel3 en postadres.land --> heeft nog geen waarde in een van de testgevallen

beschikkingsbevoegdheid veld wordt idd niet gevuld bij een nietnatuurlijkpersoon. Deze zal ik weghalen.
de andere velden zal ik een testgeval voor toevoegen

**Comment by kad-hebbim** [comment]
Toevoegen:
• postadres.adresregel3 en postadres.land --> heeft nog geen waarde in een van de testgevallen
• woonadres.adresregel3 en postadres.land --> heeft nog geen waarde in een van de testgevallen

**Comment by kad-hebbim** [comment]
NNP: 71291443 heeft nu woon en postlocatie met die velden erin.

**Comment by MelvLee** [comment]
opgelost
