### ISSUE TITLE
kadasternatuurlijkpersonen geheimhoudingPersoonsgegevens verwijderen (depricated)

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#791]
property geheimhoudingPersoonsgegevens van een kadasternatuurlijkpersoon kan niet geleverd worden, omdat de API personen met geheimhoudingPersoonsgegevens niet zal leveren.

Zie https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/789#issuecomment-784052455:
> geheimhoudingPersoonsgegevens -> weg uit spec; persoon is afgeschermd, dus kunnen we niet raadplegen

dus moet geheimhoudingPersoonsgegevens depricated worden (en in toekomstige versie verwijderen)

@kad-hebbim heb ik je opmerking goed geïnterpreteerd?

**Comment by kad-hebbim** [comment]
Dat klopt inderdaad.

**Comment by JohanBoer** [comment]
Ook hier geldt toch dat ik dat dan ook in de specificatie aan moet brengen (net zoals bij #793 ) ? Of zie ik dat verkeerd ?

**Comment by kad-hebbim** [comment]
@JohanBoer klopt -> zie #793
