### ISSUE TITLE
kadaster natuurlijk persoon heeftPartnerschap datums verwijderen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#792]
in kadasternatuurlijkpersonen zitten nu properties heeftPartnerschap.datumSluiting en heeftPartnerschap.datumOntbinding.

Deze worden niet geleverd door de API (niet geleverd door de daaronder liggende bron). Dus moeten deze depricated worden gemaakt ( en in toekomstige release verwijderd).

**Comment by JohanBoer** [comment]
Deze properties waren in versie 1.2.0 al deprecated : true.
