### ISSUE TITLE
beslagen aantekeningen.betreftGedeelteVanPerceel verwijderen (depricated)

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#793]
bij /beslagen moet aantekeningen.betreftGedeelteVanPerceel depricated worden. Dit property is alleen van toepassing op hypotheken.

**Comment by JohanBoer** [comment]
Ik neem aan dat @kad-hebbim er voor gaat zorgen dat deze property bij beslagen niet meer geleverd gaat worden. Als we deze echter willen depricaten dan moet dat in de specificatie gebeuren liojkt mij. Zal ik daar een voorstel voor doen ?

**Comment by kad-hebbim** [comment]
@JohanBoer: dit klopt inderdaad. Momenteel zijn we nog bezig om te kijken of er meerdere velden zijn die deprecated moeten worden, dus misschien dat er meer volgen...

**Comment by fsamwel** [comment]
er is ook nog een aantal andere issues waar gegevens niet geleverd kunnen worden: #791, #792

ik had deze issues op naam van @kad-hebbim gezet, omdat hij in https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/789#issuecomment-784052455 zei "aanpassen van de specificaties; zal ik deze week een pull request voor aanleveren."

Natuurlijk ook prima wanneer @JohanBoer dat doet
