### ISSUE TITLE
testpersonen bestaan niet meer

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#794]
een hele serie kadasternatuurlijkpersonen die voorheen wel bestonden (en ik gebruik in de test) geven nu een 404:
/kadasternatuurlijkpersonen/80000001
/kadasternatuurlijkpersonen/80000002
/kadasternatuurlijkpersonen/80000003
/kadasternatuurlijkpersonen/80000004
/kadasternatuurlijkpersonen/80000005
/kadasternatuurlijkpersonen/80000006
/kadasternatuurlijkpersonen/80000007

Deze zijn gemaakt n.a.v. https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/375#issuecomment-705610219

**Comment by kad-hebbim** [comment]
Opgelost.
