### ISSUE TITLE
gerefereerde testdata bestaat niet

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#795]
Verschillende resources, waarnaar vanuit andere resources (bijv. onroerende zaak of zakelijkgerechtigde) verwezen wordt (via identificatie en/of _links) bestaan niet (meer), dus geven een 404.

De volgende personen bestonden eerst wel (en zitten in mijn test), maar nu niet meer:
/kadasternietnatuurlijkpersonen/71291493
/kadasternietnatuurlijkpersonen/24268006

De volgende stukken en stukdelen bestaan niet.
/stukdelen/1008956910
/stukdelen/1009533989
/stukken/20170112037138
/stukken/20040616004631
/stukdelen/1009221604
/stukken/20110103000422
/stukdelen/1000370114
/stukken/18020130003032

**Comment by kad-hebbim** [comment]
> Verschillende resources, waarnaar vanuit andere resources (bijv. onroerende zaak of zakelijkgerechtigde) verwezen wordt (via identificatie en/of _links) bestaan niet (meer), dus geven een 404.
> 
> De volgende personen bestonden eerst wel (en zitten in mijn test), maar nu niet meer:
> /kadasternietnatuurlijkpersonen/71291493 **-> opgelost**
> /kadasternietnatuurlijkpersonen/24268006 **-> opgelost**
> 
> De volgende stukken en stukdelen bestaan niet.
> /stukdelen/1008956910 **-> opgelost**
> /stukdelen/1009533989 **-> weggehaald; linkt naar een kadasterstuk**
> /stukken/20170112037138 **-> weggehaald; is een kadasterstuk**
> /stukken/20040616004631 **-> opgelost**
> /stukdelen/1009221604 **-> opgelost**
> /stukken/20110103000422 **-> opgelost**
> /stukdelen/1000370114 **-> opgelost**
> /stukken/18020130003032 **-> opgelost**
