### ISSUE TITLE
Templated externe links naar de BAG API o.b.v. nummeraanduiding tonen bij een OnroerendeZaak

### ISSUE THREAD

**Issue by kad-hebbim** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#798]

**Comment by fsamwel** [comment]
@kad-hebbim  De link naar BAG verwijst nu naar https://api.bag.test.kadaster.nl/esd/huidigebevragingen/v1. Dit is dus de testomgeving van BAG.

Ik denk dat je naar de BAG productieomgeving kan verwijzen. Deze bevat immers open data, dus kan ook voor testen gebruikt worden. De gerefereerde testomgeving wordt gebruikt om nieuwe versies van de BAG API te testen en is dus niet bedoeld voor andere gebruikers.

**Comment by fsamwel** [comment]
ik zie geen wijziging in de link naar BAG:
```
        "adressen": [
            {
                "href": "https://api.bag.test.kadaster.nl/esd/huidigebevragingen/v1/adressen/{adressen.nummeraanduidingIdentificatie}",
                "templated": true
            }
        ]
```

Volgens [uri-templating.feature](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/master/features/uri-templating.feature) kan je hier een serverurl placeholder {bagserverurl} gebruiken. Dit zou dan worden:
```
        "adressen": [
            {
                "href": "{bagserverurl}/adressen/{adressen.nummeraanduidingIdentificatie}",
                "templated": true
            }
        ]
```

**Comment by fsamwel** [comment]
@MelvLee heeft in https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/437#issuecomment-862106859 aangegeven dat het niet echt fout is en geen probleem. Templates uri zou wel handig zijn
