### ISSUE TITLE
OnroerendeZaak uitbreiden met filiatie (ontstaanUit)

### ISSUE THREAD

**Issue by kad-hebbim** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#799]

**Comment by fsamwel** [comment]
@kad-hebbim ik heb geen testgeval met isOntstaanUit.indicatieVervallenKadastraalOnroerendeZaak

dit kan wel voorkomen toch? Of verwijst dit door naar de actuele zaak?

Bijvoorbeeld bij:
Perceel 1 is gesplitst naar Perceel 1A (Perceel 1A heeft op dat moment isOntstaanUit=Perceel 1 en Perceel 1 is nog actueel)
Perceel 1A is vervolgenssamengevoegd met Perceel 2 in Perceel 3 zodat Perceel 1A is vervallen
Komt dan in Perceel 3 te staan isOntstaanUit=Perceel 1?
@CathyDingemanse wat is precies afgesproken hoe dit moet werken (ik was tijdens laatste overleg waarin dit besproken werd niet op mijn scherpst zoals je weet dus kan het me niet precies herinneren)

**Comment by fsamwel** [comment]
@kad-hebbim niet alle situaties voor isOntstaanUit hebben een waarde voor aard. Kan dat in productie zijn, dat er geen aard is hiervoor? in imKad heeft aard in Objecttype OnroerendeZaakFiliatie namelijk kardinaliteit 1

**Comment by fsamwel** [comment]
Bij /kadastraalonroerendezaken/59020170670000 krijg ik:
```
    "isOntstaanUit": [
        {
            "aard": {
                "code": "19",
                "waarde": "Verenigen percelen"
            },
            "kadastraalOnroerendeZaakIdentificatie": "59020131170000"
        }
    ],
```

Hoe kan deze situatie, waarbij 1 enkel perceel is verenigd in een nieuw perceel? Verenigen gebeurt toch ten minste met twee percelen?

**Comment by fsamwel** [comment]
@kad-hebbim /kadastraalonroerendezaken/59020170810218 geeft isOntstaanUit:
```
    "isOntstaanUit": [
        {
            "kadastraalOnroerendeZaakIdentificatie": "59020130970000"
        },
        {
            "kadastraalOnroerendeZaakIdentificatie": "59020170670000"
        }
    ],
```
/kadastraalonroerendezaken/59020170670000 geeft echter niet isOvergegaanIn. Dit zijn inverse relaties (gecheckt bij @kad-pothot), dus als het de ene kant op isOntstaanUit levert, zou ik de andere kant op isOvergegaanIn verwachten
