### ISSUE TITLE
Als gemeente wil ik de gegevens van een kadastrale onroerende zaak kunnen raadplegen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#8]
...zodat ik deze gegevens kan gebruiken.

Op basis van de kadastrale aanduiding van de KADASTRALE ONROERENDE ZAAK wordt een raadpleegbericht opgesteld om 1 KADASTRALE ONROERENDE ZAAK te raadplegen.

Raadpleegresultaat: De KADASTRALE ONROERENDE ZAAK waarvan de kadastrale aanduiding overeenkomt met de ingevulde zoek-argumenten uit het verzoekbericht wordt opgenomen in het antwoordbericht.

**Acceptatiecriteria**
- [x] De kadastrale onroerende zaak waarvan gegevens worden geraadpleegd kan worden geselecteerd op basis van de kadastraleIdentificatie

**Definition of done**
- [ ] functionele specificatie
- [x] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by Debatse** [comment]
Voorstel: op basis van de kadastrale aanduiding.....wordt een raadpleegbericht opgesteld om de actuele KADASTRALE ONROERENDE ZAAK op tijdstip van raadplegen te kunnen terugkoppelen.


Waarom aanscherping? omdat een kadastrale onroerende zaak in de tijd gezien meerdere kadastrale aanduidingen kan hebben. Op een moment t1 is er slechts één (1) kadastrale aanduiding uniek

**Comment by JohanBoer** [comment]
#14

**Comment by JohanBoer** [comment]
De eerste poging is daar. Nog niet compleet, maar voor mij wel een eye-opener als het gaat om welke inhoudelijk/technische discussie we nog moeten voeren. Dit heeft met name te maken met de definitie van resources, welke resources embedded worden opgenomen en welke resources ook met een endpoint ontsloten moeten worden. Het productmodel dat opgeleverd is schetst een ander beeld dan de bijgevoegde schets van 3 weken terug. 
ter illustratie de UML van de hier opgeleverde OAS3 toegevoegd. 
![image](https://user-images.githubusercontent.com/18071357/53106027-80612d80-3532-11e9-9630-9707e9850d2e.png)
![20190124_151148 003](https://user-images.githubusercontent.com/18071357/53106057-8ce58600-3532-11e9-9f49-246dbff463fb.jpg)

**Comment by JohanBoer** [comment]
Inmiddels zijn we veel stappen verder dit is in mijn ogen een verouderde issue die niets meer toevoegt aan de user stories en issues die we nu op het scrumboard hebben staan. Voorstel om deze af te sluiten .

@CathyDingemanse Wat vind jij ?
