### ISSUE TITLE
OnroerendeZaak(Appartementsrecht) uitbreiden met bijbehorend(e) grondperce(e)l(en)

### ISSUE THREAD

**Issue by kad-hebbim** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#800]

**Comment by fsamwel** [comment]
lastig te testen. Er is één testsituatie met samenhangende percelen en appartementsrechten
ik nog geen testgevallen om de functionaliteit goed te testen. bijvoorbeeld een testsituatie waarbij (zoals beschreven in #823 (comment)) een actueel appartementsrecht is gesplitst, of een situatie waarbij een actueel perceel is gesplitst (zie ook #837)
