### ISSUE TITLE
interne server fout bij zoeken kadasterpersonen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#805]
zoeken kadasternatuurlijkpersonen en kadasternietnatuurlijkpersonen geeft een 500 server error:

{
    "type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_InternalServerError",
    "title": "Interne server fout.",
    "status": 500,
    "detail": "Internal Server Error",
    "instance": "/kadasternatuurlijkpersonen?q=Willem%20Jansens",
    "code": "serverError"
}

{
    "type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_InternalServerError",
    "title": "Interne server fout.",
    "status": 500,
    "detail": "Internal Server Error",
    "instance": "/kadasternietnatuurlijkpersonen?q=bankbedrijf",
    "code": "serverError"
}

**Comment by KayodeBakker** [comment]
@kad-hebbim Wij hebben hier bij testen van onze koppeling (en het demo'n aan anderen) last van. Zou hier z.s.m. wat aan kunnen worden gedaan?

**Comment by kad-hebbim** [comment]
@KayodeBakker @fsamwel : het zoeken op personen werkt weer.
