### ISSUE TITLE
Langere en meer realistische teksten in toelichtingen t.b.v. testen eindgebruikerapplicaties

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#806]
We hebben nu op een aantal plekken testdata voor vrije teksten. Bijvoorbeeld:
"toelichtingBewaarder": "Een toelichting van de bewaarder."
"bewaardersVerklaring": "Ziehier een mooie verklaring."
"redenOmschrijving": "Extra uitleg"
"omschrijving": "omschrijving van deze aantekening"
"omschrijvingKadastraleObjecten": "Omschrijving van het object."
"omschrijvingTopografischeMutatie": "Omschrijving over de mutatie."

Ik vermoed dat dit soort velden in de praktijk soms vrij uitgebreide teksten kunnen bevatten. Deze moeten door een client goed worden verwerkt en op het scherm goed worden getoond aan de eindgebruiker. Een heel korte tekst zal dan vaak wel passen op het scherm, maar een uitgebreide tekst (over meerdere regels) misschien niet meer. 
Kunnen we voor het testen van de clients op dit soort vrije tekstvelden ook testdata krijgen die langer is? Bij voorkeur tekst die over meerdere regels zal gaan, en een enigszins realistische tekst, zodat de ontwikkelaar en tester een begrip krijgen van wat hier te verwachten is.

**Comment by kad-hebbim** [comment]
Lengte 120 is max.

**Comment by kad-hebbim** [comment]
**Langere teksten:**
"toelichtingBewaarder": AangebodenStuk: 18020223007191
"bewaardersVerklaring": AangebodenStuk: 18020223007191
"redenOmschrijving": AangebodenStuk: 18020223007191
"omschrijving": Aantekening: 91074411
"omschrijvingKadastraleObjecten": Stukdeel: 1000854514
"omschrijvingTopografischeMutatie": Stukdeel: 1000854514

**Comment by MelvLee** [comment]
@kad-hebbim, welk endpoint moet ik gebruiken om de omschrijving van de aantekening (91074411) te bekijken?

**Comment by kad-hebbim** [comment]
@MelvLee: kan via: /esd/bevragen/v1/kadastraalonroerendezaken/22590043870000/privaatrechtelijkebeperkingen

**Comment by MelvLee** [comment]
opgelost
