### ISSUE TITLE
OnroerendeZaak uitbreiden met bijbehorende appartementsrechten

### ISSUE THREAD

**Issue by kad-hebbim** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#820]

**Comment by fsamwel** [comment]
lastig te testen. Er is één testsituatie met samenhangende percelen en appartementsrechten
ik nog geen testgevallen om de functionaliteit goed te testen. bijvoorbeeld een testsituatie waarbij (zoals beschreven in https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/823#issuecomment-819288511) een actueel appartementsrecht is gesplitst, of waarbij een actueel perceel is gesplitst (zie ook #837)
