### ISSUE TITLE
Invulling velden omtrent filiatie

### ISSUE THREAD

**Issue by kad-hebbim** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#823]
Hieronder staan een aantal voorbeelden waarin wordt geschetst hoe de volgende velden gevuld worden in het response bericht:
- **ontstaanUit**
- **overgegaanIn**
- **bijbehorendeAppartementsrechtIdentificaties**
- **bijbehorendeGrondperceelIdentificaties**

Daarbij zijn de volgende implementatie keuzes gemaakt. Graag hoor ik of dit ook de verwachting is:
1. Bij het veld **ontstaanUit** gaan we voor appartementsrechten terug tot aan het grondperceel (meerdere niveaus terug).
2. Bij het veld **overgegaanIn** gaan we 1 niveau diep.
3. Bij het veld **bijbehorendeAppartementsrechtIdentificaties** kijken we zowel verder als terug in de 'boom'.

**Comment by kad-hebbim** [comment]
### Voorbeeld
![voorbeeld](https://user-images.githubusercontent.com/56292202/114669200-e8ba8c80-9d01-11eb-8667-84dafdf26c02.png)

**Comment by kad-hebbim** [comment]
**Perceel 3:**
```{
    "identificatie": "3",
    "domein": "NL.IMKAD.KadastraalObject",
    "type": "perceel",
    "isOntstaanUit": [
        {
            "kadastraalonroerendezaakidentificatie": "1",
	    "aard”: "Splitsen perceel”,
            "indicatieVervallenKadastraalOnroerendeZaak": true
        }
    ],
    "isOvergegaanIn": [
        {
            "kadastraalonroerendezaakidentificatie": "4",
            "kadastraalonroerendezaakidentificatie": "5"
        }
    ],
    "bijbehorendeAppartementsrechtIdentificaties": [
		"4",
		"5",
                "5.1",
		"5.2"
    ],
    …
}```

**Comment by kad-hebbim** [comment]
**Appartementsrecht 5:**
```
{
    "identificatie": "5",
    "domein": "NL.IMKAD.KadastraalObject",
    "type": "appartementsrecht",
    "isOntstaanUit": [
        {
            "kadastraalonroerendezaakidentificatie": "3"
	}
    ],
    "isOvergegaanIn": [
        {
            "kadastraalonroerendezaakidentificatie": "5.1",
            "kadastraalonroerendezaakidentificatie": "5.2"
        }
    ],
    "bijbehorendeAppartementsrechtIdentificaties": [
		"5.1”,
		"5.2”
    ],
    …
}
```

**Comment by kad-hebbim** [comment]
**Appartementsrecht 5.1**
```
{
    "identificatie": "5.1",
    "domein": "NL.IMKAD.KadastraalObject",
    "type": "appartementsrecht",
    "isOntstaanUit": [
        {
            "kadastraalonroerendezaakidentificatie": "3",
			"kadastraalonroerendezaakidentificatie": "5"
        }
    ],
    "bijbehorendeAppartementsrechtIdentificaties": [
		"5”
    ],
    "bijbehorendeGrondperceelIdentificaties": [
		"3
    ],
    …
}
```

**Comment by CathyDingemanse** [comment]
> **Appartementsrecht 5.1**
> 
> ```
> {
>     "identificatie": "5.1",
>     "domein": "NL.IMKAD.KadastraalObject",
>     "type": "appartementsrecht",
>     "isOntstaanUit": [
>         {
>             "kadastraalonroerendezaakidentificatie": "3",
> 			"kadastraalonroerendezaakidentificatie": "5"
>  


Klopt het dat 1 hier niet wordt genoemd omdat 1 niet meer bestaat (vervallen perceel)? 
Ik ga navragen bij Erfpacht en Belastingzaken of dit voor hen bruikbaar is. Je krijgt z.s.m. antwoord!

**Comment by CathyDingemanse** [comment]
> **Appartementsrecht 5.1**
> 
> ```
> {
>     "identificatie": "5.1",
>     "domein": "NL.IMKAD.KadastraalObject",
>     "type": "appartementsrecht",
>     "isOntstaanUit": [
>         {
>             "kadastraalonroerendezaakidentificatie": "3",
> 			"kadastraalonroerendezaakidentificatie": "5"
>         }
>     ],
>     "bijbehorendeAppartementsrechtIdentificaties": [
> 		"5”
>     ],

Ik dacht dat bijbehorende appartementsrechtidentificaties alleen gevuld zijn bij een grondperceel? Of zie ik nu iets over het hoofd?

**Comment by CathyDingemanse** [comment]
> **Perceel 3:**
> 
> ```
> {
>     "identificatie": "3",
>     "domein": "NL.IMKAD.KadastraalObject",
>     "type": "perceel",
>     "isOntstaanUit": [
>         {
>             "kadastraalonroerendezaakidentificatie": "1",
> 	    "aard”: "Splitsen perceel”,
>             "indicatieVervallenKadastraalOnroerendeZaak": true
>         }
>     ],
>     "isOvergegaanIn": [
>         {
>             "kadastraalonroerendezaakidentificatie": "4",
>             "kadastraalonroerendezaakidentificatie": "5"
>         }
>     ],
>     "bijbehorendeAppartementsrechtIdentificaties": [
> 		"4",
> 		"5",
>                 "5.1",
> 		"5.2"
>     ],
>     …
> }
> ```

Kan ik hieruit concluderen dat appartement 5 niet is vervallen en nog bestaat? Als simpele afnemer zou je zeggen dat dit appartementsrecht niet meer bestaat, klopt dat? Bij ontstaan uit worden de vervallen percelen niet genoemd. Is het logisch om dat hier wel te doen? Wat vind jij?

**Comment by JohanBoer** [comment]
> > **Appartementsrecht 5.1**
> > ```
> > {
> >     "identificatie": "5.1",
> >     "domein": "NL.IMKAD.KadastraalObject",
> >     "type": "appartementsrecht",
> >     "isOntstaanUit": [
> >         {
> >             "kadastraalonroerendezaakidentificatie": "3",
> > 			"kadastraalonroerendezaakidentificatie": "5"
> >  
> > ```
> 
> Klopt het dat 1 hier niet wordt genoemd omdat 1 niet meer bestaat (vervallen perceel)?
> Ik ga navragen bij Erfpacht en Belastingzaken of dit voor hen bruikbaar is. Je krijgt z.s.m. antwoord!

Volgens punt 1 bij de uitleg van Marcel zou perceel 1 ook genomend moeten worden.

**Comment by JohanBoer** [comment]
> > **Appartementsrecht 5.1**
> > ```
> > {
> >     "identificatie": "5.1",
> >     "domein": "NL.IMKAD.KadastraalObject",
> >     "type": "appartementsrecht",
> >     "isOntstaanUit": [
> >         {
> >             "kadastraalonroerendezaakidentificatie": "3",
> > 			"kadastraalonroerendezaakidentificatie": "5"
> >         }
> >     ],
> >     "bijbehorendeAppartementsrechtIdentificaties": [
> > 		"5”
> >     ],
> > ```
> 
> Ik dacht dat bijbehorende appartementsrechtidentificaties alleen gevuld zijn bij een grondperceel? Of zie ik nu iets over het hoofd?
@CathyDingemanse Dat waren toch de bijbehorendeErfpachters die alleen bij het Perceel werden geleverd ?

**Comment by kad-pothot** [comment]
> > **Appartementsrecht 5.1**
> > ```
> > {
> >     "identificatie": "5.1",
> >     "domein": "NL.IMKAD.KadastraalObject",
> >     "type": "appartementsrecht",
> >     "isOntstaanUit": [
> >         {
> >             "kadastraalonroerendezaakidentificatie": "3",
> > 			"kadastraalonroerendezaakidentificatie": "5"
> >  
> > ```
> 
> Klopt het dat 1 hier niet wordt genoemd omdat 1 niet meer bestaat (vervallen perceel)?
> Ik ga navragen bij Erfpacht en Belastingzaken of dit voor hen bruikbaar is. Je krijgt z.s.m. antwoord!

Dat klopt, we tonen als je een appartementsrecht opvraagt alleen het grondperceel waaruit de splitsing is ontstaan.
En wanneer het grondperceel wordt geraadpleegd, dan tonen we waar het grondperceel uit ontstaan is

**Comment by kad-pothot** [comment]
> > **Appartementsrecht 5.1**
> > ```
> > {
> >     "identificatie": "5.1",
> >     "domein": "NL.IMKAD.KadastraalObject",
> >     "type": "appartementsrecht",
> >     "isOntstaanUit": [
> >         {
> >             "kadastraalonroerendezaakidentificatie": "3",
> > 			"kadastraalonroerendezaakidentificatie": "5"
> >         }
> >     ],
> >     "bijbehorendeAppartementsrechtIdentificaties": [
> > 		"5”
> >     ],
> > ```
> 
> Ik dacht dat bijbehorende appartementsrechtidentificaties alleen gevuld zijn bij een grondperceel? Of zie ik nu iets over het hoofd?

Je ziet nu, naast het grondperceel, ook appartementsrecht 5 omdat 5.1 uit de ondersplitsing van appartementsrecht 5 is ontstaan.

**Comment by kad-pothot** [comment]
> > **Perceel 3:**
> > ```
> > {
> >     "identificatie": "3",
> >     "domein": "NL.IMKAD.KadastraalObject",
> >     "type": "perceel",
> >     "isOntstaanUit": [
> >         {
> >             "kadastraalonroerendezaakidentificatie": "1",
> > 	    "aard”: "Splitsen perceel”,
> >             "indicatieVervallenKadastraalOnroerendeZaak": true
> >         }
> >     ],
> >     "isOvergegaanIn": [
> >         {
> >             "kadastraalonroerendezaakidentificatie": "4",
> >             "kadastraalonroerendezaakidentificatie": "5"
> >         }
> >     ],
> >     "bijbehorendeAppartementsrechtIdentificaties": [
> > 		"4",
> > 		"5",
> >                 "5.1",
> > 		"5.2"
> >     ],
> >     …
> > }
> > ```
> 
> Kan ik hieruit concluderen dat appartement 5 niet is vervallen en nog bestaat? Als simpele afnemer zou je zeggen dat dit appartementsrecht niet meer bestaat, klopt dat? Bij "ontstaan uit" worden de vervallen percelen niet genoemd. Is het logisch om dat hier wel te doen? Wat vind jij?

_Kan ik hieruit concluderen dat appartement 5 niet is vervallen en nog bestaat?_ 
Ja

_Als simpele afnemer zou je zeggen dat dit appartementsrecht niet meer bestaat, klopt dat?_
Ja en nee, Het bestaat net zoals het grondperceel bestaat, mogelijk zijn alle rechten opgegaan in een (onder)splitsing, maar er kunnen ook andere rechten op het appartementsrecht staan die nu gewoon bestaan. (dit komt vooral voor in Rotterdam)

_Bij "ontstaan uit" worden de vervallen percelen niet genoemd. Is het logisch om dat hier wel te doen? Wat vind jij?_
Is niet logisch, het appartementsrecht is ontstaan uit de splitsing (en eventuele ondersplitsingen) en niet uit het vervallen perceel.

**Comment by CathyDingemanse** [comment]
Dank Thijs, het is me duidelijk. De voorbeelden zijn dus helemaal goed, met uitzondering van de "bijbehorendeAppartementsrechtIdentificaties" bij appartementsrecht 5.1.

**Comment by kad-hebbim** [comment]
> > > **Appartementsrecht 5.1**
> > > ```
> > > {
> > >     "identificatie": "5.1",
> > >     "domein": "NL.IMKAD.KadastraalObject",
> > >     "type": "appartementsrecht",
> > >     "isOntstaanUit": [
> > >         {
> > >             "kadastraalonroerendezaakidentificatie": "3",
> > > 			"kadastraalonroerendezaakidentificatie": "5"
> > >         }
> > >     ],
> > >     "bijbehorendeAppartementsrechtIdentificaties": [
> > > 		"5”
> > >     ],
> > > ```
> > 
> > 
> > Ik dacht dat bijbehorende appartementsrechtidentificaties alleen gevuld zijn bij een grondperceel? Of zie ik nu iets over het hoofd?
> 
> Deze snap ik ook niet, ik verwacht bij bijbehorendeAppartementsrechtIdentificaties hier niks, omdat 5.1 zelf verder niet is onder gesplitst in appartementsrechten

Dit pakken we op, zodat er niet terug gekeken wordt in de 'boom' (punt 3).

**Comment by CathyDingemanse** [comment]
> Hieronder staan een aantal voorbeelden waarin wordt geschetst hoe de volgende velden gevuld worden in het response bericht:
> 
> * **ontstaanUit**
> * **overgegaanIn**
> * **bijbehorendeAppartementsrechtIdentificaties**
> * **bijbehorendeGrondperceelIdentificaties**
> 
> Daarbij zijn de volgende implementatie keuzes gemaakt. Graag hoor ik of dit ook de verwachting is:
> 
> 1. Bij het veld **ontstaanUit** gaan we voor appartementsrechten terug tot aan het grondperceel (meerdere niveaus terug).
Dit is niet nodig. Hiervoor hebben we bijbehorende grondperceel bedacht, zodat je de hele boom kunt overslaan.
Bedoeld is om bij "overgegaan in" en "ontstaan uit" 1 niveau diep betrokken KOZen aan te geven. 

> 2. Bij het veld **overgegaanIn** gaan we 1 niveau diep.
Correct

> 3. Bij het veld **bijbehorendeAppartementsrechtIdentificaties** kijken we zowel verder als terug in de 'boom'.
Bedoeld wordt om ALLEEN bij een grondperceel alle bijbehorende actuele appartementsrechten mee te geven. Zodat we de boom kunnen overslaan. 

4. Bij een appartementsrecht verwachten we "bijbehorend grondperceel", zodat ook hier de hele boom kan worden overslagen.

**Comment by CathyDingemanse** [comment]
Wij hebben nog 1 vraag aan @kad-hebbim en @kad-pothot: kunnen we nu alle percelen en appartementsrechten opvragen, ook als deze vervallen zijn (en een einddatum hebben)? We hebben immers een einddatum en een indicatie vervallen gespecificeerd.

**Comment by kad-pothot** [comment]
vervallen appartementsrechten worden nu niet geleverd, omdat daar geen filiatie van wordt bijgehouden. 
Echter kan je uit de volgnummers van de appartementsrechten opmaken of er vervallen appartementsrechten zijn en welke dat zijn, omdat de volgenummers in volgorde worden uitgegeven.

Voorbeeld:
Je hebt appartementsrechten 1, 2 & 3.
2 & 3 worden gewijzigd (dus niet ondergesplitst) in 4 & 5.
Als je nu een volledige boom opvraagd via het grondperceel krijg je 1, 4 & 5 terug.
hieruit kan je afleiden dat 2 & 3 zijn vervallen.

**Comment by CathyDingemanse** [comment]
Ok. Maar wat te doen als andere kadastrale objecten zijn overgegaan in 2 & 3? Die kunnen we dan niet meer via de boom terugvinden. M.a.w., de boom "stopt" bij het vervallen object. Hoe zouden we dat kunnen oplossen denk je Thijs?

**Comment by kad-pothot** [comment]
Als andere kadastrale objecten zijn gesplitst in 2 & 3 en 2 & 3 vervallen dan komt het onderliggende object weer tot "leven" en komt dan ook terug in het resultaat. 
Als 2 & 3 gewijzigd worden in 4 & 5 en 2 & 3 zijn ontstaan uit een ander kadastraal object, dan zal dat kadastrale object meekomen in het resultaat wanneer 4 & 5 bestaan. Maw 4 & 5 nemen de filiatie over van 2 & 3.

**Comment by CathyDingemanse** [comment]
@kad-pothot: zoals zojuist besproken bedoel je met bovenstaande tekst inderdaad dat niet meer bestaande kadastraal onroerende zaken hun filiatierelatie overdragen aan een of meer bestaande, dus actuele kadastraal onroerende zaken. Dat betekent dat we "de boom" tot aan het grondperceel altijd helemaal kunnen aflopen, ook als de splitsing/samenvoeging in een heel ver verleden heeft plaatsgevonden. Kadastraal onroerende zaken die vervallen zijn of niet meer bestaan maken geen onderdeel uit van deze boom. Die kunnen we opvragen als historie wordt geleverd. Omdat we weten dat het leveren van historie door de BRK voor oktober 2018 heel erg lastig wordt, is met de filiatie toch de puzzel te leggen, m.n. voor erfpacht en de WOZ.
 
Acties: 
1. uitleggen dat alleen actuele KOZen bij filiatie betrokken zijn, en dat vervallen KOZzen zijn af te leiden uit ontbrekende volgnummers.
2. vraagarticulatie mbt vervallen percelen onderzoeken tbv events.

**Comment by CathyDingemanse** [comment]
@kad-pothot 
Nummer 2 van de voorgestelde actie hoeft toch niet? Ik begrijp uit jouw opmerking bij de description dat alleen vervallen appartementsrechten geen onderdeel zijn van de filiatie. Dan kunnen we bij vervallen perceel wel een einddatum opvoeren toch?

**Comment by kad-pothot** [comment]
_"Overgegaan in" en "ontstaan uit" verwijst dus nooit naar een vervallen appartementsrecht, mogelijk wel naar een vervallen perceel._ - Klopt

_Nummer 2 van de voorgestelde actie hoeft toch niet?_ - Die actie moet inderdaad niet.

_Dan kunnen we bij vervallen perceel wel een einddatum opvoeren toch?_ - Ja

**Comment by fsamwel** [comment]
1. isOvergegaanIn wordt niet geleverd voor relatie van actueel perceel naar appartementsrecht dat daaruit ontstaan is (https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/835#issuecomment-858538258)
2. indicatieVervallenKadastraalOnroerendeZaak wordt niet geleverd in isOntstaanUit bij een vervallen perceel (https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/840#issuecomment-858604932)
3. bij een aantal testgevallen is er geen aard gevuld voor isOntstaanUit (https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/799#issuecomment-858530980)
4. ik nog geen testgevallen om de functionaliteit goed te testen. bijvoorbeeld een testsituatie waarbij (zoals hierboven in het voorbeeld) een actueel appartementsrecht is gesplitst, of waarbij een actueel perceel is gesplitst (#837)
