### ISSUE TITLE
Testdata geven 410 en 404

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#824]
Bij het bevragen van de testgevallen in  https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/blob/develop/test/cases/testcases.json krijg ik een aantal fouten:

/kadastraalonroerendezaken/122003157000 410 
/kadastraalonroerendezaken/122003147000 404 
/kadasternietnatuurlijkpersonen/552056080 404

N.B. wanneer deze percelen niet meer bestaan moeten we die vanaf release v1.3 toch kunnen tonen. Ik verwacht dus geen 410 meer te kunnen krijgen. Zie #825.

Links/identificaties in /kadastraalonroerendezaken/59020170670000 (isOntstaanUit) die niet naar een bestaande resource verwijzen:
/kadastraalonroerendezaken/59020131170000 404
/kadastraalonroerendezaken/59020131070000 404

Link/identificatie in /kadastraalonroerendezaken/59020130970000 (isOntstaanUit) die niet naar een bestaande resource verwijst:
/kadastraalonroerendezaken/59020001970000 404

**Comment by fsamwel** [comment]
ik heb hierdoor, vermoed ik, nog geen testdata voor einddatum en isOvergegaanIn

**Comment by kad-hebbim** [comment]
/kadastraalonroerendezaken/122003157000 410 verwijderd als testgeval

**Comment by fsamwel** [comment]
dit issue was niet terecht. In laatste overleg(gen) is geconcludeerd dat er toch geen vervallen zaken worden geleverd (en dat voor filiatie ook niet nodig is).

Dus zou 410
