### ISSUE TITLE
verwijderen status code 410

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#825]
Met release v1.3 wordt filiatie toegevoegd en dus invulling aan de mogelijkheid om ook percelen (onroerende zaken) waar een onroerende zaak uit is ontstaan op te vragen. Daarbij moet het ook mogelijk zijn inmiddels vervallen percelen (omdat ze zijn samengevoegd of gesplitst) op te vragen. Met die reden is ook property "einddatum" toegevoegd en de links naar isOntstaanUit.

Dan kan response code 410 (Gone) ook vervallen.

**Comment by fsamwel** [comment]
@JohanBoer gezien de discussies over filiatie moeten we concluderen dat:
- we wel vervallen percelen kunnen vragen, dus daarvoor is er geen 410 nodig
- we geen vervallen appartementsrechten kunnen opvragen, dus daarvoor is 410 wel nodig

Met deze nieuwe kennis moet deze wijziging in dit issue, het verwijderen van statuscode 410, ongedaan gemaakt moet worden. Kan jij dat doen?

**Comment by JohanBoer** [comment]
zie #849

**Comment by fsamwel** [comment]
@kad-hebbim is er in de testomgeving een vervallen appartementsrecht? Wat is de identificatie daarvan?
