### ISSUE TITLE
Als tester van een client applicatie wil ik ingeschreven niet-natuurlijk personen in lijn met testdata van het Kadaster

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#830]
...zodat ik in mijn applicatie de links kan testen van BRK gegevens naar niet-natuurlijk personen.

Dit betreft RSIN en KvK nummers van ingeschreven niet-natuurlijk personen in de verschillende rollen, bijvoorbeeld zakelijk gerechtigden (persoon, betrokkenSamenwerkingsverband, betrokkenGorzenEnAanwassen), hypotheken (hypotheekhouders), enz.

Zie testgevallen bij KvK in https://www.kvk.nl/sites/aansluitendataservice/static/Testset_Handelsregister_Dataservice_v4.0.xlsx

**Comment by kad-hebbim** [comment]
Zie #851
