### ISSUE TITLE
Als PO wil ik een goede description van filiatie

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#834]
...zodat mijn afnemers goed begrijpen wat filiatie inhoudt en dit op de juiste manier begrijpen. 

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by CathyDingemanse** [comment]
overgegaan in:
de actuele kadastraal onroerende zaak of zaken waarin de kadastraal onroerende zaak is overgegaan. Vervallen kadastraal onroerende zaken zijn geen onderdeel van de filiatie, maar kun je evt. afleiden uit ontbrekende volgnummers van appartementsrechten.

ontstaan uit:
de actuele kadastraal onroerende zaak of zaken waaruit de kadastraal onroerende zaak is ontstaan. Vervallen kadastraal onroerende zaken zijn geen onderdeel van de filiatie, maar kun je evt. afleiden uit ontbrekende volgnummers van appartementsrechten.

**Comment by CathyDingemanse** [comment]
@kad-pothot Kun je bovenstaande description reviewen?

**Comment by kad-pothot** [comment]
Kleine aanpassing; aangegeven dat alleen bij appartementsrechten er geen vervallen kadastraal onroerende zaak wordt meegegeven in de filiatie.
Dit is wel het geval bij (grond)percelen.

overgegaan in:
de actuele kadastraal onroerende zaak of zaken waarin de kadastraal onroerende zaak is overgegaan. Vervallen kadastraal onroerende zaken zijn geen onderdeel van de filiatie _bij een appartementsrecht_, maar kun je evt. afleiden uit ontbrekende volgnummers van appartementsrechten.

ontstaan uit:
de actuele kadastraal onroerende zaak of zaken waaruit de kadastraal onroerende zaak is ontstaan. Vervallen kadastraal onroerende zaken zijn geen onderdeel van de filiatie _bij een appartementsrecht_, maar kun je evt. afleiden uit ontbrekende volgnummers van appartementsrechten.

**Comment by melsk-r** [comment]
Persoonlijk werd voor mij de term 'filiatie' ook niet duidelijk door het lezen van het voorstel. Volgens mij bevat het voorstel een uitleg van 2 voorbeelden van filiatie. Daaraan ontbreekt nog een algemene beschrijving. Ik heb even gegoogled en het volgende gevonden:

_Filiatie laat zien uit welke oude (vroegere) percelen het gevraagde perceel is ontstaan, of naar welke nieuwe (latere) percelen het gevraagde perceel is overgegaan._

Misschien goed om dit (of iets dergelijks) toe te voegen?

**Comment by CathyDingemanse** [comment]
we hebben in de API geen eigenschap filiatie, maar alleen overgegaan in en ontstaan uit. Daarbij gaat het niet alleen over percelen, maar ook over appartementsrechten.
