### ISSUE TITLE
OnroerendeZaak uitbreiden met filiatie (overgegaanIn)

### ISSUE THREAD

**Issue by kad-hebbim** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#835]

**Comment by fsamwel** [comment]
@kad-hebbim isOvergegaanIn krijg ik nog nergens in de mij bekende testdata.

Bijvoorbeeld appartementsrecht /kadastraalonroerendezaken/22310827210003 heeft:
    "isOntstaanUit": [
        {
            "kadastraalOnroerendeZaakIdentificatie": "22310691970000"
        }
    ],
    "bijbehorendeGrondperceelIdentificaties": [
        "22310691970000"
    ],

Maar wanneer ik het bijbehorende perceel /kadastraalonroerendezaken/22310691970000 vraag krijg ik geen isOvergegaanIn:
    "bijbehorendeAppartementsrechtIdentificaties": [
        "22310827210004",
        "22310827210003"
    ],

Hier had ik daarom ook verwacht:
    "isOvergegaanIn": [
        "22310827210004",
        "22310827210003"
    ],

**Comment by fsamwel** [comment]
@CathyDingemanse @kad-hebbim de enige voorbeelden die ik nu gevonden heb met isOvergegaanIn zijn vervallen percelen. Moet isOvergegaanIn niet ook worden opgenomen wanneer een perceel is gesplitst, maar het perceel nog wel bestaat?
Of wanneer uit een perceel appartementsrechten zijn ontstaan, moet bij dat perceel dan isOvergegaanIn niet ook de appartementsrechten bevatten? Dan kan je namelijk de hele "boom" afleiden op basis van isOntstaanUit en isOvergegaanIn

**Comment by CathyDingemanse** [comment]
> Moet isOvergegaanIn niet ook worden opgenomen wanneer een perceel is gesplitst, maar het perceel nog wel bestaat?

@kad-pothot komt dit voor, of komt dit alleen bij appartementsrechten voor (casus Rotterdam zeg maar)? Zo ja, kunnen we daar dan ook een testcase voor krijgen?

**Comment by CathyDingemanse** [comment]
> Of wanneer uit een perceel appartementsrechten zijn ontstaan, moet bij dat perceel dan isOvergegaanIn niet ook de appartementsrechten bevatten? Dan kan je namelijk de hele "boom" afleiden op basis van isOntstaanUit en isOvergegaanIn

Dit lijkt mij niet omdat het perceel niet is overgegaan in een of meer appartementsrechten. Dat blijft gewoon bestaan als perceel toch? 
@kad-pothot: klopt dat? 
@kad-pothot: Kan een appartementsrecht wel een "ontstaan uit" relatie hebben met een perceel?

**Comment by fsamwel** [comment]
@CathyDingemanse @kad-pothot dus isOntstaanUit en isOvergegaanIn zijn niet inverse relaties van elkaar?

**Comment by JohanBoer** [comment]
> @CathyDingemanse @kad-pothot dus isOntstaanUit en isOvergegaanIn zijn niet inverse relaties van elkaar?

Nee dat zijn geen inverse relaties van elkaar : 
![image](https://user-images.githubusercontent.com/18071357/121868668-8da51600-cd01-11eb-9407-670e6a141351.png)

**Comment by fsamwel** [comment]
In imKad staat bij OnroerendeZaakFiliatie (isOntstaanUit): "OnroerendeZaakFiliatie geeft aan uit welke inmiddels vervallen OnroerendeZaak de OnroerendeZaak is ontstaan ."

Bij VoorwaartseOnroerendeZaakFiliatie (isOvergegaanIn) lees ik "Voorwaartse onroerende zaak filiatie geeft de relatie aan tussen een onroerende zaak en de onroerende zaken waarin hij is overgegaan." en bij detail "Een Onroerende zaak filiatie geeft de relatie aan tussen een nieuwe en een oude Onroerende zaak. Het betreft hier de relatie tussen 2 percelen, 2 Appartementsrechten of 2 leidingnetwerken."

Dus: bij isOntstaanUit moet indicatieVervallenKadastraalOnroerendeZaak ALTIJD de waarde true hebben
En: bij isOvergegaanIn wordt NOOIT de relatie van een perceel naar een appartementsrecht gelegd

**Comment by fsamwel** [comment]
Overigens volgt de implementatie nu niet wat er staat in het [imKad](https://developer.kadaster.nl/schemas/imkad/20200130/cat/imkad-IMKAD-2-20190901.office.respec.html#graph_EAID_6AF855D7_906B_4512_91DF_9F5A0163707D) (vorige opmerking): isOntstaanUit verwijst bij een appartementsrecht ook naar het perceel, ook wanneer deze niet vervallen is. Bijvoorbeeld /kadastraalonroerendezaken/59020170810218 levert:
```
    "isOntstaanUit": [
        {
            "kadastraalOnroerendeZaakIdentificatie": "59020130970000"
        },
        {
            "kadastraalOnroerendeZaakIdentificatie": "59020170670000"
        }
    ]
```

Volgens de beschrijving van @kad-hebbim in #823 zou isOvergegaanIn wel moeten verwijzen van perceel naar appartementsrecht. Zie https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/823#issuecomment-819290147.

Dus wellicht komt mijn verwarring omdat imKad, de beschrijving van @kad-hebbim in #823, de interpretatie van @CathyDingemanse (https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/835#issuecomment-859670680) en @JohanBoer  (https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/835#issuecomment-860530579) en de feitelijke implementatie nu alle vier verschillende zijn. En welke is dan de juiste?

Mijn persoonlijke voorkeur heeft de beschrijving van @kad-hebbim in#823, want dan kan je de boom zowel omhoog als omlaag volgen met alleen resp. isOntstaanUit en isOvergegaanIn. Deze oplossing, altijd leveren isOntstaanUit en isOvergegaanIn en waarbij isOntstaanUit en isOvergegaanIn inverse relaties zijn, is voor gebruikers verreweg het eenvoudigst en meest eenduidig.

Overigens vragen de user stories alleen het opbouwen van de boom omhoog (dus via isOntstaanUit).

**Comment by fsamwel** [comment]
@kad-hebbim isOvergegaan wordt nu ook niet geleverd bij ondersplitsing van appartementsrecht.
/kadastraalonroerendezaken/59020170810219 is gesplitst naar 59020170810593 en 59020170810594. In de nieuwe appartementsrechten zit isOntstaanUit met verwijzing naar 59020170810219, maar in 59020170810219 zit geen isOvergegaan.
Daardoor is het nu niet mogelijk vanuit isOvergegaan te zien bij welke splitsingen het betrokken is en waarin het is overgegaan.

**Comment by fsamwel** [comment]
@kad-hebbim appartementsrecht 22310827210003 heeft:
```
    "isOntstaanUit": {
        "aard": {
            "code": "25",
            "waarde": "Splitsing in appartementsrechten"
        },
        "kadastraalOnroerendeZaken": [
            {
                "identificatie": "22310691970000",
                "type": "perceel"
            }
        ]
    },
    "bijbehorendeGrondpercelen": [
        {
            "identificatie": "22310691970000"
        }
    ],
```

Maar perceel 22310691970000 heeft:
```
    "isOvergegaanIn": {
        "aard": {
            "code": "25",
            "waarde": "Splitsing in appartementsrechten"
        },
        "kadastraalOnroerendeZaken": [
            {
                "identificatie": "22310827210004",
                "type": "appartementsrecht"
            }
        ]
    },
    "bijbehorendeAppartementsrechten": [
        {
            "identificatie": "22310827210004",
            "volgnummer": 4
        }
    ],
```

Ik had hier ook 22310827210003 verwacht.

**Comment by kad-hebbim** [comment]
Opgelost.

**Comment by fsamwel** [comment]
@kad-hebbim bij /kadastraalonroerendezaken/59020170670000 krijg ik:
```
    "isOntstaanUit": {
        "aard": {
            "code": "19",
            "waarde": "Verenigen perceel"
        },
        "kadastraalOnroerendeZaken": [
            {
                "identificatie": "59020131170000",
                "type": "perceel"
            },
            {
                "identificatie": "59020131270000",
                "type": "perceel"
            }
        ]
    }
```

de omschrijving bij aard 19 is niet correct. Hier had ik verwacht:
```
        {
            "code": "19",
            "waarde": "Verenigen percelen"
        }
```

**Comment by kad-hebbim** [comment]
Opgelost.

**Comment by MelvLee** [comment]
opgelost
