### ISSUE TITLE
Als ontwikkelaar van een client applicatie die filiatie gebruikt heb ik verschillende complexe testgevallen nodig

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#837]
...zodat ik mijn applicatie kan testen en de werking kan demonstreren

Zie bijgevoegd document met een aantal testsituaties die we nodig hebben:

[testgevallen filiatie.docx](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/files/6592754/testgevallen.filiatie.docx)

Verder hebben we voor ons erfpachtsysteem de mogelijke Erfpacht situaties nodig, die Thijs zou beschrijven. We willen dan de erfpacht situatie voor en na de splitsing of samenvoeging weten. Voor Erfpacht, willen we weten wat de verschillende manieren zijn waarop Erfpacht in de BRK wordt geregistreerd. Dan gaat het over het recht van erfpacht op percelen en appartementsrechten en wat er gebeurt bij splitsingen van meerdere niveaus (vve en appartementen). 

Bij de huidige testcases mis ik nog kadastraalobjecten met adressen die:

- gekoppeld zijn aan de BAG via alleen administratief
- gekoppeld zijn aan de BAG via alleen geo
- niet gekoppeld zijn aan de BAG

**Comment by kad-hebbim** [comment]
@fsamwel:

Situaties 1, 4, 6, 7 & 8** kunnen voorkomen, de rest kan niet.
** zie punt 2.

**Uitleg:**
1.	Percelen kunnen alleen verenigen of splitsen (en niet tegelijkertijd), en daarbij vervallen altijd de oude percelen. Uitzondering is splitsen in appartmentsrechten. Hierdoor vallen situaties 2, 5, 8, 10 & 11 af.
2.	Appartementen kunnen niet worden samengevoegd, wel gewijzigd van 2 naar 1 appartementsrecht, maar het nieuwe appartementsrecht neemt de filiatie van de oude appartementsrechten over. Daardoor kan situatie 8 in principe wel, maar krijg je niet de filiatie naar de vervallen appartementsrechten te zien.

**Comment by fsamwel** [comment]
@kad-hebbim ik heb testgeval 2 en 8 verwijderd, testgeval 3 (is nu 2 geworden) anders getekend. Idem voor testgeval 5 (is 4 geworden) en 10 (is 8 geworden). Ik heb 9 (is 7 geworden) gewijzigd naar ondersplitsing van appartementsrecht
[testgevallen filiatie2.docx](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/files/6657326/testgevallen.filiatie2.docx)

**Comment by fsamwel** [comment]
@kad-hebbim we hebben nu 2 testgevallen voor filiatie, die met 59020001770000, en die met 22310691970000. Is er ook voortgang om de in dit issue beschreven testgevallen aan te bieden?

**Comment by kad-hebbim** [comment]
Momenteel hebben we de volgende filiatieboom:

![image](https://user-images.githubusercontent.com/56292202/128673531-34648f5a-7b24-4f28-a900-b02ea2a8e3c1.png)

Dekken we daar niet alle testgevallen mee af?

**Comment by kad-hebbim** [comment]
Bovenstaand filiatieboom dekt de verschillende scenario's af.
