### ISSUE TITLE
verwijderen property einddatum en indicatieVervallen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#840]
na laatste overleg(gen) over filiatie is geconcludeerd dat de BRK bevragen API geen vervallen zaken zal of hoeft te kunnen leveren. Daarom moet het nieuwe property "einddatum" en "indicatieVervallen" worden verwijderd.

Ook moet response 410 weer worden toegevoegd (verwijderen daarvan ongedaan gemaakt)

**Comment by fsamwel** [comment]
@kad-hebbim /kadastraalonroerendezaken/59020001970000 geeft me nu wel "indicatieVervallen": true, maar geen einddatum.

/kadastraalonroerendezaken/59020130970000 levert:
    "isOntstaanUit": [
        {
            "aard": {
                "code": "20",
                "waarde": "Splitsen perceel"
            },
            "kadastraalOnroerendeZaakIdentificatie": "59020001970000"
        }
    ],

Daarin zit dus niet "indicatieVervallenKadastraalOnroerendeZaak": true voor 59020001970000.

Is /kadastraalonroerendezaken/59020001970000 nu wel of niet vervallen? En leveren we dus wel of niet vervallen onroerende zaken?

**Comment by JohanBoer** [comment]
Wijzigingen staan bij mij lokaal klaar. Ik heb echter voor de vorige wijzigen (#836)  geen branch aangemaakt. Ik wacht moet de PR aanmaken tot die is gemerged.

**Comment by fsamwel** [comment]
> Wijzigingen staan bij mij lokaal klaar. Ik heb echter voor de vorige wijzigen (#836) geen branch aangemaakt. Ik wacht moet de PR aanmaken tot die is gemerged.

@JohanBoer Het is dus ernstig de vraag of deze velden wel moeten worden verwijderd. Blijkt nu dat vervallen percelen wel kunnen worden geleverd

**Comment by fsamwel** [comment]
> @kad-hebbim /kadastraalonroerendezaken/59020001970000 geeft me nu wel "indicatieVervallen": true, maar geen einddatum.
> 
> /kadastraalonroerendezaken/59020130970000 levert:
> 
> ```
>     "isOntstaanUit": [
>         {
>             "aard": {
>                 "code": "20",
>                 "waarde": "Splitsen perceel"
>             },
>             "kadastraalOnroerendeZaakIdentificatie": "59020001970000"
>         }
>     ],
> ```
> 
> Daarin zit dus niet "indicatieVervallenKadastraalOnroerendeZaak": true voor 59020001970000.
> 
> Is /kadastraalonroerendezaken/59020001970000 nu wel of niet vervallen? En leveren we dus wel of niet vervallen onroerende zaken?

hiervoor nieuw issue  #845 gemaakt

**Comment by fsamwel** [comment]
conclusie is dat einddatum en indicatieVervallen NIET moeten worden verwijderd

**Comment by fsamwel** [comment]
@kad-hebbim ik krijg bij een vervallen perceel geen indicatieVervallen. Bijvoorbeeld 59020001770000 (samengevoegd) en 59020001970000 (gesplitst)
