### ISSUE TITLE
einddatum ontbreekt in vervallen percelen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#846]
/kadastraalonroerendezaken/59020001970000 is vervallen, want is gesplitst. Deze heeft "indicatieVervallen": true.

Dan verwacht ik ook een einddatum ("Datum waarop de kadastraal onroerende zaak is vervallen")

**Comment by fsamwel** [comment]
@JohanBoer kan je deze verwijderen uit de OAS

**Comment by JohanBoer** [comment]
N.a.v. overleg op 30-06-2021 wordt de einddatum uit de resource KadastraalOnroerendeZaak verwijderd.
