### ISSUE TITLE
Als PO wil ik een gesprek met de NLX designers

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#85]
...zodat wij de impact op onze API specificatie kunnen bepalen.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by JanWillemKooi** [comment]
Afspraak is ingepland door Cathy

**Comment by JanWillemKooi** [comment]
Gesprek is 25 apr geweest. Cathy is tevreden met de uitkomst en gaat wat is besproken bijvoegen bij deze user story. Daarna kan deze naar Done.

**Comment by JanWillemKooi** [comment]
Update 1 jun call: Cathy is bezig met het verslag maar wil deze laten lezen aan Eelco voordat het op GitHub geplaatst wordt.

**Comment by CathyDingemanse** [comment]
zie https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/blob/master/docs/20190425_afstemming%20autorisatie%20NLX-HaalCentraal.pdf
