### ISSUE TITLE
ETO geeft 500 server error op kadasterpersonen zoeken

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#855]
GET https://api.brk.kadaster.nl/esd-eto-apikey/bevragen/v1/kadasternietnatuurlijkpersonen?q=bankbedrijf
```
{
    "type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_InternalServerError",
    "title": "Interne server fout.",
    "status": 500,
    "detail": "Internal Server Error",
    "instance": "/kadasternietnatuurlijkpersonen?q=bankbedrijf",
    "code": "serverError"
}
```

of GET https://api.brk.kadaster.nl/esd-eto-apikey/bevragen/v1/kadasternatuurlijkpersonen?q=Willem Jansens
```
{
    "type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_InternalServerError",
    "title": "Interne server fout.",
    "status": 500,
    "detail": "Internal Server Error",
    "instance": "/kadasternatuurlijkpersonen?q=Willem%20Jansens",
    "code": "serverError"
}
```

**Comment by kad-pothot** [comment]
@fsamwel Er was een token verlopen, die is inmiddels vervangen door een nieuwe. Alles zou het weer moeten doen

**Comment by KayodeBakker** [comment]
@kad-pothot Is een verlopen token een issue dat gebruikers specifiek is of omgeving specifiek? Ik heb namelijk dezelfde issue maar dan op https://api.brk.acceptatie.kadaster.nl/esd/bevragen/v1

**Comment by fsamwel** [comment]
@KayodeBakker bij mij doet https://api.brk.acceptatie.kadaster.nl/esd/bevragen/v1 het wel

getest met natuurlijk persoon:
https://api.brk.acceptatie.kadaster.nl/esd/bevragen/v1/kadasternatuurlijkpersonen?q=Willem%20Jansens

en niet-natuurlijk persoon:
https://api.brk.acceptatie.kadaster.nl/esd/bevragen/v1/kadasternietnatuurlijkpersonen?q=bankbedrijf%20rotterdam

Overigens in op dit moment  https://api.brk.kadaster.nl/esd-eto-apikey/bevragen/v1 de omgeving die je zou moeten gebruiken om te testen. De acceptatieomgeving wordt gebruikt om nieuwe versies te testen, daarop staat nu de niet afgeronde versie v1.3. Zie https://vng-realisatie.github.io/Haal-Centraal-BRK-bevragen/getting-started#probeer-en-test-de-api
