### ISSUE TITLE
isOntstaanUit en isOvergegaanIn zijn arrays met arrays?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#860]
We hebben in de laatste wijzigingen filiatie in isOvergegaanIn en isOntstaanUit gewijzigd, zodat er één aard is bij meerdere samengevoegde of gesplitste onroerende zaken. Toch wordt de isOvergegaanIn en isOntstaanUit zelf ook nog als array gedefinieerd.

Dit suggereert dat je dus toch isOntstaanUit of isOvergegaanIn kunt krijgen met meerdere verschillende aard.

Dus zou je nu zoiets kunnen krijgen:
```
  "isOntstaanUit": [
    {
      "aard": {
        "code": "20",
        "waarde": "Splitsen perceel"
      },
      "kadastraalOnroerendeZaken": [
        {
          "identificatie": "59020001970000",
          "type": "perceel"
        }
      ]
    },
    {
      "aard": {
        "code": "19",
        "waarde": "Verenigen percelen"
      },
      "kadastraalOnroerendeZaken": [
        {
          "identificatie": "59020131170000",
          "type": "perceel"
        },
        {
          "identificatie": "59020170810219",
          "type": "perceel"
        }
      ]
    }
  ],
```

@kad-hebbim en @kad-pothot dit is toch niet mogelijk? Er kan toch in één onroerende zaak maar een isOntstaanUit zijn met één aard? Idem voor isOvergegaanIn?

**Comment by kad-hebbim** [comment]
Dit is niet mogelijk en ik zal de spec hiervoor aanpassen en indienen als pull request.
