### ISSUE TITLE
Veld indicatieVervallen nog nodig in PerceelFiliatie?

### ISSUE THREAD

**Issue by kad-hebbim** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#862]
Is het veld indicatieVervallen nog wel nodig bij een PerceelFiliatie? Aangezien men toch een nieuwe aanvraag moet doen om de huidige percelen op te kunnen vragen.

**PS:**
Momenteel kunnen we niet voor elk geval (gemakkelijk) bepalen of object vervallen is:
- ontstaanUit Perceel vanuit Grondperceel -> altijd indicatieVervallen=true.
- ontstaanUit Grondperceel vanuit Appartementsrecht uit een Hoofdsplitsing -> altijd indicatieVervallen=false.
- overgegaanIn Perceel vanuit Perceel -> kan beiden zijn; is niet gemakkelijk te halen uit de bron.

**Comment by kad-pothot** [comment]
@kad-hebbim Ik denk toch dat we  indicatieVervallen moeten laten staan bij ontstaanUit, en altijd weglaten bij OvergegaanIn.
Het is voor een klant denk toch makkelijker om, waneer wij de data hebben, die te tonen, zodat ze daar ook toegang tot hebben, ipv het ergens moeten hebben herinnerd dat bepaalde situatie altijd dezelde resultaten geven.

**Comment by fsamwel** [comment]
afgesproken dat @kad-hebbim indicatieVervallen gaat verwijderen uit de specs en code

**Comment by JohanBoer** [comment]
@kad-hebbim Deze kan dan toch ook gesloten worden ?
