### ISSUE TITLE
beschikkingsbevoegdheid niet meer geleverd

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#864]
voorheen werd bij /kadasternatuurlijkpersonen/70882239 beschikkingsbevoegdheid geleverd. Nu niet meer.

**Comment by fsamwel** [comment]
bij deze persoon 70882239 wordt nu ook heeftPartnerschap niet meer geleverd.

**Comment by kad-hebbim** [comment]
Opgelost.
