### ISSUE TITLE
tijd ontbreekt in tijdstipAanbieding en tijdstipOndertekening

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#871]
/stukken/20190409001159 geeft nu:
```
    "tijdstipAanbieding": "2019-04-09T00:00:00+02:00",
    "tijdstipOndertekening": "2019-04-09T00:00:00+02:00",
```

Eerder werd hierbij ook het tijdstip, dus de uren en minuten geleverd. Dat was resp. '2019-04-09T10:33:00+02:00' en '2019-04-09T08:40:00+02:00'

**Comment by kad-hebbim** [comment]
Opgelost in testgevallen.

**Comment by MelvLee** [comment]
Bij bovengenoemde stuk is dit nu correct. Bij stuk 18020223007191 is dit volgens mij niet het geval

**Comment by kad-hebbim** [comment]
18020223007191 heeft als tijdstip 00.00.00 vanuit de bron.

**Comment by MelvLee** [comment]
opgelost
