### ISSUE TITLE
kadasternietnatuurlijkpersoon met relatie betrokkenGorzenEnAanwassen wordt niet gevonden en relatie niet getoond

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#878]
Wanneer ik "Bankbedrijf van vrucht" raadpleeg met /kadasternietnatuurlijkpersonen/71291493, wordt er geen kadastraalOnroerendeZaakIdentificaties geleverd.

Deze persoon bestaat en heeft een relatie met een onroerende zaak, namelijk via 
/kadastraalonroerendezaken/76870487970000/zakelijkgerechtigden/30493367 in betrokkenGorzenEnAanwassen. Dus verwacht ik ook dat ik deze persoon kan vinden én dat ik in deze persoon de relatie naar deze onroerende zaak zie.

Zoeken met /kadasternietnatuurlijkpersonen?q=bankbedrijf vond voorheen ook "Bankbedrijf van vrucht", nu niet meer (alleen "bankbedrijf"). Waarschijnlijk hangt dit met bovenstaande samen, dat alleen gezocht wordt naar personen met een relatie naar een onroerende zaak.

In KadasterNatuurlijkPersoonHalKadasterNatuurlijkPersoon is kadastraalOnroerendeZaakIdentificaties niet gedefinieerd. Dus is het voor een gebruiker (en voor mij) ook niet duidelijk wat deze hier kan verwachten. 
Zijn dit alleen de zaken waar de persoon zelf zakelijk gerechtigde is, of zijn dit alle zaken waar de persoon een rol in heeft (zoals samenwerkingsverband of betrokkenGorzenEnAanwassen.

**Comment by CathyDingemanse** [comment]
@kad-pothot voegt een uitleg toe over:

- waarom dit geen bug is
- hoe je alle percelen van de gorzen en aanwassen kunt vinden.

**Comment by kad-pothot** [comment]
De niet natuurlijk persoon die aan gorzen en aanwassen worden gekoppeld in de BRK zijn fictieve personen met als rechtsvorm "gorzen en aanwassen". Deze persoon bestaat alleen om aan te kunnen geven bij een tenaamstelling van een kadastraal object dat deze onderdeel is van een "gorzen en aanwassen"-gebied.

Wanneer deze persoon wordt opgevraagd worden de betrokken objecten niet teruggegeven. hier is voor gekozen omdat het niet als wenselijk wordt gezien om fictieve personen te bevragen.

Om er achter te komen welke kadastrale objecten betrokken zijn bij een bepaald "gorzen en aanwassen"-gebied heb je één van de eigenaren nodig. Wanneer je die persoon opvraagt krijg je een lijst terug met objecten waarvan deze persoon kadastraal gerechtigd is. Vervolgens kan je uit deze lijst alle objecten selecteren waarbij de fictieve "gorzen en aanwassen"-persoon betrokken is en dat geeft dan de lijst van kadastrale objecten binnen het "gorzen en aanwassen"-gebied.

**Comment by CathyDingemanse** [comment]
@MelvLee zou je van bovenstaande een feature kunnen maken die ook nog testbaar is?
@kad-hebbim zou jij daarvoor testgevallen kunnen maken?

**Comment by kad-hebbim** [comment]
@MelvLee @JohanBoer @fsamwel @kad-pothot @CathyDingemanse 
Er is een nieuw fictief kadaster niet natuurlijk persoon toegevoegd
`71291497 - Gorzen en Aanwassen van Gebied`
welke nu als betrokkenGorzenEnAanwassen is gelinkt aan
`/kadastraalonroerendezaken/76870487970000/zakelijkgerechtigden/30493367`

Voorheen was dit de ingeschreven niet natuurlijk persoon `71291493`.

Voor de feature file:
Door een eigenaar (`70882239`) te bevragen van 1 van deze onroerendezaken krijg je de lijst waarvan alle objecten geselecteerd kunnen worden waarbij de fictieve "gorzen en aanwassen"-persoon betrokken is.
Dat geeft dan de lijst van kadastrale objecten binnen het "gorzen en aanwassen"-gebied.

**Comment by MelvLee** [comment]
@kad-hebbim, als ik het goed begrijp dan zeggen we het volgende beschreven met Gherkin:

Gegeven de KadastraalOnroerendeZaak met identificatie 76870487970000
* heeft een ZakelijkGerechtigde van het type 'eigenaar' met persoon identificatie 70882239
* dat is betrokken bij een GorzenEnAanwassen gebied gekoppeld aan een niet-natuurlijk persoon met identificatie 71291497
En de KadastraalOnroerendeZaak met identificatie A
* heeft een ZakelijkGerechtigde van het type 'eigenaar' met persoon identificatie 70882239
* dat is betrokken bij een GorzenEnAanwassen gebied gekoppeld aan een niet-natuurlijk persoon met identificatie 71291497
En de KadastraalOnroerendeZaak met identificatie B
* heeft een ZakelijkGerechtigde van het type 'eigenaar' met persoon identificatie 70882239
* dat is betrokken bij een GorzenEnAanwassen gebied gekoppeld aan een niet-natuurlijk persoon met identificatie 71291498

Scenario: zoeken van kadastraal onroerende zaken die zijn betrokken bij een GorzenEnAanwassen gebied
Als de KadastraalOnroerendeZaken moet worden opgehaald die zijn betrokken bij een GorzenEnAanwassen gebied gekoppeld aan niet-natuurlijk persoon met identificatie 71291497
Dan wordt met GET /kadastraalonroerendezaken?persoon__identificatie=70882239&zakelijkGerechtigde__type=eigenaar&expand=zakelijkGerechtigden KadastraalOnroerende Zaken met embedded ZakelijkGerechtigden voor de betreffende persoon opgehaald
En wordt de KadastraalOnroerendeZaken betrokken bij het GorzenEnAanwassen gebied bepaald door te filteren op _embedded.zakelijkGerechtigden.betrokkenGorzenEnAanwassen.identificatie=71291497
En is het filter resultaat de KadastraalOnroerendeZaken met de volgende identificaties:
| KadastraalOnroerendeZaak identificatie |
| 76870487970000                                     |
| A                                                              |

Als dit klopt, dan zou er minimaal een KadastraalOnroerendeZaak (voor A) worden toegevoegd aan de testdata, want tot nu toe is er maar één KOZ waar `70882239` eigenaar is en  `71291497` is gekoppeld via betrokkenGorzenEnAanwas.

Verder heb ik onderstaande rule en bijbehorend scenario gespecificeerd

Rule: Het is niet mogelijk om de identificaties van betrokken KadastraalOnroerendeZaken op te vragen voor een fictief persoon

Scenario: raadplegen van de niet-natuurlijk persoon gekoppeld aan een Gorzen en Aanwassen Gebied
Als GET /kadasternietnatuurlijkpersonen/71291497 wordt verstuurd
Dan bevat de response geen lijst van KadastraalOnroerendeZaak identificaties waar deze persoon bij betrokken is

**Comment by kad-hebbim** [comment]
@MelvLee 
Scenario klopt zo wel als ik kijk naar de comment van Thijs.

**Comment by kad-hebbim** [comment]
@MelvLee @JohanBoer @fsamwel:
Als het echt nodig is om meer dan 1 OnroerendeZaak terug te krijgen (in theorie kun je het nu namelijk testen, alleen krijg je nu een lijst terug met 1 item), dan zou ik het volgende kunnen doen:

De kortste klap is om `71291497` toe te voegen als BetrokkenGorzenEnAanwassen aan de andere OnroerendeZaak `76870482670000` waar NatuurlijkPersoon `70882239` eigenaar van is 

Kanttekening hierbij is dan wel dat ik NatuurlijkPersoon `50550743` ook moet toevoegen als eigenaar aan dit OnroerendeZaak; wil je het helemaal correct maken. Anders krijg je via die persoon niet alle OnroerendeZaken terug waar `71291497` BetrokkenGorzenEnAanwassen is...
Dit betekent dus dat er wijzigingen zullen komen in de testgevallen en dat er waarschijnlijk assertions zullen omvallen in jullie huidige testcases, want:
- NatuurlijkPersoon `50550743` wordt ook eigenaar van OnroerendeZaak `76870482670000`
- OnroerendeZaak `76870482670000` krijgt een extra ZakelijkGererechtigde erbij.

Graag hoor ik van @JohanBoer of hij hier last van heeft bij zijn testen. 

Aangezien dit een aanpassing is in de testgevallen en niet in de code, kun je die ook pas toevoegen nadat Johan al zijn testen heeft afgerond voor de huidige opzet van jullie testcases...

**Comment by MelvLee** [comment]
@kad-hebbim, ik denk dat we de aanpassing kunnen uitstellen totdat alle testen zijn afgerond. Dan hebben de anderen er op dit moment geen last van.

**Comment by JohanBoer** [comment]
Ik ben nu klaar met testen en heb een mail naar Marcel gestuurd. Eventueel kan de testdata nu aangepast worden voor Gorzen en Gewassen. 
Dan kan ik daarna checken welke impact dat heeft op de huidige tests.
@MelvLee Heb jij al testen bedacht voor deze functionaliteit of ga ik mij daarop storten (eventueel met jouw hulp) ?

**Comment by kad-hebbim** [comment]
> Ik ben nu klaar met testen en heb een mail naar Marcel gestuurd. Eventueel kan de testdata nu aangepast worden voor Gorzen en Gewassen.
> Dan kan ik daarna checken welke impact dat heeft op de huidige tests.
> @MelvLee Heb jij al testen bedacht voor deze functionaliteit of ga ik mij daarop storten (eventueel met jouw hulp) ?

@JohanBoer, @MelvLee 
De testdata is aangepast. Dus dit kan getest worden.

**Comment by MelvLee** [comment]
> 
> 
> Ik ben nu klaar met testen en heb een mail naar Marcel gestuurd. Eventueel kan de testdata nu aangepast worden voor Gorzen en Gewassen.
> Dan kan ik daarna checken welke impact dat heeft op de huidige tests.
> @MelvLee Heb jij al testen bedacht voor deze functionaliteit of ga ik mij daarop storten (eventueel met jouw hulp) ?

@JohanBoer, je kan je storten op de Gorzen en Gewassen testen. Ik ben bezig de specificatie in een feature file te gieten

**Comment by JohanBoer** [comment]
Ik heb de tests aangepast op basis van de door Marcel aangeleverde testdata. Ik heb enkele tests toegevoegd omdat er nu op diverse plekken 2 instances werden geretourneerd in plaats van 1. Die 2e controle is op de id zoals die er voor 1 al in stond. 

Ik heb geen nieuwe testsituaties toegevoegd. Ik veronderstel dat de tests die er nu in staan afdoende zijn om de Gorzen en Gewassen te testen. 

Alle test slagen.

**Comment by MelvLee** [comment]
Wat mij opvalt uit de twee testgevallen is dat ze dezelfde eigenaren hebben. Kan ik hieruit concluderen dat de KOZ-en die betrokken zijn bij eenzelfde Gorzen en Aanwassen Gebied dezelfde eigenaren hebben?

**Comment by CathyDingemanse** [comment]
> Wat mij opvalt uit de twee testgevallen is dat ze dezelfde eigenaren hebben. Kan ik hieruit concluderen dat de KOZ-en die betrokken zijn bij eenzelfde Gorzen en Aanwassen Gebied dezelfde eigenaren hebben?

Jazeker, aangezien je ieder van deze eigenaren kunt gebruiken om te raadplegen welke percelen er bij horen.

**Comment by MelvLee** [comment]
De Gorzen en Aanwassen van Gebied functionaliteit is uitgewerkt in de [gorzen-en-aanwassen.feature](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/blob/feature/gorzen-en-aanwassen/features/gorzen-en-aanwassen.feature) file.
