### ISSUE TITLE
testdata wordt niet meer geleverd of is gewijzigd

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#879]
Verschillende testgevallen leveren nu gegevens niet meer die voorheen wel weren geleverd, of geven nu andere waarden. Ik zie geen issues waarvoor deze wijzigingen verklaarbaar zijn.

- [x] * /kadastraalonroerendezaken/76870487970000 bevat geen isVermeldInStukdeelIdentificaties en stukIdentificaties meer
- [x] * /kadastraalonroerendezaken/22590043870000/privaatrechtelijkebeperkingen/91074411 had omschrijving "omschrijving van aantekening", dat is nu "Aantekening omschrijving, consectetur adipiscing elit. Mauris feugiat auctor erat nec interdum. Nulla ac est consecte. "
- [x] * /kadastraalonroerendezaken/22590043870000/zakelijkgerechtigden/90495201 had tenaamstelling.aantekeningen[0].omschrijving "omschrijving van aantekening", dat is nu "Aantekening omschrijving, consectetur adipiscing elit. Mauris feugiat auctor erat nec interdum. Nulla ac est consecte. "
- [x] * /kadastraalonroerendezaken/23280647970000/zakelijkgerechtigden/90763535 had in tenaamstelling.aantekeningen.stukIdentificaties ["20170112112820","20200617001836"], dat is gewijzigd naar ["18050329018096","20200617001836"]
- [x] * /kadasternatuurlijkpersonen/70882239 had in heeftPartnerschap.naam.geslachtsnaam "Jansens", dat is geworden "Jansens-Jan"
- [x] * /kadasternatuurlijkpersonen/71303564 ontbreekt nu het postadres en het woonadres
- [x] * /kadasternatuurlijkpersonen?q=Willem%20Jansens vond voorheen "Willem Jansens", vindt nu geen persoon. Ook andere zoekingangen zoals /kadasternatuurlijkpersonen?q=jansens%201971-11-01 vindt deze persoon niet. 
- [x] * /kadasternatuurlijkpersonen?q=jansens dus zoeken met alleen achternaam, vindt wel "Willem Jansens", maar niet "Sidonia Jansens" (heet nu Sidonia Jansens-Jan")
- [x] * /kadasternatuurlijkpersonen?q=de%20goede vond voorheen "Christiaan de Goede", vindt nu geen persoon.
- [x] * /kadasternietnatuurlijkpersonen/71291441 werd voorheen woonadres geleverd, nu niet meer
- [x] * /kadasternietnatuurlijkpersonen/71291493 werd voorheen rsin geleverd, nu niet meer
- [x] * /kadasternietnatuurlijkpersonen?q=bankbedrijf vond voorheen ook "Bankbedrijf van vrucht", nu niet meer (alleen "bankbedrijf"). Hangt wellicht samen met #878 en https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/866#issuecomment-892571968
- [x] * /kadasternietnatuurlijkpersonen?q=bankbedrijf%20rotterdam vond voorheen "Bankbedrijf" met statutaireZetel "ROTTERDAM", nu niet meer. Zoeken op alleen q=bankbedrijf vindt deze wel (en toont dan statutaireZetel "ROTTERDAM").
- [x] * /kadastraalonroerendezaken/22590043870000/privaatrechtelijkebeperkingen/91074411 had in omschrijving "omschrijving van aantekening", dat is nu "Aantekening omschrijving, consectetur adipiscing elit. Mauris feugiat auctor erat nec interdum. Nulla ac est consecte. "
- [x] * /stukken/20170102999999 bestond eerst, maar geeft nu 404
- [x] * /stukken/17990623003542 bevat geen tijdstipAanbieding meer
- [x] * /stukken/18020223007191 bevat geen tijdstipAanbieding meer
- [x] * /stukken/18020223007191 had bewaardersVerklaring "Ziehier een mooie verklaring.", dat is nu "bewaardersverklaring dolor sit amet, consectetur adipiscing elit. Mauris feugiat auctor erat nec interdum. Nulla ac est consecte."
- [x] * /stukken/18020223007191 had geen kadasterverzoeken.redenenVerzoek[0].redenOmschrijving, maar nu wel (2)
- [x] * /stukken/18020223007191 had toelichtingBewaarder "Een toelichting van de bewaarder.",  dat is nu "ToelichingBewaarder dolor sit amet, consectetur adipiscing elit. Mauris feugiat auctor erat nec interdum. Nulla ac est consecte."
- [x] * /stukdelen/1029999990 bestond eerst, maar geeft nu 404
- [x] * /stukdelen/1000854514 had omschrijvingKadastraleObjecten "Omschrijving van het object.", dat is nu "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris feugiat auctor erat nec interdum. Nulla ac est consecte."
- [ ] * /stukdelen/1000854514 had omschrijvingTopografischeMutatie "Omschrijving over de mutatie.", dat is nu "Omschrijving dolor sit amet, consectetur adipiscing elit. Mauris feugiat auctor erat nec interdum. Nulla ac est consecte."

**Comment by kad-hebbim** [comment]
@fsamwel: zie hieronder waarom bepaalde testgevallen aangepast zijn.

- #787: 
    - /kadastraalonroerendezaken/76870487970000 bevat geen isVermeldInStukdeelIdentificaties en stukIdentificaties meer
    - /kadastraalonroerendezaken/23280647970000/zakelijkgerechtigden/90763535 had in tenaamstelling.aantekeningen.stukIdentificaties ["20170112112820","20200617001836"], dat is gewijzigd naar ["18050329018096","20200617001836"]
    - /stukken/20170102999999 bestond eerst, maar geeft nu 404
    - /stukdelen/1029999990 bestond eerst, maar geeft nu 404
- #806:
    - /kadastraalonroerendezaken/22590043870000/privaatrechtelijkebeperkingen/91074411 had omschrijving "omschrijving van  
aantekening", dat is nu "Aantekening omschrijving, consectetur adipiscing elit. Mauris feugiat auctor erat nec interdum. Nulla ac est consecte. "
    - /kadastraalonroerendezaken/22590043870000/zakelijkgerechtigden/90495201 had tenaamstelling.aantekeningen[0].omschrijving "omschrijving van aantekening", dat is nu "Aantekening omschrijving, consectetur adipiscing elit. Mauris feugiat auctor erat nec interdum. Nulla ac est consecte. "
    - /stukken/18020223007191 had bewaardersVerklaring "Ziehier een mooie verklaring.", dat is nu "bewaardersverklaring dolor sit amet, consectetur adipiscing elit. Mauris feugiat auctor erat nec interdum. Nulla ac est consecte."
    - /stukken/18020223007191 had toelichtingBewaarder "Een toelichting van de bewaarder.", dat is nu "ToelichingBewaarder dolor sit amet, consectetur adipiscing elit. Mauris feugiat auctor erat nec interdum. Nulla ac est consecte."
    - /stukdelen/1000854514 had omschrijvingKadastraleObjecten "Omschrijving van het object.", dat is nu "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris feugiat auctor erat nec interdum. Nulla ac est consecte."
    - /stukdelen/1000854514 had omschrijvingTopografischeMutatie "Omschrijving over de mutatie.", dat is nu "Omschrijving dolor sit amet, consectetur adipiscing elit. Mauris feugiat auctor erat nec interdum. Nulla ac est consecte."
- #850:
    - /kadasternatuurlijkpersonen/70882239 had in heeftPartnerschap.naam.geslachtsnaam "Jansens", dat is geworden "Jansens-Jan"
    - /kadasternatuurlijkpersonen?q=Willem%20Jansens vond voorheen "Willem Jansens", vindt nu geen persoon. Ook andere zoekingangen zoals /kadasternatuurlijkpersonen?q=jansens%201971-11-01 vindt deze persoon niet.
    - /kadasternatuurlijkpersonen?q=jansens dus zoeken met alleen achternaam, vindt wel "Willem Jansens", maar niet "Sidonia Jansens" (heet nu Sidonia Jansens-Jan")
    - /kadasternatuurlijkpersonen?q=de%20goede vond voorheen "Christiaan de Goede", vindt nu geen persoon.
    - /kadasternietnatuurlijkpersonen?q=bankbedrijf vond voorheen ook "Bankbedrijf van vrucht", nu niet meer (alleen "bankbedrijf").
    - /kadasternietnatuurlijkpersonen?q=bankbedrijf%20rotterdam vond voorheen "Bankbedrijf" met statutaireZetel "ROTTERDAM", nu niet meer. Zoeken op alleen q=bankbedrijf vindt deze wel (en toont dan statutaireZetel "ROTTERDAM").
- #871:
    - /stukken/17990623003542 bevat geen tijdstipAanbieding meer
    - /stukken/18020223007191 bevat geen tijdstipAanbieding meer
 
- Nog uitzoeken:
    - /kadasternatuurlijkpersonen/71303564 ontbreekt nu het postadres en het woonadres
    - /kadasternietnatuurlijkpersonen/71291441 werd voorheen woonadres geleverd, nu niet meer
     - /kadasternietnatuurlijkpersonen/71291493 werd voorheen rsin geleverd, nu niet meer
 Hangt wellicht samen met kadasternietnatuurlijkpersoon met relatie betrokkenGorzenEnAanwassen wordt niet gevonden en relatie niet getoond #878 en kadasterpersonen bestaan niet meer #866 (comment)
    - /stukken/18020223007191 had geen kadasterverzoeken.redenenVerzoek[0].redenOmschrijving, maar nu wel (2)

**Comment by kad-hebbim** [comment]
**Opgelost:**
- /kadasternatuurlijkpersonen/71303564 ontbreekt nu het postadres en het woonadres
- /kadasternietnatuurlijkpersonen/71291441 werd voorheen woonadres geleverd, nu niet meer
- /kadasternietnatuurlijkpersonen/71291493 werd voorheen rsin geleverd, nu niet meer

**Comment by JohanBoer** [comment]
@kad-hebbim @fsamwel @MelvLee 

  - /kadasternatuurlijkpersonen?q=Willem%20Jansens vond voorheen "Willem Jansens", vindt nu geen persoon. Ook andere zoekingangen zoals /kadasternatuurlijkpersonen?q=jansens%201971-11-01 vindt deze persoon niet.
  - /kadasternatuurlijkpersonen?q=jansens dus zoeken met alleen achternaam, vindt wel "Willem Jansens", maar niet "Sidonia Jansens" (heet nu Sidonia Jansens-Jan")
  - /kadasternatuurlijkpersonen?q=de%20goede vond voorheen "Christiaan de Goede", vindt nu geen persoon.
  - /kadasternietnatuurlijkpersonen?q=bankbedrijf vond voorheen ook "Bankbedrijf van vrucht", nu niet meer (alleen "bankbedrijf").
  - /kadasternietnatuurlijkpersonen?q=bankbedrijf%20rotterdam vond voorheen "Bankbedrijf" met statutaireZetel "ROTTERDAM", nu niet meer. Zoeken op alleen q=bankbedrijf vindt deze wel (en toont dan statutaireZetel "ROTTERDAM").

Deze bovenstaande testen falen ook nu nog. Ik begrijp de uitleg niet en kan ook uit de beschrijving van #850 niet opmaken welke testdata hoe veranderd is en wat dat voor gevolgen voor de testen heeft.

**Comment by kad-hebbim** [comment]
@JohanBoer 
Wij maken op de testomgeving gebruik van stubs voor al onze bronnen die wij raadplegen, zodat wij de controle hierover hebben en de samenhang van de data tussen de bronnen kunnen waarborgen. 
De bron die dit endpoint gebruikt is gebaseerd op fuzzy search. Fuzzy search is lastig te stubben en daarom hebben we besloten om personen op de volgende manieren beschikbaar te maken via dit endpoint:
- Niet Ingeschreven NatuurlijkPersoon: op volledige achternaam
- NietNatuurlijkPersoon: op statutaire naam 

Dit, zodat wel elk persoon te vinden is.

Bovenstaande gevallen zijn dus als volgt nu te zoeken:
- Willem Jansens: /kadasternatuurlijkpersonen?q=Jansens
- Sidonia Jansens-Jan: /kadasternatuurlijkpersonen?q=Jansens-Jan 
- Christiaan de Goede: /kadasternatuurlijkpersonen?q=Goede
- Bankbedrijf van vrucht: /kadasternietnatuurlijkpersonen?q=Bankbedrijf van vrucht
- Bankbedrijf: /kadasternietnatuurlijkpersonen?q=Bankbedrijf
