### ISSUE TITLE
Sprintwissel 3 - 4 (24 apr)

### ISSUE THREAD

**Issue by JanWillemKooi** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#89]
De Sprintwissel van 3 - 4 vindt plaats in Apeldoorn 
24 apr: 13:00 uur (Apeldoorn - Kadaster de Brug,  Laan van Westenenk 701 Apeldoorn kamer 4.01)

Agenda:
13:00 Binnenkomst, Introductie
13:10 Scrum Review: Demo Sprint 3 resultaten
14:00 Retrospective: Wat kunnen we verbeteren?
14:30 Weekly Scrum: Bijwerken Scrum Board (status Quo)
14:45 Sprint Planning: Wat? (PO)
15:15 Sprint Planning: Hoe? (team)
16:00 Sprint 4 Doel vaststellen, Wvttk, start Sprint 4

**Comment by MelvLee** [comment]
Hoi Jan Willem,

Morgen zouden wij om 9:00 ook een overleg hebben in Apeldoorn. Is dat ook op dezelfde plek?

Groet,
Melvin

----------------------------------------

**Comment by JanWillemKooi** [comment]
De agenda is gevolgd en verwerkt op het scrum board. Uit de Retrospective zijn geen specifieke verbeterpunten gekomen. Het Scrumboard wordt niet altijd door de projectdeelnemers bijgewerkt. Een aantal User Story's is opgeschreven zodat ze over meerdere sprints gaan lopen. Het zijn meer Epics dan US. Tijdens de sprint planning is geprobeerd die verder op te splitsen zodat een US afgerond kan worden binnen een sprint.
