### ISSUE TITLE
Als adviseur standaarden wil ik dat de naam van dit project aangepast wordt naar "Bevragingen Kadastraal Object" of "Bevragingen Kadastraal Onroerende Zaak"

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#9]
...zodat [er een éénduidige naam is voor gelijksoortige standaarden.

**Acceptatiecriteria**
- [ ] Overeenstemming met teamleden

**Definition of done**
- [ ] aangepaste naam

**Comment by fsamwel** [comment]
Ik denk dat "Kadastraal Object" of "Kadastraal Onroerende Zaak" te beperkt is, omdat er ook andere, gerelateerde resources in het koppelvlak zitten of kunnen komen. Ik vind indeling per bron (basisregistratie, voorziening) of per domein wel duidelijk. 
Alleen bij de ingeschreven personen hebben we daar nu nog een issue. Die hadden we ook wel "BRP-bevragingen" willen noemen, maar die naam was verwarrend geweest sinds het stopzetten van programma BRP.
Hier speelt dus dat "BRK-bevragingen" en "Bevragingen ingeschreven personen" niet helemaal gelijksoortig zijn. Deze eerste bevraagt direct bij de bron (basisregistratie), de ander (voorlopig) lokaal op een gegevensmagazijn.

Waarom heb je als adviseur standaarden last van verschillende soorten namen van gelijksoortige standaarden?

**Comment by Debatse** [comment]
Het project bevragingen heeft alleen betrekking op het opvragen van **basisgegevens**.  het betreft dus enkel en alleen gegevens uit een basisadministratie. Dat zou ik heel graag in de naam van het project terugzien. Bevragingen ingeschreven personen klopt dus niet. Want dat betekent dat we ook gemeentelijke kerngegevens bevragen en dat valt buiten de scope van het project. BRP is overigens nog steeds de term die gebruik wordt voor de basisregistratie personen.
Voorstel is de projecten BRP bevragingen en BRK- bevragingen te noemen. BRK bevragingen is veel omvattender dan alleen kadastrale onroerende zaak. Als gemeenten kan ik ook opvragen of iemand een of meer hypotheken heeft lopen
