### ISSUE TITLE
Als PO wil ik een onderzoek naar de inzet van de locatieserver als zoekengine voor de Haal Centraal BRK bevragen API

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#91]
...zodat de API eenvoudiger wordt, migratie bij binnengemeentelijke afnemers wordt voorkomen.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by JanWillemKooi** [comment]
Aantal voorbeeld zoekvragen zijn nodig vanuit de gebruikers. (Cathy)
Marianne gaat een afspraak inplannen bij Kadaster om het inhoudelijk te bespreken.

**Comment by JanWillemKooi** [comment]
Update call 1 mei: Marianne gaat afspraak met locatieservers deskundige vanuit Kadaster inplannen en Cathy (als zoekgebruiker) . Johan zou hier ook graag bij zijn.

**Comment by marianneleferink01** [comment]
Afspraak moet nog gemaakt worden.

**Comment by JanWillemKooi** [comment]
Update call 8 mei: Marianne gaat vandaag een afspraak hierover maken.

**Comment by CathyDingemanse** [comment]
Het gebruik van de locatieserver lijkt zeer veelbelovend. Mijn vraag is nu wat wijsheid is:
Gebruik van de (solar) API of maken wij een eigen specificatie (wrapper) en gebruiken wij de locatieserver  als implementatie voor deze door ons ontworpen API? Onderzocht moet worden:
- of de Solar API voldoet aan onze criteria voor bruikbaarheid (codegeneratie e.d.)
- in hoeverre de Solar API voldoet aan de API strategie
- hoe waarschijnlijk het is dat er een breaking change ontstaat als de Solar API wordt vervangen door een product van een andere leverancier (bijvoorbeeld Elastic Search).

Graag een advies.

**Comment by JanWillemKooi** [comment]
Update 29 mei call: Cathy heeft de zaken die moeten gebeuren gespecificeerd. Uitvoering ligt bij Melvin.

**Comment by JanWillemKooi** [comment]
Update call 5 jun: Cathy checkt status bij Melvin.

**Comment by MelvLee** [comment]
Er is geen OpenAPI definitie van de API van de Locatieserver. Er is wel goede documentatie.
De OpenAPI definitie zou aan de hand van de documentatie gemaakt kunnen worden, zodat consumers wel code kunnen genereren voor het aanroepen van de API's van de Locatieserver.
 
De locatieserver gebruikt een url parameter (wt) om het output formaat aan te geven. Dit wijkt af van REST waar de mediatype header gebruikt om hetzelfde te kunnen doen.
 
Er wordt expliciet aangegeven dat de Locatieserver Apache Solr als search engine wordt gebruikt. Uit de documentatie maak ik op dat de q-parameter van Solr as-is als parameter voor de Locatieserver wordt gebruikt. Dit geldt ook voor de fq-parameter.
Er is hierdoor sprake van tight koppeling tussen de Locatieserver en Solar en implementation bleed. Ook het aanroepen van de lookup endpoint zonder ID-parameter dat tot een fout leidt, laat de tight koppeling zien. De foutmelding van Solr wordt as-is teruggegeven.
Dit kan nadelig zijn voor consumers, want als de Locatieserver in de toekomst een andere search engine gaat gebruiken, dan zal dit leiden tot een breaking change.

Conclusie
Door de tight koppeling met Solr is het niet raadzaam om de API van de Locatieserver as-is aan te bieden aan consumers van de BRK API. Het beste is om een REST compliant service te implementeren die de Locatieserver wrapt

**Comment by JanWillemKooi** [comment]
Dit onderzoek heeft geresulteerd in een nieuwe US #177
