### ISSUE TITLE
Er missen type zakelijkGerechtigden in de openapi specificatie

### ISSUE THREAD

**Issue by kad-hebbim** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#911]
Momenteel wordt het element TypeZakelijkGerechtigde (enumeratie) gebruikt:
- als optie voor de typeGerechtigde parameter
- en voor het veld 'type' binnen een ZakelijkGerechtigde element. 

Deze enumeratie is gebaseerd op de waardenlijst AardZakelijkRecht (https://developer.kadaster.nl/schemas/waardelijsten/AardZakelijkRecht/) en de volgende 2 waarden uit die lijst komen nu niet terug in de enumeratie:
- 10: Zakelijk recht als bedoeld in artikel 5, lid 3, onder b, van de Belemmeringenwet Privaatrecht
- 18: Raadpleeg brondocument

Doordat deze niet in de enumeratie zitten kunnen we ZakelijkRechten met 1 van deze aarden niet mappen en geven we een foutmelding terug aan de klant, wat niet goed is. 

Hoe gaan we met dit probleem om? Ik weet namelijk niet of je een type 'Raadpleeg brondocument' kan definieren als typeGerechtigde parameter bijvoorbeeld...

**Comment by kad-hebbim** [comment]
Zie https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/blob/hotfix/aard-zakelijkrecht/specificatie/domain.yaml voor de fix.

**Comment by kad-pothot** [comment]
@KayodeBakker 
De reden dat er 6 missen is omdat ze óf niet in de registratie voorkomen van de BRK (code 15, 16 & 17), 
óf geen onderdeel zijn van de BRK, maar van de schepen of vliegtuigen registratie (codes 6, 8 & 19).

**Comment by CathyDingemanse** [comment]
hotfix is gerealiseerd! Opgelost
