### ISSUE TITLE
gesplitstZakelijkRecht ook opnemen in onroerende zaak

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#929]
In de implementatie wordt nu ook in de kadastraalonroerendezaak het gegeven gesplitstZakelijkRecht geleverd.

Bijvoorbeeld /kadastraalonroerendezaken/59020139970000 bevat "gesplitstZakelijkRecht": "erfpachter"

In de specificaties vind ik deze niet terug. @kad-pothot @kad-hebbim @JohanBoer is dit een fout in de implementatie of moet dit nog worden toegevoegd aan de specificaties?

**Comment by fsamwel** [comment]
besproken met @kad-pothot. Is goed dat het erin zit. @JohanBoer voeg jij dit toe aan de specificaties?

**Comment by fsamwel** [comment]
afgesproken dat @kad-hebbim dit toevoegt in de specificaties

**Comment by kad-hebbim** [comment]
Zie pull request: 
https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/pull/933
