### ISSUE TITLE
Maak de OAS3 met als inhoud de kadastraal onroerende zaak en aanverwante subresources voor sprint 4 gebaseerd op de spreadsheet

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#93]
![image](https://user-images.githubusercontent.com/18071357/56659487-8f349f80-669d-11e9-8d9a-27a318a62e5d.png)

**Comment by JanWillemKooi** [comment]
Johan levert een nieuwe versie van OAS3 spec op basis van de bovenstaande roze vlakken.
Kadaster reviewt.
Verwerking van de review wordt door Johan uitgevoerd.

**Comment by JohanBoer** [comment]
Vraagstuk waar ik tegenaan loop : 
- [] We hebben elke roze kolom nu als sub-resource gedefinieerd. Willen we ieder van die resources ook zelfstandig kunnen benaderen. Dit heeft te maken met de togangspaden die vanuit de business gewenst zijn. Ik kan me voorstellen dat zakelijke rechten als subresoure direct op te vragen zijn , maar van resources als TENAAMTELLING, PERSOON, NATUURLIJKPERSOON, OBJECTLOCATIEBUITENLAND etc denk ik niet dat ze zelfstandig benaderd moeten kunnen worden. 

Dat betekent iets voor de _links die we ter beschikking stellen in de OAS3. Als ee resource niet zelfstandig te benaderen is als subresource moet er geen SELF-link opgenomen worden en moet deze resource ook nergens in de _links opgenomen worden. 

Mijn voorstel is om voor die subresources die **niet zelfstandig te benaderen** zijn **GEEN links of self-links** op te nemen. 
Gaarne discussie hierover in een werksessie.

- [] De Xor constructie wordt nu in de _embedded met de oneOf-operator geregeld. Vraag is hoe we daar in de _links mee omgaan (waar van toepassing) dat een relatie 2 types kan hebben. In het ZGW-project is de oplossing bedacht  het type bij de polyforme relatie ook mee te geven. Dit is niet standaard HAL,-mechanisme. Hetzelfde geldt voor de geretourneerde resource in de _embedded. Hoe weet de consumer welke van de mogelijke 2 (of 3 bij postlocatie) typen er ontvangen wordt. Ook hier is het een optie om het type van de geretourneerde resource meet te geven. 
Ik heb in de tenaamstelling_embedded en in de tenaamstelling_links een voorstel opgenomen hoe we hier mee om kunnen gaan.
Dit is best een heftige design decision. Als we hiervoor kiezen dan moeten we dat ook terugkoppelen aan de API-strategie.

**Comment by JanWillemKooi** [comment]
Update call 1 mei: Johan verwacht vandaag dit op GitHub te plaatsen.

**Comment by JanWillemKooi** [comment]
Update call 8 mei: De laatste versie staat op GitHub. Morgen heeft Johan met Cathy en Kadaster (Marianne, Marcel, Lennart) een afspraak om dit te bespreken. Johan noemt nog specifiek de oplossing rond polymorfisme. Daarbij kunnen problemen met code generatie ontstaan bij .NET. Melvin is hier tegenaan gelopen en heeft alternatieven aangedragen. Vraag aan Kadaster is op te checken hoe dit zit met Java. De uitkomsten kunnen eventueel leiden tot adviezen voor de Landelijke API groep.
