### ISSUE TITLE
bijbehorendeAppartementsrechten zonder isOvergegaanIn

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#930]
/kadastraalonroerendezaken/59020139970000 heeft twee bijbehorendeAppartementsrechten, maar heeft geen isOvergegaanIn. Is dat mogelijk?

**Comment by kad-pothot** [comment]
Ja, isOvergegaanIn gebruiken we alleen als een kadastraal object is vervallen, in dit geval bestaat het object nog steeds, er is alleen een recht van het object bij een splitsing van appartementsrechten betrokken, waaruit nieuwe kadastrale objecten ontstaan, maar 59020139970000 bestaat nog steeds.

**Comment by fsamwel** [comment]
@kad-pothot dan begrijp ik de andere filiatie testgevallen niet. Die objecten bestaan toch ook nog?
```
{
    "identificatie": "22310691970000",
    "domein": "NL.IMKAD.KadastraalObject",
    "type": "perceel",
    "isOvergegaanIn": {
        "aard": {
            "code": "25",
            "waarde": "Splitsing in appartementsrechten"
        },
        "kadastraalOnroerendeZaken": [
            {
                "identificatie": "22310827210004",
                "type": "appartementsrecht"
            },
            {
                "identificatie": "22310827210003",
                "type": "appartementsrecht"
            }
        ]
    },
    "bijbehorendeAppartementsrechten": [
        {
            "identificatie": "22310827210004",
            "volgnummer": 4
        },
        {
            "identificatie": "22310827210003",
            "volgnummer": 3
        }
    ],
    "_links": {
        "self": {
            "href": "/kadastraalonroerendezaken/22310691970000?fields=isOvergegaanIn,bijbehorendeAppartementsrechten"
        }
    }
}
```

**Comment by kad-pothot** [comment]
Sorry, ik zat er naast, de isOvergegaanIn relatie wordt ook vanuit een in appartementsrechten gesplitst kadastraal object getoond.
@kad-hebbim mist deze filiatie in het voorbeeld?

**Comment by kad-hebbim** [comment]
> 22310827210004

@kad-pothot: geldt dit dan ook voor een gesplitst recht dat niet het recht van eigendom is op dat object? Momenteel kijken we voor het overgegaanIn veld alleen of het recht van eigendom is gesplitsts in appartementsrechten...

**Comment by kad-pothot** [comment]
@kad-hebbim Bij isOvergegaanIn kijken we op kadastraal object niveau, dus het maakt niet uit of een recht van eigendom of een een ander beperkt recht is gesplitst, er ontstaan vanuit het grondperceel (of ondergesplitst appartementsrecht) nieuwe kadastrale objecten en die hebben ontstaanUit relatiemet het grondperceel (of ondergesplitst appartementsrecht), en vanuit het gesplitste kadastrale object heb je dan altijd een isOvergegaanIn relatie.

**Comment by kad-hebbim** [comment]
@fsamwel: fix staat op de acceptatieomgeving. Onze testers zijn aan onze kant nog niet helemaal klaar met hun testen, maar heb de fix toch alvast doorgezet aangezien ik er morgen niet ben.

**Comment by fsamwel** [comment]
getest en wordt nu wel geleverd
