### ISSUE TITLE
gesplitstZakelijkRecht altijd leveren bij gebruik fields

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#932]
gesplitstZakelijkRecht moet altijd geleverd worden, ook wanneer fields wordt gebruikt en daar niet om is gevraagd

**Comment by fsamwel** [comment]
@kad-hebbim wijzigt in de implementatie
@fsamwel maakt een feature fields-extensie waarin verplicht geleverde velden worden genoemd

**Comment by fsamwel** [comment]
@kad-hebbim @kad-pothot geldt dit ook niet voor indicatieSluimerend? Moet dat dan niet ook altijd geleverd worden?

**Comment by fsamwel** [comment]
> @fsamwel maakt een feature fields-extensie waarin verplicht geleverde velden worden genoemd

correctie: er is al een feature levering-velden die beschrijft dat identificatie, domein en type altijd geleverd wordt, en er is een feature levering-koopsom die beschrijft dat de koopsom en cultuurcode altijd samen geleverd worden.

Ik voeg gesplitstZakelijkRecht i.c.m. fields toe aan feature gesplitst-zakelijk-recht

**Comment by kad-hebbim** [comment]
> @kad-hebbim wijzigt in de implementatie @fsamwel maakt een feature fields-extensie waarin verplicht geleverde velden worden genoemd

@fsamwel: fix staat op de acceptatieomgeving. Onze testers zijn aan onze kant nog niet helemaal klaar met hun testen, maar heb de fix toch alvast doorgezet aangezien ik er morgen niet ben.

**Comment by fsamwel** [comment]
> Ik voeg gesplitstZakelijkRecht i.c.m. fields toe aan feature gesplitst-zakelijk-recht

Done. Nieuwe regel toegevoegd "Rule: Bij gebruik van fields wordt gesplitstZakelijkRecht altijd geleverd wanneer die ook een waarde heeft in de resource"

**Comment by fsamwel** [comment]
getest en werkt zoals verwacht
