### ISSUE TITLE
Als PO wil ik dat het Kadaster een werkende API maakt, gebaseerd op #93  (ROZE) en gevuld met data vanuit de Kadaster-bronnen

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#94]

**Comment by JanWillemKooi** [comment]
Realisatie is afhankelijk van snelheid van #93 
Het ontwikkelteam moet voldoende tijd hebben op te kunnen realiseren

**Comment by JanWillemKooi** [comment]
Update call 1 mei: #93 moet uiterlijk maandag 6 mei, voldoende duidelijk zijn zodat deze in de komende ontwikkelsprint van Kadaster (start dinsdag 7 mei) mee kan.

**Comment by marianneleferink01** [comment]
Op donderdag 9 mei a.s. gaan we opgelverde OAS specs reviewen.  Daarna wordt api gerealiseerd door Kadaster. Issue staat op sprint voor KOL team van Kadaster

**Comment by marianneleferink01** [comment]
Naamgeving van deze story omgezet naar realiseren responsebericht voor de api, gebaseerd op story 93. 
De api zelf was al wel gemaakt. Nu moet het ook een "werkende" api worden.

**Comment by JanWillemKooi** [comment]
Update 29 mei call: Spraakverwarring over de user story's en wat wordt bedoeld. We hebben 5 stappen. 

1. Keuze maken op grond van spreadsheet. Keuze krijgt een kleur. (Marianne, Cathy, Johan) 
2. OAS3 spec opleveren (Johan)
3. Realisatie API (Marianne) op basis van bovenstaande 
4. Beschikbaar stellen API voor mensen met API-key (Marianne)
5. Testen (Remco, Melvin, Agustin, etc.)

Dus bij elke kleur krijgen we deze 5 stappen.
Roze (keuze uit sprint 3)
Geel (keuze uit sprint 5)
