### ISSUE TITLE
Productie responses leveren geen begrenzingPerceel op

### ISSUE THREAD

**Issue by KayodeBakker** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#943]
**Beschrijf de bug**
Bij het ophalen van kadastraalOnroerendeZaak bij 'https://api.brk.kadaster.nl/esd/bevragen/v1' wordt er nooit een begrenzingPerceel geometrie aangeleverd. Maakt niet uit welke identificatie er wordt gebruikt, er wordt geen begrenzingPerceel geleverd. Ook niet wanneer je met fields er niet om vraagt **en** wel om vraagt.
Ook geprobeerd met een identificatie uit de genoemde testcasussen waar in acceptatie daadwerkelijk wel een begrenzingPerceel terugkomt.

**To Reproduce**
Stappen om de bug te reproduceren
1. Ga naar 'https://api.brk.kadaster.nl/esd/bevragen/v1/kadastraalonroerendezaken/76870487970000'.
2. Zie dat het response **geen** begrenzingPerceel bevat.
3. Ga naar 'https://api.brk.acceptatie.kadaster.nl/esd/bevragen/v1/kadastraalonroerendezaken/76870487970000'.
2. Zie dat het response **wel** begrenzingPerceel bevat.

**Verwacht gedrag**
Verwacht is dat bij het ophalen van een perceel dat hier een begrenzingPerceel wordt geleverd. Mocht hier functioneel reden voor zijn waardoor niet alle percelen een begrenzingPerceel kan hebben, documenteer dit dan voor de gebruiker.

**Comment by KayodeBakker** [comment]
Dit is natuurlijk ook bij andere vormen van bevraging van een kadastraal onroerende zaak. Zoals op kadastraleAanduiding.

**Comment by fsamwel** [comment]
@CathyDingemanse @kad-pothot is het mogelijk te beschrijven in welke gevallen we begrenzingPerceel zouden kunnen verwachten? Dat zouden we dan in de specificaties op kunnen nemen of in een feature.

**Comment by CathyDingemanse** [comment]
@kad-hebbim @kad-pothot, dit inderdaad een bug. Kunnen jullie deze in het kader van de SLA en werkafspraken  z.s.m. oppakken?

**Comment by CathyDingemanse** [comment]
> Dit is inderdaad een bug en zullen we oppakken.

Super Marcel!

**Comment by kad-hebbim** [comment]
> Top! Is er zicht op wanneer dat wordt opgepakt?

Deze bug zijn we momenteel aan het oplossen en verwachten dit begin augustus op te leveren.

**Comment by kad-hebbim** [comment]
Deze bug is opgelost en doorgevoerd in productie.
@KayodeBakker 
@CathyDingemanse

**Comment by CathyDingemanse** [comment]
Thnx Marcel! Wij gaan er mee aan de slag!
