### ISSUE TITLE
Stukidentificaties en _links.stukken worden niet geleverd

### ISSUE THREAD

**Issue by KayodeBakker** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#947]
**Beschrijf de bug**
Bij het raadplegen van of zoeken naar een kadastraal onroerende zaak worden er geen stukidentificaties of _links.stukken getoond.
We kunnen dit alleen terug vinden bij de test cases met identificatie '76870482670000' en '17150075470000'. Volgens de test cases overzicht horen meerdere cases een stukidentificatie te retourneren + een stuk in de _links, echter dit lijkt niet het geval.
Tegelijk kan geen stukidentificatie in een kadastraal onroerende zaak worden gevonden in productie met geen enkele case.
Zoals het er nu op lijkt, is dit niet beschikbaar in productie (desondanks dat er wel gezocht kan worden op stukken en stukdelen) en lijkt de test alleen maar 2 van de 15+ cases te implementeren.

Graag zie ik hier redenatie of oplossingen voor.

**To Reproduce**
Stappen om de bug te reproduceren
1. Ga naar /kadastraalonroerendezaken/{identificatie}
3. Zoek naar stukidentificaties of _links.stukken
4. Zie dat er geen waarde geleverd wordt met uitzondering van in de test bij '76870482670000' en '17150075470000'.

**Verwacht gedrag**
Verwacht is een overzicht van werkende test cases (dit staat los van dit vraagstuk want de test cases dienen te werken zoals beschreven) en dat productie netjes stukidentificaties weergeeft bij het ophalen van een kadastraal onroerende zaak. Mocht dit by design zijn dan zien we graag uitleg voor waarom dit normaal gedrag is.

**Comment by fsamwel** [comment]
ik zie dit ook. Bijvoorbeeld perceel 76870487970000 had voorheen een stuk en een stukdeel. Nu worden beide niet meer geleverd.

**Comment by CathyDingemanse** [comment]
De identificaties van ter inschrijving aangeboden stukken en kadasterstukken is niet uniek (oorzaak). Besloten is om de mapping van oude AKR stukken op de backlog te zetten, maar andere ter inschrijving aangeboden stukken te leveren, inclusief stukdeelidentificaties.

Huidige situatie: het lijkt er op dat er alleen stukken worden geleverd bij zakelijk gerechtigde, 
@fsamwel wil jij dit uitzoeken/testen?

**Comment by CathyDingemanse** [comment]
Voor kadastrale onroerende zaken:
In test worden er bij 2 van de 15 testcases een stuk geleverd.
In productie worden op dit moment helemaal GEEN stukidentificaties meer geleverd!

**Comment by fsamwel** [comment]
Er zijn wel enkele testgevallen waarbij er een stukidentificatie en stukdeelidentificatie wordt geleverd, zie  [/test/cases](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/tree/master/test/cases#readme).

Bijvoorbeeld /kadastraalonroerendezaken/76870482670000 heeft /stukdelen/500001938598 en /stukken/20200227000564.

**Comment by kad-hebbim** [comment]
We zijn dit momenteel aan het uitzoeken.

**Comment by kad-pothot** [comment]
Deze relatie tussen een stukdeel en een kadastraal object komt in de praktijk zelden tot nooit voor i.c.m. een hypotheken 4 stuk (denk hooguit aan bijvoorbeeld een rechterlijke uitspraak die de oppervlakte/grens van een perceel veranderd). 

Komt wel met interne stukken vaker voor, vooral bij grenscorrecties. Maar interne stukken leveren we niet naar buiten toe.
Dus klopt dat dit niet tot nooit voorkomt in productie data.
