### ISSUE TITLE
kadasternietnatuurlijkpersonen operatie retourneerd 500 internal server error bij specifieke request met in de body bericht "Unable to route to API"

### ISSUE THREAD

**Issue by teunvandemerwe** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#953]
**Beschrijf de bug**
Request naar operatie kadasternietnatuurlijkpersonen geeft internal server error met body bericht Unable to route to API.

**To Reproduce**
Stappen om de bug te reproduceren
1. Doe GET op https://api.brk.kadaster.nl/esd/bevragen/v1/kadasternietnatuurlijkpersonen/146181331
2. Na lang wachten een 500 internal server

Geef het reproductie path mee

**Verwacht gedrag**
Verwacht is een 404 indien niet gevonden of 200 indien wel gevonden. 

Bijvoorbeeld https://api.brk.kadaster.nl/esd/bevragen/v1/kadasternietnatuurlijkpersonen/172091001 gaat wel goed.

**Comment by CathyDingemanse** [comment]
@kad-hebbim @FerrydeJong kunnne jullie hier naar kijken? Dank!

**Comment by JaccovdBerg** [comment]
Is er al voortgang op dit issue?

**Comment by FerryDeJong** [comment]
Goedemiddag, 
Ook het waarom je geen antwoord krijgt op deze vraag hebben wij even onderzocht. 

Deze niet natuurlijk persoon die jullie opvragen heeft 3260 percelen op naam staan. Van al deze percelen worden bij de aanroep van de BRK Api ook alle eigendomsgegevens opgehaald om daarmee de zakelijkgerechtigden mee te kunnen bepalen. 

Dat duurt langer dan de time-outs, en daardoor krijg je geen antwoord op deze vraag. Dat probleem kan optreden met grote gerechtigden. 

Groet
Ferry

**Comment by PeaceNlove** [comment]
Waarom worden eigenlijk alle percelen hier opgehaald. Er is toch een API endpoint waar je voor een gegeven identificatie alle percelen kan  uitvragen. Als je zo nodig daarin geïnteresseerd bent zou ik eerder een link naar die resource verwachten ipv een uitlijsting van alle perceelids. 
Het vervelende is ook dat het er niet op lijkt dat ik die percelen kan omzeilen. In het proces wat ik implementeer wil ik van een perceel de eigenaar weten en dan vervolgens van de eigenaar de adresgegevens. Wanneer de eigenaar aangegeven is als een brk_niet_natuurlijk_persoon moet ik de adresgegevens op dit endpoint opvragen en vanuit mijn proces ben ik dan niet geïnteresseerd in wat die organisatie nog meer aan percelen bezit.
Maar als ik een request doe voor alleen  "woonplaats" in de fields parameter https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature  dan maakt dat weinig tot niets uit in de responstijden. Het is altijd tussen de 20 en 25 seconden als ik 172091001 uitvraag, met of zonder fields parameter. En 146181331 kan  ik dus nooit een adres van terugkrijgen, tenzij (we zijn het zelf namelijk) al onze percelen verkopen dan wel dat de performance aan de API kan fors omhoog gaat.

**Comment by CathyDingemanse** [comment]
Hallo allemaal, wij zijn er mee bezig, en laten zsm weten wat de vervolgacties zijn. Kunnen jullie mij jullie contactgegevens mailen?
mailto: c.dingemanse@comites.nl

**Comment by CathyDingemanse** [comment]
@PeaceNlove, @teunvandemerwe of @JaccovdBerg zouden jullie voor ons:

1. de exacte request met de fields parameter in deze issue willen opgeven? Dan weten wij precies wat jullie hebben gedaan.
2. zouden jullie met deze kadasternietnatuurlijkpersoon de /kadastraalonroerendezaken willen bevragen? Wij willen graag weten of dit ook fout gaat.

**Comment by teunvandemerwe** [comment]
@CathyDingemanse 

Bij deze een antwoord op je vragen.

1. /kadasternietnatuurlijkpersonen?q=146181331 (https://api.brk.kadaster.nl/esd/bevragen/v1/kadasternietnatuurlijkpersonen/146181331)
2. @PeaceNlove zie jij een mogelijkheid voor kadastraalOnroerendeZaakIdentificatie van 146181331

**Comment by CathyDingemanse** [comment]
Zie issue #956

**Comment by brienen** [comment]
Besloten is dat deze als zodanig opgelost gaat worden

**Comment by teunvandemerwe** [comment]
Is hier ook een verwachte datum voor dat dit opgelost wordt?
