### ISSUE TITLE
Gebruik BSN in URL bij Get-bevragingen is ongewenst 

### ISSUE THREAD

**Issue by brienen** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#967]
Bericht van Kadaster: In sommige API’s zitten in de URL de gegevens die je opvraagt, dat kan ook de BSN zijn. 

Door een afnemer zijn wij erop gewezen dat het op die manier uitwisselen van die informatie als ongewenst wordt gezien. 
Wij hebben dat intern besproken en wij zijn het eens met het commentaar wat wij hebben ontvangen, wij gaan dit in onze producten aanpassen. 

Dit betekend een breaking change in BRK Bevragen.

**Comment by kad-hebbim** [comment]
[PR](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/pull/971)

**Comment by melsk-r** [comment]
Neem in BsnBody bij burgerservicenummer:

`description: Het burgerservicenummer van de persoon die een zakelijk recht op een kadastraal onroerende zaak heeft. Deze persoon is zakelijk gerechtigde van de kadastraal onroerende zaak.`

op.
