### ISSUE TITLE
grootgrondbezitters uitvragen

### ISSUE THREAD

**Issue by PeaceNlove** [VNG-Realisatie/Haal-Centraal-BRK-bevragen#987]
Is het mogelijk de zakelijke rechten van grootgrond 'bezitters'* uit te vragen? 
Ik lees hier bijvoorbeeld dat het aantal resultaten beperkt kan worden en in die situatie geen resultaat gegeven wordt: https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/blob/master/specificatie/kadastraal-onroerende-zaken.yaml

Bijvoorbeeld zou ik willen weten welke zakelijke rechten Waterschap AGV (mijn opdrachtgever) allemaal heeft. Maar ik lijk dus tegen die beperking aan te lopen, ik kan het wel op een eigenaar met een gering aantal zakelijk rechten opvragen, maar bij AGV krijg ik niets. 

*bezitters is hier even figuurlijk spreken, als er sprake is van erfpacht door als zakelijk recht wil ik dat ook terugkrijgen

**Comment by FerryDeJong** [comment]
Hallo PeaceNlove, 
Welke identificatie probeer je op te vragen, dan kunnen wij even zien of we jouw probleem kunnen reproduceren. 
Alvast bedankt voor je antwoord, 
Groet
Ferry

**Comment by PeaceNlove** [comment]
Hallo Ferry,
ik doe dit request:
/kadastraalonroerendezaken?persoon__identificatie=146181331 <- zou waterschap AGV moeten zijn als BRK NNP
alvast bedankt :-)
Joël

**Comment by FerryDeJong** [comment]
Hi Joël, 
Dank voor je antwoord, dat helpt. 

Wij hebben de aanvraag even gereproduceerd en ontvangen daar de volgende resultaten op;

In v1 krijgen we inderdaad de melding dat het product niet geleverd kan worden. 
Daar leveren we niks uit als persoon meer dan 100 objecten op naam heeft. En deze persoon heeft dat. 

Dit was een probleem in de v1, omdat we daarbij altijd in respons al meteen het hele antwoord van alle betrokken objecten meeleveren. Omdat dit de infrastructuur fors belast is dat gemaximaliseerd op 100 objecten. Echter heb je dan dus een probleem als de gerechtigde meer dan 100 objecten op naam heeft. 

Dit probleem hebben we opgelost in v2. Daar ontvang je als gebruiker niet meer het volledige antwoord van de betrokken objecten, maar een lijst met objecten. Die objecten kan je dan vervolgens opvragen. Daardoor kunnen grotere personen wel geleverd worden. 

In v2 wordt het product geleverd na ongeveer 1 minuut. 

Om dit probleem op te lossen kunnen jullie overstappen op de nieuwste versie van de API. 
Dan kan je deze vraag succesvol stellen. 

Hopelijk kan je hiermee verder, vriendelijke groet, 
Ferry
